### ISSUE TITLE
Adding new front-end website 

### ISSUE THREAD

**Issue by DHRUVKHANDELWAL00** [TusharKesarwani/Front-End-Projects#10]
hey @TusharKesarwani , can I add a tic-tac-toe website that I made by myself . I have used javascript, CSS, and HTML along with bootstrap.

**Comment by TusharKesarwani** [comment]
Go ahead @DHRUVKHANDELWAL00

**Comment by DHRUVKHANDELWAL00** [comment]
hey @TusharKesarwani , i am already adding a tic-tac-toe game but u have made another issue and assigned someone else. please look into it.
Also i am ready to make a PR for it

**Comment by DHRUVKHANDELWAL00** [comment]
![image](https://user-images.githubusercontent.com/99539203/210547447-fcc20eaa-7c36-451c-8b04-40538255860d.png)
