### ISSUE TITLE
UNIT CONVERTOR

### ISSUE THREAD

**Issue by DHRUVKHANDELWAL00** [TusharKesarwani/Front-End-Projects#100]
CONVERTS DIFFRENT UNITS OF LENGTH,TEMPERATURE,ETC TO REQUIRED ONES.

**Comment by DHRUVKHANDELWAL00** [comment]
@TusharKesarwani  please assign me

**Comment by tejasri415** [comment]
@TusharKesarwani  Please assign this issue to me

**Comment by DHRUVKHANDELWAL00** [comment]
@tejasri415 create your own issue

**Comment by abhilipsasahoo03** [comment]
@DHRUVKHANDELWAL00 have you created a PR yet? If so, please link your issue to your PR. If you do not plan to work on it, then let us know so that we can assign someone else willing to work on this issue.
