### ISSUE TITLE
[SSoC'23] Bingo Game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [TusharKesarwani/Front-End-Projects#1004]
## **Describe the project**
- This game project is written in the HTML, CSS and JS languages.
- Providing an intuitive and attractive UI.
- Also adding a background music.
- Along with the background music, adding a controls for the background music with mute/unmute buttons and a slider.
- Adding a loading page at the start of the game will give a shiny look to the game.
- This game is for multi-player game.
- Adding a congratulation page at the end of the game.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**
![Screenshot2](https://github.com/TusharKesarwani/Front-End-Projects/assets/114330097/fef36162-bdc6-4321-b782-aeb803e43436)

**Comment by harshit-paneri** [comment]
Game is not allow.
