### ISSUE TITLE
[New Project]: Spotify Clone

### ISSUE THREAD

**Issue by shambhavisingh011** [TusharKesarwani/Front-End-Projects#1005]
## **About the project**
I wish to add a clone displaying the home page of Spotify.

## Issue Type:
- [x] New Project

## **Screenshots**

![final_preview](https://github.com/TusharKesarwani/Front-End-Projects/assets/121101577/6931fc88-b9f8-4a53-86b6-8f7ded18014d)

**Comment by AditiSingh06** [comment]
Hi, @TusharKesarwani I would like to work on this project. Please, assign it to me under SSOC'23.

**Comment by Pranay38** [comment]
Hey! I want to work on this issue

**Comment by Gyanthakur** [comment]
I want to work on this issue.

**Comment by TusharKesarwani** [comment]
Already present in the repo
