### ISSUE TITLE
Image Search App With JavaScript API Under SSOC 2.0

### ISSUE THREAD

**Issue by Thejasbshetty** [TusharKesarwani/Front-End-Projects#1011]
Description:

The Image Search App with JavaScript API is a web application that allows users to search for images using a JavaScript API. The app provides a user-friendly interface where users can enter their search query and view the resulting images.

The application leverages a JavaScript API, which acts as a bridge between the app and an image database or search engine. This API enables the app to send search requests and receive image data in response. There are various JavaScript APIs available for image search, such as the Google Custom Search API or the Unsplash API, which provide access to vast collections of images.

Once a user enters a search query, the app sends the query to the JavaScript API, which then processes the request and retrieves relevant images based on the query. The app displays the images in a visually appealing manner, allowing users to scroll through the results and view each image individually.

Additionally, the Image Search App may offer additional features to enhance the user experience. For example, it could include pagination to load more images as the user scrolls, allowing them to explore a larger number of results. It may also include options for filtering or sorting the search results based on criteria like image size, color, or relevance.

To build such an app, you would need to have a good understanding of JavaScript, HTML, and CSS. You would also need to choose and integrate a suitable JavaScript API for image search. This would involve making HTTP requests, handling responses, and manipulating the DOM to display the images.

Overall, the Image Search App with JavaScript API provides a convenient way for users to search for images and explore visual content based on their interests or needs.

**Comment by Thejasbshetty** [comment]
@TusharKesarwani please asign me this task for SSOC'23

**Comment by TusharKesarwani** [comment]
Make new PR with an attractive UI and also make it responsive
