### ISSUE TITLE
Add Todo App 

### ISSUE THREAD

**Issue by SattyamSamania** [TusharKesarwani/Front-End-Projects#1012]
## **Describe the project**
I want to add a Todo App using React Js with Add and Delete features.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
 
![Screenshot (13)](https://github.com/TusharKesarwani/Front-End-Projects/assets/67833888/294d0af6-c88d-4c5b-a834-905d62f44d0e)

**Comment by its-kundan** [comment]
!assign

**Comment by TusharKesarwani** [comment]
Already present in the repo
