### ISSUE TITLE
Front-End-Project : Calculator

### ISSUE THREAD

**Issue by abhyuday1212** [TusharKesarwani/Front-End-Projects#1025]
-Adding more features of a Scientific calculator to the Existing Simple Calculator Using Javascript & adding corresponding Html and CSS.

Features like -
Trigonometric Operations
Logarithmic Operations
Exponential Operations
Inverse Operations
Inverse Trigonometric Operations

![calculator](https://github.com/TusharKesarwani/Front-End-Projects/assets/115206840/8d5b7cdb-65b7-4356-83f9-b4d29900a9bb)

**Comment by abhyuday1212** [comment]
@TusharKesarwani sir this issue is assigned to me or not?

**Comment by Jatingupta9120** [comment]
sir please assign this issue to me

**Comment by imrish4** [comment]
@TusharKesarwani Please assign this issue to me under ssoc'23 program .

**Comment by abhyuday1212** [comment]
please open this issue
