### ISSUE TITLE
Falling Blocks

### ISSUE THREAD

**Issue by thakurdiwakar** [TusharKesarwani/Front-End-Projects#1027]
## **Falling blocks**
Falling Blocks is a simple yet addictive game in which players use a platform at the bottom of the screen to catch falling blocks. The goal is to catch as many blocks as possible in order to score as many points as possible.

The game starts with a player-controlled platform in the bottom-center of the screen. Blocks of various shapes and colours begin to fall from the top of the screen at a consistent rate. To collect the falling pieces, the player must move the platform horizontally using the left and right arrow keys (or any other predefined controls).

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![Screenshot (107)](https://github.com/TusharKesarwani/Front-End-Projects/assets/76618190/74e40888-19c3-4c3e-81da-ee66623b47b6)

**Comment by thakurdiwakar** [comment]
Hey please assign me this issue @TusharKesarwani

**Comment by thakurdiwakar** [comment]
Assign me please @TusharKesarwani

**Comment by TusharKesarwani** [comment]
Game projects are not accepted
