### ISSUE TITLE
[New Project] Apple Calculator

### ISSUE THREAD

**Issue by yashpreet2707** [TusharKesarwani/Front-End-Projects#1029]
## **Describe the project**
It's a replica of an Apple Calculator. It is a good project. It is made using HTML, CSS, JavaScript.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
deployed link - https://apple-calculator-dupe.onrender.com/

## **Screenshots**
<img width="649" alt="Screenshot 2023-06-06 at 3 45 05 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/111020648/66631b98-ae98-4bff-9cec-e72a6c0a3dd8">

- If applicable, add screenshots to help explain your problem.

**Comment by yashpreet2707** [comment]
Thanks @TusharKesarwani , but you didn't assign me.

**Comment by joel5902** [comment]
Is this issue assigned to someone, if not assigned could you please assign this to me.

**Comment by SweetyPandey789** [comment]
I want to work on this ,could you assign this to me..

**Comment by TusharKesarwani** [comment]
Already present in the repo
