### ISSUE TITLE
Change the UI of Calculator

### ISSUE THREAD

**Issue by linga66** [TusharKesarwani/Front-End-Projects#1032]
I want to change the Buttons of the calculator page
I would like to change the shape of the buttons and want to give a good presentation

![Screenshot (496)](https://github.com/TusharKesarwani/Front-End-Projects/assets/103192975/29f3d790-4fd3-4549-b450-f3be98e56d61)

Assign me this issue @TusharKesarwani 
I can solve this
I'm a SSOC contributor

**Comment by Rajneesh2223** [comment]
i want to change the gradient of button and  i can see their is some spaces between which i want to modify it so i kindly request you to please assign me this project

**Comment by Jaskaran2609** [comment]
can you plz assign the issue i want to work on it
