### ISSUE TITLE
Tip Calculator

### ISSUE THREAD

**Issue by patnaikankit** [TusharKesarwani/Front-End-Projects#1033]
## **Describe the project**
A tip calculator is a web application that helps users calculate to calculate the tip for any restaurant bill. The web application will be built using HTML, CSS and Javascript.  Here are some details about the app's features:
1. The user will be prompted to enter the amount and the percentage of the bill they would like to tip.
2.  The app will then show the total amount to be paid.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ +] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

![Screenshot (44)](https://github.com/TusharKesarwani/Front-End-Projects/assets/116827173/a62f162f-07e0-4ef5-93e0-16ea69d4e6bd)

**Comment by patnaikankit** [comment]
@TusharKesarwani @harshit-paneri  Can you please assign me this issue under SSOC 2.0 contribution?
Thank You

**Comment by Insiyaya** [comment]
please assign this issue
