### ISSUE TITLE
UI of Zomato Clone

### ISSUE THREAD

**Issue by shruti8302** [TusharKesarwani/Front-End-Projects#1034]
**Is your feature request related to a problem? Please describe.**

![Screenshot (450)](https://github.com/TusharKesarwani/Front-End-Projects/assets/93856491/2b2cf299-6729-4549-a5af-9d236ca7c532)

**Describe the solution you'd like**
As a part of SSOC'23, I would like to improve the card components of Zomato Clone. Kindly assign this issue to me.

**Comment by aaviiothic** [comment]
hey, i would like to work on this, please assign me this issue.

**Comment by TusharKesarwani** [comment]
Already present in the repo
