### ISSUE TITLE
UI of Villa hotel website

### ISSUE THREAD

**Issue by shruti8302** [TusharKesarwani/Front-End-Projects#1035]
@TusharKesarwani As a part of SSOC'23, I would like to improve the UI of Villa hotel website. Kindly assign this issue to me.

**Comment by Akshatverma01** [comment]
@TusharKesarwani Sir please assign this project as I'm proficient in developing good UI for websites and I am sure to built the best UI for this project.

**Comment by weedertree** [comment]
Sir please assign me this project as i'd like to contribute, Regards

**Comment by mayurd8862** [comment]
Empower me with the opportunity to take on this project and make a significant impact!

**Comment by TusharKesarwani** [comment]
Create a new issue with proper description
