### ISSUE TITLE
PROJECT: Joke Teller 

### ISSUE THREAD

**Issue by akshit20421** [TusharKesarwani/Front-End-Projects#1037]
**PROJECT DESCRIPTION**

-->The Joke Teller project is an interactive web project designed to bring laughter to users' lives.
-->This project will utilize a speech API to convert text into spoken words, enabling the users to deliver the jokes audibly.
-->Users will be able to provide their name using the Voice Recognition API by giving a voice command such as "Please feed my {name}" or "Robo, my name is {name}".
-->The Voice Recognition API accurately captures the user's name from their spoken command.

**Comment by harshit-paneri** [comment]
already created.
