### ISSUE TITLE
Improving UI of E-Commerce landing Page

### ISSUE THREAD

**Issue by SportingDot1024** [TusharKesarwani/Front-End-Projects#1046]
**Describe the bug**
The CSS is not implemented correctly for E-Commerce Landing Page

**Expected behavior**
The links were to be working along with CSS, which was not happening in the landing page.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: Samsung A22 5G
 - OS: 13
 - Browser: Brave

Please assign it to me under SSOC 2.0

**Comment by harshitcompcode** [comment]
Assign me this issue under ssoc 2023

**Comment by Karansankhe** [comment]
I would like to do the issue

**Comment by mayurd8862** [comment]
Empower me with the opportunity to take on this project and make a significant impact!

**Comment by TusharKesarwani** [comment]
Create a new issue with proper screenshots
