### ISSUE TITLE
Youtube Clone

### ISSUE THREAD

**Issue by harshit-sharmaaa** [TusharKesarwani/Front-End-Projects#1049]
I want to add a Youtube Clone Project using HTML and CSS

<h1>Issue Type</h1>

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

![Screenshot_20230605_195838](https://github.com/TusharKesarwani/Front-End-Projects/assets/121124691/b3c50907-8e65-46d4-9113-61594d3ec0a2)

@Arun9739 Kindly assign me this

**Comment by harshit-sharmaaa** [comment]
@harshit-paneri Kindly assign me this

**Comment by Vaishnavikathar18** [comment]
@harshit-sharmaaa please assign me this issue

**Comment by Vaishnavikathar18** [comment]
@TusharKesarwani please assign me this issue

**Comment by harshit-paneri** [comment]
already assign to someone else, And they also send the PR.

> @TusharKesarwani please assign me this issue

**Comment by harshit-paneri** [comment]
> @harshit-sharmaaa please assign me this issue

Already assign to someone else, and they also send the PR
