### ISSUE TITLE
Stock Profit and Loss calculator 

### ISSUE THREAD

**Issue by abhiimali** [TusharKesarwani/Front-End-Projects#105]
A Front End Project To Calculate Stock Profit and Loss

**Comment by TusharKesarwani** [comment]
Please add any screenshot of the project
And elaborate how you are doing this calculation

**Comment by abhiimali** [comment]
UI Looks Like This :) 


![1673269053717](https://user-images.githubusercontent.com/55556198/211313431-17a4d646-5663-4fe7-b14c-11a1da236713.png)

**Comment by abhilipsasahoo03** [comment]
> UI Looks Like This :) 
> 
> 
> ![1673269053717](https://user-images.githubusercontent.com/55556198/211313431-17a4d646-5663-4fe7-b14c-11a1da236713.png)
> 

Can you also attach screenshot of the output it shows after entering the values?

**Comment by abhiimali** [comment]
Output UI : 
![image](https://user-images.githubusercontent.com/55556198/215832320-afc8e64e-cc1b-407a-841a-d52331979894.png)
