### ISSUE TITLE
Update readme of Armstrong Checker under SSOC 2.O

### ISSUE THREAD

**Issue by harshit-sharmaaa** [TusharKesarwani/Front-End-Projects#1051]
I got very frustrated when i don't see proper readme of a project, So i will update the readme in order to ease the idea for everyone to get a glimpse of a project.

I want to update the readme of Armstrong Checker Game Project
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/121124691/21d048fc-8ef9-402c-9fff-592510652d69)

@TusharKesarwani Kindly assign me this issue under SSOC 2.O

**Comment by TusharKesarwani** [comment]
Create a new issue with a proper explanation of the bug
