### ISSUE TITLE
Update readme of Stone Paper Game under SSOC 2.O

### ISSUE THREAD

**Issue by harshit-sharmaaa** [TusharKesarwani/Front-End-Projects#1052]
I got very frustrated when i don't see proper readme of a project, So i will update the readme in order to ease the idea for everyone to get a glimpse of a project.

I want to update the readme of Stone Paper Game Project
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/121124691/df00c0ea-5e04-4060-8c72-d75983b64474)

@TusharKesarwani Kindly assign me this issue under SSOC 2.O

**Comment by TusharKesarwani** [comment]
Create a new issue with a proper explanation of the bug
