### ISSUE TITLE
Improve UI of step-progress-bar Undder SSOC 2.O

### ISSUE THREAD

**Issue by harshit-sharmaaa** [TusharKesarwani/Front-End-Projects#1053]
i want to improve the UI of step-progress-bar project

As seen below , its very boring and a lot of page area is wasted , So i will improve the sizing and some css properties of this project.

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/121124691/1d0bd9bd-9124-48c9-b958-a09a0c31353f)

@TusharKesarwani Kindly assign this to me under SSOC 2.O

**Comment by shrutimishra27** [comment]
Hey @TusharKesarwani and @harshit-paneri , I would like to wok on the issue.
You may check my github profile, I have worked on various projects and UI/UX websites.

**Comment by harshit-paneri** [comment]
> Hey @TusharKesarwani and @harshit-paneri , I would like to work on the issue. You may check my github profile, I have worked on various projects and UI/UX websites.

Hey @shrutimishra27 This issue is created by @harshit-sharmaaa , you can create your own issues.
