### ISSUE TITLE
Update readme of 3D Maze under SSOC 2.O

### ISSUE THREAD

**Issue by harshit-sharmaaa** [TusharKesarwani/Front-End-Projects#1054]
I got very frustrated when i don't see proper readme of a project, So i will update the readme in order to ease the idea for everyone to get a glimpse of a project.

I want to update the readme of 3D Maze Project
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/121124691/fba02aaa-8557-4468-9241-e27a63acfc95)

@TusharKesarwani Kindly assign me this issue under SSOC 2.O

**Comment by TusharKesarwani** [comment]
Create a new issue with a proper explanation of the bug
