### ISSUE TITLE
Readme of Calendar project

### ISSUE THREAD

**Issue by harshit-sharmaaa** [TusharKesarwani/Front-End-Projects#1056]
As seen in Calendar project , the readme is not showing "Project Looks"

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/121124691/45eb16ef-7709-489c-9788-931699ea1aaf)

I will update the readme of this project

@TusharKesarwani Kindly assign me this issue under SSOC 2.O

**Comment by mayurd8862** [comment]
I become frustrated when I encounter a project without a comprehensive readme. Therefore, I will take the initiative to update the readme, ensuring that it provides a clear overview of the project and facilitates understanding for all users.
@TusharKesarwani please assign me this issue

**Comment by TusharKesarwani** [comment]
Create a new issue with a proper explanation of the bug and also do not create more than 4 issues at a time
