### ISSUE TITLE
Update readme of Calculator under SSOC 2.O

### ISSUE THREAD

**Issue by harshit-sharmaaa** [TusharKesarwani/Front-End-Projects#1057]
I got very frustrated when i don't see proper readme of a project, So i will update the readme in order to ease the idea for everyone to get a glimpse of a project.

I want to update the readme of Calculator Project
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/121124691/f05a9833-6623-4117-8489-d548e0fd58c9)
@TusharKesarwani Kindly assign me this issue under SSOC 2.O

**Comment by dalalsoham** [comment]
please assign this issue

**Comment by TusharKesarwani** [comment]
Create a new issue with a proper explanation of the bug and also do not create more than 4 issues at a time
