### ISSUE TITLE
[Bug]: 404 'Page Not Found' Error in Multiple Projects in Front-End-Projects List

### ISSUE THREAD

**Issue by NarendraKoya999** [TusharKesarwani/Front-End-Projects#1061]
**Describe the bug**
### [Issue Description]: 404 Page Not Found Error Happens in Multiple Projects When Click on Particular Project Live Link.

**To Reproduce**
1. Go to 'https://frontendprojects.netlify.app/'
2. Click on 'Projects Link in Nav Bar Section '
3. Scroll down to 'Projects Names: 1) Product Launching Website 2) Tindog Website 3) The Hangman Game'
4. Click on 'Particular Above Named 3 Project Live Links '
5. See error

**Expected behavior**

**Screenshots**
<img width="679" alt="404 Error" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/84512164/4e5e128f-16fb-4636-923f-f563e1ff87be">

**Desktop (please complete the following information):**
 - OS: [Microsoft Windows]
 - Browser [ Google Chrome]
 - Version [114.0.5735.110 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**
 - Device: [Redmi Note5 PRO]
 - OS: [Android 9]
 - Browser [Google Chrome]
 - Version [110.0.5563.116 (Official Build)]

**Additional context**

- This above Bug happens in 3 Projects in Front End Projects Website.
- Also, This Bug shown on Both Smartphones and Desktop Versions.

**Comment by The-Alan-Turing** [comment]
These projects do not exist in the repo.

**Comment by NarendraKoya999** [comment]
**Hi @TusharKesarwani . I have raised above Quote. Please respond to above Comment**
