### ISSUE TITLE
[Bug]: UI of Product Launching Website Project 'Live Title Card Screenshot' is Not Much Readable

### ISSUE THREAD

**Issue by NarendraKoya999** [TusharKesarwani/Front-End-Projects#1062]
**Describe the bug**
### [Issue Description]: UI of Product Launching Website Project Live Title Card Screenshot is Not Much Readable in Projects List Section.

**To Reproduce**
1. Go to 'https://frontendprojects.netlify.app/'
2. Click on 'Projects Link in Nav Bar Section'
3. Scroll down to 'Separate Projects Section'
4. See error on **Project Launching Website Project Live Title Card Screenshot**

**Expected behavior**

**Screenshots**
<img width="289" alt="Product" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/84512164/5a4927fc-0e11-4316-8097-dcfdfff98dc8">

**Desktop (please complete the following information):**
 - OS: [Microsoft Windows]
 - Browser [ Google Chrome]
 - Version [114.0.5735.110 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**
 - Device: [Redmi Note5 PRO]
 - OS: [Android 9]
 - Browser [Google Chrome]
 - Version [110.0.5563.116 (Official Build)]

**Additional context**

- **This above Bug Happens in Only Product Launching Website Project.**

**Comment by ayesha-firdaus** [comment]
can i work on this issue

**Comment by Pranay38** [comment]
Hey! I want to work on this issue

**Comment by NarendraKoya999** [comment]
Hi @TusharKesarwani . This Issue I am raised 3 weeks ago. That's time  What I am raised Product Launching Website Project is listed in your Projects List. But, currently, this Project is not in your Projects List.
- So, I can move to similar problems in Projects List and that Issues correct It
- Am I go with that Issues?

**Comment by NarendraKoya999** [comment]
**Hi @TusharKesarwani . I have Raised above Quote. Please respond to above Comment**
