### ISSUE TITLE
Weather Predictor

### ISSUE THREAD

**Issue by geetanjaliverma** [TusharKesarwani/Front-End-Projects#1063]
Hey, I want to add a weather predictor project to this Repo. It ia a simple HTML, CSS and JS based web app that uses weather API to predict weather. Please assign this to me.

Thanks

**Comment by sanju50201** [comment]
Can i get assigned to complete this project, however i will be using React instead of Pure JavaScript?

**Comment by pseudofool** [comment]
I would like to work on this. Please assign it to me.

**Comment by TusharKesarwani** [comment]
Already present in the repo
