### ISSUE TITLE
Search Bar Not working.

### ISSUE THREAD

**Issue by rahulrana701** [TusharKesarwani/Front-End-Projects#1064]
**Describe the bug**
The search bar is not working , it should search the project when user enters a project name he/she wants...

**Expected behavior**
it should search the project when user enters a project name he/she wants...

**Screenshots**
<img width="388" alt="Screenshot 2023-06-07 115338" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/123585591/393c0a84-b961-457a-a2fd-1fdf553d8b12">

**Comment by rahulrana701** [comment]
hi @TusharKesarwani I would like to work on this issue please assign it to me.

**Comment by Gyanthakur** [comment]
hi @TusharKesarwani I would like to work on this issue please assign it to me.

**Comment by rahulrana701** [comment]
Hi @TusharKesarwani assign it to me I will work on this issue..

**Comment by rahulrana701** [comment]
hi @TusharKesarwani please assign this issue to me.

**Comment by rahulrana701** [comment]
hi @TusharKesarwani why are you not responding ?? I want to work on this issue.

**Comment by RIYASANVI7** [comment]
hi @TusharKesarwani please assign this issue to me

**Comment by rahulrana701** [comment]
@TusharKesarwani  Why are you not assigning the issues brother , it's been 2 weeks I opened this issue and still no response
