### ISSUE TITLE
Front-End-Project : 3D Login Page

### ISSUE THREAD

**Issue by abhyuday1212** [TusharKesarwani/Front-End-Projects#1066]
-I want to redesign the UI of the login page by adding enhanced transitions and 3D Animations.

Features:
-Real-time 3D Annimations.
-Overall Ui Enhancement.
-Change the look but retain the feel of the page.

**Comment by Kiran-116** [comment]
Please assign this issue to me

**Comment by 1-23-smy** [comment]
i will work on it
