### ISSUE TITLE
Google clone: I would like to add Grid and Google Waffels on the top right corner once user will click on Grid Google waffles will appear

### ISSUE THREAD

**Issue by Swapnalighadge** [TusharKesarwani/Front-End-Projects#1069]
Hey @TusharKesarwani 

The grid of the nine small boxes that are found on the top right corner of the browser  i would like to add those 9 dots and  various Google products like Google Chrome and Gmail (Google Waffles).once user will click on those 9 dots nothing but Grid user will able to to see all Google Waffles hence it will be easy for the user to access various features of Google
Kindly assign me under SSOC
<img width="960" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/102608194/cc8ae2ec-226d-46a8-99ca-34dc95efa8c7">

**Comment by TusharKesarwani** [comment]
Already present in the repo
