### ISSUE TITLE
i want to add about us section in the footer part of website.

### ISSUE THREAD

**Issue by Praveenkumar07007** [TusharKesarwani/Front-End-Projects#1075]
The about us section could be implemented by adding a new page to the website or by adding a section to the footer. The section could include the following information:
1.Company name
2.Mission statement

I believe that adding an about us section to the website would be a valuable addition that would benefit both the company and its customers.

Thank you for your consideration.

**Comment by priya-thv** [comment]
assign it to me

**Comment by Praveenkumar07007** [comment]
hi @TusharKesarwani please this task assign it to me i want to work on this issue.
