### ISSUE TITLE
Timer and Stopwatch

### ISSUE THREAD

**Issue by starkver23** [TusharKesarwani/Front-End-Projects#1078]
## **Describe the project**
I want to create a countdown timer and stopwatch using html, css and js. The feature will be as soon as the timer ends there will a notification alert shown on the screen indicating that the countdown has ended
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [✅ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by starkver23** [comment]
@TusharKesarwani please assign this issue to me. Thanks

**Comment by Gyanthakur** [comment]
#1078 time counter issue it fixed
to
#1081   its is done 
<img width="949" alt="Screenshot 2023-06-08 124254" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/98226958/5cf63a3e-4ed1-4d1a-a811-f8b010eb4dff">

**Comment by Pranay38** [comment]
Hey! I want to work on this issue

**Comment by priyanshimaheshwari** [comment]
I want to work on this issue

**Comment by Akshatverma01** [comment]
Hello sir, I am eager to work on this issue as I am completely able to do this.
Here's the link you can refer to::  https://akshatverma01.github.io/Code-Clause-task1-STOPWACTCH-TIMER/


Please assign this issue to me . @TusharKesarwani
