### ISSUE TITLE
Shopping cart project , built with html,css,javascript and firebase (Full stack web app)

### ISSUE THREAD

**Issue by KaranSapra124** [TusharKesarwani/Front-End-Projects#1087]
## **Describe the project**
Shopping cart project built using html,css,javascript and firebase with database technology.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

Techstack used:-

FRONTEND TECH:-
HTML,CSS,JAVASCRIPT

BACKEND TECH:-
FIREBASE

## **Screenshots**

![Screenshot (626)](https://github.com/TusharKesarwani/Front-End-Projects/assets/88654249/2e1ac285-67cc-4d67-8cb6-9025ee08f3ff)

**Comment by TusharKesarwani** [comment]
Only front-end projects are allowed
