### ISSUE TITLE
new project: snake-water-gun game using javascript [SSOC'23]

### ISSUE THREAD

**Issue by Nikita06211** [TusharKesarwani/Front-End-Projects#1089]
## **Describe the project**
I would like to create a simple snake water gun game 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
game explanation:
the computer will make a random choice out of snake, water or gun and then the user gets to choose his/her choice.
Out of snake and water-> snake wins
out of snake and gun-> gun wins
out of gun and water-> water wins

## **Screenshots**

<img width="917" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/120494269/1604c21a-cea4-46cd-97bf-481a9c72996a">

<img width="920" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/120494269/c5dc6ad4-d1e6-40eb-979d-9b2bf0d1dd2a">

<img width="919" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/120494269/fb3946a0-4ac9-43ce-88d0-9506ee2f1267">

please assign me this issue under SSOC'23

**Comment by TusharKesarwani** [comment]
Game projects are not allowed
