### ISSUE TITLE
Microsoft Home Pgae clone 

### ISSUE THREAD

**Issue by Durgesh4993** [TusharKesarwani/Front-End-Projects#1092]
Demo Vedio :

https://github.com/TusharKesarwani/Front-End-Projects/assets/98798977/e09c242d-9ccf-42cb-8843-a9e9e0daf3cf

Technoloy Used 👍🏻 
HTML
CSS
JavaScript ..

**Comment by Zaid1681** [comment]
Heyy, @Durgesh4993 Kindly assign me this work , under SSOC , I am keen to develop thi page
