### ISSUE TITLE
Front-End-Projects : Chess

### ISSUE THREAD

**Issue by abhyuday1212** [TusharKesarwani/Front-End-Projects#1096]
The Chess UI in the project has some issues like-
-Improper Ui for the web.
-Choice of time control is not available.
-stopwatch is not there.
-Not ending the game if one opponent checkmates the other.
-pawns can move only one step instead of two.

Features addition-
-Proper Time control option.
-Stopwatch addition.
-Fixing the Ui and making the page responsive.
-Fixing the logical code-based errors in the code.
-Fixing the overall UI of the application.

![chess](https://github.com/TusharKesarwani/Front-End-Projects/assets/115206840/816da8d8-48b9-496a-80e7-4de2b3d15d85)

@TusharKesarwani  Kindly assign this issue to me.

**Comment by Gyanthakur** [comment]
assign it to me

**Comment by Geek-Tekina** [comment]
Kindly issue this to me.

**Comment by Srilekha-09** [comment]
assign it to me

**Comment by abhyuday1212** [comment]
kindly open this issue as i am working on this. I just have not raised the PR as it is not complete yet
@TusharKesarwani
