### ISSUE TITLE
Want to Add Glowing Text Animations

### ISSUE THREAD

**Issue by Mansi8874** [TusharKesarwani/Front-End-Projects#1097]
## **Describe the project**
The project aims to create a glowing text animation effect using HTML and CSS. The purpose is to add a visually appealing and attention-grabbing animation to a heading on a web page.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
I want to work on this issue. Please assign this issue to me @TusharKesarwani 

## **Screenshots**
Like this
![Screenshot (199)](https://github.com/TusharKesarwani/Front-End-Projects/assets/101468475/56a8d88a-8c5d-41d8-a599-9fb3aa2f20e6)
![Screenshot (200)](https://github.com/TusharKesarwani/Front-End-Projects/assets/101468475/e90c7ac4-c588-4f64-8812-3c1eff44c1c2)

**Comment by shraddhatech16** [comment]
I want to work on this issue. Please assign this issue to me
