### ISSUE TITLE
3D Rotating Cube

### ISSUE THREAD

**Issue by Mansi8874** [TusharKesarwani/Front-End-Projects#1098]
## **Describe the project**
The project aims to create a 3D rotating cube using HTML, CSS, and JavaScript. The end result will be an interactive cube that rotates in 3D space.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
I want to work on this issue. Please assign this issue to me @TusharKesarwani

**Comment by Gyanthakur** [comment]
Assign it to me.
