### ISSUE TITLE
 Bug Report for BeautyZone Portfolio Section

### ISSUE THREAD

**Issue by Aqua-beast** [TusharKesarwani/Front-End-Projects#1100]
**Describe the bug**
After thoroughly evaluating and testing the BeautyZone project, I have identified two specific issues in the portfolio section. Firstly, unnecessary space and alignment problems affect the overall layout. Secondly, the "Submit Now" button at the bottom appears to have excessive padding, resulting in an irregular shape and affecting the visual harmony of the section.

**To Reproduce**
1. Go to the BeautyZone project website.
2. Scroll down to the portfolio section.
3. Observe the spacing and alignment of the portfolio items.
4. Notice the irregular shape and padding of the "Submit Now" button.

**Expected behavior**

1. The portfolio section should have consistent spacing and alignment, ensuring a visually appealing layout.
2. The "Submit Now" button should maintain a proper shape without excessive padding, providing a neat and professional appearance.

**Screenshots**
<img width="1068" alt="Screenshot 2023-06-08 234546" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/85673066/d83aed05-0b15-4f9f-abec-33308a84934d">
<img width="1067" alt="Screenshot 2023-06-08 234611" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/85673066/bc3b2ada-0a0c-4345-bf28-2b24ac68dfc5">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I kindly request @TusharKesarwani to assign this issue to me under the #SSOC 2.0 project. By addressing these concerns, I aim to improve the user experience and ensure that the portfolio section of the BeautyZone project aligns with the desired design and functionality.

**Comment by avinashji1302** [comment]
Please assign me this!

**Comment by priyanka-6675** [comment]
sir plz assing this issue to  me..
