### ISSUE TITLE
Enhancing UI -- Armstrong Checker

### ISSUE THREAD

**Issue by akshit20421** [TusharKesarwani/Front-End-Projects#1101]
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/103023426/0742d23a-ca63-4df5-8ba9-72731ab08dd2)
Some issues (UI)
-->Monotonous Colors:
The use of monotonous colors in the UI can make it appear dull and uninteresting. 
-->Clear Placeholder Text: The placeholder text should be placeholder-specific, indicating the format or expected input, rather than appearing as if it is already filled. This can be achieved by using lighter or more transparent text for the placeholder compared to the actual input text.
-->The current background styling of the Armstrong Checker UI presents a monotonous and simplistic appearance, which detracts from the overall visual appeal and user experience. The lack of variety and visual interest in the background design can make the interface feel bland and unengaging.

**Comment by khushi-shrama** [comment]
Hi @TusharKesarwani @harshit-paneri ,

I'd like to contribute to this project and I'm interested in working on the issue #1101. I believe I can add value to this problem. If possible, could you assign this issue to me? I'm excited to collaborate with it and compete in SSOC 2.0.

Thank you for your consideration!

**Comment by akshit20421** [comment]
**Kindly assign the issue to me @harshit-paneri @TusharKesarwani**

**Comment by akshit20421** [comment]
Kindly assign the issue to me @harshit-paneri @TusharKesarwani
