### ISSUE TITLE
Add new project: Password Generator

### ISSUE THREAD

**Issue by shubhanshurav** [TusharKesarwani/Front-End-Projects#1103]
## **Describe the project**

Hi @TusharKesarwani, I want to add Password generator web App. so please assign me this issue.

## Expected behavior

- In this project, you can generate up to 20-digit random password.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

**Comment by mayurd8862** [comment]
Empower me with the opportunity to take on this project and make a significant impact!

**Comment by sneha097** [comment]
I would appreciate it if you could assign me an issue to work on. I'm eager to make a positive impact on the project.

**Comment by RIYASANVI7** [comment]
hi @TusharKesarwani please assign this issue to me

**Comment by dpvasani** [comment]
please assign to me this project so i can create pull request i have made this project

**Comment by dpvasani** [comment]
@TusharKesarwani

**Comment by dpvasani** [comment]
@TusharKesarwani assign to me

**Comment by TusharKesarwani** [comment]
Already present in the repo
