### ISSUE TITLE
Scientific Calculator

### ISSUE THREAD

**Issue by mdvadiyatnaqvi** [TusharKesarwani/Front-End-Projects#1106]
## **Describe the project**
Scientific Calculator is the project which will be developed using HTML, CSS and JavaScript which will be able to perform all the operations like sin, cos, tan, log, square root, n^n, mod, factorial and other functionality as well.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**
![sciCalc](https://github.com/TusharKesarwani/Front-End-Projects/assets/127572794/a2165d3e-bce8-42c7-b0cc-434934db4c86)

Kindly Consider this issue under SSOC 2.0
And Kindly assign this issue to me!

**Comment by mdvadiyatnaqvi** [comment]
Hey @TusharKesarwani 
Kindly assign this issue to me under SSOC 2.0

**Comment by noobcoder007-exe** [comment]
Hey I am a contributor under SSoC'23...please assign it to me.

**Comment by Khushi6517** [comment]
I am a contributor in ssoc 2.0.Can you assign this issue to me.

**Comment by mayank2mahi** [comment]
@TusharKesarwani Please sir assign me this issue under ssoc
