### ISSUE TITLE
Improve the card UI

### ISSUE THREAD

**Issue by whiteknight16** [TusharKesarwani/Front-End-Projects#1110]
**Is your feature request related to a problem? Please describe.**
The cards on homepage doesn't look good
**Describe the solution you'd like**
Will update the css chagning fonts and other stuffs
**Describe alternatives you've considered**
None as such
**Additional context**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/111869559/d0147994-a2d0-4bf2-91ff-60bcdea61b31)

**Comment by whiteknight16** [comment]
kindly assign it to me

**Comment by sneha097** [comment]
I kindly request the opportunity to be assign this issue and to me. I am confident in my ability to deliver high-quality solutions that will positively impact the project.

**Comment by harshit-paneri** [comment]
> kindly assign it to me

mention the project URL also
