### ISSUE TITLE
Love result predictor

### ISSUE THREAD

**Issue by whiteknight16** [TusharKesarwani/Front-End-Projects#1111]
## **Describe the project**
A handy lov result predictor that takes the name of two persons and give them a love score based on certain algo
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Based on HTML CSS and JS
## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/111869559/ffd4166d-28c3-4ec2-9a28-090b8124a6f0)

**Comment by whiteknight16** [comment]
kindly assign me this issue

**Comment by TusharKesarwani** [comment]
Not required
