### ISSUE TITLE
[SSoC'23] Realtime Currency Converter

### ISSUE THREAD

**Issue by amansgith** [TusharKesarwani/Front-End-Projects#1115]
## **Describe the project**
I would like to add a frontend project of realtime currency conversion website which will convert the amounts using live country rates and convert to other countries currency, also it will show the unit rates of that countries selected.

##Tech Stack used
HTML, CSS, Javascript, and Basics of API

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
I will be contributing this project under SSoC'23.. Please assign this issue to me.
Thank you

**Comment by RIYASANVI7** [comment]
hi @TusharKesarwani please assign this issue to me

**Comment by mayurd8862** [comment]
please assign me this issue

**Comment by mayank2mahi** [comment]
@TusharKesarwani Please assign me this issue, i eagerly want to work on it
