### ISSUE TITLE
New Project Request: Adding Unit Converter

### ISSUE THREAD

**Issue by arcVaishali** [TusharKesarwani/Front-End-Projects#1117]
## Description
I want to add a **Unit Converter** that can convert a value from one unit to another. This unit converter will contain,
 - temperature converter
 - length converter
 - weight converter
 - volume converter
 -  area converter
 -  time converter

## Example-
<img width="914" alt="unit-converter-1" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/98754461/e0f48c74-e5fb-4b3c-bba0-a14854365fbd">
<img width="914" alt="unit-converter-2" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/98754461/5ea8d163-33e0-4056-926b-3465cc7fcd61">

## Issue Type:
-  **New Project**

**Comment by Akshatverma01** [comment]
Hii!! Recently in a one-month internship I develop a unit convertor . Please assign this issue to me , I can easily handle the bug.
The link of my unit convertor is as:  https://akshatverma01.github.io/Code-Clause-Unit-Converter/
![Screenshot (33)](https://github.com/TusharKesarwani/Front-End-Projects/assets/121783296/1055fea2-7b20-47e0-bf07-0ffb3ade5316)

**Comment by arcVaishali** [comment]
**@TusharKesarwani** Kindly assign me this issue under SSOC label.
