### ISSUE TITLE
Apple's Landing Page UI Clone

### ISSUE THREAD

**Issue by anurag-327** [TusharKesarwani/Front-End-Projects#1118]
## Apple's Website Landing UI Clone
I would like to create a UI clone of Apple's Website

## Issue Type:
-  New Project

## Additional Description
I have a good experience working with tailwind CSS so I would be using HTML, Tailwind CSS and JavaScript to clone Apple's Landing page.

## Screenshots

- So the project would look something like this
![Screenshot 2023-06-09 222325](https://github.com/TusharKesarwani/Front-End-Projects/assets/98267696/ce3221bc-e990-49e7-9507-c6b551352fbd)

@TusharKesarwani I would request you Please assign this issue to me.

**Comment by anurag-327** [comment]
@TusharKesarwani  do assign this issue to me

**Comment by anurag-327** [comment]
Please assign this issue to me...

**Comment by priyanka-6685** [comment]
@TusharKesarwani please assign this apple website landing ui clone
