### ISSUE TITLE
Website UI not responsive..

### ISSUE THREAD

**Issue by rahulrana701** [TusharKesarwani/Front-End-Projects#1120]
**Describe the bug**
The ui of the website is not responsive , it is breaking at various points.

**Expected behavior**
The ui of the wesbite should be completely responsive for all widths 

**Screenshots**

<img width="154" alt="Screenshot 2023-06-10 000306" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/123585591/30aaaae5-cee1-4a47-b6b8-34ebd269771d">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

I would like to work on this issue , I will make the ui responsive for all points , please assign it to me..

**Comment by Akshatverma01** [comment]
Hey, I am proficient in web and can fix this bug . I will make it responsive for all ratios. Please assign this to me.

**Comment by noobcoder007-exe** [comment]
Hey... I am a contributor in SSoC'23...I can resolve this.

**Comment by rahulrana701** [comment]
hi @TusharKesarwani  it's been so long why are you not assigning this issue , I have opened it last week and I want to work on it , so please assign it to me
