### ISSUE TITLE
UI changes in DAY PLANNER

### ISSUE THREAD

**Issue by shekaushik** [TusharKesarwani/Front-End-Projects#1124]
**While going through the code of this project I found some issues /problems :**
The UI of the project is boring .
There is no edit/delete icon in task bars .
There is no way to track /keep log if a task has been completed before it assigned time.

**The solution I'd like to implement**
Making the UI colourful and add a feature to switch color palatte according to user's preference.
Adding a edit/delete icon to the right most of task bars.
Adding a checklist to keep log of the work done priorly.

**Comment by pkd019** [comment]
Hey @TusharKesarwani I want to add this project. please assign me this issue under SSOC'23.
