### ISSUE TITLE
Rock Paper scissor game under SSOC 2.O

### ISSUE THREAD

**Issue by harshit-sharmaaa** [TusharKesarwani/Front-End-Projects#1127]
## **Describe the project**
Rock Paper Scissor Game Made using HTML CSS and JavaScript
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

My final project will look something like this
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/121124691/6a7291b2-8f38-4ab1-8353-b6be72fcf13e)

**Comment by harshit-sharmaaa** [comment]
@TusharKesarwani @harshit-paneri Kindly assign me this under SSOC 2.O

**Comment by Rajneesh2223** [comment]
in this project i can contribute in so i request you to kindly assign this to me under ssoc 2.0

**Comment by harshit-paneri** [comment]
already created
