### ISSUE TITLE
Adding functionality in Project - BMI Calculator of adding height in ft also

### ISSUE THREAD

**Issue by MohitNamdev22** [TusharKesarwani/Front-End-Projects#1130]
**Is your feature request related to a problem? Please describe.**
In the project BMI calculator, there is no option for entering height in Ft there is only a cm option, so it sometimes becomes too difficult for users to use the app.

**Describe the solution you'd like**
What can be done to solve this is adding a drop-down option for both cm and ft, then the user can select either from both of them.
Can I work on this under SSOC'23?

**Additional context**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/89779447/f2f00897-41dc-4eb3-807b-58a8454a00eb)

**Comment by pkd019** [comment]
Hey @TusharKesarwani I want to add this project. please assign me this issue under SSOC'23.

**Comment by ronakmunjapara** [comment]
Hello. I am new and would love to contribute.
I would like to fix this concern, if no one is already on it.

**Comment by abhipandey1402** [comment]
I want to work on this issue and also allow me to improve UI if possible. 
along with the height part, we can also give optional units for weight like pounds and kg because most fitness freaks and the global market prefer pound unit which would be great for user experience.
