### ISSUE TITLE
WindBits Project

### ISSUE THREAD

**Issue by kanishkakataria** [TusharKesarwani/Front-End-Projects#1134]
## **Describe the project**

- WindBits ,the application for showcasing current atmospheric conditions is a handy go to weather app where the user can fetch atmospheric conditions from different cities around the world.Contributing to this will definitely leverage the new creative ideas I can fed to it.
- I would like to pin point the main features that I would like to add to this.

- I would like to add pop up messages showcasing weather Travelling should be done,an umbrealla should be carried,hat should be worn according to the weather conditions in a fancy but elegant manner to keep the page user friendly.

- According to the weather an image related to that weather would also get displayed or an animation accordingly.
- Would also like to modify if I come across any change during the creation

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Please Assign this issue under SSOC'23.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by kanishkakataria** [comment]
@TusharKesarwani or @harshit-paneri please assign this issue to me

**Comment by harshit-paneri** [comment]
Issue is close due to no update or PR

**Comment by kanishkakataria** [comment]
@harshit-paneri i am working on the project ....due to 2 issues assigned i was not able to update pr .
Moreover pr is updated after the completion right but it was still on going

**Comment by kanishkakataria** [comment]
I request you to reassign me as i m on the verge of its completion. Thank you

**Comment by harshit-paneri** [comment]
> @harshit-paneri i am working on the project ....due to 2 issues assigned i was not able to update pr . Moreover pr is updated after the completion right but it was still on going

you raise 2 issues and both are assign to you but due to this others contributors are waiting, I suggest please raise one issue at a time.
Now this issue is assign to other

**Comment by kanishkakataria** [comment]
@harshit-paneri the other issue is of other project .
We were not being checked on this before .
Now i am about to complete. Someone will start it now.what should i do now

**Comment by harshit-paneri** [comment]
you can create a unique feature in your project, make sure the unique feature is main feature

**Comment by kanishkakataria** [comment]
Either there should be like no one else can raise issue on the same issue but here 3 people did.
The one who starts doing it and the ones who are waiting are both stuck .
I request you to see this as it creates problem for all
@harshit-paneri

**Comment by kanishkakataria** [comment]
@harshit-paneri i mentioned unique feature of pop up message suggesting wearables for different weather which wasn't there before n so it got assigned to me.

**Comment by kanishkakataria** [comment]
I request @TusharKesarwani and @harshit-paneri to seek to the above problem please .
Hope to hear from you soon

**Comment by harshit-paneri** [comment]
> 

Okay, please give screen shot of your current progress

**Comment by kanishkakataria** [comment]
@harshit-paneri below attatching ss of the work done till date....styling and other modifications of background are still left as i would be doing at the end of work as it requirements adjustments accordingly
