### ISSUE TITLE
Product Preview Card

### ISSUE THREAD

**Issue by MisterMickey** [TusharKesarwani/Front-End-Projects#1136]
## **Describe the project**

Product Preview Card using HTML and CSS

## Issue Type:
- [x] New Project

Kindly assign me this issue under SSOC

## **Screenshots**
![d0bm3lh8bp36gyi3jiop](https://github.com/TusharKesarwani/Front-End-Projects/assets/93720428/dd7e68ec-df42-445d-88f3-bba102d5a35c)

**Comment by TusharKesarwani** [comment]
Already present in the repo
