### ISSUE TITLE
Testimonial Grid Section 

### ISSUE THREAD

**Issue by MisterMickey** [TusharKesarwani/Front-End-Projects#1137]
## **Describe the project**

Testimonial Grid Section using HTML and CSS

## Issue Type:
- [x] New Project

## **Screenshots**

![desktop-preview](https://github.com/TusharKesarwani/Front-End-Projects/assets/93720428/efed98ea-0353-4974-a23b-c41baf543bee)

**Comment by harshsinghcs** [comment]
Sir, I do not understand the issue. can you describe it? I would be happy to work on that and it would be a pleasure for me to work on that.

**Comment by TusharKesarwani** [comment]
Already present in the repo
