### ISSUE TITLE
FAQs Box are in improper size..

### ISSUE THREAD

**Issue by imranah10** [TusharKesarwani/Front-End-Projects#1138]
**Describe the bug**
FAQs Boxes are in improper size.

**To Reproduce**
1.Click FAQs box.
2.Box contents are not fit.
3.it appears only on large devices.

**Expected behavior**
Now it works on all devices.

**Screenshots**
![Educational-Website](https://github.com/TusharKesarwani/Front-End-Projects/assets/95746830/e914f4a9-822b-4de0-9e4b-799abe1e2be3)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Shu12388y** [comment]
@imranah10 can you assign this issue me
