### ISSUE TITLE
Adding a project Tripocity

### ISSUE THREAD

**Issue by viveksondhiya** [TusharKesarwani/Front-End-Projects#114]

**Comment by viveksondhiya** [comment]
Added the Tripocity project

**Comment by abhilipsasahoo03** [comment]
@viveksondhiya please link the issue to your PR.

**Comment by viveksondhiya** [comment]
i already added the project but where I can find my pr

**Comment by abhilipsasahoo03** [comment]
> i already added the project but where I can find my pr

If you have created a PR, then it must be present in the list of your recent PRs. If it's merged/closed, look for your merged/closed PRs list. Then copy the issue  number and link it to that PR like: `closes Issue #issue_number`>

**Comment by viveksondhiya** [comment]
![image](https://user-images.githubusercontent.com/98210740/214919399-cc69a490-c7df-4658-b657-82942e7a41f2.png)

@abhilipsasahoo03  this one..?

**Comment by abhilipsasahoo03** [comment]
#67

**Comment by abhilipsasahoo03** [comment]
Okay I'm closing this issue now.
