### ISSUE TITLE
[SSoC'23] Fixing the UI of GitHub Profile Wrapper project

### ISSUE THREAD

**Issue by rishabhchaudhary0210** [TusharKesarwani/Front-End-Projects#1141]
**Is your feature request related to a problem? Please describe.**
The UI of the GitHub Profile Wrapper is totally broken and looks really ugly and presents a bad user experience.

**Describe the solution you'd like**
I would like to fix it to make the UI better and responsive to smaller screens.
Also fix the functioning as per the description of the project.

**Describe alternatives you've considered**
If not fixing the existing page it could be totally revamped and made from scratch and hence be given a total new look.

**Additional context**

Kindly Assign me this Issue under SSOC'23
Present Look of the broken UI
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/97378312/05f558ae-8f62-4c4e-a632-efcff781d188)

**Comment by avinashji1302** [comment]
Please assign me this .... I would like to fix it
