### ISSUE TITLE
New Blog Site

### ISSUE THREAD

**Issue by Anirudh3167** [TusharKesarwani/Front-End-Projects#1142]
## Blog Site
A place for everyone to blog

### Project Name
**Blog Site**
### Features
A blog site with better UI / UX. 
Built on NextJs
Fully designed
Multi page website
The design is responsive to smaller screen size
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

Kindly assign me this issue

## **Additional context**
With the power of NextJs the website can also be connected with the backend too

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/77240291/5855be4c-0d3e-4ec4-a51c-b4872894511b)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/77240291/f4380d23-888d-44c0-85d7-5398b40a25bf)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/77240291/421e9a7b-2686-49fb-8845-c0c65ee6d1b5)

- If applicable, add screenshots to help explain your problem.

**Comment by Manishkr1007** [comment]
hii @TusharKesarwani  please assign me in this issue.

**Comment by Anirudh3167** [comment]
@Manishkr1007 I have worked on it.
Just waiting for the assignment

**Comment by Niranjan-Kumar-Singh** [comment]
Let me work on this project. Please assign this project to me.

**Comment by Niranjan-Kumar-Singh** [comment]
Let me get the chance
