### ISSUE TITLE
Weather Dashboard

### ISSUE THREAD

**Issue by AnkitMajee** [TusharKesarwani/Front-End-Projects#1146]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
Features of the Project
This is very useful project. This project is used for any Weather Website.

*FEATURES*
1. Search Weather in Your City
2. See Temperature
3. See Humidity
4. See Wind Speed
5. See UV Index
6. See 5 Days Weather
7. Clear Search History etc.

***************************************

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/76817118/364883e5-071d-453a-9e8e-6ef79eab254d)

- If applicable, add screenshots to help explain your problem.

**Comment by tanbirali** [comment]
Hey Can I work on this issue?

**Comment by mayurd8862** [comment]
@TusharKesarwani please assign me this issue...

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
