### ISSUE TITLE
calculator logo should be a png image

### ISSUE THREAD

**Issue by ivedmohan** [TusharKesarwani/Front-End-Projects#1148]
![image_2023-06-10_230630321](https://github.com/TusharKesarwani/Front-End-Projects/assets/118909117/10822016-56e0-4090-8b5a-e0df427d5ebf)

**I would like to make calculator logo image into png so that white border around it will be removed and it will look good**

**Comment by ivedmohan** [comment]
Assign me this issue @TusharKesarwani

**Comment by RAJharsh02** [comment]
hi @TusharKesarwani  i want to work on this issue please assign this to me

**Comment by ivedmohan** [comment]
@RAJharsh02 let me work on this issue I haven't got any and I have raised it this will be my 1st issue

**Comment by mayurd8862** [comment]
please Empower me with the opportunity to take on this project and make a significant impact!

**Comment by vibhuti0** [comment]
@TusharKesarwani  i would be happy to work on this issue . Please assign me the issue.
