### ISSUE TITLE
Snake Game 

### ISSUE THREAD

**Issue by Ayush9951** [TusharKesarwani/Front-End-Projects#1149]
Hi @TusharKesarwani, I am a contributor in SSOC'23.
I want to add a new project in the repository.
It's a simple snake game which I'll create using JavaScript.
please assign me this task under label ssoc'23

**Comment by Saminakalwar** [comment]
hey I'm  Samina SSOC'23  contributor .I am interested to add a snake game in your repisitory .Kindly assign me this task for which I can assure u It will be likeable.

**Comment by TusharKesarwani** [comment]
Game projects are not accepted
