### ISSUE TITLE
Netflix Landing Page Clone

### ISSUE THREAD

**Issue by champati-v** [TusharKesarwani/Front-End-Projects#1150]
## **Describe the project**
Netflix landing page clone using HTML and CSS.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
This website is responsive for mobile devices.

## **Screenshots**

![Screenshot (2)](https://github.com/TusharKesarwani/Front-End-Projects/assets/108168139/9ff0bd6a-528d-490e-97d3-797c27adbd9f)
![Screenshot (3)](https://github.com/TusharKesarwani/Front-End-Projects/assets/108168139/02bdcf85-faaa-4f57-ab5c-0393d2e21db6)

**Comment by champati-v** [comment]
Hii @TusharKesarwani.
Apologies, actually I created a PR without getting assigned first. Can you pleaes assign this issue to me.
Thank you.

**Comment by harshit-paneri** [comment]
> Hii @TusharKesarwani. Apologies, actually I created a PR without getting assigned first. Can you pleaes assign this issue to me. Thank you.

okay but next time make sure you can only send PR to assigned issues
