### ISSUE TITLE
Url Shortener 

### ISSUE THREAD

**Issue by Rushabt11** [TusharKesarwani/Front-End-Projects#1151]
## **Describe the project**
A Url Shortener will be able to shorten the website links. basically, it is a service that helps to make a website URL/link concise and clear. There is no project in the repository about URL shorteners. The shortened URL redirects users to the original, longer URL when clicked. Social media platforms often have character limits for posts or tweets. URL shorteners allow you to share long links in a concise and space-efficient manner. 

For Building Url Shortener, I will use a simple API for shortening the website URL, and also users will be able to see the total number of visits to shortened url visits, share the shortened URL with social media sites, etc.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
There are several URL shorteners available on Google such as bit.ly, TinyURL,rebrand.ly. Mostly many URL shorteners are used for branding and marketing purposes. Also Some Major Issues of Url Shorteners regarding their Security. These are some things that need to be ensured while using any Url Shortener.

**Comment by uttam-kumar-sahoo** [comment]
import pyshorteners
def shorten_url(url):
    s = pyshorteners.Shortener()
    short_url = s.tinyurl.short(url)
    return short_url

long_url = input("Enter a URL")
short_url = shorten_url(long_url)
print("Short URL:", short_url)
