### ISSUE TITLE
Hunt Your Card

### ISSUE THREAD

**Issue by dhruvishavaghani** [TusharKesarwani/Front-End-Projects#1152]
## **Describe the project**
Hunt Your Card is a simple card game based on selecting the correct card by player. 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
- There will be 4 shuffling cards, the front side of the cards will be hidden.
- One target card will be given.
- The player has to randomly select one card from the shuffling cards.
- If the selected card is the same as the target card points will be incremented.

## **Screenshots**

![Hunt_Your_Card](https://github.com/TusharKesarwani/Front-End-Projects/assets/109460833/d792410d-dc8f-445a-a1a9-340f28dccac4)

**Comment by zugzwang03** [comment]
Game projects not allowed anymore.
