### ISSUE TITLE
Add logo finder

### ISSUE THREAD

**Issue by devWonderkind** [TusharKesarwani/Front-End-Projects#1153]
## **Describe the project**
It's a website for find a logo. Here you can type URL of website and you can find logo as well as download logo.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Screenshots**

![LF](https://github.com/TusharKesarwani/Front-End-Projects/assets/110322061/1ef0b350-1d2b-46a0-8c75-eab2075f46db)

![LF2](https://github.com/TusharKesarwani/Front-End-Projects/assets/110322061/6cf95b23-72c0-40a4-ab7e-884a3a852573)

**Comment by coder-chahal** [comment]
Heyy @TusharKesarwani I want to add this project. please assign me this issue under SSOC'23.

**Comment by zugzwang03** [comment]
#281 is already done.
