### ISSUE TITLE
Dropdown menu of Weather site

### ISSUE THREAD

**Issue by suma30** [TusharKesarwani/Front-End-Projects#1155]
**Describe the bug**
There is a line after the second place name which is not required in the dropdown menu of places.

**Screenshots**

![Screenshot (44)](https://github.com/TusharKesarwani/Front-End-Projects/assets/112741893/95d8a413-5226-4130-920f-6b4b9a992d4c)

I want to remove that line and make it look good,
Please assign me this issue @TusharKesarwani

**Comment by zugzwang03** [comment]
That website is quite static otherwise even. Try to make that dropdown clickable, add pages leading to usage guide, and about this app, also make the card's length a bit longer in order to make that visually attractive.

**Comment by suma30** [comment]
Can I know what information to include in about and usage guide pages, should it be my own or could you give any idea please

**Comment by zugzwang03** [comment]
Write on your own, an abstract about how the app work, and its motive
