### ISSUE TITLE
Netflix Frontend Clone Website 

### ISSUE THREAD

**Issue by harshal2002** [TusharKesarwani/Front-End-Projects#1156]
## **Describe the project**
NetFlix Frontend Clone Website is a frontend clone of the official website of Netflix created using HTML and CSS. It was made with the aim to understand the frontend design of the Netflix website

## Issue Type:
- [ ✔] New Project

## **Additional context**
GitHub repository: https://github.com/harshal2002/NetflixClone

I will follow the code of conduct
## **Screenshots**
![Screenshot (555)](https://github.com/TusharKesarwani/Front-End-Projects/assets/76609079/2226c9f5-1b66-456f-ad4b-8b42e60aeb71)

![Screenshot (556)](https://github.com/TusharKesarwani/Front-End-Projects/assets/76609079/affc8eb8-2ce2-4a68-94d4-780444b2e268)

![Screenshot (557)](https://github.com/TusharKesarwani/Front-End-Projects/assets/76609079/0dd2647e-4b31-429a-b09f-24e43302446f)

**Comment by champati-v** [comment]
Hii @harshal2002 as I have already created a pull request for Netflix landing page clone, you may look for some other issues/projects.
Thank you!

**Comment by harshal2002** [comment]
> Hii @harshal2002 as I have already created a pull request for the Netflix landing page clone, you may look for some other issues/projects. Thank you!

Hello, @champati-v I saw that you made a pull request without the issue getting assigned to you which is like breaking the rules. On the other hand, I have mentioned all the required information and waiting patiently for @TusharKesarwani 's reply. If the project maintainer wants then I shall look for some other issue

**Comment by harshal2002** [comment]
@TusharKesarwani Please assign this issue to me so that I can make my PR as I already have my project ready. Thankyou

**Comment by zugzwang03** [comment]
#1047 is already working on it. So closing this issue which is created later.
