### ISSUE TITLE
Projects/Dynamic js Quiz

### ISSUE THREAD

**Issue by pancham1305** [TusharKesarwani/Front-End-Projects#1159]
**Is your feature request related to a problem? Please describe.**
We can make it more dynamic by API integration that sends 10 random questions so a person cannot just read the answers from javascript file. we can also make it such that if a person leaves the screen for more than 5 seconds then the document will automatically submitted.

**Describe the solution you'd like**
Using an API "https://the-trivia-api.com/" we can make it more dynamic and use javascript to make it difficult to cheat making it a nearly perfect quiz app.

**Describe alternatives you've considered**
- API integration: `https://the-trivia-api.com` which makes the site more dynamic.
- feature which doesn't allow the person handling quiz to leave the screen for more than 5 seconds.

**Comment by Divyanshu9822** [comment]
great idea dude 👍
