### ISSUE TITLE
Rent Wheels App

### ISSUE THREAD

**Issue by tarunvyshnav777** [TusharKesarwani/Front-End-Projects#1162]
## **Describe the project**
I want to add a Car rental responsive website.

## Issue Type:

- [ ] Feature Request
- [ ] Bug Report
- [ ] Documentation
- [ ] New Project

## **Screenshots**
The website will be responsive with all the required features.
![Screenshot (24)](https://github.com/TusharKesarwani/Front-End-Projects/assets/105963438/d7ea5b95-4091-404f-a3bb-b40a0c82c908)

could you please assign me this under SSOC'23.

**Comment by zugzwang03** [comment]
make it using HTML, CSS and JS only.
