### ISSUE TITLE
Cafe Landing Page

### ISSUE THREAD

**Issue by Kunal9155** [TusharKesarwani/Front-End-Projects#1168]
A responsive landing page for a cafe , it can be use for promotional and advertisement purposes.!
assigned me with this issue @TusharKesarwani 
Please consider this !

**Comment by zugzwang03** [comment]
Show some glimpses of what you wish to do.

**Comment by Kunal9155** [comment]
sure , 
I created this " https://kunal9155.github.io/Cafe-WebPage/ " 
I want to add this work in open source community. please consider this !

**Comment by Kunal9155** [comment]
hey

**Comment by Kunal9155** [comment]
hey
created Pull Request for the same #1254 
Thank You

**Comment by Kunal9155** [comment]
created PR #1255 for the same
