### ISSUE TITLE
 Typing Test Web App - JavaScript Implementation

### ISSUE THREAD

**Issue by neeraj542** [TusharKesarwani/Front-End-Projects#1173]
## **Describe the project**
Create a web-based typing test application using HTML, CSS, and JavaScript. The goal of this project is to provide users with a platform to practice and improve their typing speed and accuracy. The application should present users with a passage of text and track their typing performance, including words per minute (WPM), accuracy percentage, and elapsed time.

## Issue Type:

- [x] Bug Report
- [x] Feature Request
- [x] Documentation
- [x] New Project

## Minimal Features:
**1. User Interface:**

- Design and implement a clean and user-friendly interface using HTML and CSS.
- Display the passage of text that users will type.
- Include a text input field for users to enter their typed text.
- Show the user's current typing statistics, including WPM, accuracy, and elapsed time.

**2. Typing Performance Tracking:**

- Track the user's typing speed in words per minute (WPM).
- Calculate the accuracy percentage of the user's typed text.
- Measure the elapsed time from the start to the completion of typing.

**3. Passage Generator:**

- Create a set of predefined passages to be used for the typing test.
- Randomly select a passage for each new typing test session.

**4. Reset and Retry:**

- Provide an option to reset the typing test and start a new session.
- Allow users to retry the same passage or select a new passage for subsequent tests.

**5. Results History:**

- Store and display a history of the user's previous typing test results.
- Include the date, WPM, accuracy, and duration of each test.

**6. Responsive Design:**

- Ensure the application is responsive and adapts well to different screen sizes and devices.

## **Additional context**
This project will be a valuable tool for individuals seeking to improve their typing skills and can be deployed on various platforms. Contributions are welcome to enhance the user interface, add additional features, improve performance, or fix any issues.

I kindly request your attention to review my issue and consider merging it into the SSoC'23 program. I am eager to start working on this project and contribute to its success under your mentorship and guidance. Should you require any further information or have any questions, please do not hesitate to reach out to me.

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/114648043/c5e2c225-57cd-4996-a10c-5c852f33f8f2)

**Comment by zugzwang03** [comment]
#86 has already been done.
