### ISSUE TITLE
Prime, odd or even number checker

### ISSUE THREAD

**Issue by khushigarg1** [TusharKesarwani/Front-End-Projects#118]

**Comment by MridulGupta007** [comment]
i can implement it

**Comment by khushigarg1** [comment]
Please assign this issue to me

**Comment by zugzwang03** [comment]
Issues would be assigned on a first come, first serve basis. @khushigarg1 your issue looks good, wait till you get assigned by @TusharKesarwani.

**Comment by Rishikavishnoi** [comment]
@khushigarg1 assigned ..start working ✌️
