### ISSUE TITLE
dice game 

### ISSUE THREAD

**Issue by leesha19** [TusharKesarwani/Front-End-Projects#1181]
**Is your feature request related to a problem? Please describe.**
dic egame which decides which player won 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mahesh-Narakanti** [comment]
Is your feature request related to a problem? Please describe.
I can complete this project,plz assign it to me

Describe the solution you'd like
By using HTML,CSS,JS

Additional context
![Screenshot (101)](https://github.com/TusharKesarwani/Front-End-Projects/assets/119794954/c7b07807-d40f-4466-93c7-b923d200d7aa)

**Comment by zugzwang03** [comment]
Game projects not accepted now.
