### ISSUE TITLE
Tourism

### ISSUE THREAD

**Issue by suma30** [TusharKesarwani/Front-End-Projects#1185]
**Is your feature request related to a problem? Please describe.**
In the Tourism website the background image of search bar goes behind the navbar which is not appealing

**Describe the solution you'd like**
It would look better if the image is adjusted below the navbar

**Describe alternatives you've considered**
I would like to change it

**Additional context**
![Screenshot (47)](https://github.com/TusharKesarwani/Front-End-Projects/assets/112741893/01b0857f-065f-4a82-9f5a-c610f0882950)

@TusharKesarwani Please assign me this issue

**Comment by zugzwang03** [comment]
Yeah go for a better enhancement!
