### ISSUE TITLE
Moving Circle Game

### ISSUE THREAD

**Issue by Jacinth-Mahanta** [TusharKesarwani/Front-End-Projects#1187]
## **Describe the project**
The game starts when you click the "Start" button. The circle will move to a random position within the game container every second. You have 10 seconds to click on the circle as many times as possible. After 10 seconds, the game ends and an alert is shown.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## Screenshots
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/96361743/59b6aded-1f36-45af-accb-42b6a1f060b3)

**Comment by zugzwang03** [comment]
We aren't accepting game projects as of now.
