### ISSUE TITLE
Lines Background Animation 

### ISSUE THREAD

**Issue by vimarsh11** [TusharKesarwani/Front-End-Projects#1190]
## **Describe the project**
Lines Background Animation is web background formed using HTML, CSS. It can be used in any website to make attractive. 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

https://github.com/TusharKesarwani/Front-End-Projects/assets/104987339/8a98af74-aa24-457b-9f9c-27741bc461f2

**Comment by zugzwang03** [comment]
Merely adding animation would be a too meagre thing to work on, think about something more to add on to this effect to make a better project.
