### ISSUE TITLE
Enhancement on the Audio-Text-Converter project

### ISSUE THREAD

**Issue by noobcoder007-exe** [TusharKesarwani/Front-End-Projects#1192]
I'm a contributor under SSoC'23. I have this project idea.....please assign this to me.

**Comment by zugzwang03** [comment]
Can you describe its working a little more? Like based on one's speech, the corresponding text will be written down, is it like that?

**Comment by zugzwang03** [comment]
#356 is already done, but you can enhance it further, add multiple features in it.
