### ISSUE TITLE
Fixing the Typo in Readme File

### ISSUE THREAD

**Issue by Ayan67131** [TusharKesarwani/Front-End-Projects#1193]
**Describe the bug**
Their exists a typo  'Scrrenshot ' which is actually ' Screenshot'. Furthermore i can help to write a better and clear readme file for this project .
**To Reproduce**

**Screenshots**

![ReadmeEdit](https://github.com/TusharKesarwani/Front-End-Projects/assets/92906981/ef115775-9181-48cb-90dd-03a6f5bfc9a0)

**Comment by zugzwang03** [comment]
You want to revamp the entire README.md for this project? @Ayan67131

**Comment by zugzwang03** [comment]
Go ahead then!
