### ISSUE TITLE
Add "Back to Top" Button to the README.md

### ISSUE THREAD

**Issue by kunalnandre** [TusharKesarwani/Front-End-Projects#1194]
I would like to add a button in the README.md file for "Back to Top". It would be highly beneficial for contributors to navigate through the README.md file more easily, ultimately increasing the time spent reading the repository's README.md file.

Example:

![BacktoTop](https://github.com/TusharKesarwani/Front-End-Projects/assets/111383966/1ead8590-f96e-4a51-859a-e7992de6f231)

## Please have a look and assign this issue to me under SSOC 2.0

**Comment by zugzwang03** [comment]
The README isn't that long though, @TusharKesarwani what's your opinion on this?

**Comment by kunalnandre** [comment]
> The README isn't that long though, @TusharKesarwani what's your opinion on this?

Yes, but I think there is a need for one button at the bottom of the README.md page. It would be very useful for contributors to save time.

**Comment by ranjanmangla1** [comment]
assign me this issue, already filed a merge request

**Comment by Bhanuteja01** [comment]
Assign me this issue
