### ISSUE TITLE
Display of image in BMICalculator project

### ISSUE THREAD

**Issue by kundu-baivab** [TusharKesarwani/Front-End-Projects#1196]
**Is your feature request related to a problem? Please describe.**
When the BMI of a user is calculated, an example image describing the physique of the user is to be shown, but it's not displayed.

**Describe the solution you'd like**
There's a problem with the source pathway of the image to be displayed in the project. I noticed this small error in the Javascript code while reading the source code. I would like to correct the pathway so that the project would seem more appealing to the users.

Please assign this issue to me.

- Project screenshot as of now:
NO IMAGE
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/106022593/37ee92e0-e93b-4e5f-97b4-bdb939496d94)

- Project screenshot after I correct the image source pathway:
With image thus increasing UI
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/106022593/c20bf58a-6923-403c-9c78-b1e1bf64f64e)

**Comment by zugzwang03** [comment]
This issue is already resolved in the present version of the website
