### ISSUE TITLE
Improving   user interface  of the existing  gym-website

### ISSUE THREAD

**Issue by snahanku** [TusharKesarwani/Front-End-Projects#1198]
**Is your feature request related to a problem? Please describe.**
I would like to improve the ui of the website by adding visible features  such as hovering effect  , improving alignment  etc .

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I would  like to contribute to this project to make it a better visual website  using existing knowledge of html , css , bootstrap and javascript . I would request  to assign me this project as  i have prior experience in such website development .

**Comment by zugzwang03** [comment]
Which project are you talking about?

**Comment by snahanku** [comment]
Hi , am talking about the gym-website.  Further more do I need  mention the
name of the website in the title section of the issue ,  please guide me in
the process , as am new to contributions to opensource.

**Comment by zugzwang03** [comment]
Isn't the gym website UI already quite advanced? Are you sure you can enhance it further?

**Comment by snahanku** [comment]
I can improve the website by adding features like hover effect  on the navigation bars  , enhancing the alignments and improve the color contrast  of the website. I would like to  work on this projects as i have  some previous experiences with such websites . Therefore am requesting you  to please  assign me this project .

**Comment by zugzwang03** [comment]
also improve the dummy texts.
