### ISSUE TITLE
Planet defense game

### ISSUE THREAD

**Issue by SimranLahrani842** [TusharKesarwani/Front-End-Projects#1199]
A clear and concise description of the project you are going to add to this repository.
We need to defend planet earth with the help of a gun and hit all stones and meteroids approaching planet earth.This is a game in html,css and js with good ui.

## Issue Type:
- [x] New Project

**Comment by SimranLahrani842** [comment]
> A clear and concise description of the project you are going to add to this repository. We need to defend planet earth with the help of a gun and hit all stones and meteroids approaching planet earth.This is a game in html,css and js with good ui.
> 
> ## Issue Type:
> * [x]  New Project

@TusharKesarwani and @Arun9739 please assign me this

**Comment by zugzwang03** [comment]
Game projects not accepted!
