### ISSUE TITLE
Text editor in python

### ISSUE THREAD

**Issue by SimranLahrani842** [TusharKesarwani/Front-End-Projects#1200]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
Text editor is most commonly used for coding.I ll build a text editor of my own in python where you can save,edit and make changes in file ..

## Issue Type:
- [x] New Project

**Comment by SimranLahrani842** [comment]
> ## **Describe the project**
> A clear and concise description of the project you are going to add to this repository. Text editor is most commonly used for coding.I ll build a text editor of my own in python where you can save,edit and make changes in file ..
> 
> ## Issue Type:
> * [x]  New Project

@TusharKesarwani and @Arun9739 please assign me this

**Comment by zugzwang03** [comment]
#600 already done
