### ISSUE TITLE
Music Player in python

### ISSUE THREAD

**Issue by SimranLahrani842** [TusharKesarwani/Front-End-Projects#1201]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
One can load Hindi or English songs and can play them.One can stop,pause and start the songs again if required.

## Issue Type:
- [x] New Project

**Comment by SimranLahrani842** [comment]
> ## **Describe the project**
> A clear and concise description of the project you are going to add to this repository. One can load Hindi or English songs and can play them.One can stop,pause and start the songs again if required.
> 
> ## Issue Type:
> * [x]  New Project

Assign me this @Arun9739 @TusharKesarwani @zugzwang03

**Comment by zugzwang03** [comment]
#480 already done.
