### ISSUE TITLE
Age calculator in html,css and js

### ISSUE THREAD

**Issue by SimranLahrani842** [TusharKesarwani/Front-End-Projects#1203]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
We need to enter our date of birth from the calendar and click on button to get exact age of us.
## Issue Type:
- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

**Comment by zugzwang03** [comment]
#1169 is already done.
