### ISSUE TITLE
Adding hovering Effect

### ISSUE THREAD

**Issue by dhruvishavaghani** [TusharKesarwani/Front-End-Projects#1212]
**Is your feature request related to a problem? Please describe.**
Description of the particular project is added below the Project name in a small font which might not be user-friendly and can be difficult for a user to read it. 

**Describe the solution you'd like**
I can create a hover effect so that whenever the user puts a cursor on a particular project hover effect will be generated and a description of the project will be displayed in an eye-catching manner so that the user can easily read the description for the project.

![Screenshot 2023-06-14 214748](https://github.com/TusharKesarwani/Front-End-Projects/assets/109460833/ddb9d2f7-4bb7-4e49-8793-1bec8bbe6a24)

**Comment by Neha5679** [comment]
I would like to contribute. Please assign me

**Comment by sarmistha-02** [comment]
@TusharKesarwani sir can you please assign me this issue. I can provide some animation effects to provide a better user interface for the above problem.
