### ISSUE TITLE
I would like to add rock paper and scissor game 

### ISSUE THREAD

**Issue by MrinalCom** [TusharKesarwani/Front-End-Projects#1229]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ✔] New Project

## **Additional context**
It will be a rock paper and scissor game where players can play with computer or other players

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by MAYURIKOTHARI299** [comment]
@harshit-paneri @TusharKesarwani please assign me this issue under SSOC 2.0

**Comment by zugzwang03** [comment]
Game projects not accepted.
