### ISSUE TITLE
To add a dark mode to the E-COMMERCE LANDING PAGE

### ISSUE THREAD

**Issue by parasharesnehal** [TusharKesarwani/Front-End-Projects#1243]
**Is your feature request related to a problem? Please describe.**
In the current landing page there is a light theme, which I wish to change to a dark theme.

**Describe the solution you'd like**
To add a dark mode/theme to the existing version of the page.

**Describe alternatives you've considered**
Current versions of the markup languages, more appealing and interactive UI. 

@TusharKesarwani I request you to assign me this issue, as I have prior knowledge of the same.

**Comment by iamworrell** [comment]
can you assign this issue to me?

**Comment by parasharesnehal** [comment]
Hi @TusharKesarwani  Sir ,I haven't made a PR on this issue because I am unable to make another PR,as
 one is already open.Here's the link of another PR I made ->https://github.com/TusharKesarwani/Front-End-Projects/pull/1813
Thus I reuest you to review this PR and open issue #1243 so that I can make the PR immediately.
