### ISSUE TITLE
Building a QR Code Reader

### ISSUE THREAD

**Issue by Swap-Nova** [TusharKesarwani/Front-End-Projects#1246]
## Hey @TusharKesarwani I am planning to build a <i> QR code reader </i> through ReactJS.
* We can use the npm module html5-qrcode which is a lightweight library. 
* It is easily integrated with the pre-existing code. It has a real-time application that users can use very efficiently.
* Therefore, if possible, assign me this project and I will start working on it asap.

**Comment by zugzwang03** [comment]
React Projects not allowed.

**Comment by Swap-Nova** [comment]
Very well I can work with basic HTML, CSS & JS.

**Comment by Swap-Nova** [comment]
Thanks
