### ISSUE TITLE
Adding 2048 game

### ISSUE THREAD

**Issue by MohammadAsiya** [TusharKesarwani/Front-End-Projects#1247]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
2048 is a popular puzzle game where the goal is to combine numbered tiles on a grid to reach the elusive tile of 2048. Each move combines adjacent tiles of the same number, doubling their value. The player must strategically slide tiles in four directions without running out of space or moves. With simple rules and addictive gameplay, 2048 challenges your strategic thinking and numerical skills. 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![2048](https://github.com/TusharKesarwani/Front-End-Projects/assets/121110715/6e342c10-58c7-47b9-b6f7-0e3e7259f4d6)
Please assign this task to me under ssoc 2.0

**Comment by zugzwang03** [comment]
game projects not accepted!
