### ISSUE TITLE
Adding instagram clone

### ISSUE THREAD

**Issue by MohammadAsiya** [TusharKesarwani/Front-End-Projects#1248]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Tanyamodi** [comment]
I would like to work on this issue, kindly assign this to me.

**Comment by TusharKesarwani** [comment]
> I would like to work on this issue, kindly assign this to me.

You can create issues of your own
