### ISSUE TITLE
[New Game]: Memory Card Game 

### ISSUE THREAD

**Issue by Anushka-gupta496** [TusharKesarwani/Front-End-Projects#1253]
## **Describe the project**
Memory card game is a simple matching cards game in which all the cards are flipped backside on a surface and two cards are flipped face up over each turn. The objective of this game is to match all the pairs of cards.
In this project there will be a timer of 30 secs for the user to match all the pairs of cards and there will also be a number of flips counter. By clicking the refresh button, the user can start a fresh game.

## Issue Type:
- [x] New Project

## **Screenshot**

![Screenshot (119)](https://github.com/TusharKesarwani/Front-End-Projects/assets/98311688/bf0ee2c4-5970-444b-ab12-06bbc0b14207)

**Comment by zugzwang03** [comment]
game projects not allowed.
