### ISSUE TITLE
Real time character counter 

### ISSUE THREAD

**Issue by SimranLahrani842** [TusharKesarwani/Front-End-Projects#1263]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
project aims to create a real-time character counter using JavaScript. It features a text area container that displays both the total character count and remaining character count of 50. As users type, the total character count dynamically increases, and the remaining character count decreases. The text area locks once the limit of 50 characters is reached, and the remaining character count becomes zero. With this functionality, users can keep track of their remaining characters and be alerted when they hit the character limit.
## Issue Type:
- [x] New Project

**Comment by SimranLahrani842** [comment]
> ## **Describe the project**
> A clear and concise description of the project you are going to add to this repository. project aims to create a real-time character counter using JavaScript. It features a text area container that displays both the total character count and remaining character count of 50. As users type, the total character count dynamically increases, and the remaining character count decreases. The text area locks once the limit of 50 characters is reached, and the remaining character count becomes zero. With this functionality, users can keep track of their remaining characters and be alerted when they hit the character limit.
> 
> ## Issue Type:
> * [x]  New Project

Please assign me @TusharKesarwani

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
