### ISSUE TITLE
Copyright year missing in the footer section of the homepage

### ISSUE THREAD

**Issue by gauravsingh1281** [TusharKesarwani/Front-End-Projects#1265]
<img width="960" alt="Screenshot 2023-06-16 224357" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/85905403/e30ed277-0322-4f82-bec2-59e897a881f1">

**Comment by gauravsingh1281** [comment]
@TusharKesarwani Please assign this issue to me I want to work on it.

**Comment by Neha5679** [comment]
I would like to work on it. Please assign me

**Comment by gauravsingh1281** [comment]
Assign this issue to me because I have raised this issue first.

**Comment by techmannih** [comment]
Hello @TusharKesarwani , 
I want to handle this issue ...and please assign me

**Comment by zugzwang03** [comment]
the footer style is subjective, @TusharKesarwani what say on this?

**Comment by TusharKesarwani** [comment]
Not required
