### ISSUE TITLE
Making URL shortener using html, css, js

### ISSUE THREAD

**Issue by s2ahil** [TusharKesarwani/Front-End-Projects#1268]
## **Describe the project**
**A URL shortener** is a tool that takes a long URL (Uniform Resource Locator) and creates a shorter, condensed version of it that redirects to the original URL when accessed .

## Issue Type:
- [x] New Project

## **Additional context**

**purpose :** the purpose of a URL shortener is to make it easier to share long URLs, especially on platforms like Twitter where character limits make it difficult to share long links.

Please assign this to me so that i can start working on it.

**Comment by zugzwang03** [comment]
#1151 already in progress.
