### ISSUE TITLE
Expense Tracker: Financial Assistance Features #SSOC23

### ISSUE THREAD

**Issue by nandanchebbi560** [TusharKesarwani/Front-End-Projects#1269]
**Is your feature request related to a problem? Please describe.**
1) An expense tracker manages the expenses but it shouldn't stop there, without providing clear details about the history of payments the person using the expense tracker won't learn and modify their expense plan.
2) Expense Tracker does not provide any additional help when managing the expenses
3) Expense Tracker does not have any option to create a financial plan with a tracker in the app thereby making the app limited in its functionality to help the individual.
4) Plain UI is very unappealing to look at and pushes the users away from using this product.

**Describe the solution you'd like**
1) History tab option in a navigation menu, once clicked, on the same page on the right-hand side, it'll provide the history of expenses with a clear concise description of the expense.
2) Tips for Savings: On the left-hand side, Tips will be shown on how to save money with each type of expense.
3) In the navigation menu, the Fin Plan tab will be available when once clicked, it'll allow for creating a financial plan for managing expenses and the plan will display on the right-hand side of the expense tracker.
4) The product needs to look appealing to the user and it would make it easier & fun to use this device so, a box like CSS design for the expense tracker, animations when hovering over the button and clicking the button, animations for inputting the expenses EOD and making the platform more.

#SSOC2023

**Comment by nandanchebbi560** [comment]
@TusharKesarwani Please assign me this issue

**Comment by zugzwang03** [comment]
#595 already done.
