### ISSUE TITLE
Theme Switcher

### ISSUE THREAD

**Issue by vimarsh11** [TusharKesarwani/Front-End-Projects#127]
I want to create theme switcher using HTML, CSS and JavaScript.

**Comment by harshit-paneri** [comment]
@vimarsh11 It's Good If you provide some figma images of your Idea✨

**Comment by vimarsh11** [comment]
![figma](https://user-images.githubusercontent.com/104987339/211207862-fe0b317d-f8af-409f-98c1-7400cbb5ada1.jpeg)
@harshit-paneri

**Comment by Rishikavishnoi** [comment]
@vimarsh11 assigned

**Comment by harshit-paneri** [comment]
> ![figma](https://user-images.githubusercontent.com/104987339/211207862-fe0b317d-f8af-409f-98c1-7400cbb5ada1.jpeg) @harshit-paneri

Great @vimarsh11 , You can start work on it
