### ISSUE TITLE
Simple pokedex, html scss/css, boostrap, javascript and poke api. 

### ISSUE THREAD

**Issue by LemonMantis5571** [TusharKesarwani/Front-End-Projects#1272]
## **Describe the project**
A beginner friendly HTML, CSS, BOOSTRAP and Javascript responsive pokedex.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [Yes ] New Project

## **Additional context**
Build a beginner friendly pokedex only using javascript, also libraries for toast and search included.
This project can make you understand simple async/await api calls and DOM manipulation.

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/85099589/eb9f0831-ef0b-455d-8227-d41687dc2d70)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/85099589/984f9192-1145-4e11-a697-a4494167213e)

**Comment by zugzwang03** [comment]
this is like a game project, also api calling and backend projects not accepted.
