### ISSUE TITLE
Adding basic drum rolls using JS

### ISSUE THREAD

**Issue by shrey-aa** [TusharKesarwani/Front-End-Projects#1276]
## **Description of the project Drum Rolls**
An external page that can be used to play drumrolls while playing any game or can be played just for fun. 

## Issue Type:
- [ ] Documentation
- [ ] New Project

## **Additional context**
I am participant of SSOC'23. I am very much interested in Front-end. Please assign me with this addition of new  project.

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
