### ISSUE TITLE
Want to add stylish JS Games

### ISSUE THREAD

**Issue by Paramhans-Singh** [TusharKesarwani/Front-End-Projects#1278]
## **Describe the project**
I Want to add stylish JS Games that are build with Babel and Vanilla JS.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Pls assign this to me under SSOC23

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/101575816/86e9da26-a304-4835-ac91-ee0d545b6977)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/101575816/2c143f23-943f-4969-b218-4015a959fd8b)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/101575816/92005407-604c-4e9d-83b6-d7fca73f3d28)

**Comment by Paramhans-Singh** [comment]
Pls assign this to me under SSOC23

**Comment by zugzwang03** [comment]
game projects not accepted!
