### ISSUE TITLE
Adding Pagination in Website

### ISSUE THREAD

**Issue by dishamodi0910** [TusharKesarwani/Front-End-Projects#1279]
**Is your feature request related to a problem? Please describe.**
Going through all the projects and scrolling down, again and again, seems frustrating. 
So I would like to add a pagination feature to the website.

**Describe the solution you'd like**
A pagination feature where within a page it would contain only 20 projects and rest of the projects are visible on next page.

**Comment by dishamodi0910** [comment]
@TusharKesarwani @Arun9739 Please assign me this issue.

**Comment by zugzwang03** [comment]
nice thing, what say on this? @TusharKesarwani
