### ISSUE TITLE
Bird Game

### ISSUE THREAD

**Issue by Shr-reny** [TusharKesarwani/Front-End-Projects#1283]
## **Describe the project**
It's an absolutely simple project which is a game where aiming at a bird and clicking would shoot it and increase a point.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
It's made entirely using Html and CSS only.

## **Screenshots**

![Bird_game](https://github.com/TusharKesarwani/Front-End-Projects/assets/125943681/69292604-0b79-4824-8aa3-10cf7ab48b85)

**Comment by zugzwang03** [comment]
Game projects not accepted!
