### ISSUE TITLE
Mobi calculator

### ISSUE THREAD

**Issue by Du-Nothing** [TusharKesarwani/Front-End-Projects#1285]
It's  a phone like calculator and also show present time
![Mobi calci](https://github.com/TusharKesarwani/Front-End-Projects/assets/128450855/9924c26c-9b10-4401-baf0-228042260e09)
.

## Issue Type:

- [ ] Bug Report
- [] Feature Request
- [ ] Documentation
- [] New Project

Please assign me this project.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Du-Nothing** [comment]
Please assign ASAP.

**Comment by TusharKesarwani** [comment]
The calculator is already present in the repo
