### ISSUE TITLE
Add ReadMe file in the BMICalculator project

### ISSUE THREAD

**Issue by krutika-ladani** [TusharKesarwani/Front-End-Projects#1286]
ReadMe file is missing in the BMICalculator project. I want to add it.
Please assign me this issue under SSOC 2.0.

**Comment by panjyar** [comment]
hey @TusharKesarwani  @himanshu1221 @Abhishantpadam @Amit0412  @unikdahal  
Can you please assign me this issue.

**Comment by krutika-ladani** [comment]
@TusharKesarwani, @harshit-paneri and @zugzwang03 please assign me this issue under SSOC 2.0

**Comment by techmannih** [comment]
hello @TusharKesarwani , 
i want to handle this issue... please assign me
