### ISSUE TITLE
Want to add my open source project MESSI MANIA

### ISSUE THREAD

**Issue by Soumyajit2825** [TusharKesarwani/Front-End-Projects#1288]
## **Describe the project**
A simple fan made web-page of LIONEL MESSI
Made by HTML CSS and JavaScript

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

**Comment by zugzwang03** [comment]
try to make it responsive as well!

**Comment by Soumyajit2825** [comment]
@zugzwang03 Sure!

**Comment by Soumyajit2825** [comment]
@TusharKesarwani Merge it
