### ISSUE TITLE
want to change the UI  of website-bookmark.

### ISSUE THREAD

**Issue by HimanshiDafouty** [TusharKesarwani/Front-End-Projects#1293]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zugzwang03** [comment]
try to make a significant change in the UI, depending upon your changes, your PR merging will be decided.

**Comment by HimanshiDafouty** [comment]
sure
