### ISSUE TITLE
[SSoC 2.0] Number to words convertor front end project

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [TusharKesarwani/Front-End-Projects#1296]
## **Describe the project**
- Enter the number in the input box
- Using Javascript, convert the entered number into words
- Number to words conversion is done instantly on entering the number

## Issue Type:

- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani please assign this project to me for a contribution in this repository under the SSoC 2.0 program

**Comment by TusharKesarwani** [comment]
Project is already present in the repo
