### ISSUE TITLE
Image Filter Website

### ISSUE THREAD

**Issue by rudra016** [TusharKesarwani/Front-End-Projects#1297]
## **Describe the project**
In this project, we will be creating an image filter application using HTML, CSS, and JavaScript. The application will allow users to upload an image and apply various filters to manipulate its appearance. We will utilize the <canvas> element, which provides a powerful API for drawing graphics and manipulating images in the browser.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Users will be able to select and upload an image, apply various filters to manipulate its appearance, and reset it to its original state. The canvas element provides a flexible and efficient way to apply image filters and render the modified image in real-time.

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/94120092/47d8f0d6-38d5-4c41-acbc-917220904a58)

**Comment by zugzwang03** [comment]
#326 already done.
