### ISSUE TITLE
New Project : Avoider Game

### ISSUE THREAD

**Issue by shubhisingh184** [TusharKesarwani/Front-End-Projects#1298]
## **Describe the project**

Avoider is a game, where you must avoid other attacking balls of different colors (red) in order to protect your own player ball(blue). You just have to manage to save your player ball (blue) by avoiding other balls.
Tech Stack Used : HTML, CSS & JavaScript

### Features
1. In this game, you have to save your ball by avoiding other attacking balls.
2. You can use right/ left keys to move the move according to the situation.
3. After successfully avoiding each attacking ball, you get one point.
4. Points will get reflected on the scoreboard.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
![Screenshot (353)](https://github.com/TusharKesarwani/Front-End-Projects/assets/67328331/1a369165-aed0-4707-8da6-746b12b09334)

- If applicable, add screenshots to help explain your problem.

**Comment by zugzwang03** [comment]
Game projects not accepted!
