### ISSUE TITLE
Dictionary App

### ISSUE THREAD

**Issue by kavyaag2607** [TusharKesarwani/Front-End-Projects#1304]
## **Describe the project**
Dictionary App is used to search the meaning of an English word

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/121026499/11c0af5d-0f90-485e-aee0-124966e67acc)

- If applicable, add screenshots to help explain your problem.

**Comment by zugzwang03** [comment]
#120 already done
