### ISSUE TITLE
Website UI not responsive.

### ISSUE THREAD

**Issue by rahulrana701** [TusharKesarwani/Front-End-Projects#1308]
**Describe the bug**
The UI of the website is not responsive it is breaking at various points , I would like to make it responsive.

**Expected behavior**
The website should be responsive for all devices and shoudn't break at some points.

**Screenshots**
<img width="210" alt="Screenshot 2023-06-19 125203" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/123585591/5d8e08ee-c713-417d-9016-a2bffed929d2">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by techmannih** [comment]
hello @rahulrana701 ,
I want to handle this issue .....please assign me
