### ISSUE TITLE
Search Bar Not working.

### ISSUE THREAD

**Issue by rahulrana701** [TusharKesarwani/Front-End-Projects#1311]
Describe the bug
The search bar is not working , it should search the project when user enters a project name he/she wants...

Expected behavior
it should search the project when user enters a project name he/she wants...

Screenshots
<img width="428" alt="Screenshot 2023-06-19 132115" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/123585591/ce85857f-a730-48c2-88df-8e74a61a2bc2">

**Comment by mandliyarajendra11** [comment]
bro press enter or click on the map icon , its working

**Comment by rahulrana701** [comment]
Not in that way brother ,I want that  if someone searches for a project by typing it's name in it the project should show up . In this way I want this search bar to work.

**Comment by ChavvaNarayana** [comment]
Please assign to me this issue

**Comment by mandliyarajendra11** [comment]
> Not in that way brother ,I want that if someone searches for a project by typing it's name in it the project should show up . In this way I want this search bar to work.

ohh :)
