### ISSUE TITLE
Maze-Generation-Game

### ISSUE THREAD

**Issue by shambhavisingh011** [TusharKesarwani/Front-End-Projects#1313]
## **Describe the project**
I want to add an interesting Maze-Generation Game. It is built using HTML, CSS, and JAVASCRIPT. It keeps the user engaged by asking them to get through the maze and eventually win if pass through it.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/121101577/b749f555-acc5-4e4e-bfc6-736e8eded378)

- If applicable, add screenshots to help explain your problem.

**Comment by zugzwang03** [comment]
game projects not accepted
