### ISSUE TITLE
To-Do-List

### ISSUE THREAD

**Issue by Mansi8874** [TusharKesarwani/Front-End-Projects#1314]
## **Describe the project**
The interactive to-do list is a web application designed to help users manage their tasks efficiently. With a clean and intuitive user interface created using HTML and CSS, users can easily add, update, and delete tasks.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
I want to work on this issue . Please Assign this issue to me @TusharKesarwani 
## **Screenshots**
<img width="1285" alt="Screenshot 2023-06-19 at 3 19 01 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/101468475/f626f617-9b65-41ce-bfac-a623274ae665">

**Comment by priyanka-6675** [comment]
hello , please assign to me to enhance the features of its.

**Comment by zugzwang03** [comment]
#980 already working
