### ISSUE TITLE
URL Shortening Landing Page Project

### ISSUE THREAD

**Issue by SaketGudimella** [TusharKesarwani/Front-End-Projects#1317]
## **Describe the project**
The URL Shortening Landing Page project aims to develop a web application that enables users to shorten long URLs into concise and shareable links for easier sharing on platforms with character limitations. 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**

The project will leverage front-end technologies such as HTML, CSS, and JavaScript to create a responsive and intuitive user experience. 

Key Features: 

1)  URL Shortening: The landing page should have a form or input field where users can enter their long URLs.

2) Shortened URL Generation: Upon submitting the long URL, the landing page should generate a unique shortened URL based on a reliable algorithm.

3) Copy to Clipboard: Users should have the option to copy the shortened URL to their clipboard with a simple click.

4) Redirect Functionality: When someone clicks on a shortened URL, they should be redirected to the original long URL seamlessly.

@TusharKesarwani Please assign me this issue usder SSOC'23.

**Comment by zugzwang03** [comment]
#1151 already done
