### ISSUE TITLE
Rapid-API key exposed

### ISSUE THREAD

**Issue by Harshit-Raj-14** [TusharKesarwani/Front-End-Projects#132]
https://github.com/TusharKesarwani/Front-End-Projects/blob/d4591740e68488a8b484a9eafa8366afd73d6745/Projects/Weather/script.js#L5

I would like to bring the matter to the kind notice of the moderators that someone's API key has been exposed on this repo.
Please push that to gitignore or change it into a variable.

Or you can assign this job to me and I am happy to do it.

Thank you.

**Comment by harshit-paneri** [comment]
Hey 👋🏻, Great Work, but this is public API key and not harmful for anyone, so don't worry about it.
