### ISSUE TITLE
more button in project section

### ISSUE THREAD

**Issue by mandliyarajendra11** [TusharKesarwani/Front-End-Projects#1321]
**Is your feature request related to a problem? Please describe.**

The problem is that in the project section, there are so many projects that even scrolling doesn't reach the end, and it takes a long time to load, especially for the sections below like the footer. It doesn't make sense to spend so much time just to reach there, and there will be more projects ahead. So, I want to add an "Expand More" button here, which, when clicked, will show the remaining projects.

please assign me this issue under ssoc

**Comment by zugzwang03** [comment]
@TusharKesarwani what say on this?
