### ISSUE TITLE
sticky navbar

### ISSUE THREAD

**Issue by mandliyarajendra11** [TusharKesarwani/Front-End-Projects#1323]
**Is your feature request related to a problem? Please describe.**
A sticky navbar, also known as a fixed navbar, is a type of navigation bar that remains visible and fixed in its position on the screen, even when the user scrolls down the page. It stays "stuck" at the top (or any other specified position) of the viewport, ensuring that the navigation menu is always accessible and easily reachable for the user.

i want to work on this issue please assign me

**Comment by zugzwang03** [comment]
@TusharKesarwani what say on this?

**Comment by TusharKesarwani** [comment]
Not required
