### ISSUE TITLE
Portfolio Website 

### ISSUE THREAD

**Issue by amrit03b** [TusharKesarwani/Front-End-Projects#1336]
The idea is to make a general template for a portfolio website using  HTML, CSS and JavaScript

## Issue Type:

- [  ] New Project

**Comment by amrit03b** [comment]
Please assign me this issue

**Comment by amrit03b** [comment]
Please assign me this issue

**Comment by priyanka-6675** [comment]
plz assing to me sir..

**Comment by chandug25** [comment]
Hey @zugzwang03 can you please assign it to me .
