### ISSUE TITLE
Othello board game

### ISSUE THREAD

**Issue by SaketGudimella** [TusharKesarwani/Front-End-Projects#1344]
## **Describe the project**
This project aims to develop a front-end implementation of the Othello board game, providing an interactive and visually appealing user interface for players to enjoy.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

@TusharKesarwani Please assign me this project under SSoC'23.

**Comment by zugzwang03** [comment]
game projects not allowed.
