### ISSUE TITLE
Interactive music player web app

### ISSUE THREAD

**Issue by LemonMantis5571** [TusharKesarwani/Front-End-Projects#1347]
## **Describe the project**
A web music player only using html, css (tailwind), javascript

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
A music app player that displays new background when music changed and plays new music.

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/85099589/8be54485-88a5-484e-8f95-033bca2a7fd3)

**Comment by LemonMantis5571** [comment]
I would like this issue be assigned to me

**Comment by zugzwang03** [comment]
#480 on it

**Comment by LemonMantis5571** [comment]
> #480 on it

Is plagiarized projects accepted? cuz the referenced one is it
https://github.com/sayantanm19/js-music-player
https://www.geeksforgeeks.org/create-a-music-player-using-javascript/
