### ISSUE TITLE
Adding Gallery Page required for website

### ISSUE THREAD

**Issue by dhruti26** [TusharKesarwani/Front-End-Projects#1356]
## **Description**
This gallery tab can be useful in any websites to feature the photos, ideas etc. It will be made using HTML and beautify using CSS

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

**Comment by dhruti26** [comment]
@TusharKesarwani Please assign me this issue under SSOC'23

**Comment by zugzwang03** [comment]
#1256 in progress
