### ISSUE TITLE
To change the background of weather website

### ISSUE THREAD

**Issue by DiyaDalakoti** [TusharKesarwani/Front-End-Projects#1359]
**Is your feature request related to a problem? Please describe.**
To change the background of weather website

**Describe the solution you'd like**
Adding more attractive background

**Comment by Shahil093** [comment]
Assign me this issue I can add good and more attractive background to it

**Comment by zugzwang03** [comment]
also add responsiveness to cards, enhance UI, and try making the dropdown functional for different cities.
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/95460021/4cfa5169-c945-42c7-8fdf-f345a7fc5eb6)
