### ISSUE TITLE
Quote Generator

### ISSUE THREAD

**Issue by harsitagarwalla187** [TusharKesarwani/Front-End-Projects#137]

**Comment by harsitagarwalla187** [comment]
Can you assign it to me under SWOC 23

**Comment by Vanshiii203** [comment]
@harsitagarwalla187 Are you still working on this issue??

**Comment by harsitagarwalla187** [comment]
> @harsitagarwalla187 Are you still working on this issue??

@Vanshiii203 Yes

**Comment by ArtiHere** [comment]
Can you assign it to me under SWOC 23
