### ISSUE TITLE
Build Github explorer

### ISSUE THREAD

**Issue by MrinalCom** [TusharKesarwani/Front-End-Projects#1370]
## **Describe the project**
fetch details of users by just entering their name and by single click we can move to their profile

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [✓ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
@TusharKesarwani @himanshu1221 @Abhishantpadam @Asrk03 @Ayush9951 #763

**Comment by harshit-paneri** [comment]
Hey @MrinalCom, are you working on it?

**Comment by MrinalCom** [comment]
yes
