### ISSUE TITLE
want to add dynamics that looks visually more appealing in the sign-in page.

### ISSUE THREAD

**Issue by HimanshiDafouty** [TusharKesarwani/Front-End-Projects#1373]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zugzwang03** [comment]
which project?

**Comment by HimanshiDafouty** [comment]
[
![Screenshot (38)](https://github.com/TusharKesarwani/Front-End-Projects/assets/116953498/d26af172-f651-4f78-b427-ecebe2c7843b)
](url)

**Comment by HimanshiDafouty** [comment]
This one

**Comment by zugzwang03** [comment]
and what dynamics you want to add?

**Comment by HimanshiDafouty** [comment]
Animations and transitions , while hovering or action performed. It looks quite simple
