### ISSUE TITLE
i want to add accordion component

### ISSUE THREAD

**Issue by azizlimonu** [TusharKesarwani/Front-End-Projects#1376]
## **Describe the project**
I want to add a Accordion component that allow user to present a collapsible and expandable set of items.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
![accordion](https://github.com/TusharKesarwani/Front-End-Projects/assets/106480374/e90a2bff-fcd3-4bbf-99c4-022cce2eb675)

please assign me to add this project, thank you
- If applicable, add screenshots to help explain your problem.

**Comment by avinashji1302** [comment]
Please assign me this and elaborate it

**Comment by TusharKesarwani** [comment]
Create a new issue with proper description
