### ISSUE TITLE
Coinbase Landing page clone

### ISSUE THREAD

**Issue by LemonMantis5571** [TusharKesarwani/Front-End-Projects#1378]
## **Describe the project**
The clone replicates the design and layout of the Coinbase landing page, including sections such as a navigation menu, a hero section promoting the platform's features, sections highlighting benefits and key statistics, a step-by-step onboarding process, and a footer call-to-action. This project will be made using HTML, CSS and Boostrap only.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/85099589/5d002af3-8f4e-4f42-bb61-eb0a2de42d3b)

**Comment by LemonMantis5571** [comment]
i would like to be assigned to me

**Comment by LemonMantis5571** [comment]
@harshit-paneri @TusharKesarwani  please assign this to me

**Comment by harshit-paneri** [comment]
Describe your project.

**Comment by LemonMantis5571** [comment]
Sorry for no providing a proper description before.
> Describe your project.

The clone replicates the design and layout of the Coinbase landing page, including sections such as a navigation menu, a hero section promoting the platform's features, sections highlighting benefits and key statistics, a step-by-step onboarding process, and a footer call-to-action. This project will be made using HTML, CSS and Boostrap only.
