### ISSUE TITLE
Text not visible

### ISSUE THREAD

**Issue by Divya5003** [TusharKesarwani/Front-End-Projects#1381]
**Describe the bug**
In the Tripocity project, the text is not visible over the images.

**Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/99502665/37e5d997-5bae-435f-b114-b8307f84257f)

Please assign me this issue @TusharKesarwani @zugzwang03

**Comment by harshitcodes22** [comment]
Can you assign this to me
