### ISSUE TITLE
Weather website using HTML, CSS and Javascript

### ISSUE THREAD

**Issue by Mansi8874** [TusharKesarwani/Front-End-Projects#1382]
## **Describe the project**
The weather website is a simple web application that allows users to check the current weather conditions of a particular location. 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
I want to work on this. Please assign this issue to me. @TusharKesarwani 

## **Screenshots**
<img width="721" alt="Screenshot 2023-06-21 at 6 15 27 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/101468475/db550a02-8e66-410b-9d32-5cf20ec64aae">

**Comment by Niranjan-Kumar-Singh** [comment]
I have done this project before, I want to work in this project. Please assign this project to me.

**Comment by aaviiothic** [comment]
Please assign me this issue
