### ISSUE TITLE
Log In and Sign Up Form

### ISSUE THREAD

**Issue by Mansi8874** [TusharKesarwani/Front-End-Projects#1383]
## **Describe the project**
This project provides a vibrant and user-friendly login and sign-up form, ideal for effortless integration into any website development process.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
I want to work on this issue. Please assign this  issue to me @TusharKesarwani

**Comment by TusharKesarwani** [comment]
I already warned everyone to not create more than 4 issues at a time
First work and close old issues then create new issues
