### ISSUE TITLE
Add Random Password Generator built 

### ISSUE THREAD

**Issue by ranjanmangla1** [TusharKesarwani/Front-End-Projects#1386]
## **Describe the project**
I want to add a random password generator to this repo

## Issue Type:

- [ ] Feature Request
- [ ] New Project

Please assign me this issue.

**Comment by Khushi6517** [comment]
Sir can u please assign this project to me.

**Comment by eshan-one** [comment]
Hey @TusharKesarwani can you assign me this issue. I have already worked on this project

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
