### ISSUE TITLE
Myntra Clone

### ISSUE THREAD

**Issue by kavyaag2607** [TusharKesarwani/Front-End-Projects#1391]
## **Describe the project**
I want to add clone of homepage of Myntra website built using HTML and CSS. 
Please assign me this under SSOC'23.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/121026499/b9b64c14-4056-4c75-a2b0-c3afc6303628)

- If applicable, add screenshots to help explain your problem.

**Comment by kavyaag2607** [comment]
@TusharKesarwani, @zugzwang03 sir please assign me this issue under SSOC 2.0

**Comment by Vaishnavikathar18** [comment]
@TusharKesarwani please assign me this issue as I am new to open source

**Comment by chandug25** [comment]
@TusharKesarwani can you please assign this issue to me ?
