### ISSUE TITLE
Add Calculator Project

### ISSUE THREAD

**Issue by Abhay3819** [TusharKesarwani/Front-End-Projects#1396]
## **Describe the project**
Hii @TusharKesarwani , I want to add this project so please assign to me.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![project32](https://github.com/TusharKesarwani/Front-End-Projects/assets/110670975/765d77c2-19a1-488e-9aba-4cb72685bd94)

**Comment by Khushi6517** [comment]
sir can u please assingn this issue to me..

**Comment by aaviiothic** [comment]
Please assign me the issue

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
