### ISSUE TITLE
Add another languages

### ISSUE THREAD

**Issue by Gungun1643** [TusharKesarwani/Front-End-Projects#1399]
**Is your feature request related to a problem? Please describe.**
There is an issue that the website only can give speech-to-text conversion in Hindi.

**Describe the solution you'd like**
I would like to add more languages such as English, Gujarati, and Marathi. So that a maximum number of people can make use of it. 

**Describe alternatives you've considered**
I will make a select option and then try to get the text of the speech in that language

Here is the project link:
https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Audio-Text-Converter

**Comment by Harshal662** [comment]
I can do that
