### ISSUE TITLE
Add images

### ISSUE THREAD

**Issue by Gungun1643** [TusharKesarwani/Front-End-Projects#1403]
**Describe the bug**
The website is not having the images of the desired item.

**To Reproduce**
1. Add the images 

**Expected behavior**
Images should be shown on the page

**Screenshots**
![bandicam 2023-06-22 12-34-35-371](https://github.com/TusharKesarwani/Front-End-Projects/assets/104245345/455b1c44-9e3b-4797-8efa-d82dc4642508)
![bandicam 2023-06-22 12-34-29-480](https://github.com/TusharKesarwani/Front-End-Projects/assets/104245345/67aee78a-ecfe-4282-b8d9-d41477ffa9f7)

**Additional context**
This is the site link.
https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Filters

**Comment by Gungun1643** [comment]
@TusharKesarwani

**Comment by Khushi6517** [comment]
Sir can u please assign this project to me.

**Comment by priyanka-6675** [comment]
i would  like to work on this work plz assign to me
