### ISSUE TITLE
Add web page links 

### ISSUE THREAD

**Issue by Gungun1643** [TusharKesarwani/Front-End-Projects#1404]
**Describe the bug**
The buttons are not redirecting to the correct webpage
**To Reproduce**
1. Add the correct webpage links 

**Expected behavior**
On clicking the button we need to go to the playstation or xbox series purchase page

**Video**

https://github.com/TusharKesarwani/Front-End-Projects/assets/104245345/953ca992-de3c-42d1-aab1-d283281ca258

**Additional context**
Here is the link of the project 
https://github.com/TusharKesarwani/Front-End-Projects/assets/104245345/7302209c-8fcd-4f2b-bff4-5b0f6b3e4fd1

**Comment by ChavvaNarayana** [comment]
@Gungun1643 Can you provide more information or details, please?

**Comment by TusharKesarwani** [comment]
Not required
