### ISSUE TITLE
Zomato landing page ->get app button not working properly 

### ISSUE THREAD

**Issue by Gungun1643** [TusharKesarwani/Front-End-Projects#1407]
**Describe the bug**
When clicking on the app button we are not able to go the app download store 

**To Reproduce**
1. Add the appropriate link

**Expected behavior**
Go to play store

**Screenshots**

**Additional context**
Here is the link for reference .
https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Zomato-Landing-Page

**Comment by LemonMantis5571** [comment]
I can work on this as following with the padding issues.

**Comment by anveshadixit** [comment]
i can also work on this

**Comment by Gungun1643** [comment]
You need to create your own issue.

**Comment by TusharKesarwani** [comment]
I already warned everyone to not create more than 4 issues at a time
First work and close old issues then create new issues
