### ISSUE TITLE
Add padding to the cards in the landing page -> Zomato 

### ISSUE THREAD

**Issue by Gungun1643** [TusharKesarwani/Front-End-Projects#1408]
**Describe the bug**
The page looks congested so need to add padding.

**To Reproduce**
1. Add padding 
2. Add more pictures 

**Expected behavior**

**Screenshots**
![bandicam 2023-06-22 13-53-37-964](https://github.com/TusharKesarwani/Front-End-Projects/assets/104245345/015e1f15-e001-4acc-9fc3-923618730fbf)

**Additional context**
Here is the link for reference:
https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Zomato-Landing-Page

**Comment by LemonMantis5571** [comment]
If the creator of the issue doesn't mind, I can fix this.

**Comment by TusharKesarwani** [comment]
I already warned everyone to not create more than 4 issues at a time
First work and close old issues then create new issues
