### ISSUE TITLE
New Text Utility

### ISSUE THREAD

**Issue by Shahil093** [TusharKesarwani/Front-End-Projects#1410]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Shahil093** [comment]
Please assign me this issue

**Comment by TusharKesarwani** [comment]
Create a new issue with proper description
