### ISSUE TITLE
Add readme in timer project

### ISSUE THREAD

**Issue by LemonMantis5571** [TusharKesarwani/Front-End-Projects#1416]
**Is your feature request related to a problem? Please describe.**
Project doesn't have  a proper and descritive readme

**Describe the solution you'd like**
I will add a clear and concise readme

Project:
https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Timer

**Comment by harshit-paneri** [comment]
Don't Send PR if you are not assigned yet.
