### ISSUE TITLE
Add this personal expense tracker project

### ISSUE THREAD

**Issue by harshitcompcode** [TusharKesarwani/Front-End-Projects#1417]
## **Describe the project**
A personal expense tracker web application that allows users to manage their income and expenses. It provides features to add, edit, and delete transactions, categorize them, perform calculations, and display a summary of the financial situation. Users can track their finances easily and make informed decisions.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [* ] New Project

## **Screenshots**

![Screenshot (233)](https://github.com/TusharKesarwani/Front-End-Projects/assets/84669711/e3795988-d673-4c2a-b1d7-738dc9a30df1)

**Comment by shivamsinghrajputcse** [comment]
can i get this project for contributing?

**Comment by jahnvisahni31** [comment]
please assign me this issue

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
