### ISSUE TITLE
Armstrong checker

### ISSUE THREAD

**Issue by suma30** [TusharKesarwani/Front-End-Projects#1418]
**Is your feature request related to a problem? Please describe.**
The background color of the page and the input box is same which is not so attractive.

**Describe the solution you'd like**
If the colors are different it would look better.

**Describe alternatives you've considered**
Changing the background color of the page.

**Additional context**
![Screenshot (53)](https://github.com/TusharKesarwani/Front-End-Projects/assets/112741893/ce8e7157-4a73-413c-a3ac-7d092ae35fee)

@TusharKesarwani @zugzwang03 please assign me this issue

**Comment by aaviiothic** [comment]
Assign me this issue please

**Comment by TusharKesarwani** [comment]
Do not create duplicate issue and pull request
