### ISSUE TITLE
News website project using HTML, CSS and JS

### ISSUE THREAD

**Issue by Samratghosh2004** [TusharKesarwani/Front-End-Projects#1420]
## **Describe the project**
Make an attractive responsive news channel site using HTML, CSS and JS, the user interface should be clean and fair. It must contain some newly published news after refreshing.

## Issue Type:

   - [ ] Bug Report
   - [ ] Feature Request
   - [ ] Documentation
  ✅ New Project

## **Additional context**
I expect that it might be done with a proper approach.

## **Something like 👇**

![WhatsApp Image 2023-06-22 at 23 12 03](https://github.com/TusharKesarwani/Front-End-Projects/assets/122769836/68e10d89-1170-4af3-b239-a369f5d99e5d)

**Comment by Akash1965** [comment]
@Samratghosh2004 @TusharKesarwani please assign me this issue. Also can I use React??

**Comment by arnab236** [comment]
@Samratghosh2004 @TusharKesarwani @zugzwang03 Can I get assigned for this issue?
