### ISSUE TITLE
Add hover effect to navbar in Triposity project

### ISSUE THREAD

**Issue by vibhuti0** [TusharKesarwani/Front-End-Projects#1422]
**Is your feature request related to a problem? Please describe.**
CSS animations can personalize your site and create delightful experiences for visitors. When a website visitor hovers over an animated element like a link or button, for example, Home, Hotels button This isn’t just eye candy — it’s also visual feedback that their interactions are working.

**Describe the solution you'd like**
I would like to add the hover effect to the navbar in the Triposity Project to make it look more delightful.

**Additional context**
[
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/103572736/9175cebd-696a-4c6f-8e3c-0408ea940c91)
](url)

please assign me this issue @TusharKesarwani  @zugzwang03

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start.
