### ISSUE TITLE
Country Guide App

### ISSUE THREAD

**Issue by kavyaag2607** [TusharKesarwani/Front-End-Projects#1423]
## **Describe the project**
I want to add a project made using HTML,CSS and JAVASCRIPT that allows the user to search for a particular country and then displays the information related to that country.
Please assign me this under SSOC'23

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by kavyaag2607** [comment]
@TusharKesarwani, @zugzwang03 sir please assign me this issue under SSOC 2.0

**Comment by Avdhesh-Varshney** [comment]
@zugzwang03 @TusharKesarwani sir, please assign this project to me to work under SSoC 2.0 program
