### ISSUE TITLE
Enhancing Speech to Text converter 

### ISSUE THREAD

**Issue by akshit20421** [TusharKesarwani/Front-End-Projects#1424]
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/103023426/9affec29-91e2-4a91-9b35-c2fb58b750a6)

**Issues--**
--> Currently, the project lacks a defined theme, color scheme, and a visually appealing look. This issue aims to enhance the project's appearance and create a more engaging user interface.
**Possible solutions --**
--> Defining a theme.
--> A proper color scheme.
-->Incorporate visual cues and feedback to enhance the user experience.
By addressing these theme, color, and overall look issues, we can significantly enhance the project's visual appeal, user experience, and engagement.

Kindly assign the issue @zugzwang03 @TusharKesarwani @harshit-paneri

**Comment by Benrobo** [comment]
Kindly assign this to me @TusharKesarwani
