### ISSUE TITLE
Transparent Login Form

### ISSUE THREAD

**Issue by Shivani0364** [TusharKesarwani/Front-End-Projects#1426]
## **Describe the project**
I want to add a project made using HTML,CSS and JAVASCRIPT that allows the user to login. It is basically a Transparent Login Form.
Please assign me this under SSOC'23

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
Login forms are used in almost every website and Application.  A Transparent login form design is the Eye catcher it is to authenticate the access to the user.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Neha5679** [comment]
I would like to work on it. Please assign me

**Comment by priyanka-6675** [comment]
i would like to work on this issues plz assign to me

**Comment by TusharKesarwani** [comment]
Login form project is already present in the repo
