### ISSUE TITLE
Coffee Menu (CSS Project)

### ISSUE THREAD

**Issue by vanya31** [TusharKesarwani/Front-End-Projects#143]

**Comment by Vanshiii203** [comment]
Please elaborate your issue.

**Comment by vanya31** [comment]
Its basically a coffee menu, just a display of css skills. I'll add a screenshot to clarify.
![image](https://user-images.githubusercontent.com/72427243/211211517-8b90c702-75b5-4005-92b2-297997f97ad1.png)

**Comment by Vanshiii203** [comment]
@vanya31 Go ahead!
