### ISSUE TITLE
[SSoC 2.0] Generate Leap years in a Range of Years

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [TusharKesarwani/Front-End-Projects#1431]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
- Front end project
- Created using HTML, CSS and JS
- This project has a attractive and responsive user interface
- Generate number of leap years in between two entered years

## Issue Type:

- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.
- This project will tell the number of leap years and enlist those years
- This project can also check the entered year is a leap year or not

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @zugzwang03 Sirs, please assign this project to me to work on it and give a valuable contribution in this repository under SSoC 2.0 program

**Comment by Achandu905** [comment]
is this solved.?
