### ISSUE TITLE
Beyblade Card Catalog

### ISSUE THREAD

**Issue by mohammadshahjahan** [TusharKesarwani/Front-End-Projects#1433]
## **Describe the project**
Beyblade Card Catalog web page. The goal of this project is to build an interactive frontend page that displays Beyblade cards fetched from a JSON file and incorporates a filtering mechanism to enhance user experience and facilitate card exploration.
The web page will showcase a visually appealing interface where Beyblade cards will be presented. The project will leverage a JSON file containing data for various Beyblade cards. This data will be dynamically fetched and utilized to populate the card catalog, ensuring easy maintenance and future expansion of the card collection. The frontend page will incorporate a filtering mechanism to allow users to narrow down their card search based on specific criteria. The web page will be developed with a responsive design approach, ensuring optimal display and functionality across different devices and screen sizes. 

## Technologies:
- HTML
- CSS
- JavaScript

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
The frontend interface will incorporate a filtering feature, enabling users to narrow down their card search based on specific parameters. The web page will be created with a mobile-responsive design approach, guaranteeing excellent display and usability across diverse devices and screen dimensions.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by jahnvisahni31** [comment]
please assign me this issue

**Comment by mohammadshahjahan** [comment]
Please assign me this issue under SSOC 2.0 @TusharKesarwani

**Comment by mohammadshahjahan** [comment]
@TusharKesarwani  @zugzwang03 Sirs, please review this pr and merge it into the main branch of this repository for a successful contribution under SSoC 2.0 program

**Comment by mohammadshahjahan** [comment]
@TusharKesarwani  @zugzwang03 Dear Sirs, I kindly request you to review this pull request and consider merging it into the main branch of this repository. By doing so, we will achieve a successful contribution under the SSoC 2.0 program. The pull request includes the addition of a project and the resolution of a bug that was previously preventing projects from rendering on the main page.

Thank you for your attention and consideration.
