### ISSUE TITLE
Add ReadMe.md to Drink Water Reminder project

### ISSUE THREAD

**Issue by krutika-ladani** [TusharKesarwani/Front-End-Projects#1435]
ReadMe file is missing in the Drink water reminder project. I want to add it.
Please assign me this issue under SSOC 2.0.

**Project url**: https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/DrinkWaterReminderApplication

**Comment by krutika-ladani** [comment]
@TusharKesarwani, @zugzwang03 and @harshit-paneri please assign me this issue under SSOC 2.0

**Comment by hyunjunghwang** [comment]
Can I try working on this?
