### ISSUE TITLE
Copyright year not updated

### ISSUE THREAD

**Issue by Divya5003** [TusharKesarwani/Front-End-Projects#1436]
**Describe the bug**
The Shades - Business Website has hardcorded year value 2022.

**Expected behavior**
A function to get the current year.

**Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/99502665/75fbcda1-7d11-4756-a302-429d1e85f321)

Please assign this issue to me.

**Comment by harshit-paneri** [comment]
Suggest to add more feature also.

**Comment by Divya5003** [comment]
We can add a back to top button to navigate to the top of the webpage.

**Comment by Divya5003** [comment]
Should I create a new issue for that?

**Comment by harshit-paneri** [comment]
no not required

**Comment by TusharKesarwani** [comment]
Not required

**Comment by TusharKesarwani** [comment]
Do not link two PRs in one issue
