### ISSUE TITLE
3D Social Media Icons

### ISSUE THREAD

**Issue by Mansi8874** [TusharKesarwani/Front-End-Projects#1437]
## **Describe the project**
3D social Media icons using html css and javascript.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
I want to work on this issue. Please assign this issue to me @TusharKesarwani 

## **Screenshots**

<img width="864" alt="Screenshot 2023-06-23 at 4 34 47 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/101468475/cd3db8c2-c769-4530-bf25-eff05f0923e1">

**Comment by TusharKesarwani** [comment]
I already warned everyone to not create more than 4 issues at a time
First work and close old issues then create new issues
