### ISSUE TITLE
[SSoC 2.0] Playable Piano Project

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [TusharKesarwani/Front-End-Projects#1445]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

- Front end project
- Created using HTML, CSS and JS
- Showing keys on the screen
- Piano board is responsive to all the devices
- For larger screen piano board will be larger and for smaller screen it will be smaller
- It will responsive with the mouse click and keyboard pressing buttons
- Adding a volume slide to make it more attractive and functioning

## Issue Type:

- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by harshit-paneri** [comment]
> @TusharKesarwani @harshit-paneri @zugzwang03 Sirs, please assign this project to me to work on it and contribute under SSoC 2.0 open source program

I request you to please work on single project at one time, bcz if I assign you 3-4 issues other contributors are not able to work on it.

**Comment by Avdhesh-Varshney** [comment]
@harshit-paneri Sir, you are right, but i have completed these projects 

Screenshot
![Screenshot 2023-06-24 012215](https://github.com/TusharKesarwani/Front-End-Projects/assets/114330097/9aff6384-8a9c-4984-9919-9651ce0d33c3)

That's why i have created these issues.

**Comment by harshit-paneri** [comment]
Okay
