### ISSUE TITLE
[SSoC 2.0] Video Player Front end project

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [TusharKesarwani/Front-End-Projects#1446]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
- Front end project
- Creating using HTML, CSS and JS
- This project will fetch the videos from the current directory
- Enlist all the videos names in front of the user
- Asking for to play which video
- Click on that name and video will start playing
- Adding controls of sounds and screen
- Attractive background with best user interface and providing a best experience to the user

## Issue Type:

- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.
- This project will be very helpful to automate any directory to play the videos

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @harshit-paneri @zugzwang03 Sirs, Please assign this project to me to work on it and contribute a valuable pr on this repository under SSoC 2.0 program

**Comment by harshit-paneri** [comment]
> ## **Describe the project**
> A clear and concise description of the project you are going to add to this repository.
> 
> * Front end project
> * Creating using HTML, CSS and JS
> * This project will fetch the videos from the current directory
> * Enlist all the videos names in front of the user
> * Asking for to play which video
> * Click on that name and video will start playing
> * Adding controls of sounds and screen
> * Attractive background with best user interface and providing a best experience to the user
> 
> ## Issue Type:
> * [x]  New Project
> 
> ## **Additional context**
> Add any other context or screenshots about the project here.
> 
> * This project will be very helpful to automate any directory to play the videos
> 
> ## **Screenshots**

are you planning to make YouTube with other background?

**Comment by Avdhesh-Varshney** [comment]
@harshit-paneri sir not exact, Just a front end video player which can takes the list of the videos where these files will be kept and using js fetching the list of the videos and enlist those towards the user.
User will chose the video and play them and enjoy it.

**Comment by harshit-paneri** [comment]
> @harshit-paneri sir not exact, Just a front end video player which can takes the list of the videos where these files will be kept and using js fetching the list of the videos and enlist those towards the user. User will chose the video and play them and enjoy it.

Okay, Lets do.
