### ISSUE TITLE
adding a button from which given result remove and again button come for search in world info website

### ISSUE THREAD

**Issue by 2020B1531074** [TusharKesarwani/Front-End-Projects#1457]
![Screenshot (166)](https://github.com/TusharKesarwani/Front-End-Projects/assets/98419710/1571c8b1-cd1b-4ceb-8c03-a160a9e992e3)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 2020B1531074** [comment]
please assigned me this issue

**Comment by priyanka-6675** [comment]
sir plz assign this to me
