### ISSUE TITLE
workspace button is not working in windows11 project

### ISSUE THREAD

**Issue by 2020B1531074** [TusharKesarwani/Front-End-Projects#1458]
![Screenshot (165)](https://github.com/TusharKesarwani/Front-End-Projects/assets/98419710/792be538-cf28-4bdd-aec9-e7fb3ec8e631)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TusharKesarwani** [comment]
That was a webpage, not a whole windows system
