### ISSUE TITLE
Fixing the current UI

### ISSUE THREAD

**Issue by detronetdip** [TusharKesarwani/Front-End-Projects#1463]
Currently here are multiple UI related issues which are making the website not well visually

See the below 
![Screenshot from 2023-06-24 22-34-09](https://github.com/TusharKesarwani/Front-End-Projects/assets/64276906/9e24ebd4-3b42-4577-839e-86e31aaba4c6)
 here the search box is not aligned properly with the image and it is not looking good.

Next if we reduce the screen size the button looks horrible

![Screenshot from 2023-06-24 22-34-46](https://github.com/TusharKesarwani/Front-End-Projects/assets/64276906/a5d98dd2-f0d7-4782-aaa9-ede37ca89314)

In smaller screen the space in the right hand side is too much

![Screenshot from 2023-06-24 22-35-15](https://github.com/TusharKesarwani/Front-End-Projects/assets/64276906/c021853d-d6ef-43e1-8210-41ea01d37580)

This things are impacting the the visual of the website.

**Comment by detronetdip** [comment]
@TusharKesarwani If this issue looks reasonable please assign me this issue I want to work on this

**Comment by rahulrana701** [comment]
@TusharKesarwani  I have already fixed this issue and created a pr for this which got approved by the mentors 
<img width="932" alt="Screenshot 2023-06-28 135626" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/123585591/073e4ccf-0008-4226-b9d5-f6667c3ab09a">
<img width="943" alt="Screenshot 2023-06-28 135651" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/123585591/8979fd5f-90a1-42f2-a817-f636f32a1440">
