### ISSUE TITLE
[Feature]: Contributors' Names Not Displayed in Contributors Section

### ISSUE THREAD

**Issue by Kalyan-velu** [TusharKesarwani/Front-End-Projects#1466]
## Is your feature request related to a problem? Please describe.
The problem is that the contributors' names are not displayed in the contributors section of the repository. Currently, there is no visibility or acknowledgment of the individuals who have contributed to the project, making it difficult to identify and recognize their contributions.

## Describe the solution you'd like
I would like to suggest adding a `title` attribute to the contributors' names in the contributor's section. This attribute would display the name of the contributor as a tooltip when users hover over their avatars or names. By implementing this solution, the contributors' names would become visible and easily identifiable, enhancing transparency and recognition for their contributions.

## Describe alternatives you've considered
An alternative solution could be to display the contributors' names directly in the contributor's section without the need for a tooltip. However, this might clutter the UI, especially if there are numerous contributors. The `title` attribute provides a concise and elegant solution by showing the name only when the user hovers over the contributor's avatar or name, maintaining a clean and organized display.

## Additional context
Currently, the lack of contributors' names in the contributor's section makes it challenging to acknowledge and appreciate individual contributions. By adding the `title` attribute, users can hover over contributors' avatars or names to see their respective names, fostering a more inclusive and collaborative environment for the project.

No additional screenshots or context is available at the moment.

**Comment by Kalyan-velu** [comment]
Can I work on this??

**Comment by TusharKesarwani** [comment]
Already present in the website
