### ISSUE TITLE
3D SocialMedia Icons

### ISSUE THREAD

**Issue by Rohith1816** [TusharKesarwani/Front-End-Projects#1467]
## **3D SocialMedia Icons**
3D SocialMedia Icons with a small animation while hovering over it 

Project have a feautre i.e., while hovering over the icon I have added a small animation

Please assign this task to me under SSOC because this is my first contribution in SSOC

**Comment by khushi767** [comment]
Please assign this task to me under SSOC i will add social media icons

**Comment by Gyanthakur** [comment]
please assign this issue for me

**Comment by TusharKesarwani** [comment]
Already present
