### ISSUE TITLE
Give proper title to the drink water reminder project

### ISSUE THREAD

**Issue by krutika-ladani** [TusharKesarwani/Front-End-Projects#1470]
Title of drink water reminder project is default title 'Document'. I want to change it to 'H2OTracker'
@zugzwang03 / @harshit-paneri please assign me this issue.

![Screenshot (64)](https://github.com/TusharKesarwani/Front-End-Projects/assets/119760273/026d75c7-1c43-49f5-b242-c1860e763766)

**Comment by zugzwang03** [comment]
Hey don't create issues on very small changes, you can rather fix bugs on many projects as a whole, but this is way too small for taken as an issue. I overlooked initially.

**Comment by krutika-ladani** [comment]
> Hey don't create issues on very small changes, you can rather fix bugs on many projects as a whole, but this is way too small for taken as an issue. I overlooked initially.

Ok! sorry for that, I will keep it in mind next time. But what about README files? Many projects are missing those, so is it okay to add that? @zugzwang03
