### ISSUE TITLE
Beauty Zone 

### ISSUE THREAD

**Issue by AdityaGaur7** [TusharKesarwani/Front-End-Projects#1476]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![Screenshot (256)](https://github.com/TusharKesarwani/Front-End-Projects/assets/121216575/6e280913-4d99-40ad-843e-16a3a0793fe8)

the submit button's size is incorrect 
@TusharKesarwani sir assign this to me

**Comment by amanupadhyay33822** [comment]
I am currently a member of ssoc. please assign this issue to me.

**Comment by lalitkumawat1m** [comment]
I am not able to see this issue now I think some one has fixed it
