### ISSUE TITLE
Movie ticket booking Site

### ISSUE THREAD

**Issue by MridulGupta007** [TusharKesarwani/Front-End-Projects#148]
Pls assign

**Comment by harshit-paneri** [comment]
Provide Little more Details , Not only Heading.

**Comment by AnuragJha003** [comment]
I want to contribute to this repo please assign. I will start working on it from 24th January.

**Comment by AnuragJha003** [comment]
Do we have to build from scratch ?

**Comment by MridulGupta007** [comment]
@AnuragJha003 It is already assigned to me, the pr will be made by tonight
