### ISSUE TITLE
Age generator

### ISSUE THREAD

**Issue by SimranLahrani842** [TusharKesarwani/Front-End-Projects#1481]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
I m going to create an age calculator. As you can see from the final version of the project, we have a container here with the title age calculator with an input of a date. If we click on the date input, we can choose the date of our birthday. For example, if we choose a date in in 2022 and if we click now on Calculate Age, you can see the age is calculated based on this date and saying your age is 21 years old.
## Issue Type:
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by SimranLahrani842** [comment]
> ## **Describe the project**
> A clear and concise description of the project you are going to add to this repository. I m going to create an age calculator. As you can see from the final version of the project, we have a container here with the title age calculator with an input of a date. If we click on the date input, we can choose the date of our birthday. For example, if we choose a date in in 2022 and if we click now on Calculate Age, you can see the age is calculated based on this date and saying your age is 21 years old.
> 
> ## Issue Type:
> * [x]  New Project
> 
> ## **Additional context**
> Add any other context or screenshots about the project here.
> 
> ## **Screenshots**
> * If applicable, add screenshots to help explain your problem.

Please add assigned comment @TusharKesarwani

**Comment by harshsinghcs** [comment]
Please assign this issue to me under SSOC 2.0 @TusharKesarwani @SimranLahrani842
