### ISSUE TITLE
Binary - Decimal Converter

### ISSUE THREAD

**Issue by Khushi6517** [TusharKesarwani/Front-End-Projects#1484]
I want to add a project made using HTML, CSS, JavaScript that help us to convert Binary number to decimal and Decimal to Binary.

Issue Type:
- [x] New Project

![convertor](https://github.com/TusharKesarwani/Front-End-Projects/assets/112777258/cc2d1078-e7ef-4bcc-bf18-c5fd56af3b9e)

**Comment by Khushi6517** [comment]
Sir, Can u please assign this issue to me.

**Comment by Khushi6517** [comment]
@TusharKesarwani  @harshit-paneri  
Sir can u please merge this ....

**Comment by Tanyamodi** [comment]
I would like to work on this issue, kindly assign this to me.

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
