### ISSUE TITLE
Adding Memory Card Game

### ISSUE THREAD

**Issue by dhruti26** [TusharKesarwani/Front-End-Projects#1488]
## **Description**
I want to add Memory Card game, in which we flip cards and match it,made using HTML,CSS and Javascript

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

**Comment by Vaishnavikathar18** [comment]
Please assign me this issue

**Comment by dhruti26** [comment]
@harshit-paneri @TusharKesarwani @zugzwang03 Please assign me this issue under SSOC'23

**Comment by zugzwang03** [comment]
game projects not allowed!
