### ISSUE TITLE
Add Log-in Form Project

### ISSUE THREAD

**Issue by Abhay3819** [TusharKesarwani/Front-End-Projects#1494]
## **Describe the project**
Hii @TusharKesarwani , I want to add this project so please assign to me.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![Screenshot (579)](https://github.com/TusharKesarwani/Front-End-Projects/assets/110670975/bb4a0579-1098-4b17-b3d9-be37bc5f12a7)

**Comment by TusharKesarwani** [comment]
Already present in the repo
