### ISSUE TITLE
Add Temperature Converter Project

### ISSUE THREAD

**Issue by Abhay3819** [TusharKesarwani/Front-End-Projects#1495]
## **Describe the project**
Hii @TusharKesarwani , I want to add this project so please assign to me.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**
![Screenshot (580)](https://github.com/TusharKesarwani/Front-End-Projects/assets/110670975/3996d19c-8eee-4342-be08-c505da83ea5b)

**Comment by Shital2409** [comment]
Please assign me this project I want to work on it under ssoc.2.0

**Comment by mayurd8862** [comment]
@TusharKesarwani please assign me this issue, this will be my first open source project and it will be helpful for my future open source journey.

**Comment by TusharKesarwani** [comment]
Already present in the repo
