### ISSUE TITLE
Add Image gallery Project

### ISSUE THREAD

**Issue by Abhay3819** [TusharKesarwani/Front-End-Projects#1496]
## **Describe the project**
Hii @TusharKesarwani , I want to add this project so please assign to me.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![Screenshot (578)](https://github.com/TusharKesarwani/Front-End-Projects/assets/110670975/64e934ce-3aa1-4beb-aef2-f7dfb88f87c4)

**Comment by Jaskaran2609** [comment]
Please assign this to me under SSOC.2.0

**Comment by TusharKesarwani** [comment]
Not required
