### ISSUE TITLE
Add Banking System Project

### ISSUE THREAD

**Issue by Abhay3819** [TusharKesarwani/Front-End-Projects#1498]
## **Describe the project**
Hii @TusharKesarwani , I want to add this project so please assign to me.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![Screenshot (582)](https://github.com/TusharKesarwani/Front-End-Projects/assets/110670975/f39d37a7-17e6-4be5-98f4-470cb4ac70f0)

![Screenshot (583)](https://github.com/TusharKesarwani/Front-End-Projects/assets/110670975/65ae849f-e8ff-429d-87e2-9bc02f1ba61c)

**Comment by Akshat111111** [comment]
Please Assign this project,I want to improve it
