### ISSUE TITLE
Adding New Front End Web Application for Food Website using bootstrap

### ISSUE THREAD

**Issue by ARCHITABHATTAD** [TusharKesarwani/Front-End-Projects#15]
@TusharKesarwani please assign me this issue under swoc tag!

**Comment by TusharKesarwani** [comment]
Go ahead @ARCHITABHATTAD

**Comment by ARCHITABHATTAD** [comment]
@TusharKesarwani, I have already submitted my PR and the project is also merged into your repo...but I wish to make a few more changes in my project....I that possible?

**Comment by TusharKesarwani** [comment]
> @TusharKesarwani, I have already submitted my PR and the project is also merged into your repo...but I wish to make a few more changes in my project....I that possible?

Yes you can
