### ISSUE TITLE
Quiz app 

### ISSUE THREAD

**Issue by SimranLahrani842** [TusharKesarwani/Front-End-Projects#1501]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
A quiz app displays questions along with 4 options.
We need to select the right answers.
The questions can be anything related to html too.
The final score will be displayed at the last.
Made using HTML,CSS and JS.

## Issue Type:
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by SimranLahrani842** [comment]
> ## **Describe the project**
> A clear and concise description of the project you are going to add to this repository. A quiz app displays questions along with 4 options. We need to select the right answers. The questions can be anything related to html too. The final score will be displayed at the last. Made using HTML,CSS and JS.
> 
> ## Issue Type:
> * [x]  New Project
> 
> ## **Additional context**
> Add any other context or screenshots about the project here.
> 
> ## **Screenshots**
> * If applicable, add screenshots to help explain your problem.

Assign me this @zugzwang03

**Comment by koval77** [comment]
Hello, could you assign me this, please?
