### ISSUE TITLE
Amazon Clone

### ISSUE THREAD

**Issue by Mansi8874** [TusharKesarwani/Front-End-Projects#1503]
## **Describe the project**
Amazon clone built using HTML and CSS- provide a similar visual experience to Amazon's website.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
I want to work on this issue. Please assign this issue to me @TusharKesarwani 

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by TusharKesarwani** [comment]
I already warned everyone to not create more than 4 issues at a time
First work and close old issues then create new issues
