### ISSUE TITLE
Weather app using Html,css,js

### ISSUE THREAD

**Issue by princekumarg** [TusharKesarwani/Front-End-Projects#1508]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by princekumarg** [comment]
@harshit-paneri please assigne this issue to me

**Comment by TusharKesarwani** [comment]
Project is already present in the repo
