### ISSUE TITLE
React Movie and Series Application

### ISSUE THREAD

**Issue by Srilekha-09** [TusharKesarwani/Front-End-Projects#1522]
## **Describe the project**
I want to contribute to a project on movie application where I want to show all the trending Movies and Series .Users can also select series and movies based on their preferred genre and they can also get the details about the specific series or movie. Create a section where the user can search for movies and series as well, users can search by the movie name or series name and they will get to see all the results related to that particular name.

## Issue Type:
- [ *] New Project

**Comment by TusharKesarwani** [comment]
React projects are not accepted
