### ISSUE TITLE
I want to make a Text Editor application.

### ISSUE THREAD

**Issue by kumar007ambi** [TusharKesarwani/Front-End-Projects#1526]
## **Describe the project**
This app will convert simple text into bold,italic,underlined and centered

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by 07-Atharv** [comment]
I am intrested in these

**Comment by TusharKesarwani** [comment]
Project is already present
