### ISSUE TITLE
Caesar Cipher

### ISSUE THREAD

**Issue by suma30** [TusharKesarwani/Front-End-Projects#1529]
**Describe the bug**
The boxes are not at the Centre of page and also
the second box is not having the borders same as other one.

**Expected behavior**
Centered elements and similar borders

**Screenshots**
![Screenshot (58)](https://github.com/TusharKesarwani/Front-End-Projects/assets/112741893/3eea64ea-251f-4090-9613-f5bb92753cad)

**Additional context**
@TusharKesarwani @zugzwang03 Please assign me this issue

**Comment by TusharKesarwani** [comment]
Everything is working fine already
Changes are not needed
