### ISSUE TITLE
FaceBook Login page Clone

### ISSUE THREAD

**Issue by SattyamSamania** [TusharKesarwani/Front-End-Projects#1532]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
- I want to add a clone of FaceBook Login Page made with HTML and Tailwind  CSS.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

![Screenshot (15)](https://github.com/TusharKesarwani/Front-End-Projects/assets/67833888/1172cbd2-f41c-47a7-aa99-238f7d6be3a0)

**Comment by Vaishnavikathar18** [comment]
@TusharKesarwani can u please assign me this issue

**Comment by Vaishnavikathar18** [comment]
@SattyamSamania can u please assign me this issue

**Comment by TusharKesarwani** [comment]
Login page project is already present in the repo
