### ISSUE TITLE
Blur Image

### ISSUE THREAD

**Issue by kumar007ambi** [TusharKesarwani/Front-End-Projects#1535]
**Describe the bug**
In Villa Hotel Website , in about page resort image is blurry. 

**Expected behavior**
I want to add a good quality image.

**Screenshots**
![IssueSSOC1](https://github.com/TusharKesarwani/Front-End-Projects/assets/60788663/695bc431-9d77-4587-a95f-51f9dcf77047)

**Comment by TusharKesarwani** [comment]
Not Required
