### ISSUE TITLE
Navbar not responsive

### ISSUE THREAD

**Issue by ak-sh-at** [TusharKesarwani/Front-End-Projects#1536]
**Describe the bug**
In the project SSOC'23 Navbar clone (https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/SSOC'23%20Navbar%20clone) the navbar is not responsive.

**Expected behavior**
The navbar should be responsive

**Screenshots**
![Screenshot (97)](https://github.com/TusharKesarwani/Front-End-Projects/assets/121859445/87e1e36a-f205-4a15-a420-90cd16cfdcd3)

**Comment by ak-sh-at** [comment]
@TusharKesarwani @zugzwang03 @harshit-paneri Please assign this issue to me under SSOC 2.0

**Comment by priyanka-6675** [comment]
sir plz assign this issue to me ....
