### ISSUE TITLE
Mouse Event Project

### ISSUE THREAD

**Issue by SimranLahrani842** [TusharKesarwani/Front-End-Projects#1540]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
We create a mouse event project that tracks the mouse's position on the screen. Moving the mouse around will display X and Y positions that change as you move. These measurements are useful for designing websites and writing CSS. We'll use the "add event listener" method to track mouse position in the browser. This mouse event project can also teach you how to use JavaScript to build web apps that respond to user input

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by UtkarshLB216** [comment]
Good first issue

**Comment by TusharKesarwani** [comment]
Not required
