### ISSUE TITLE
Sorting Algorithm Visulizer.

### ISSUE THREAD

**Issue by princekumarg** [TusharKesarwani/Front-End-Projects#1542]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
<img width="1011" alt="Screenshot 2023-07-01 164228" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/86905668/5a503d7e-58f2-40d6-b9b4-539cad9ce344">

**Comment by princekumarg** [comment]
@TusharKesarwani please assign this issue to me.

**Comment by TusharKesarwani** [comment]
Already present in the repo
