### ISSUE TITLE
Footer Text not alligned and Bottom Scrollbar

### ISSUE THREAD

**Issue by kumar007ambi** [TusharKesarwani/Front-End-Projects#1543]
**Describe the bug**
The bottom scroolbar is unnessecary and Footer or Bottom copyright Text should be fixed.

**Expected behavior**
The bottom scrollbar needs to be fixed and the copyright text should be center alligned.

**Screenshots**
![SSOC_Issue3](https://github.com/TusharKesarwani/Front-End-Projects/assets/60788663/ea23dfea-156a-42c4-a976-28d6db436721)

**Comment by Shital2409** [comment]
assign me this issue pl!

**Comment by kumar007ambi** [comment]
@TusharKesarwani can you assign me this issue

**Comment by kumar007ambi** [comment]
@TusharKesarwani @zugzwang03 @harshit-paneri can I start working on it.
