### ISSUE TITLE
Free study resource website for students of different engineering branch

### ISSUE THREAD

**Issue by YashReddy1963** [TusharKesarwani/Front-End-Projects#1547]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
I want to create a website where students of different engineering branches can access study resources for free
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.
The website will have a user-friendly UI where students will be able to access resources like books, notes for different engineering branch students
In this project I have created three section of computer science, mechanic and electronics branch where they can get access to different projects for free
![Screenshot (83)](https://github.com/TusharKesarwani/Front-End-Projects/assets/119090589/b4ecd089-b952-43a5-8dd4-f855cac81dde)
## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot (82)](https://github.com/TusharKesarwani/Front-End-Projects/assets/119090589/33c4baf4-a80f-443a-8821-4f55fc39f2c0)

**Comment by YashReddy1963** [comment]
Hey @TusharKesarwani would you please assign me this issue under SSOC'23

**Comment by YashReddy1963** [comment]
@Arun9739, @siddhi-244, @harsh5902  will you please assign me this issue since my project is half completed

**Comment by TusharKesarwani** [comment]
Not required
