### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by ak-sh-at** [TusharKesarwani/Front-End-Projects#1549]
**Describe the bug**
In the project Mixtape (https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Mixtape) 
The navbar is not responsive.
Further, the text inside container is flowing out on small screens.

**Expected behavior**
Website should be responsive.

**Screenshots**

On normal window screens

![Screenshot (100)](https://github.com/TusharKesarwani/Front-End-Projects/assets/121859445/ad37e953-9bf1-4e3f-8170-e46e4f8b1124)
 
On Small Window screens

![Screenshot (99)](https://github.com/TusharKesarwani/Front-End-Projects/assets/121859445/c61361ab-f263-4605-9467-e7e02739f7e8)

**Comment by ak-sh-at** [comment]
@TusharKesarwani @zugzwang03 @harshit-paneri Please assign this issue to me under SSOC 2.0

**Comment by RazaHussainAziz** [comment]
Please assign this issue to me.
