### ISSUE TITLE
[SSoC 2.0] Whatsapp Clone Frontend project

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [TusharKesarwani/Front-End-Projects#1551]
## **Describe the project**
Title - Whatsapp clone
Tech using - HTML, CSS and JS

I would like to clone the whatsapp website.
Adding Responsiveness for the small devices and large devices.

## Issue Type:

- [x] New Project

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @harshit-paneri @zugzwang03 please assign this project to me

**Comment by SubiditaB** [comment]
Please assign me this issue. I really want to do this. Can I contribute to it too? 
@Avdhesh-Varshney , please.

**Comment by SubiditaB** [comment]
please assign me this issue. I would love to contribute to this. Please can I contribute too? @TusharKesarwani

**Comment by Avdhesh-Varshney** [comment]
> please assign me this issue. I would love to contribute to this. Please can I contribute too? @TusharKesarwani 

This is wrong. Please create your own issue. I'm working on it.
