### ISSUE TITLE
Magic Notes Front-End _Project

### ISSUE THREAD

**Issue by Adityamishra9719** [TusharKesarwani/Front-End-Projects#1556]
## **Describe the project**
      MAGIC NOTES 
It is a simple notes keeping project .
It is a REACT APP .
There are two fields the title field and the message field and a add button using it you can add the note
There is delete button for deleting the notes.
It looks like the below screen shot :-

## **Screenshots**
![Magic Notes](https://github.com/TusharKesarwani/Front-End-Projects/assets/105539123/bf9dc59a-f558-4596-ad2d-81a9c590fcf3)

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

Pls assign this project to me .
Thank you

**Comment by Adityamishra9719** [comment]
Hi, @TusharKesarwani pls assign this to me

**Comment by Akshat111111** [comment]
Please assign me the project
