### ISSUE TITLE
Issue in Analog Clock

### ISSUE THREAD

**Issue by Abhishantpadam** [TusharKesarwani/Front-End-Projects#1558]
**Describe the bug**
There are two issues in Analog clock
- The Clock is not oriented correctly means it is upside down. It's showing correct time but upside down.
- And the other issue is numbers are not in correct orrientation like if you see number 6 it will not look like 6 it will more look like 9.

**To Reproduce**
1. Go to 'Front-End-Projects Repository'
2. Click on 'Projects'
3. Click on 'Analog Clock'
4. Run the index file in your local host
5. now to see the correct time, Rotate your screen upside down or 180°.
6. Please see the screenshot what i'm talking about.

**Expected Behavior**
should be oriented correctly. and tell correct time.

**Screenshots**
<img width="1440" alt="Screenshot 2023-07-02 at 11 18 56 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/46023761/61de40d5-da59-4800-8844-0139884500d7">

**Desktop :**
 - OS: [iOS]
 - Browser [Chrome, safari]

**Comment by Abhishantpadam** [comment]
Please assign this issue to me.

**Comment by manishsinghmodi** [comment]
please assign to me.

**Comment by Abhishantpadam** [comment]
Please assign this issue to me. I will solve this issue.

**Comment by Abhishantpadam** [comment]
Hi Tushar its been a week to post the issue here please assign this issue to me so that i can start working on it.
