### ISSUE TITLE
Ecommerce website

### ISSUE THREAD

**Issue by vaishnavi-3969** [TusharKesarwani/Front-End-Projects#1568]
## **Describe the project**
A fully functional e-commerce website with product listings, search functionality, user authentication, shopping cart, checkout process, and order history. Implementation of  features like product filtering, sorting, and pagination for a seamless user experience using HTML, CSS and JS

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

**Comment by debdutta04** [comment]
please assign me this issue i would like to work on this

**Comment by chandug25** [comment]
hey @vaishnavi-3969 could you please assign this issue to me , ?

**Comment by TusharKesarwani** [comment]
Project is already present in the repo
