### ISSUE TITLE
Gooey cursor

### ISSUE THREAD

**Issue by suma30** [TusharKesarwani/Front-End-Projects#1572]
**Describe the bug**
The font and its style are not very appealing.

**Expected behavior**
Proper styling and size of elements.

**Screenshots**
![Screenshot (64)](https://github.com/TusharKesarwani/Front-End-Projects/assets/112741893/f4fa3086-608b-4818-bbb2-a7c174e99fa5)

**Additional context**
@TusharKesarwani @zugzwang03 @harshit-paneri Please assign me this issue for gooey cursor site

**Comment by Shital2409** [comment]
@TusharKesarwani please assign me this issue under ssoc2.0
