### ISSUE TITLE
Shopping-List

### ISSUE THREAD

**Issue by Keyuri-19** [TusharKesarwani/Front-End-Projects#1575]
## **Describe the project**
A page made with the help of html css and Javascript which will add and remove items according to the user and will generate list of items mentioned by the user 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/115471178/98459304-cad1-41cd-aed7-09cc21cda4ac)

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Keyuri-19** [comment]
@harshit-paneri @TusharKesarwani @zugzwang03 Please assign these issue to me.

**Comment by ashajyothi06** [comment]
please assign me this issue @TusharKesarwani

**Comment by Keyuri-19** [comment]
@TusharKesarwani @harshit-paneri @zugzwang03  Please assign my issue to me
