### ISSUE TITLE
On Search button, there is history visible of the searched data

### ISSUE THREAD

**Issue by maitri-vv** [TusharKesarwani/Front-End-Projects#1577]
**Describe the bug**
On the search button, one can see the search history when clicked on the button. It should be off to have privacy for the site users.

**To Reproduce**
1. Go to 'Home page -> Projects -> Search Projects'
2. Click on 'Enter Projects to search '
3. See error

**Expected behavior**
Disabling search history

**Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/87691594/0595ed0f-d4f4-48a8-9b91-eb253ac32579)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maitri-vv** [comment]
Raised a PR: #1578 for addressing the issue

**Comment by Jatingupta9120** [comment]
plz assign this issue to me under ssoc this is my first contribution I m begineer
