### ISSUE TITLE
Countdown Timer

### ISSUE THREAD

**Issue by Keyuri-19** [TusharKesarwani/Front-End-Projects#1583]
## **Describe the project**
A Countdown Timer build with the help of HTML CSS and JavaScript which will start counting the time left for the value of date and time entered by the user.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/115471178/3e1974b5-7f7c-46b5-ab0f-907b94c5223b)

**Comment by Keyuri-19** [comment]
@TusharKesarwani @zugzwang03 @harshit-paneri Please assign these issue to me

**Comment by karenhernandeze** [comment]
Hi, can I be assigned this issue?
