### ISSUE TITLE
Youtube Clone

### ISSUE THREAD

**Issue by TusharGagal** [TusharKesarwani/Front-End-Projects#1585]
## **Describe the project**
A fully functional youtube clone very similar to youtube website with suggested videos, channel details, channel videos, video deatils, playlist videos,playlist details search option. Implentation of these features by youtube api from Rapid api. 
Tech stack: HTML,CSS,JS
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

@TusharKesarwani please assign me this project as this my first contribution in SSOC'23.

**Comment by Vaishnavikathar18** [comment]
@TusharKesarwani please assign me this issue

**Comment by TusharKesarwani** [comment]
The project is already present in the repo

**Comment by TusharGagal** [comment]
using react js????

**Comment by TusharGagal** [comment]
all mentor reply after a long time i am not able to contribute into a single issue under ssoc. i have commented on mainy unassigned issues but got no replies form mentor.
