### ISSUE TITLE
[SSOC'23] Basic banking System Website

### ISSUE THREAD

**Issue by shubhanshurav** [TusharKesarwani/Front-End-Projects#1586]
## **Describe the project**

Hey @TusharKesarwani , I want to add "Basic Banking System" website. so please assign me this issue under gssoc'23.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/87806305/da088f64-c25e-446c-aed7-25b52dd617fa)

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/87806305/c0b14a76-0da7-4c08-bba7-fe8dc7c82f29)

**Comment by shubhanshurav** [comment]
Hey @TusharKesarwani, please assign me this issue under SSOC'23.

**Comment by TusharKesarwani** [comment]
https://github.com/TusharKesarwani/Front-End-Projects/issues/1498
