### ISSUE TITLE
Flipkart Clone

### ISSUE THREAD

**Issue by Vanshika-73** [TusharKesarwani/Front-End-Projects#159]
I wanna to add my flipkart clone project which is made using HTML,CSS.

**Comment by sumitkr2000** [comment]
Hey @abhilipsasahoo03 @Vanshiii203  can I work on this issue?

**Comment by Vanshiii203** [comment]
You can ,create a new issue and then I will assign it to you

**Comment by sumitkr2000** [comment]
ok mam @Vanshiii203  :)
