### ISSUE TITLE
Prime checker

### ISSUE THREAD

**Issue by ak-sh-at** [TusharKesarwani/Front-End-Projects#1590]
**Describe the bug**
In the project Prime Checker (https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/prime%20checker) the placeholder text is cut off and the text "Check" is overflowing out of button.

**Expected behavior**
The placeholder text in input should be visible and the text inside button should not overflow.

**Screenshots**

![Screenshot (110)](https://github.com/TusharKesarwani/Front-End-Projects/assets/121859445/e5980342-1e55-4fcc-862a-2142269b373c)

**Comment by ak-sh-at** [comment]
@TusharKesarwani @zugzwang03 @harshit-paneri Please assign this issue to me under SSOC 2.0

**Comment by SubiditaB** [comment]
Please assign this issue to me @ak-sh-at 
I want to contribute to this please.
