### ISSUE TITLE
New Project: 

### ISSUE THREAD

**Issue by ritik48** [TusharKesarwani/Front-End-Projects#1599]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by TusharKesarwani** [comment]
Create a new issue with proper description and screenshot
