### ISSUE TITLE
New Project: Wordle Game

### ISSUE THREAD

**Issue by ritik48** [TusharKesarwani/Front-End-Projects#1600]
### Wordle game
Here user will be displayed blank boxes, and will have to guess the word.
With each guesses the user will be given a hint like:

- if the letter in the guess exists in the original word but is at wrong position, then it's color will change to yellow.
- if the letter in the guess exists in the original word and is at a right position, then it's color will change to green.

### Features:
- flexibility in selecting word length
- easy, medium and tough category options
- there will be fixed number of guesses. and based on in how many guess user figured out the word, score will be given.
- 
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Abhilasha-Sagar** [comment]
@ritik48 Please assign this to me. I want to work on this project.

**Comment by TusharKesarwani** [comment]
Game projects are not accepted
