### ISSUE TITLE
issue in readme files

### ISSUE THREAD

**Issue by khushi767** [TusharKesarwani/Front-End-Projects#1607]
there are some spelling mistakes in readme file.
https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/3D%20Login%20Page

@TusharKesarwani please assign me this

**Comment by SubiditaB** [comment]
@TusharKesarwani I can edit and work on this issue. please assign me this.

**Comment by Jatingupta9120** [comment]
plz assign this issue to me  I will correct it in 10 min

**Comment by harshsinghcs** [comment]
I request to @TusharKesarwani sir kindly assign me this issue

**Comment by TusharKesarwani** [comment]
Create a new issue with proper description and screenshot
