### ISSUE TITLE
Age Calculator Image Missing

### ISSUE THREAD

**Issue by Prachurya-Ray** [TusharKesarwani/Front-End-Projects#1612]
**Describe the bug**
Image of the 'Age Calculator' not added in Image Folder.

**To Reproduce**
1. Go to 'img'
2. Click on 'projects'
3. See no image for Age Calculator

<img width="960" alt="Screenshot 2023-07-06 125324" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/70370699/c57e71ad-79f8-4003-9886-e73b4c55b38b">

**Comment by 07-Atharv** [comment]
I will take up these

**Comment by harshsinghcs** [comment]
@TusharKesarwani @Prachurya-Ray 
Kindly assign me this under SSOC'2.0

**Comment by mayurd8862** [comment]
@TusharKesarwani sir please assign me this issue
