### ISSUE TITLE
[SSoC 2.0] Distance conversion project

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [TusharKesarwani/Front-End-Projects#1613]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
- This project can convert one unit of length to other units. 
- Like, cm, mm, miles, foots, km, yards, etc.

## Issue Type:

- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.
- This project will be very helpful for the children to learn the conversion of units of length.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @harshit-paneri @zugzwang03 please assign this project to me

**Comment by Jatingupta9120** [comment]
plz assign this issue to me

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
