### ISSUE TITLE
[New Project] Guess The Number 

### ISSUE THREAD

**Issue by JadavShraddha** [TusharKesarwani/Front-End-Projects#1614]
## **Describe the project**
A number guessing game is a simple guessing game where a user is supposed to guess a number between 0 and 100 in a maximum of 10 attempts.
The game will end after 10 attempts and if the player failed to guess the number, and then he loses the game

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/95160083/14a7707b-b46e-4f9c-8c01-a7ba17f4f388)

**Comment by Jatingupta9120** [comment]
kindly this issue assign to me I m a begginer this is will be my first contribution

**Comment by abhinavchy875** [comment]
Kindly assign me this issue @JadavShraddha  as i am beginner i want to work on this project
Bug report : Game is not ending after 10 attempt  in a winning cause and a new game should 
start after winning 

 
![quine](https://github.com/TusharKesarwani/Front-End-Projects/assets/102803786/da01d116-b982-475a-a880-b35084664fd4)

**Comment by TusharKesarwani** [comment]
Game projects are not accepted
