### ISSUE TITLE
[New Project][Gradient Background Generator]

### ISSUE THREAD

**Issue by JadavShraddha** [TusharKesarwani/Front-End-Projects#1616]
## **Describe the project**
In this project we can generate background color.
Here we can generate background color by two ways first we can generate customize background and second way by random generator.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/95160083/03a8220c-eed0-4a45-a929-57b26ac8b6f5)

**Comment by JadavShraddha** [comment]
@TusharKesarwani please assign me this issue

**Comment by ghsharma** [comment]
@TusharKesarwani please assign me this issue under SSOC 2.0

**Comment by mayurd8862** [comment]
@TusharKesarwani please assign me this issue as this will be my first project for open source

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
