### ISSUE TITLE
Shopping List

### ISSUE THREAD

**Issue by pavitrachavda97** [TusharKesarwani/Front-End-Projects#1621]
## **Describe the project**
The shopping list project allows users to create, manage, and update a list of items they need to purchase. It provides functionality for adding items and removing them from the list. Users can also view and modify the list as needed.

## Issue Type:
- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Tech Stack: 
- HTML
- CSS
- JavaScript

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/91004608/833a241b-fbd4-4d55-b594-55e04e7af3d8)

**Comment by ratuladhikary21** [comment]
please assign me this issue under ssoc 2

**Comment by ghsharma** [comment]
please assign me this issue under the SSOC 2.0

**Comment by Jaskaran2609** [comment]
can you please assign me this issue under the SSOC 2.0

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
