### ISSUE TITLE
Add a Word Count App

### ISSUE THREAD

**Issue by Ayush9951** [TusharKesarwani/Front-End-Projects#1628]
Hi @TusharKesarwani, @zugzwang03 , I am a contributor in SSOC'23.
I want to add a new project in repo, It's a word counter app.
please assign me this task under label ssoc'23

**Comment by TusharKesarwani** [comment]
The project is already present in the repo

**Comment by Ayush9951** [comment]
Yes, but project is built from scratch with a different Javascript logic, you should consider adding the project, as a same problem can have multiple solutions.
