### ISSUE TITLE
[SSoC 2.0] Math Puzzle website for children

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [TusharKesarwani/Front-End-Projects#1634]
## **Describe the project**
Title - Math Practice
Tech using - HTML, CSS and JS

- Options for addition, subtraction, multiplication, division, percentage, etc. calculations for practising.
- Questions will comes accordingly as selections.
- Creating a sound on each correct answer and wrong answer so to attract children more and more.
- Responsive for the small devices too.

## Issue Type:

- [x] New Project

## **Additional context**
- Very helpful for the children

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @harshit-paneri @zugzwang03 sir, please assign this project to me

**Comment by TusharKesarwani** [comment]
Game projects are not accepted
