### ISSUE TITLE
[SSoC 2.0] Clone of Amazon Prime Website

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [TusharKesarwani/Front-End-Projects#1635]
## **Describe the project**
Title - Clone of Amazon Prime Website
Tech using - HTML and CSS

- Clone of amazon prime website with same hover, cards, images, etc. effects.
- Design using CSS only
- Attractiver user interface with best experience.
- responsive towards the mobile devices.

## Issue Type:

- [x] New Project

## **Additional context**
https://www.primevideo.com/offers/nonprimehomepage/ref=dv_web_force_root

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @harshit-paneri @zugzwang03 sir, please assign this project to me

**Comment by chandug25** [comment]
Hey @zugzwang03@harshit-paneri @TusharKesarwani could you please assign this isssue
