### ISSUE TITLE
Speech-to-text

### ISSUE THREAD

**Issue by pavitrachavda97** [TusharKesarwani/Front-End-Projects#1639]
## **Describe the project**
Speech-to-text is a technology that converts audio input into written text.
Tech Stack: ReactJS.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Expected behavior:
When user will start speaking it will capture audio and then print output after listening.

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/91004608/c4977210-167d-4f78-a63e-fa9bfb3b020d)

**Comment by Jaishree2310** [comment]
@pavitrachavda97 can you please assign this to me under ssoc?

**Comment by real-varshney** [comment]
i want to complete this task, pls assign this to me.

**Comment by Shubham0850** [comment]
If anyone hasn't started yet, I can take the lead; but if you've already begun, please let me know. Thanks! 😃

**Comment by real-varshney** [comment]
I haven't started yet, but i have tried same thing for my own site, I was
never able to complete it, but i have pretty good idea where to start from.

Thank you

**Comment by Jaishree2310** [comment]
Can we start without assigning?
because I'm waiting for assigning

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
