### ISSUE TITLE
Theme Switcher

### ISSUE THREAD

**Issue by ak-sh-at** [TusharKesarwani/Front-End-Projects#1648]
**Describe the bug**

In the project Theme Switcher (https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Theme%20Switcher) the theme switcher and the paragraph container are overlapping with each other on small screens.

**Expected behavior**

There should be a gap between theme switcher and paragraph container.

**Screenshots**

![Screenshot (130)](https://github.com/TusharKesarwani/Front-End-Projects/assets/121859445/66479dca-2af1-4177-bbfa-557f49ce946c)

**Comment by ak-sh-at** [comment]
@TusharKesarwani @zugzwang03 @harshit-paneri Please assign this issue to me under SSOC 2.0

**Comment by sruthi-j603** [comment]
please assign this isse to me under SSOC 2.0
