### ISSUE TITLE
Add TinDog project

### ISSUE THREAD

**Issue by blindaks** [TusharKesarwani/Front-End-Projects#1652]
## **Describe the project**
It is a website like 'Tinder', except it is for dogs.

## Issue Type:
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

![Screenshot (18)](https://github.com/TusharKesarwani/Front-End-Projects/assets/128223364/47b6bef0-d685-4787-8b9c-2952c1a0cf14)
![Screenshot (19)](https://github.com/TusharKesarwani/Front-End-Projects/assets/128223364/a00b458c-8a6f-4bfd-b37c-68b646eb516c)
![Screenshot (20)](https://github.com/TusharKesarwani/Front-End-Projects/assets/128223364/831e4ffd-70f3-4564-9e36-2d2643a5ce06)
![Screenshot (21)](https://github.com/TusharKesarwani/Front-End-Projects/assets/128223364/475fc361-d50d-4301-aed6-f96cfbc92ab3)

**Comment by chandug25** [comment]
Can you please assign to me , i wil do it @blindaks

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
