### ISSUE TITLE
Add Temperature Converter

### ISSUE THREAD

**Issue by blindaks** [TusharKesarwani/Front-End-Projects#1653]
## **Describe the project**
- This project uses front-end web technologies: HTML, CSS, and JavaScript.
- It converts temperatures to and from Celsius, Fahrenheit, and Kelvin. 

## Issue Type:
- New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot (24)](https://github.com/TusharKesarwani/Front-End-Projects/assets/128223364/99b9ddf0-97e0-494d-8947-7536d8bdbd6b)
![Screenshot (25)](https://github.com/TusharKesarwani/Front-End-Projects/assets/128223364/c5557ed5-e812-4fbc-9654-d178b5ced948)

PLEASE assign this issue to me!

**Comment by harshsinghcs** [comment]
please assign this issue to me, sir @blindaks

**Comment by blindaks** [comment]
@TusharKesarwani @harshit-paneri @zugzwang03 Please assign this issue to me.

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
