### ISSUE TITLE
Background-Generator

### ISSUE THREAD

**Issue by Keyuri-19** [TusharKesarwani/Front-End-Projects#1656]
## **Describe the project**
It is the webpage which will be able to generate the background of your choice colours. It is made with the help of HTML, CSS and JavaScript. Also you can generate the random background.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/115471178/f2094688-65e1-4221-b911-2868d29ba727)

**Comment by Keyuri-19** [comment]
@TusharKesarwani @harshit-paneri @zugzwang03 Please assign these issue to me.

**Comment by faraz3728** [comment]
<!DOCTYPE html>
<html>
<head>
  <title>Random Gradient Background</title>
  <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
  <div class="container">
    <h1>Random Gradient Background</h1>
    <form id="colorForm">
      <label for="color1">Color 1:</label>
      <input type="color" id="color1" name="color1" required>
      <br>
      <label for="color2">Color 2:</label>
      <input type="color" id="color2" name="color2" required>
      <br>
      <button type="submit">Generate Gradient</button>
    </form>
  </div>
  
  <script src="script.js"></script>
</body>
</html>

body {
  font-family: Arial, sans-serif;
  text-align: center;
}

.container {
  margin-top: 100px;
}

h1 {
  margin-bottom: 20px;
}

form {
  display: inline-block;
}

button {
  margin-top: 10px;
}
const colorForm = document.getElementById('colorForm');

colorForm.addEventListener('submit', function(event) {
  event.preventDefault();
  
  const color1 = document.getElementById('color1').value;
  const color2 = document.getElementById('color2').value;
  
  generateGradient(color1, color2);
});

function generateGradient(color1, color2) {
  const gradientDirection = Math.random() * 360;
  const gradient = `linear-gradient(${gradientDirection}deg, ${color1}, ${color2})`;
  
  document.body.style.background = gradient;
}
