### ISSUE TITLE
Weight_converter

### ISSUE THREAD

**Issue by ak-sh-at** [TusharKesarwani/Front-End-Projects#1657]
**Describe the bug**

In the project Weight_converter (https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Weight_converter) 
when the input is a negative number then also it is converting it into other units.

**Expected behavior**

When a negative number is given as input a message should be displayed "Enter a positive number".

**Screenshots**

![Screenshot (132)](https://github.com/TusharKesarwani/Front-End-Projects/assets/121859445/ca959ec1-f065-40b9-a978-afc63b7f83de)

**Comment by ak-sh-at** [comment]
@TusharKesarwani @zugzwang03 @harshit-paneri Please assign this issue to me under SSOC 2.0

**Comment by zugzwang03** [comment]
#460
