### ISSUE TITLE
Random Background Color Generator/Flipper

### ISSUE THREAD

**Issue by bhagirath-bhp** [TusharKesarwani/Front-End-Projects#1667]
## **Describe the project**
A random Background generator that generates a random background color on every click and also shows the hex code of the generated background color

## Issue Type:

- [ ] Bug Report
- [x ] Feature Request
- [x ] Documentation
- [x ] New Project

## **Screenshots**
![Screenshot (130)](https://github.com/TusharKesarwani/Front-End-Projects/assets/112346654/5f79963b-9c75-431b-b572-09cc5a146d93)

**Comment by bhagirath-bhp** [comment]
Please assign this issue to me

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
