### ISSUE TITLE
bill tip calculator

### ISSUE THREAD

**Issue by ak-sh-at** [TusharKesarwani/Front-End-Projects#1669]
**Describe the bug**

In the project Bill tip calculator( https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/bill%20tip%20calculator) results are calculated for negative bill amount also.

**Expected behavior**

Negative bill amount should not be accepted as input and if input is negative then an alert should be displayed "Please enter positive bill amount"

**Screenshots**

![Screenshot (136)](https://github.com/TusharKesarwani/Front-End-Projects/assets/121859445/9bd49624-b43f-40ef-845b-13b8f3b0532d)

**Comment by ak-sh-at** [comment]
@TusharKesarwani @zugzwang03 @harshit-paneri Please assign this issue to me under SSOC 2.0

**Comment by sruthi-j603** [comment]
Kindly assign this issue to me under SSOC 2.0
