### ISSUE TITLE
Temperature converter

### ISSUE THREAD

**Issue by ak-sh-at** [TusharKesarwani/Front-End-Projects#1670]
**Describe the bug**

In the project Temperature converter (https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Temperatureconverter) input below lowest possible temperature in all scales is accepted.

**Expected behavior**

Temperature input below lowest possible temperature should not be accepted with a proper message being displayed as alert.
Lowest possible temperature :
Celsius : −273.15 °C
Fahrenheit : −459.67 °F
Kelvin : 0 K
Rankine : 0 R

**Screenshots**

![Screenshot (137)](https://github.com/TusharKesarwani/Front-End-Projects/assets/121859445/8f877119-648d-44f2-95d4-7d1eade56d41)

**Comment by ak-sh-at** [comment]
@TusharKesarwani @zugzwang03 @harshit-paneri Please assign this issue to me under SSOC 2.0

**Comment by ghsharma** [comment]
please assign me this issue
