### ISSUE TITLE
Styling for the password generator

### ISSUE THREAD

**Issue by chandug25** [TusharKesarwani/Front-End-Projects#1688]
Sure, I can help you write the issue in the requested format. Based on the format provided, here's an example of how you could write the issue for the password generator:

**Is your feature request related to a problem? Please describe.**
The problem with the password generator is that it lacks proper styling, making it less user-friendly and visually unappealing.

**Describe the solution you'd like**
I would like to improve the styling of the password generator to enhance the user experience and make it visually appealing. This could include adding appropriate colors, fonts, and layout adjustments to create a more professional and modern look.

**Describe alternatives you've considered**
One alternative solution would be to use a pre-built CSS framework, such as Bootstrap or Tailwind CSS, to quickly style the password generator. This would save time and ensure a consistent design across the project.

**Additional context**
Screenshot: 
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/93117365/176d64c4-f1a1-440f-aafe-c3f255853f95)

By addressing the styling issue, we can enhance the overall user experience and improve the project's aesthetics.

**Comment by chandug25** [comment]
@TusharKesarwani  @zugzwang03  @harshit-paneri 
Kindly assign me this under SSOC 2.0

**Comment by harshsinghcs** [comment]
Kindly assign this issue to me @TusharKesarwani  it is my humble request to you please assign this issue to me to make my 1st contribution.
