### ISSUE TITLE
Styling the Temperature Converter

### ISSUE THREAD

**Issue by chandug25** [TusharKesarwani/Front-End-Projects#1690]
Certainly! Here's an example of how you can write the issue for the temperature converter project, focusing on improving its styling:

**Is your feature request related to a problem? Please describe.**
The problem with the temperature converter project is that it has poor styling, making it visually unappealing and difficult to use.

**Describe the solution you'd like**
I would like to revamp the styling of the temperature converter to create a more visually appealing and user-friendly interface. The desired changes include:

1. Background: Update the background with a modern and visually pleasing design, possibly using a gradient or a relevant image.

2. Fonts and Typography: Apply appropriate typography to enhance readability. Consider using a combination of fonts for headings, content, and buttons to create a visually appealing hierarchy.

3. Colors: Choose a well-coordinated color scheme that improves visibility and creates a pleasant aesthetic. Use colors that are consistent with the purpose of the application, such as cool or warm tones associated with temperature.

4. Layout: Optimize the layout to ensure a clean and organized display of elements. Consider the placement of input fields, labels, and conversion results to improve usability and intuitive interaction.

**Describe alternatives you've considered**
One alternative solution would be to utilize a CSS framework, such as Bulma or Material-UI, to streamline the styling process and achieve a modern and professional look for the temperature converter. These frameworks offer pre-defined components and styles that can be easily customized to suit the project's needs.

**Additional context**
Screenshot:
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/93117365/7ab90b3e-2551-460f-a176-06eacf123c0c)

By improving the styling of the temperature converter, we can create a more engaging and visually appealing user experience, ultimately enhancing the overall quality of the project.

**Comment by chandug25** [comment]
@TusharKesarwani  @zugzwang03    @harshit-paneri 
Kindly assign me this under SSOC 2.0

**Comment by Dhanush-prabhu06** [comment]
Kindly assign this issue to me under SSOC2.0.

Background color : blue with shade effect.
First 2 boxes will be aligned in top row and and next 2 boxes in the 2nd row as it is now with proper re-sizing of the boxes and appropriate space between the boxes.
I would also add a different color contrast for the input section box and the other 3 converted sections will remain in the default color.
