### ISSUE TITLE
Password Checker

### ISSUE THREAD

**Issue by Devchawla2608** [TusharKesarwani/Front-End-Projects#1692]
## **Describe the project**
Password Checker checks , How secure is your password?

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [✅] New Project

## **Additional context**
Password Checker checks whether password is strong enough or not

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/92145696/45086e3c-5a64-4e01-9c7f-aa2e38ceb5fb)

**Comment by debdutta04** [comment]
please assign me this under ssoc

**Comment by Devchawla2608** [comment]
please assign me this under ssoc

**Comment by Devchawla2608** [comment]
@TusharKesarwani  please assign this issue to me

**Comment by harshsinghcs** [comment]
please assign me this under ssoc @TusharKesarwani

**Comment by Devchawla2608** [comment]
@TusharKesarwani  please assign this issue to me

**Comment by Devchawla2608** [comment]
@zugzwang03 please assign this issue to me
