### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Abhilasha-Sagar** [TusharKesarwani/Front-End-Projects#1695]
## **Describe the project**
To-Do List that helps to add and delete items and save in local storage to retrieve the data. Easy and beginner friendly project using HTML,CSS and JavaScript.

## Issue Type:

- [X] New Project

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/92221327/327d80f0-bba5-498e-a8a1-5357e454460f)

**Comment by debdutta04** [comment]
please assign me this issue

**Comment by jks1111** [comment]
@TusharKesarwani @zugzwang03 please assign me this issue under ssoc
