### ISSUE TITLE
Wants to add a  news-letter sinig-in page

### ISSUE THREAD

**Issue by MohdSaquib114** [TusharKesarwani/Front-End-Projects#1696]
## **Project Description**
Your users should be able to:

- Add their email and submit the form
- See a success message with their email after successfully submitting the form
- See form validation messages if:
  - The field is left empty
  - The email address is not formatted correctly
- View the optimal layout for the interface depending on their device's screen size
- See hover and focus states for all interactive elements on the page

![desktop-design](https://github.com/TusharKesarwani/Front-End-Projects/assets/107548091/61cced9b-a2d0-4107-8cd2-de171f3c5bf9)
![desktop-success](https://github.com/TusharKesarwani/Front-End-Projects/assets/107548091/fd3e0bb9-3d44-4d98-853e-0198a644a308)
![mobile-design](https://github.com/TusharKesarwani/Front-End-Projects/assets/107548091/28b62560-60a9-4613-bb12-e8ff04041da7)
![mobile-success](https://github.com/TusharKesarwani/Front-End-Projects/assets/107548091/7105b4a7-7003-4d0c-b14c-7abfaf6b9c68)

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by MohdSaquib114** [comment]
@TusharKesarwani  please assign me this

**Comment by kritikashrmaa** [comment]
heyy please assign this issue to me

**Comment by MohdSaquib114** [comment]
@kritikashrmaa no one is responding to this issue

**Comment by MohdSaquib114** [comment]
@TusharKesarwani  thanks for assigning me this issue.
