### ISSUE TITLE
Please assign me a project

### ISSUE THREAD

**Issue by Anarv2104** [TusharKesarwani/Front-End-Projects#1704]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by amansgith** [comment]
brother this is not the way to get assigned to an issue
you have to either 
1. create a new issue mentioning proper details of your new ideas or projects you want to add or 
2. you can find any bugs in the existing ones and then provide a proper desciption of it in the new issue you create and ask to get assigned
3. also you can ask to get assigned to any issue which is currently unassigned by asking the conversation

try seeing the issues created by other people or watch on youtube to "how to get assigned to an issue or create a new issue"
hope that helps
