### ISSUE TITLE
Instagram Clone[SSOC'23]

### ISSUE THREAD

**Issue by apu52** [TusharKesarwani/Front-End-Projects#1716]
## **Describe the project**
Hello Sir/Ma'am👨‍💻 ,I am Arpan Chowdhury, a aspiring Web developer.🤖 Here is the project of the front-end Web Development. We all use the most famous social media platform INSTAGRAM. So, here is the frontend clone of the landing page👆🏻 .
## Issue Type:

- [] Bug Report
- [] Feature Request
- [] Documentation
- [X] New Project

## **Additional context**
It is made using HTML , CSS & JS.

## **Screenshots**

![Screenshot 2023-06-17 191450](https://github.com/apu52/InstaClone/assets/114172928/d2b4ba78-1442-436d-8f61-1b7d12bb132c)

Please assign me the issue under **SSOC 2.0**

**Comment by apu52** [comment]
@TusharKesarwani @siddhi-244 @Arun9739 Please assign me the issue under SSOC 2.0

**Comment by Bharatpathak08** [comment]
@TusharKesarwani could you plz assign me this

**Comment by Vaishnavikathar18** [comment]
Can u please assign me this issue

**Comment by apu52** [comment]
@TusharKesarwani @siddhi-244 @Arun9739 Please assign me this issue

**Comment by TusharKesarwani** [comment]
Already present in the repo
