### ISSUE TITLE
Temperature Converter Website[SSSOC'23]

### ISSUE THREAD

**Issue by apu52** [TusharKesarwani/Front-End-Projects#1717]
## **Describe the project**
Hello Sir/Ma'am👨‍💻 ,I am Arpan Chowdhury, a aspiring Web developer.🤖 Here is the project of the front-end Web Development. All of us use many websites or other platforms to check the conversion between Celsius-Fahrenheit-Kelvin-Rankine. Why waste your time in so much searching🔎?Just use this website to check the results within seconds.
## Issue Type:

- [] Bug Report
- [] Feature Request
- []Documentation
- [X] New Project

## **Additional context**
It is made using HTML,CSS & JS.

## **Screenshots**

https://github.com/apu52/Temperature_Converter/assets/114172928/266bcd52-a059-4875-89f4-50bbac58aed9

please assign me the issue under **SSOC 2.0**

**Comment by apu52** [comment]
@TusharKesarwani @siddhi-244 @Arun9739 Please assign me the issue under SSOC 2.0

**Comment by blindaks** [comment]
@apu52 already done by me!

**Comment by apu52** [comment]
Ok...@blindaks cam you pls give me the repo link

**Comment by TusharKesarwani** [comment]
Already present in the repo
