### ISSUE TITLE
Portfolio [SSOC'23]

### ISSUE THREAD

**Issue by its-akshay** [TusharKesarwani/Front-End-Projects#1723]
## **Describe the project**
Made the landing page of a Portfolio Website currently used placeholder but one can change according to them.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X ] New Project

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/71098450/b6a7ea27-f606-48cc-aca6-3da297e3ff2f)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/71098450/578fb708-98de-4f61-b103-8d343671baf6)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/71098450/e91b9ab7-d3bf-486a-8063-44ac7d215056)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/71098450/f88fb9ff-9f09-4eb4-835b-00e0dcf2bf59)

**Comment by its-akshay** [comment]
Please assign me the issue under SSOC 2.0.

**Comment by rishav2404** [comment]
Assign this to me.

**Comment by raj-ravan** [comment]
Please assign me the issue

**Comment by TusharKesarwani** [comment]
Already present in the repo
