### ISSUE TITLE
[SSoC 2.0] Instagram Logo Clone

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [TusharKesarwani/Front-End-Projects#1730]
## **Describe the project**
Title - Clone of Instagram Logo
Tech using - HTML and CSS only

## Issue Type:

- [x] New Project

## **Additional context**
- Also adding neon light effect with hovering effect.

**Comment by Avdhesh-Varshney** [comment]
@harshit-paneri @TusharKesarwani @zugzwang03 sir, please assign this project to me

**Comment by sujalshah-bit** [comment]
Can I contribute in this project @Avdhesh-Varshney @sangdeepganvir @Abhishantpadam @Sonu64
