### ISSUE TITLE
Movie app

### ISSUE THREAD

**Issue by marshadkhn** [TusharKesarwani/Front-End-Projects#1733]
## **Describe the project**
**I would like to add a front-end project in this repo name as _usePopcorn_. It's a app that display you all the movies on the internet and add in to watch list**

**_The web app contain following features_**
- You can rate movie according to you
- All the movies are available in this app
- You can remove the movies from list
- Maximize and minimize the both page

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/80325579/91c84fda-ff00-44c5-884d-cedf17ce5cdd)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/80325579/49f9eeec-88f1-4640-ac52-f7eeaed5096f)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/80325579/2b940add-b42f-48f6-bc80-16888029823c)

**Comment by sujalshah-bit** [comment]
i want to contribute  in this project  but i am newbie in open source but i know about development. So how can i contribute in this project.

**Comment by marshadkhn** [comment]
@TusharKesarwani 
Please assign me this issue
