### ISSUE TITLE
Adding padding and make the change in font style and some more feature.

### ISSUE THREAD

**Issue by Manishkr1007** [TusharKesarwani/Front-End-Projects#1738]
**Describe the bug**
I think it is more intractive by changing some internal css and by adding more css .

**Comment by YASHASVASISHTA** [comment]
hey can you please assign this issue for me

**Comment by Akash2866** [comment]
Hii can you assign this issue to me for SSOC 2.0. I would love to modify this and make my first contribution in SSOC 2.0
