### ISSUE TITLE
Instagram Login Page Clone [New Project]

### ISSUE THREAD

**Issue by gauravsingh1281** [TusharKesarwani/Front-End-Projects#1744]
## **Describe the project**
I wanted to create an Instagram login page clone using HTML, CSS, and JavaScript under SSOC 2.0.

## Issue Type:

-  New Project

## **Screenshots**

https://github.com/TusharKesarwani/Front-End-Projects/assets/85905403/a6d5a935-7d55-4916-9fec-44f40dfaa643

**Comment by gauravsingh1281** [comment]
@TusharKesarwani @zugzwang03 Please assign this issue to me I want to work on it.

**Comment by YASHASVASISHTA** [comment]
hey can you assign thus to me ?
