### ISSUE TITLE
Wants to add weather app

### ISSUE THREAD

**Issue by Adityamishra9719** [TusharKesarwani/Front-End-Projects#1748]
### Project title
WEATHER WEB APP

### Project Description
This weather web app is made using HTML , CSS , and JAVASCRIPT
It include a search button you can search any city for weather check .
It include a random Background change as per city name .

## **Screenshots**
![Screenshot 2023-07-15 175304](https://github.com/TusharKesarwani/Front-End-Projects/assets/105539123/a968609e-95ff-4613-b154-37b8a68d620e)

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

Please assign this to me .

**Comment by devagya-rattan** [comment]
please assign me this issue i have worked recently on a weather app

**Comment by faizi-7** [comment]
Please assign it to me

**Comment by TusharKesarwani** [comment]
Already present in the repo
