### ISSUE TITLE
Adding the Alert Message in AirQualityProjects

### ISSUE THREAD

**Issue by 2020B1531074** [TusharKesarwani/Front-End-Projects#1749]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 2020B1531074** [comment]
when we touch on a search button without filling the details enter latitude here in AirQuality projects then its shows the alert message
![Screenshot (174)](https://github.com/TusharKesarwani/Front-End-Projects/assets/98419710/3233e693-bd15-4531-832a-066dfb481eb1)

**Comment by 2020B1531074** [comment]
i already done this.Please assigned me this

**Comment by Madhav-2808** [comment]
I can solve this issue
