### ISSUE TITLE
Alarm Setter Website

### ISSUE THREAD

**Issue by dhruti26** [TusharKesarwani/Front-End-Projects#1758]
## **Description**
Alarm setter is used to set Alarm with sound effects , build using HTML,CSS and Javascript

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

Please assign me this issue under SSOC'23

**Comment by dhruti26** [comment]
@TusharKesarwani @zugzwang03 Please assign me this issue under SSOC'23

**Comment by anubhav1206** [comment]
Can I work on this?
