### ISSUE TITLE
Adding Scroll to top Button in the Educational Website

### ISSUE THREAD

**Issue by Keyuri-19** [TusharKesarwani/Front-End-Projects#1762]
**Is your feature request related to a problem? Please describe.**
User have scrolled down and suddenly want to scroll up then will take much time.

**Describe the solution you'd like**
Want to add Scroll to Top button so that it will be very convenient for the user.

**Describe alternatives you've considered**

**Additional context**

**Comment by Keyuri-19** [comment]
@TusharKesarwani @harshit-paneri @zugzwang03 Please assign these issue to me.

**Comment by shivm29** [comment]
hey I want to work on this issue! Can i contribute?

**Comment by Pavithra-ks-06** [comment]
Hey ! I would like to contribute and work on this issue pls assign it to me
