### ISSUE TITLE
In this chess game the pawns can only move one slot in their fisrt turn. They should be able to move 2 slots. 

### ISSUE THREAD

**Issue by kakashi2020** [TusharKesarwani/Front-End-Projects#1766]
Modify so each pawn can move either 1 or 2 slots on their first turn instead of just 1. 

(This is my first time trying to contribute to the community, so this is more of a personal test to understand how to work with open-source projects. But please feel free to give me feedback :) )

![screenshot](https://github.com/TusharKesarwani/Front-End-Projects/assets/62034089/53f1be48-ddc7-4fa4-badc-e5db8857e7c5)

**Comment by i-m-karanagarwal** [comment]
I would like to work on this please assign it to me.

**Comment by VIVEKANAND-SINHA** [comment]
Hi, there I am new to open source and wanted to learn I would like to work on this project kindly assign it to me and provide me some guidance to work on it.
thanks

**Comment by TusharKesarwani** [comment]
Not required
