### ISSUE TITLE
Redesign a front-end food ordering website

### ISSUE THREAD

**Issue by ARCHITABHATTAD** [TusharKesarwani/Front-End-Projects#177]
Wanted to add some new files and make the site responsive.
https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Food%20Ordering%20website

Changes :
1. Improving the UI
2. Adding a JS file for better functionality
3. Adding a readme.md file

**Comment by Vanshiii203** [comment]
@ARCHITABHATTAD Go ahead!

**Comment by ARCHITABHATTAD** [comment]
@Vanshiii203 I had my exams due to which I could not make any contributions....asking you to reconsider

**Comment by Vanshiii203** [comment]
@ARCHITABHATTAD assigned to you

**Comment by SohamRoy-01** [comment]
## Hi @Vanshiii203 and @TusharKesarwani 
### - I have a done a project of Food ordering website if no one is doing it I can upload then..
###     Thank You

**Comment by TusharKesarwani** [comment]
> ## Hi @Vanshiii203 and @TusharKesarwani 
> ### - I have a done a project of Food ordering website if no one is doing it I can upload then..
> ###     Thank You

Share the screenshot

**Comment by SohamRoy-01** [comment]
> > ## Hi @Vanshiii203 and @TusharKesarwani
> > ### - I have a done a project of Food ordering website if no one is doing it I can upload then..
> > ### Thank You
> 
> Share the screenshot

https://github.com/SohamRoy-01/Food-Ordering-Website
