### ISSUE TITLE
Feat: add pre-loader animation 

### ISSUE THREAD

**Issue by harmeetsingh11** [TusharKesarwani/Front-End-Projects#1782]
**Is your feature request related to a problem? Please describe.**
Currently, there is no pre-loader animation, when the site is loaded. We need to improve it

**Describe the solution you'd like**
I would like to add loading animation. Loading animations are notifications that reassure users that the system is still handling their request. 

**Record** 
- [x] I agree to follow this project's Code of Conduct 
- [x] I'm a SSOC 2.0 contributor
- [x] I want to work on this issue

**Comment by Ashish1100** [comment]
The following is a rough sketch of how you can accomplish this using HTML, CSS, and JavaScript:

1. Create the HTML structure:
Start by creating a simple HTML structure for your pre-loader animation. We can use a <div> element as the container for the loader.

2. CSS the pre-loader container: 
Next, add some CSS to style the pre-loader container. We may center it on the screen and use whatever animation we like.

3. Add the JavaScript to conceal the pre-loader after the page has loaded:
Finally, we must include some JavaScript to hide the pre-loader after the site's content has entirely loaded. You may use either the window.onload or the more recent DOMContentLoaded event.

**Comment by harmeetsingh11** [comment]
@Ashish1100 thanks for the workflow. Please assign me this issue, so that I can start working on it.
