### ISSUE TITLE
[NEW PROJECT]: Essentia - Skin Care Product website

### ISSUE THREAD

**Issue by blindaks** [TusharKesarwani/Front-End-Projects#1788]
## **Describe the project**
A website for skincare products : Essentia

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project
![Screenshot (63)](https://github.com/TusharKesarwani/Front-End-Projects/assets/128223364/fffb3931-7459-4c16-be54-0d7b62e81fb6)
![Screenshot (64)](https://github.com/TusharKesarwani/Front-End-Projects/assets/128223364/9f82d104-bb35-45e2-a196-e250f25f41ae)
![Screenshot (65)](https://github.com/TusharKesarwani/Front-End-Projects/assets/128223364/0d605224-4700-4395-b201-19bf0ca63fda)

**Comment by RazaHussainAziz** [comment]
Can I also work in this project ?

**Comment by raj-ravan** [comment]
Can I also work in this project ?
