### ISSUE TITLE
Air  Quality project

### ISSUE THREAD

**Issue by ParthGharat27** [TusharKesarwani/Front-End-Projects#1809]
Helllo ,
Here in Air Quality project, the output screen does not return the location of given coordinates of latitude & longitude.
So I would like to work on this issue 
Please assign me this issue @TusharKesarwani  
![air](https://github.com/TusharKesarwani/Front-End-Projects/assets/123398580/c0e24ea1-7427-4d29-a873-e5c3aa89775e)

**Comment by ParthGharat27** [comment]
@TusharKesarwani can you assign me this issue

**Comment by ParthGharat27** [comment]
@TusharKesarwani 
I'am getting a error: " remote: Permission to TusharKesarwani/Front-End-Projects.git denied to ParthGharat27. "
can you please grant me permission.

**Comment by TusharKesarwani** [comment]
> @TusharKesarwani I'am getting a error: " remote: Permission to TusharKesarwani/Front-End-Projects.git denied to ParthGharat27. " can you please grant me permission.

Share the screenshot of the error
