### ISSUE TITLE
3D racing car game

### ISSUE THREAD

**Issue by Parul1606** [TusharKesarwani/Front-End-Projects#1818]
## **Describe the project**

I would like to add 3D Car racing game.
The Tech Stack I will use: - 
HTML: The structure of the web page and the canvas element to render the 3D scene.
CSS: Styling the HTML elements, layout, and other visual aspects of the game's user interface.
JavaScript:  The core programming language used to implement the 3D car racing game.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/80768852/4c5b2c9f-11ba-491c-b30e-5997e27ce0c9)

**Comment by TusharKesarwani** [comment]
Game projects are not accepted
