### ISSUE TITLE
Guess the word game

### ISSUE THREAD

**Issue by Abhilasha-Sagar** [TusharKesarwani/Front-End-Projects#1819]
## **Describe the project**
This project helps to create a game in which the user has to guess the word which is randomly picked from a list of words. The user wins if he guesses the words before the total number of guesses provided to the user ends. Otherwise, the game is over and the word is shown.

## Issue Type:

- [x] New Project

## **Additional context**
Beginner-friendly project using HTML, CSS, and JavaScript.

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/92221327/ed760996-c4f9-492c-a0e9-87a8faf100ea)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/92221327/8cfc923c-2458-4a4f-b140-5eee080aa585)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/92221327/6ae0b063-ce97-4535-af3a-aee23d58852e)

**Comment by Abhilasha-Sagar** [comment]
@TusharKesarwani @zugzwang03 Please assign this to me.

**Comment by zugzwang03** [comment]
game projects not allowed.
