### ISSUE TITLE
DRUM KIT

### ISSUE THREAD

**Issue by sumitkr2000** [TusharKesarwani/Front-End-Projects#182]
hey, @TusharKesarwani I want to add a project where a user can produce different types of dum sounds and create music. Please assign me this issue.

**Comment by Vanshiii203** [comment]
@sumitkr2000 The drumkit project is already present in the repo. You can raise some other issues and work on them.

**Comment by sumitkr2000** [comment]
But where is it I cant see any folder! @Vanshiii203

**Comment by Vanshiii203** [comment]
> But where is it I cant see any folder! @Vanshiii203

https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/The%20Great%20Drumkit

**Comment by sumitkr2000** [comment]
ohh it is the greaaaaatttttt drumkit 😂
