### ISSUE TITLE
[SSoC'23] Google Chrome Dinosaur game Clone

### ISSUE THREAD

**Issue by amansgith** [TusharKesarwani/Front-End-Projects#1837]
## **Describe the project**
I would like to add a clone project of the offline game available on google chrome browser known as the dinosaur game with some my own twist

##Tech Stack used:
-HTML
-CSS
-Javascript
-basics of Jquery

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
I will try make the game as similar as possible and playable.. with my some own twists and using the tech stacks above mentioned.
Please assign this issue to me as soon as possible :)

**Comment by amansgith** [comment]
Please assign this issue to me
Thank you :)

**Comment by TusharKesarwani** [comment]
Game projects are not accepted
