### ISSUE TITLE
Animated-wallpaper Project

### ISSUE THREAD

**Issue by harshsinghcs** [TusharKesarwani/Front-End-Projects#1842]
## **Describe the project**
This project is based on HTML, CSS & Java Script like a window wallpaper

resize the button and add some image

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![Screenshot (63)](https://github.com/TusharKesarwani/Front-End-Projects/assets/115187902/cef9a656-7602-4437-a4b0-2fd8db702ca3)

![Screenshot (59)](https://github.com/TusharKesarwani/Front-End-Projects/assets/115187902/519364cf-5112-4b0a-9d81-9d83a4b6cdf5)

**Comment by harshsinghcs** [comment]
please assign this issue to me under SSOC 2023 @TusharKesarwani @zugzwang03

**Comment by zugzwang03** [comment]
Put modifications here, like why keep only "Hello Harsh" in the text, allow user to edit it, only then it becomes useful for all.

**Comment by harshsinghcs** [comment]
ok ma'am

**Comment by zugzwang03** [comment]
great idea

**Comment by harshsinghcs** [comment]
> great idea

thankyou😊

**Comment by harshsinghcs** [comment]
![Screenshot (64)](https://github.com/TusharKesarwani/Front-End-Projects/assets/115187902/c12ba6e5-e354-41c9-8cc1-e914ef4a44ef)

issue is solved🤝
