### ISSUE TITLE
LinkSave

### ISSUE THREAD

**Issue by shivangi2002** [TusharKesarwani/Front-End-Projects#1843]
## **Describe the project**
this is an javascript extension in which we can save all the links we want and can also delete.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem
- 
<img width="960" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/73734324/ddd8cf45-780a-4626-883b-28f7d2ab42b2">

**Comment by Benrobo** [comment]
Please @TusharKesarwani assign this to me.
