### ISSUE TITLE
Blog website project: Add sticky navigation bar, Hamburger menu feature and improve UI of the project

### ISSUE THREAD

**Issue by shreyaa26** [TusharKesarwani/Front-End-Projects#1844]
**Current Situation:**
The current blog website project lacks a sticky navigation bar and a hamburger menu for smaller screens. As users scroll down the page, the navigation bar disappears, making it inconvenient to access the menu quickly. Additionally, the website lacks a responsive hamburger menu for mobile users, resulting in a less-than-optimal experience on smaller devices.

**Proposed Feature**
I propose adding a sticky navigation bar and a hamburger menu to the blog website. The sticky navigation bar should become fixed at the top of the page as users scroll down, ensuring easy access to the menu at all times. On smaller screens, a hamburger menu should replace the standard navigation to improve mobile user experience.

**Expected behavior-**
1.When users scroll down the page, the navigation bar should transition to a sticky position and stay fixed at the top of the viewport.
2.On screens with limited width (e.g., mobile devices), the regular navigation bar should be replaced by a hamburger menu icon.
3.Clicking on the hamburger menu icon should reveal a dropdown menu containing all navigation links.

**Additional context**
Screenshot of sticky navigation bar from my personal project - 
![1](https://github.com/TusharKesarwani/Front-End-Projects/assets/112085658/42d61ca5-2479-4466-9532-529b7910e19a)

Screenshot of Hamburger menu from my personal project -
![2](https://github.com/TusharKesarwani/Front-End-Projects/assets/112085658/e9cbaec1-0d0a-472f-8ef8-217f520fd994)

**Comment by shreyaa26** [comment]
> Can you assign this to me ?

I was waiting it to be assigned to me :(

**Comment by harshitcodes22** [comment]
Okay No problem
