### ISSUE TITLE
TDL 

### ISSUE THREAD

**Issue by Parul1606** [TusharKesarwani/Front-End-Projects#1847]
## **Describe the project**
I would like to add To-do List webapp built using HTML, CSS & JavaScript.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
In this to-do list webapp we can edit or delete our task.

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/80768852/341b3653-d704-42bb-9834-1166dad57128)

**Comment by HimanshuMaurya2300** [comment]
Please assign me this issue

**Comment by HimanshuMaurya2300** [comment]
@TusharKesarwani @Parul1606  Please assign me this issue
