### ISSUE TITLE
Expense Tracker

### ISSUE THREAD

**Issue by Parul1606** [TusharKesarwani/Front-End-Projects#1848]
## **Describe the project**
I would like to add Expense Tracker built using HTML, CSS & JavaScript.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
It automatically calculates the Left balance user has to just add all their transactions. Both the field should be filled by the user (i.e title of the expense and how much he/she has spend or earn as -Ve or +Ve respectively. Bonus is we can also delete the transaction if its not added properly like value or title of it.

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/80768852/ba3df61d-8bce-436e-b4ea-587843407537)

**Comment by HimanshuMaurya2300** [comment]
Please assign me this issue.

**Comment by HimanshuMaurya2300** [comment]
@TusharKesarwani  @Parul1606  Please assign me this issue
