### ISSUE TITLE
Add Color Flipper Project

### ISSUE THREAD

**Issue by Jeevan2305** [TusharKesarwani/Front-End-Projects#1850]
## **Describe the project**
The color flipper project is a simple web application built using HTML, CSS, and JavaScript. Its main functionality is to generate random colors with a click of a button. When the button is clicked, the background color of the webpage changes to a random color, creating a visually appealing and dynamic user experience.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Technologies Used:**
- HTML: For creating the structure of the webpage.
- CSS: For styling the elements and defining the layout.
- JavaScript: For generating random colors and handling the button click event.

## **Project Benefits:**
The color flipper project serves as a fun and educational exercise for beginner web developers to practice HTML, CSS, and JavaScript skills. It introduces concepts like DOM manipulation, event handling, and working with colors. Additionally, it provides an opportunity to explore and experiment with various color combinations, making it a visually engaging project.

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/75674374/c2eea0a1-3167-499b-abb2-734f65cc6d1c)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/75674374/aa5d31cf-af47-4d32-9631-ca7c12e9b7c3)

Please assign me this issue

**Comment by Jeevan2305** [comment]
@TusharKesarwani @zugzwang03 Please assign me this issue

**Comment by HimanshuMaurya2300** [comment]
@TusharKesarwani  @zugzwang03  Please assign me this issue

**Comment by iamabir04** [comment]
@TusharKesarwani @zugzwang03 Assign me this issue

**Comment by SHAIK-MUNEERUDDIN** [comment]
Hello, I would like to work on this. Could you please assign me this issue?
