### ISSUE TITLE
Age Calculator

### ISSUE THREAD

**Issue by suma30** [TusharKesarwani/Front-End-Projects#1854]
**Describe the bug**
The age calculator element is not exactly at the Centre of the page

**Expected behavior**
Element at the Centre of the page for better look

**Screenshots**
![Screenshot (75)](https://github.com/TusharKesarwani/Front-End-Projects/assets/112741893/c112ad92-6ce5-4a4c-9494-6cc7657134cd)

**Additional context**
@TusharKesarwani @zugzwang03 @harshit-paneri Please assign me this issue for age calculator

**Comment by sagargoyal-bit** [comment]
Assign it to me

**Comment by suma30** [comment]
@zugzwang03 Someone mentioned that this issue is already completed, could please check into it and inform me should I close my issue?
