### ISSUE TITLE
Realtime Comment System

### ISSUE THREAD

**Issue by HimanshuMaurya2300** [TusharKesarwani/Front-End-Projects#1859]
## **Describe the project**
A real-time comment system application is an interactive and dynamic platform that enables users to engage in immediate discussions and share their thoughts on various content, such as articles, videos, or social media posts. Unlike traditional comment systems, which require manual page refreshing to see new comments, real-time comment systems offer instant updates without the need for page reloads.
This application leverages technologies like WebSockets or Server-Sent Events (SSE) to establish a continuous connection between the user's browser and the server. As a result, when a user submits a comment, it is instantly displayed to all other users accessing the same content, creating a seamless and engaging conversation flow.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [x] Documentation
- [x] New Project

## **Additional context**
I would like to add this project to the program of SSOC 23
Please assign this issue to me.

## **Screenshots**
![Screenshot 2023-07-27 192200](https://github.com/TusharKesarwani/Front-End-Projects/assets/96130363/e74ff7c4-6f54-4c04-9fa4-aa063fc16577)

**Comment by HimanshuMaurya2300** [comment]
@TusharKesarwani Please assign this issue to me

**Comment by HimanshuMaurya2300** [comment]
please sir assign this issue to me

**Comment by TusharKesarwani** [comment]
Only front-end projects are accepted
