### ISSUE TITLE
Modifying Chess Project

### ISSUE THREAD

**Issue by Akash2866** [TusharKesarwani/Front-End-Projects#1860]
**Is your feature request related to a problem? Please describe.**
In the chess game , I found an issue in pawns' movement. The pawn can only move to 1 position in front at a time.

**Describe the solution you'd like**
So I would like to modify the chess project and solve this issue of pawns' movement in this Chess project.
![chess](https://github.com/TusharKesarwani/Front-End-Projects/assets/91870183/f0d401e0-f602-430e-8f54-424d9c595b93)

**Comment by Akash2866** [comment]
@TusharKesarwani @zugzwang03 @harshit-paneri 
Kindly assign me this issue under SSOC'2.0

**Comment by zugzwang03** [comment]
so you want to change it to?

**Comment by Akash2866** [comment]
Yes the rules for pawn is that it can move either 1 or 2 moves in starting.
