### ISSUE TITLE
Random Quote Generator

### ISSUE THREAD

**Issue by VaibhavArora314** [TusharKesarwani/Front-End-Projects#188]
Hey, I want to add a random quote generator using HTML, CSS, JS, and [AnimeChanAPI](https://github.com/RocktimSaikia/anime-chan) to get quotes. 
Please assign me this issue.

**Comment by Vanshiii203** [comment]
Hey @VaibhavArora314 Someone is already working on this issue; if they fail to complete it, it will be assigned to you. Until then, you can raise some other issues and work on them.

**Comment by VaibhavArora314** [comment]
okay, thanks!
