### ISSUE TITLE
Expense Tracker

### ISSUE THREAD

**Issue by Parul1606** [TusharKesarwani/Front-End-Projects#1880]
## **Describe the project**
I would like to add Expense Tracker built using HTML, CSS & JavaScript.

## Issue Type:

- [x] New Project

## **Additional context**

It automatically calculates the Left balance user has to just add all their transactions. Both the field should be filled by the user (i.e title of the expense and how much he/she has spend or earn as -Ve or +Ve respectively. Bonus is we can also delete the transaction if its not added properly like value or title of it.

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/80768852/f940e4ab-acf8-4ed6-9c7c-89fcd20c5130)

**Comment by TusharKesarwani** [comment]
Already present in the repo
