### ISSUE TITLE
TDL

### ISSUE THREAD

**Issue by Parul1606** [TusharKesarwani/Front-End-Projects#1881]
## **Describe the project**
I would like to add To-do List webapp built using HTML, CSS & JavaScript.

## Issue Type:

- [x] New Project

## **Additional context**

In this to-do list webapp we can edit or delete our task.

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/80768852/e3b5a200-e80e-43c0-aecf-0a31c4a8f072)

**Comment by TusharKesarwani** [comment]
Already present in the repo
