### ISSUE TITLE
UX/UI Improvement for Note app

### ISSUE THREAD

**Issue by Benrobo** [TusharKesarwani/Front-End-Projects#1886]
**Is your feature request related to a problem? Please describe.**
There's alot of improvement that need to be done to note app. The app isn't responsive at all, and still lacks some important features

**Describe the solution you'd like**
I would love to improve the app to a much more better note taking application which would serve as a real product users would be willing to use.

**Additional context**
![Screenshot 2023-07-29 at 14 57 30](https://github.com/TusharKesarwani/Front-End-Projects/assets/65370456/ce19e217-e5d1-46a2-b16e-8a48c4d3bd51)

**Comment by Coderdivine** [comment]
Hey, I want to work on this issue. Can you please assign it to me?

**Comment by Benrobo** [comment]
@TusharKesarwani kindly assign this to me..

**Comment by Benrobo** [comment]
@Coderdivine the issue was created initially so I can work on it.. you might as well look for other related issues to be worked on or try creating one yourself if you feel some applications lacks some features or contains bugs.
