### ISSUE TITLE
React Weather App With 5 Days Forecast

### ISSUE THREAD

**Issue by Adedoyin-Emmanuel** [TusharKesarwani/Front-End-Projects#1887]
## **Describe the project**

# **Introducing ForecastX - The ultimate weather forecasting app**

ForecastX is a free and open-source React-based weather app with modern UI technologies. It allows users to track atmospheric conditions for any country or city, automatically saves and updates weather for favourite locations, and offers a 5-day weather forecast with 3-hour intervals. The app works offline, is built on Progressive Web App (PWA) technology, and supports cross-platform access. Users can customize settings to personalize their experience.

## How does it work?

ForecastX was built on the [openweatherapi](https://openweathermap.org/), you can search cities or countries to get their weather details, or automatically track where you are using the geolocation API to get your current location weather details. This information are cached and stored in the browser localStorage. When the site loads, the images, pages and all are cached using service workers, so you can always access them offline. The app also would automatically forecast the 5 days weather condition pending on your current location or your search term.

## Key Features

1. Can track the atmospheric condition of any country or city.
2. Can automatically track the weather of any saved location.
3. It built customised settings.
4. Works offline.
5. Can predict the weather of any geographical area for the next 5 days and 3-hour intervals.
6. It is free and open source.
7. Built using modern UI technologies.
8. Cross-Platform Application.
9. Built on the PWA technology.

## Why Choose ForecastX ?

Accurate 5-day forecast, automatic location tracking, and offline access. Personalize your experience. Free, open-source, and accessible on all devices. Embrace the weather with confidence!

Try it now: [Awesome Weather App](https://zedd-weather.vercel.app/)

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x]  New Project

## **Technologies used for this project**

  - ReactJS
  - Bootstrap5
  - OpenWeather API

## **Screenshots**

![Screenshot from 2023-07-29 15-04-52](https://github.com/TusharKesarwani/Front-End-Projects/assets/88517758/82dc0c33-0bfa-44c3-b3b4-c01642178692)
![Screenshot from 2023-07-29 15-04-40](https://github.com/TusharKesarwani/Front-End-Projects/assets/88517758/3835ce53-59ca-4196-bbb5-a1b2df0ac0c0)
![Screenshot from 2023-07-29 15-04-27](https://github.com/TusharKesarwani/Front-End-Projects/assets/88517758/0951a4bf-24d2-4574-a8f7-37b5fae81bca)
![Screenshot from 2023-07-29 15-03-14](https://github.com/TusharKesarwani/Front-End-Projects/assets/88517758/7d7c3c9c-df24-4390-8678-a3bc2e11ea89)
![Screenshot from 2023-07-29 15-03-08](https://github.com/TusharKesarwani/Front-End-Projects/assets/88517758/bac3e77d-b1c5-4fd2-afe5-b13dbc94c0e1)

**Comment by TusharKesarwani** [comment]
React projects are not accepted

**Comment by Adedoyin-Emmanuel** [comment]
What about HTML games?  Are they accepted?
