### ISSUE TITLE
A project whose style can be changed according your taste using HTML,CSS and JS

### ISSUE THREAD

**Issue by monishkajha17** [TusharKesarwani/Front-End-Projects#189]

**Comment by monishkajha17** [comment]
In this we would be able to change the font, background, style and colors of the project.

**Comment by Vanshiii203** [comment]
Hey @monishkajha17 please elaborate your idea.

**Comment by monishkajha17** [comment]
Here, we can change the font of the website , or the background, genre, edge style and can switch to the favorite mode. By just entering it

**Comment by harshit-paneri** [comment]
> In this we would be able to change the font, background, style and colors of the project.

ye you can

**Comment by harshit-paneri** [comment]
> Here, we can change the font of the website , or the background, genre, edge style and can switch to the favorite mode. By just entering it

yes you can change this things, but for which project?

**Comment by monishkajha17** [comment]
for any of the website you or the user want?
without writing the codes, by simply entering it

**Comment by harshit-paneri** [comment]
> for any of the website you or the user want? without writing the codes, by simply entering it

You have to choose your project , where you can improve somthings, or create an issue .

**Comment by monishkajha17** [comment]
okay will do it

**Comment by Anubhavgupta14** [comment]
@monishkajha17 Are you SWOC 3.0 Participate?

**Comment by monishkajha17** [comment]
@harshit-paneri I will create a whole new project showcasing how user can change the styles covered in a video

**Comment by harshit-paneri** [comment]
> @harshit-paneri I will create a whole new project showcasing how user can change the styles covered in a video

Great, before start working on it , just raise an issue before it

**Comment by harshit-paneri** [comment]
> > @harshit-paneri I will create a whole new project showcasing how user can change the styles covered in a video
> 
> Great, before start working on it , just raise an issue.

**Comment by monishkajha17** [comment]
So, I should close this issue or raise another one or you can assign this issue to me

**Comment by harshit-paneri** [comment]
Okay you can edit this same one also with correct title

**Comment by monishkajha17** [comment]
@harshit-paneri Pls check

**Comment by harshit-paneri** [comment]
> @harshit-paneri Pls check

Yup 👍

**Comment by monishkajha17** [comment]
@harshit-paneri Can you pls assign me this issue so that I can start working on it

**Comment by harshit-paneri** [comment]
> @harshit-paneri Can you pls assign me this issue so that I can start working on it

already assigned

**Comment by monishkajha17** [comment]
thanks
