### ISSUE TITLE
To-Do-List

### ISSUE THREAD

**Issue by khushigarg1** [TusharKesarwani/Front-End-Projects#191]

**Comment by Vanshiii203** [comment]
Hey @khushigarg1  Someone is already working on this issue; if they fail to complete it, it will be assigned to you. Until then, you can raise some other issues and work on them.

**Comment by khushigarg1** [comment]
> Hey @khushigarg1 Someone is already working on this issue; if they fail to complete it, it will be assigned to you. Until then, you can raise some other issues and work on them.

Okay Sure
