### ISSUE TITLE
Deployed Netlify App is being shown as 'Dangerous'

### ISSUE THREAD

**Issue by zabihshaik** [TusharKesarwani/Front-End-Projects#1921]
**Describe the bug**
When I opened the deployed link from the About Section of GitHub Repo, I couldn't access the website, and it was showing an error. Screenshot attached.

**To Reproduce**
1. Go to 'About Section of the GitHub Repo'
2. Click on 'the deployed link'
3. See error

**Expected behavior**
The original deployed web app/website with secure https link and access to the web app.

**Screenshots**
![Frontend Projects Website Error](https://github.com/TusharKesarwani/Front-End-Projects/assets/91183455/b52ee398-76de-4cc4-b213-7dedc85be307)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 116

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TusharKesarwani** [comment]
Go ahead and fix the issue

**Comment by TusharKesarwani** [comment]
Go ahead and fix the issue @gkm0001
