### ISSUE TITLE
Scientific Calculator

### ISSUE THREAD

**Issue by apu52** [TusharKesarwani/Front-End-Projects#1936]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
Hello sir, 
Here is Scientific Calculator.👨🏻‍💻 I have made it using HTML,CSS & JS. It contains normal arithmetic fuctions(+,-,*,/) as well as cube , square , square root & cube root of a no. as well as trgnometric function & percentege.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**

- Normal Arithmetic functions
- Trignoetric Functions
-  Percentage
-  Square, cube of a number
-  Square root, cube root of a no.
## **Screenshots**
![image](https://github.com/apu52/Scientific-Calculator/assets/114172928/9b3fb0c2-921f-41eb-b4c3-cfaf84d656ff)

**Comment by TusharKesarwani** [comment]
Project is already present in the repo
