### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by pabitra0011** [TusharKesarwani/Front-End-Projects#1939]
## **Describe the project**
A weather app that forcast current day and past 7 day weather.
User can check weather by city name and current location.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

**Comment by ninadvyas** [comment]
hello @TusharKesarwani can i work on this issue???

**Comment by ninadvyas** [comment]
Can you just give me brief about the issue. According to me I need to make weather app that that has the features that you requested in the issue.

**Comment by TusharKesarwani** [comment]
> hey @TusharKesarwani, can you just give me brief about the issue that what I need to do? According to me I need to make weather app that that has the features that you requested in the issue.

Yeah, you're right
Just implement the features

**Comment by ninadvyas** [comment]
Thank you @TusharKesarwani ,I'll start working on it.

**Comment by kakashihatakesh6** [comment]
Hi @TusharKesarwani can i work on this project if its not assigned to anyone yet? i have already build the application on openweather api on nextjs with good ui. []((https://nimbus-hub-weather.netlify.app/)) [](https://github.com/kakashihatakesh6/nimbus-hub-weather)

**Comment by kakashihatakesh6** [comment]
Hi @TusharKesarwani can i work on this project if its not assigned to anyone yet? i have already build the application on openweather api on nextjs with good ui. 
(https://nimbus-hub-weather.netlify.app/)
(https://github.com/kakashihatakesh6/nimbus-hub-weather)
