### ISSUE TITLE
Developer Profile Card using CSS and HTML

### ISSUE THREAD

**Issue by monishkajha17** [TusharKesarwani/Front-End-Projects#194]

**Comment by Rishikavishnoi** [comment]
@monishkajha17  please describe your project idea

**Comment by monishkajha17** [comment]
Here, User will be able to create a responsive business card(for developers that's why developer card) they will enter the basic information like name, their designation and their social media handles link. 
![Screenshot (229)](https://user-images.githubusercontent.com/109274817/211836017-b222a323-a2c3-4576-b759-9d34d66be5a1.png)

**Comment by monishkajha17** [comment]
It is the screenshot how it will look alike

**Comment by monishkajha17** [comment]
@Rishikavishnoi this is the project
