### ISSUE TITLE
Add a website built for gym users. Want to work under swoc'23

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [TusharKesarwani/Front-End-Projects#1945]
## **Project name- AnyTime Fitness Gym**
This website consist of information about the gym, its price list, facilities provides, info about the gym trainers, payment gateway and much more. The website has a interactive interface. Various html, css and javascript elements are used in it.

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/123376847/47cf82fa-c8cf-4392-80c3-5c06cbbc6a2a)
Attached above the screenshot to show the look of the website.

**Comment by TusharKesarwani** [comment]
Another contributor is already working in this project
