### ISSUE TITLE
[BUG]: Navigation Links Not Redirecting to Destination Pages in the Zomato Clone Website

### ISSUE THREAD

**Issue by akhilrocz** [TusharKesarwani/Front-End-Projects#1953]
**Describe the bug**
Navigation links are not responsive, i.e they are not redirecting to destination pages when clicked

**To Reproduce**
1. Go to 'Zomato Landing Page'
2. Click on 'Navigation links.'
3. See the bug.

**Expected behavior**
The navigation links should be responsive.

https://github.com/TusharKesarwani/Front-End-Projects/assets/118684885/3184d5d4-6cbc-44f3-8d6f-3e4264085ae4

**Desktop 
 - OS: [Winows]
 - Browser [chrome]
 - Version  [118.0.5993.118 ]

**Comment by oiabhishekk** [comment]
assign this issue to me

**Comment by notajax24** [comment]
Is this still open? I want to contribute.

**Comment by Ved-panchal** [comment]
You have not created any different pages.
In the index.html you have to add your page path as
"/login" in "a" tag href attribute.

**Comment by tiwarisurbhi14** [comment]
can i fix it please

**Comment by Aaraav** [comment]
Hey, I can fix it.please give assign me this tast
