### ISSUE TITLE
Tic Tac Toe

### ISSUE THREAD

**Issue by aadium** [TusharKesarwani/Front-End-Projects#1964]
## **Describe the project**
I have finished creating a tic-tac-toe game with React.js, and wish to add it here. Please disregard my previous issue which had the same title. In this issue, I have provided a more detailed explanation here..

## Issue Type:
- [ ] New Project

## **Additional context**
The game is created using React.js

## **Screenshots**
![Screenshot 2023-12-14 164643](https://github.com/TusharKesarwani/Front-End-Projects/assets/47914987/ab527bb3-0d69-4663-ac10-b2c81b8f2892)

**Comment by TusharKesarwani** [comment]
React projects are not accepted in this repo
