### ISSUE TITLE
Can't Open the file

### ISSUE THREAD

**Issue by gagan257** [TusharKesarwani/Front-End-Projects#1966]
**Describe the bug**
Not being able to open the file after downloading the pdf format it says "We can't open the file and says something went wrong"

**System**

Chrome version : 121.0.6167.16
Windows version: 11

**Comment by TusharKesarwani** [comment]
Could you please describe the issue

**Comment by gagan257** [comment]
In `PDF Merger` I uploaded 2 PDFs and when I tried to download them, it basically Failed.
UPDATE: I turned off Ad Blocker and somehow it worked.
But with same Ad blocker when turned on I was able to download any PDF from my projects that I have hosted till date and it is working fine.
