### ISSUE TITLE
Netflix Home Page Clone 

### ISSUE THREAD

**Issue by DineshK3012** [TusharKesarwani/Front-End-Projects#1967]
## **Describe the project**
A Netflix homepage clone website made with only HTML, CSS, JAVASCRIPT and is fully responsive to all types of devices of different sizes, whether it is a laptop, tablet, or mobile phone.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
[Netflix Homepage Clone ](https://github.com/DineshK3012/NetflixClone)

## **Screenshots**
<img width="946" alt="Screenshot 2023-10-08 101813" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/87605928/ec15372c-0eb0-429f-843e-7ebc4254a2c6">

<img width="196" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/87605928/5f6cb7bb-2845-49f2-bb7b-8edbab2cb21b">

**Comment by TusharKesarwani** [comment]
Already present in the repo
