### ISSUE TITLE
Create new UI for the home page

### ISSUE THREAD

**Issue by TusharKesarwani** [TusharKesarwani/Front-End-Projects#2]
If you are interested to work in this issue then write assign me in the comment

**Comment by Sahad-09** [comment]
Hey i would like to work on it

**Comment by TusharKesarwani** [comment]
Go ahead @Sahad-09

**Comment by Shubhodaya** [comment]
Hey! I would also like to work on it.

**Comment by ROUNAK-K-JHA-2002** [comment]
I would Like to create a new UI for Product Launching Website.

**Comment by TusharKesarwani** [comment]
> I would Like to create a new UI for Product Launching Website.

Create new issue I will assign it to you

**Comment by TusharKesarwani** [comment]
> Hey! I would also like to work on it.

Go ahead @Shubhodaya

**Comment by ROUNAK-K-JHA-2002** [comment]
> > I would Like to create a new UI for Product Launching Website.
> 
> Create a new issue I will assign that to you

CreatedThe issue.
