### ISSUE TITLE
Update in BMI Calculator Project

### ISSUE THREAD

**Issue by vanya31** [TusharKesarwani/Front-End-Projects#201]
Found a slight error in the JS of the BMI calculator project. Would like to update the same.

**Comment by Vanshiii203** [comment]
Please explain the error in detail

**Comment by vanya31** [comment]
The default script displays "obese" even as the app is loaded, without any input. Its a bug in the conditionals. It's supposed to display a neutral message, something along the lines of "please enter height and weight/ no values have been entered".

**Comment by Vanshiii203** [comment]
@vanya31 Assigned to you!

**Comment by Vanshiii203** [comment]
@vanya31 Are you still working on this issue?

**Comment by vanya31** [comment]
Yes, I'm sorry got caught up in a college project. Will resolve by evening.
