### ISSUE TITLE
Moody Website

### ISSUE THREAD

**Issue by sumitkr2000** [TusharKesarwani/Front-End-Projects#211]
Hey, @TusharKesarwani I want to add this project to this repo. Please assign me this issue.

Screenshot:-

![Screenshot (530)](https://user-images.githubusercontent.com/100675296/212004829-29ace5d5-47f6-4dba-9dc0-51f16a9fbcac.png)

**Comment by sumitkr2000** [comment]
I want to add the same project

**Comment by Vanshiii203** [comment]
You cannot add the same project as it has been created by someone else. You can take a reference and create your own project

**Comment by sumitkr2000** [comment]
Ok mam @Vanshiii203 :(
