### ISSUE TITLE
Maze Game

### ISSUE THREAD

**Issue by khushigarg1** [TusharKesarwani/Front-End-Projects#216]
A maze game using JavaScript would involve creating a grid of div elements that make up the walls and paths of the maze, as well as a player character that the user can move through the maze. The game would involve the user using arrow keys or WASD keys to move the player character through the maze, trying to reach the end while avoiding walls or obstacles.
It will generate random maze when user select easy, medium and hard.
I will code for maze myself that will look something like this 
![maze](https://user-images.githubusercontent.com/84948160/212165363-c5366bc8-16c7-427b-8f13-f3c11cefa3f7.png)

**Comment by Vanshiii203** [comment]
Please explain your idea. It would be better if you could attach some relevant screenshots or designs.

**Comment by khushigarg1** [comment]
> Please explain your idea. It would be better if you could attach some relevant screenshots or designs.

@Vanshiii203 Done!
