### ISSUE TITLE
Keepeer App

### ISSUE THREAD

**Issue by kuldeepjoshi27** [TusharKesarwani/Front-End-Projects#217]
please assign it to me.

**Comment by Vanshiii203** [comment]
@kuldeepjoshi27 Please explain your idea. It would be better if you could attach some relevant screenshots or designs.

**Comment by kuldeepjoshi27** [comment]
![keeper](https://user-images.githubusercontent.com/105864220/212145455-0b6f990d-1698-4f45-a3df-ed46c0371b12.png)
![keeper1](https://user-images.githubusercontent.com/105864220/212145461-4dae7b6d-3590-4085-b6a0-99b8e2574ac0.png)
![keeper2](https://user-images.githubusercontent.com/105864220/212145466-3238bcf9-f593-4192-b880-e9f6283a674d.png)

**Comment by kuldeepjoshi27** [comment]
these are the screenshots maam of keeper app i have created i have used react in this project

**Comment by kuldeepjoshi27** [comment]
@Vanshiii203 have an eye maam

**Comment by Vanshiii203** [comment]
@kuldeepjoshi27 Assigned to you
