### ISSUE TITLE
Tic Tac Toe Game 

### ISSUE THREAD

**Issue by Harikaraja** [TusharKesarwani/Front-End-Projects#218]
I have done the project by my own logic and css

**Comment by Vanshiii203** [comment]
Hey @Harikaraja Someone is already working on this issue; if they fail to complete it, it will be assigned to you. Until then, you can raise some other issues and work on them.

**Comment by Harikaraja** [comment]
Will u let me know if they fail to complete

**Comment by Harikaraja** [comment]
Will you let me know if they fail to complete the task?

**Comment by Vanshiii203** [comment]
> Will u let me know if they fail to complete
yes!
