### ISSUE TITLE
Animated card

### ISSUE THREAD

**Issue by vimarsh11** [TusharKesarwani/Front-End-Projects#232]
I want to create animated card, so assign me this project.

**Comment by Rishikavishnoi** [comment]
@vimarsh11 Please describe  your idea and  attach  a screenshots if you can.

**Comment by vimarsh11** [comment]
I will use HTML, CSS to make different types of HOVER cards (ex-Name card, Flip card etc.) through which any one can use it in their website.

**Comment by Vanshiii203** [comment]
The project is already present in the repository. If you have any ideas or changes for that project, you can create an issue for it.
