### ISSUE TITLE
Crypto Dashboard

### ISSUE THREAD

**Issue by MridulGupta007** [TusharKesarwani/Front-End-Projects#243]
Shows the current value of various tokens in real time

**Comment by abhilipsasahoo03** [comment]
Hi @MridulGupta007 can you please elaborate on how it's different from https://github.com/TusharKesarwani/Front-End-Projects/issues/63

Like are there any other functionalities that you'd like to focus on?

**Comment by Imsachin010** [comment]
hey @MridulGupta007 I'm interested in creating a Crypto dashboard  by using nodejs next js and apis from coingecko. Please assign the same.

**Comment by abhilipsasahoo03** [comment]
Hi as the contributor is unable to complete issue #63, you can go ahead with creating a PR for Crypto dashboard.
