### ISSUE TITLE
web cam intregration

### ISSUE THREAD

**Issue by Addyzil** [TusharKesarwani/Front-End-Projects#254]
you can view the webcam, and control it

**Comment by abhilipsasahoo03** [comment]
@Addyzil can you please provide sort of a demo video or screenshot of your project to give us a brief idea of its functionality?

**Comment by Addyzil** [comment]
![WEBCAM - Screenshot](https://user-images.githubusercontent.com/104382317/212460213-ab225b64-c75f-4d75-8128-48caed9a57bc.png)

**Comment by Addyzil** [comment]
sir can you please check i have uploaded the screenshot

**Comment by Addyzil** [comment]
web cam integration
(# 254)
