### ISSUE TITLE
Banklist Project (UI part)

### ISSUE THREAD

**Issue by abhijeet-26** [TusharKesarwani/Front-End-Projects#264]
HTML, CSS, JS

**Comment by Vanshiii203** [comment]
@abhijeet-26 can you please provide sort of screenshot of your project?

**Comment by abhijeet-26** [comment]
![s2](https://user-images.githubusercontent.com/68768410/212463460-b55a52ca-574e-488e-afc4-dc94e2aa0a05.png)
![s1](https://user-images.githubusercontent.com/68768410/212463465-3e205db5-3d67-4e11-95ad-89b1afbc5c4b.png)

**Comment by abhijeet-26** [comment]
Here I used some dummy login credential.

**Comment by Vanshiii203** [comment]
I think your issue is same as #169.
