### ISSUE TITLE
Food Ordering website main page

### ISSUE THREAD

**Issue by Sreehitha2003** [TusharKesarwani/Front-End-Projects#268]
I want to create an animated frontend for food ordering website using HTML,CSS and ReactJS

**Comment by Vanshiii203** [comment]
Hey @Sreehitha2003 we are not accepting React Projects

**Comment by Sreehitha2003** [comment]
Then I will do it using HTML,CSS

**Comment by Vanshiii203** [comment]
> Then I will do it using HTML,CSS

Do you want to make changes to the existing project or you want to create a new one as this project is already present in the repo

**Comment by Sreehitha2003** [comment]
Yess

**Comment by swetika23** [comment]
Ma'am can I create my own page from scratch?

**Comment by Vanshiii203** [comment]
@Sreehitha2003 @swetika23 Since this project is already present in the repo, If you have any idea or changes for the project you can create an issue for that. You can view the project here- https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Food%20Ordering%20website

**Comment by swetika23** [comment]
@Vanshiii203 please assign this project to me

**Comment by abhilipsasahoo03** [comment]
@Sreehitha2003 @swetika23 if you have ideas for enhancement of the project, feel free to create a separate issue and attach reference images for the changes you make or features you add. I'm closing this issue.
