### ISSUE TITLE
Random Quote Generator 

### ISSUE THREAD

**Issue by Kumar-Ankit56** [TusharKesarwani/Front-End-Projects#269]
**Project title**
Random Quote Generator

**Project Description**
The idea behind this project is when user will click on the get button every time, he will get the new random motivate quote.

**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**For more details, please refer to the attached images.**

**Comment by Vanshiii203** [comment]
Hey @Kumar-Ankit56 Someone is already working on this issue; if they fail to complete it, it will be assigned to you. Until then, you can raise some other issues and work on them

**Comment by Kumar-Ankit56** [comment]
@Vanshiii203 it's ok,
But how long it will take as I have checked it been week.
Like for single issue after assigning how long it can be hold by assignee.
