### ISSUE TITLE
Tours and Travel

### ISSUE THREAD

**Issue by Kaushan-Dutta** [TusharKesarwani/Front-End-Projects#270]
**Project Description**
Building the frontend of a travel website, along with all its components like landing page, service page, contact page. I will also be adding a preloader which runs before loading any page. 

**Tech Stacks**
- [x] React
- [x] Tailwind
- [x] API

**Comment by LiQuiD-404** [comment]
@Kaushan-Dutta Sorry but we are not accepting React projects for this repository.

**Comment by Kaushan-Dutta** [comment]
@LiQuiD-404  No problem with that, so I can do with plain HTML,CSS , and Javascript

**Comment by Vanshiii203** [comment]
> @LiQuiD-404 No problem with that, so I can do with plain HTML,CSS , and Javascript

@Kaushan-Dutta you can go ahead with this

**Comment by LiQuiD-404** [comment]
> @LiQuiD-404 No problem with that, so I can do with plain HTML,CSS , and Javascript

Sure. Best of Luck ✨

**Comment by Kaushan-Dutta** [comment]
Ok!! Thanks for accepting my issue
