### ISSUE TITLE
Code Editor using HTML,CSS,JS

### ISSUE THREAD

**Issue by Harikaraja** [TusharKesarwani/Front-End-Projects#276]
This code Editor can be used to write codes for HTML,CSS,JS .

**Comment by SarveshLimaye** [comment]
Hey @Harikaraja, this project is already present in the repository. You can view the project here - https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Code-editor 

If you have any ideas or changes for the project, you can create an issue for it .
