### ISSUE TITLE
OTP Verification page

### ISSUE THREAD

**Issue by Sreehitha2003** [TusharKesarwani/Front-End-Projects#279]

**Comment by Vanshiii203** [comment]
can you please provide sort of screenshot/reference of your project?

**Comment by Sreehitha2003** [comment]
![Screenshot 2023-01-15 134224](https://user-images.githubusercontent.com/87296340/212529781-60435a16-9715-4efd-8462-fc5d8b1a68c6.png)

**Comment by Sreehitha2003** [comment]
![image](https://user-images.githubusercontent.com/87296340/212529809-4f226124-fae8-4295-a330-abba0b0954ba.png)

**Comment by LiQuiD-404** [comment]
@Sreehitha2003 Assigned you the issue. Best of Luck ✨
