### ISSUE TITLE
BrainF**k interpreter in HTML CSS and Javascript

### ISSUE THREAD

**Issue by Dinex-dev** [TusharKesarwani/Front-End-Projects#282]
[BrainF**k](https://esolangs.org/wiki/Brainfuck) interpreter with UI built in HTML/CSS and logic implemented in JavaScript

**Comment by abhilipsasahoo03** [comment]
Hi @Dinex-dev can you add a demo video to show the working of the interpreter and to give us a brief idea of how the UI looks?
