### ISSUE TITLE
Language Translator

### ISSUE THREAD

**Issue by Nehaaa3121** [TusharKesarwani/Front-End-Projects#287]

**Comment by LiQuiD-404** [comment]
@Nehaaa3121 Could you please explain what your project is about?

**Comment by Nehaaa3121** [comment]
yes sure. it will work as a translator where the user can check the translation of the sentence or word in any language. suppose if someone doesn't know the English  then they checkout the meaning on our translator web app.

**Comment by Nehaaa3121** [comment]
@LiQuiD-404

**Comment by vaibhavchaubey** [comment]
@Nehaaa3121 I have assigned you the issue now you can work on it.

**Comment by Nehaaa3121** [comment]
> @Nehaaa3121 I have assigned you the issue now you can work on it.

Thanks and if possible could you please approve my pr #283 .
