### ISSUE TITLE
Loading Screen 

### ISSUE THREAD

**Issue by Shubham185y** [TusharKesarwani/Front-End-Projects#289]
there is no loading screen redirection to main page i can do that please assign it to me

**Comment by Vanshiii203** [comment]
Do you want to add a pre-loader to the website?

**Comment by RAJEEVKUMAR9598** [comment]
@Shubham185y @TusharKesarwani assign this issue to me..

**Comment by RAJEEVKUMAR9598** [comment]
I make a loading page..can you assign me please

**Comment by Vanshiii203** [comment]
@RAJEEVKUMAR9598 Issues are assigned on a first come first serve basis. Please look for other unassigned open issues to work on, or feel free to create your own

**Comment by RAJEEVKUMAR9598** [comment]
@Vanshiii203 i pull a repo can you check once??

**Comment by RAJEEVKUMAR9598** [comment]
actually outside nothing is mentioned for this issue ..assigned or not so just i create a pr...

**Comment by Vanshiii203** [comment]
> actually outside nothing is mentioned for this issue ..assigned or not so just i create a pr...

You cannot create a PR directly

**Comment by Anubhavgupta14** [comment]
@Shubham185y Add the description, what you want to make, attach SS if possible so that this issue can be assign to you.

**Comment by Shubham185y** [comment]
yes i want to add preloader to every page like this 
![image](https://user-images.githubusercontent.com/100077254/212696679-8b162763-b9ce-4762-9a51-7f4bcda2c1b0.png)

**Comment by Shubham185y** [comment]
Please Assign this to me

**Comment by Shubham185y** [comment]
i have linked the issue with the PR please review it
