### ISSUE TITLE
Style Loading.

### ISSUE THREAD

**Issue by RAJEEVKUMAR9598** [TusharKesarwani/Front-End-Projects#293]
This page is used when we open any website..its loaded website data.Basically it creates using HTML, CSS,JS. 
@Anubhavgupta14  can you assign me.defineitly it is useful for any website
![START](https://user-images.githubusercontent.com/99285150/212689325-c7ed050e-2763-4910-94e4-6167586ca55b.PNG)

https://user-images.githubusercontent.com/99285150/212691537-c727f9f2-d3ce-48c9-9504-83d0b2e91a47.mp4

**Comment by Anubhavgupta14** [comment]
@RAJEEVKUMAR9598 Is it a pre-loader ?
