### ISSUE TITLE
university management system website

### ISSUE THREAD

**Issue by sarasiddiquie** [TusharKesarwani/Front-End-Projects#297]

**Comment by LiQuiD-404** [comment]
@sarasiddiquie Can you please provide some description of your project? Also, share some reference images of your project.

**Comment by sarasiddiquie** [comment]
I aim to make a portal where, universities can sign up and manage normal stuff like, attendance, announcement page, assignment ,tests and etc. this feature will be available to teachers and students. it will make management easy for students and teachers both.
