### ISSUE TITLE
Groceries selling website landing page

### ISSUE THREAD

**Issue by Sreehitha2003** [TusharKesarwani/Front-End-Projects#299]

**Comment by AnuragJha003** [comment]
I want to contribute to this repo please assign. I will start working on it from 24th January.

**Comment by AnuragJha003** [comment]
Can more details be provided? Like requirements of the landing page and all?
@Sreehitha2003

**Comment by Sreehitha2003** [comment]
I want to work on it

**Comment by AnuragJha003** [comment]
Oh nice then we can work on it together then . But will we be assigned for this ?
