### ISSUE TITLE
A New UI for Product Launching Website

### ISSUE THREAD

**Issue by ROUNAK-K-JHA-2002** [TusharKesarwani/Front-End-Projects#3]

**Comment by sarasiddiquie** [comment]
please assign this issue to me. Thankyou

**Comment by TusharKesarwani** [comment]
Go ahead @ROUNAK-K-JHA-2002

**Comment by TusharKesarwani** [comment]
> please assign this issue to me. Thankyou

If you want to work on this project then create a new issue I will assign that issue to you
