### ISSUE TITLE
Improvement In HexCodeGenerator.

### ISSUE THREAD

**Issue by Kumar-Ankit56** [TusharKesarwani/Front-End-Projects#301]
I'm looking to improve the designing system of Hex-Code UI as currently with present code. While clicking on the gradient button it card container suddenly getting increased.

## Refer this attachment for what I have changed.
![Screenshot (146)](https://user-images.githubusercontent.com/73521123/212870900-b931bda1-cb90-47d3-97ef-734ca7bd9eee.png)

My Update changes
![Screenshot (147)](https://user-images.githubusercontent.com/73521123/212870985-f4166669-d036-42cd-a6a7-c72dae775c03.png)

**Comment by harsh5902** [comment]
go for it @Kumar-Ankit56 👍

**Comment by ArtiHere** [comment]
Can you assign it to me under SWOC 23
