### ISSUE TITLE
Password Strength Checker

### ISSUE THREAD

**Issue by khushigarg1** [TusharKesarwani/Front-End-Projects#302]
Please assign it to me.

**Comment by harsh5902** [comment]
Is this the new project you want to add or new functionality to the Password Generator project??

**Comment by khushigarg1** [comment]
> Is this the new project you want to add or new functionality to the Password Generator project??

It is just a project that will help users ensure that their passwords are secure by analyzing the complexity and strength of the chosen password or not. Like it will check for numbers, lowercase, uppercase and some special characters and will show password strength like weak , moderate and strong.

**Comment by harsh5902** [comment]
Instead of making project I would recommend to add a feature in password generator project, to test our own password's complexity(If user want to make his/her own password).

**Comment by khushigarg1** [comment]
Yess suree
