### ISSUE TITLE
News Website using HTML CSS Javascript

### ISSUE THREAD

**Issue by silentspectator20** [TusharKesarwani/Front-End-Projects#305]
Kindly please assign me this issue.

Regards

**Comment by Durgesh4993** [comment]
I am also intrested in this project could you please assign me

**Comment by silentspectator20** [comment]
@harsh5902 I am planning to make a news website containing all the latest news and categorize all the news into different categories like General news, Business news, Sports news, etc.

**Comment by harsh5902** [comment]
good !!
assigned.
