### ISSUE TITLE
Tip Calculator 

### ISSUE THREAD

**Issue by suryanshhh28** [TusharKesarwani/Front-End-Projects#306]
A tip calculator basically calculates the fair amount of tip that you can give depending upon various factors such the customer satisfaction and the number of people who are going to split the bill among themselves. I will make this project using pure HTML, CSS and vanila javascript.

**Comment by Durgesh4993** [comment]
could you assign this work to me

**Comment by Vanshiii203** [comment]
Hey @suryanshhh28 Someone is already working on this issue; if they fail to complete it, it will be assigned to you. Until then, you can raise some other issues and work on them

**Comment by abhilipsasahoo03** [comment]
This issue has already been worked upon before by someone else previously and their PR has been merged, so I'm closing this issue.
