### ISSUE TITLE
A Basic Expense Tracker web app with React 

### ISSUE THREAD

**Issue by SxxAq** [TusharKesarwani/Front-End-Projects#313]
I want to add a Expense Tracker web app  project built with React js.

**Comment by JawwadAlSabbir** [comment]
Can you please give some awesome brief descriptions about this project?

**Comment by SxxAq** [comment]
Its a basic webApp for storing expenses by a particular date.  
![Capture1](https://user-images.githubusercontent.com/98530202/213025360-ddab5914-daff-4305-8f2b-534cc7004555.PNG)

**Comment by SxxAq** [comment]
There is nothing awesome about this. its just a basic project which stores expenses by particular dates. it was project 0 on a course.

**Comment by Vanshiii203** [comment]
Hey @SxxAq we are not accepting React Projects
