### ISSUE TITLE
love calculator website

### ISSUE THREAD

**Issue by deepshikha2708** [TusharKesarwani/Front-End-Projects#322]

**Comment by deepshikha2708** [comment]
please assign me this issue

**Comment by LiQuiD-404** [comment]
@deepshikha2708 Can you provide some details about your project?

**Comment by deepshikha2708** [comment]
It will be a web page consisting of a heading and one description....two boxes where we can write the names and calculating...I am thinking for generating a random number output with a comment.

**Comment by deepshikha2708** [comment]
or should I add something more?

**Comment by LiQuiD-404** [comment]
@deepshikha2708 Alright sounds good. Assigned you the issue. Best of Luck ✨
