### ISSUE TITLE
Brick Breaker Game

### ISSUE THREAD

**Issue by kuldeepjoshi27** [TusharKesarwani/Front-End-Projects#328]
this is a Brick Breaker Game game.
The object of brick breaker is to break the bricks that are distributed around the top of the game screen. The bricks get broken after coming in contact with a ball that bounces around the screen.
I have used HTML,CSS,JAVASCRIPT to make it.
please assign it to me.
![Screenshot 2023-01-18 231158](https://user-images.githubusercontent.com/105864220/213255287-1fcdfc2c-afc5-41f4-a36a-347898614f40.png)

**Comment by LiQuiD-404** [comment]
@kuldeepjoshi27 Assigned you the issue. Best of Luck ✨
