### ISSUE TITLE
Creating a Netflix Like website

### ISSUE THREAD

**Issue by aryaman1202** [TusharKesarwani/Front-End-Projects#330]
I would like to create a Netflix like front end website using my knowledge of HTML and CSS. Please assign me this issue for SWOC 23.

**Comment by Vanshiii203** [comment]
Hey @aryaman1202  Someone is already working on this issue; if they fail to complete it, it will be assigned to you. Until then, you can raise some other issues and work on them

**Comment by aryaman1202** [comment]
@Vanshiii203 Okay thank you for the suggestion.

**Comment by Vanshiii203** [comment]
@aryaman1202Assigned to you
