### ISSUE TITLE
Usability Hub Clone

### ISSUE THREAD

**Issue by Vanraj8169** [TusharKesarwani/Front-End-Projects#332]
UsabilityHub is a remote user research platform that takes the guesswork out of design decisions by validating them with real users.

**Tech Stack used** : HMTL, CSS

**Screenshots** : 
![image](https://user-images.githubusercontent.com/87256781/213268378-789944c5-b195-4e7c-8d15-0146452d202d.png)
![image](https://user-images.githubusercontent.com/87256781/213268674-7ab55c22-cfa1-4375-8413-145f1c470cbd.png)

@TusharKesarwani  please assign me this issue

**Comment by abhilipsasahoo03** [comment]
Okay I'm assigning you the issue! Go ahead and all the very best!🌟 @Vanraj8169

**Comment by abhilipsasahoo03** [comment]
Hi @Vanraj8169 I just checked. There's already a clone of UsabilityHub present in the repo, therefore I'll be adding the duplicate label. Feel free to create any other issue.
