### ISSUE TITLE
Creating a Blog Website using HTML CSS and JS

### ISSUE THREAD

**Issue by aryaman1202** [TusharKesarwani/Front-End-Projects#333]
I am planning to create a blog website using my knowledge of HTML,CSS and JavaScript. Please assign this issue to me for SWOC 23.

**Comment by aryaman1202** [comment]
@Vanshiii203 Kindly please review my PR and merge it.

**Comment by Vanshiii203** [comment]
@aryaman1202 i have already commented on your PR
