### ISSUE TITLE
Puzzle game using HTML,CSS and JS

### ISSUE THREAD

**Issue by monishkajha17** [TusharKesarwani/Front-End-Projects#338]
Here, I will create a puzzle game where the user can solve the puzzle

**Comment by S-ishita** [comment]
please assign me this issue.

**Comment by S-ishita** [comment]
@zugzwang03 please assign me this issue.

**Comment by monishkajha17** [comment]
@zugzwang03 Yes di bss I am adding other puzzles as well will make PR toady
