### ISSUE TITLE
Personal portfolio website with vertical Navbar.

### ISSUE THREAD

**Issue by ADITYA0714** [TusharKesarwani/Front-End-Projects#339]
I will be making the personal portfolio website with vertical navbar . I will only make the landing page of the website. I will make the site using html, css, js .
kindly issue me this project.

**Comment by LiQuiD-404** [comment]
@ADITYA0714 Provide some reference image or screenshot of your project.

**Comment by ADITYA0714** [comment]
![Screenshot (158)](https://user-images.githubusercontent.com/95866052/213513374-ab293645-0a48-4e26-9236-b531d256c4de.png)

**Comment by ADITYA0714** [comment]
This can be made by adding background and hover-effect.

**Comment by vaibhavchaubey** [comment]
@ADITYA0714 I have assigned you the issue now you can work on it.

**Comment by Vanshiii203** [comment]
someone is already working on this issue!
