### ISSUE TITLE
Personal Information Page

### ISSUE THREAD

**Issue by kuldeepjoshi27** [TusharKesarwani/Front-End-Projects#344]
i have created a static portfolio page I have used html css javascript but main part is of css.
please assign it to me.
![Screenshot 2023-01-19 222252](https://user-images.githubusercontent.com/105864220/213507944-353100d7-a9b5-4f64-b286-81d78d84a643.png)

**Comment by Imsachin010** [comment]
i think we could add some hovering features and nice color gradient please assing the same @kuldeepjoshi27
