### ISSUE TITLE
food ordering website

### ISSUE THREAD

**Issue by ashadmuneer** [TusharKesarwani/Front-End-Projects#346]
## **Describe the project**
A food ordering website by using Html and CSS. A website is fully responsive.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

**Comment by MohitNamdev22** [comment]
Hey @ashadmuneer, kindly check the projects, Food Ordering website is already made

> ## **Describe the project**
> A food ordering website by using Html and CSS. A website is fully responsive.
> 
> ## Issue Type:
> * [ ]  Bug Report
> * [ ]  Feature Request
> * [ ]  Documentation
> * [x]  New Project
