### ISSUE TITLE
Bookmarker_application

### ISSUE THREAD

**Issue by Amit0412** [TusharKesarwani/Front-End-Projects#349]
## **Describe the project**
Tech stack : Html, CSS and JavaScript and little bit of bootstrap for styling.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ✔] New Project

## **Additional context**
Beginner to medium level web developer friendly project.

**Comment by Amit0412** [comment]
Pls assign me this issue @TusharKesarwani

**Comment by MohitNamdev22** [comment]
Go for it @Amit0412 🚀
