### ISSUE TITLE
Birthday Card Using HTML,CSS 

### ISSUE THREAD

**Issue by monishkajha17** [TusharKesarwani/Front-End-Projects#361]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
Attach a reference image for your project

**Comment by monishkajha17** [comment]
Okay di

**Comment by monishkajha17** [comment]
@TusharKesarwani Can we use Bootstrap ?

**Comment by Vanshiii203** [comment]
> @TusharKesarwani Can we use Bootstrap ?

Yes
