### ISSUE TITLE
animated heart using html , css and javascript 

### ISSUE THREAD

**Issue by alisha722** [TusharKesarwani/Front-End-Projects#367]
**Is your feature request related to a problem? Please describe.**
A website of love horoscope is paid attention to, if it has some good animations, this helps to being many more users to the website. If it's a dull website rarely anyone would give a visit. so thats why I want to make an animated heart that can be used in these websites .

**Describe the solution you'd like**
A I have designed an animated pulsing heart for the love horoscope website using vibrant colors.

**Describe alternatives you've considered**
A I have used HTML , CSS and javascript for designing it

**Additional context**
![FlippantScaryGalapagosdove-size_restricted](https://user-images.githubusercontent.com/84632701/213871579-708b4d83-53a6-4c1c-b441-5383d112bd4a.gif)

**Comment by Vanshiii203** [comment]
Can you please attach aa refrence image for your project idea?

**Comment by alisha722** [comment]
> Can you please attach aa refrence image for your project idea?

yes I have attached for reference it would be somewhat like this , but not exactly this .

**Comment by alisha722** [comment]
@Vanshiii203 please assign me this

**Comment by Vanshiii203** [comment]
@alisha722 sorry but this type of project is not accepted.
