### ISSUE TITLE
Typing effect animation using css

### ISSUE THREAD

**Issue by CS50X-RGB** [TusharKesarwani/Front-End-Projects#369]
## **Describe the project**
A animation which will consist of words being typed out like when we write by keyboard we will be able to create that animation using css only. 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

https://user-images.githubusercontent.com/89659393/213868246-dfb84d43-7a65-47a4-8868-5741fd13a7b1.mp4

**Comment by tarushi16** [comment]
can use both
.typing-animation {
  animation: typing 2s linear infinite;
}

@keyframes typing {
  0% {
    width: 0;
  }
  100% {
    width: 100%;
  }
}

**Comment by CS50X-RGB** [comment]
Actually by my piece code you can change the no of characters to how many characters will the animation be applied and how the speed will reduced and increased

**Comment by CS50X-RGB** [comment]
@tarushi16 I have  added some clip about how the animation works

**Comment by CS50X-RGB** [comment]
Actually by my piece code you can change the no of characters to how many characters will the animation be applied and how the speed will reduced and increased

**Comment by CS50X-RGB** [comment]
@TusharKesarwani hi i actually didn't get it why it got closed
