### ISSUE TITLE
Color Flipper

### ISSUE THREAD

**Issue by kuldeepjoshi27** [TusharKesarwani/Front-End-Projects#374]
## **Describe the project**
It is a project based on HTML,CSS,JAVASCRIPT.
In this if we click of button color will be change we can set hex or normal color by using their certain button.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
No

## **Screenshots**
![Screenshot 2023-01-21 152703](https://user-images.githubusercontent.com/105864220/213861776-272349f7-e80c-497f-889d-531b527165e7.png)

![Screenshot 2023-01-21 152742](https://user-images.githubusercontent.com/105864220/213861781-851bfc71-356f-4f5b-b357-ec46fa5ded45.png)

**Comment by Vanshiii203** [comment]
Your issue seems to be same as #124

**Comment by kuldeepjoshi27** [comment]
> Your issue seems to be same as #124

we can say but i added two more buttons simple and hex .In simple normal colors are shown with name and in hex so many colors with hex code.

**Comment by Vanshiii203** [comment]
if you have any idea you can make changes to the existing project(https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Hex%20Code%20Generator)
