### ISSUE TITLE
Fruit Ninja Game

### ISSUE THREAD

**Issue by papri24majumder** [TusharKesarwani/Front-End-Projects#377]
**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to a problem

**Describe the solution you'd like**
I want to make the fruit ninja game using HTML, CSS, and JavaScript.

**Describe alternatives you've considered**
No alternatives

**Additional context**
Nil

**Comment by papri24majumder** [comment]
@Vanshiii203 Instead of fruit can I make a Ball ninja game? Like ball will be present in place of fruit.

**Comment by papri24majumder** [comment]
Hey, @Vanshiii203 please answer the above-asked question.

**Comment by Vanshiii203** [comment]
Yes you can
