### ISSUE TITLE
Sum of Digit

### ISSUE THREAD

**Issue by Kumar-Ankit56** [TusharKesarwani/Front-End-Projects#379]
## **Describe the project**
Sum of digit a very simple project in HTML, CSS , JS that has functionalty like enter the any number and click calcaluate button and you will have the sum of digit contain in number.

## Issue Type:
- [x] New Project

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot (152)](https://user-images.githubusercontent.com/73521123/213870340-330695d4-9137-4704-a55b-c2d65cd338ae.png)

**Comment by Vanshiii203** [comment]
Hey @Kumar-Ankit56 Calculator project is already present in the repo.

**Comment by Kumar-Ankit56** [comment]
@Vanshiii203 calculator is there but this something different please consider this.
