### ISSUE TITLE
Tutorial Documentation Website

### ISSUE THREAD

**Issue by amelia2802** [TusharKesarwani/Front-End-Projects#380]
## **Describe the project**
A website that displays the documentation/tutorial of any technical skills[EX: TutorialsPoint,JavaPoint, etc]

## Issue Type:
- [x] New Project

**Comment by amelia2802** [comment]
@TusharKesarwani Hey, can you assign me?

**Comment by abhilipsasahoo03** [comment]
@amelia2802 kindly add a reference screenshot of the website

**Comment by amelia2802** [comment]
> @amelia2802 kindly add a reference screenshot of the website

sure, here it is:

### Desktop View:
![desktop view](https://user-images.githubusercontent.com/49182604/214893755-2664783b-a53d-490f-a303-5547c4b5e2a7.jpg)

### Mobile View:
![mobile view](https://user-images.githubusercontent.com/49182604/214894032-4624c110-cfe8-4355-a7cf-510cb9798fca.jpg)

**Comment by abhilipsasahoo03** [comment]
Looks good to me. You can go ahead and create a PR. :) @amelia2802
