### ISSUE TITLE
Paragraph Generator

### ISSUE THREAD

**Issue by kuldeepjoshi27** [TusharKesarwani/Front-End-Projects#381]
## **Describe the project**
we are TIRED OF USING LOREM IPSUM I have created it using html,css,javascript.
it can create paragraph upto  9 paragraphs.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

![Screenshot 2023-01-21 194556](https://user-images.githubusercontent.com/105864220/213871042-49506cbd-f758-4d0f-984e-053da422f414.png)

**Comment by Vanshiii203** [comment]
Hey @kuldeepjoshi27 Can you explain how your idea is it different form #355 ?

**Comment by kuldeepjoshi27** [comment]
yes sure ma'am In #355 as a wikipedia page it searches that what we want ot search or we want to know about but in this #381
i have created a paragraph generator like in templates if we want to use the text diffrent from lorem epsum than we can generate by writing number of paragraph(max 9) and after entering it will generate paragraph.
