### ISSUE TITLE
Drum Instrument App

### ISSUE THREAD

**Issue by officialarmannqureshi** [TusharKesarwani/Front-End-Projects#382]
## **Describe the project**
Drum Instrument App is a online instrument app we can easily play it online and also fulfills the desire of kids to play Drum but they can't afford it so I have made a drum instrument app to play it online.
Technologies used: Javascript,HTML,CSS

## Screenshot
<img width="960" alt="image-1" src="https://user-images.githubusercontent.com/91754196/213875056-58c4e33b-1b6b-4b49-b285-6a38dae64be1.png">

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
Hey @officialarmannqureshi this project is already present in the repo. If you have any idea/changes for the existing project you can raise a issue for that (https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/The%20Great%20Drumkit)
