### ISSUE TITLE
Temperature converted

### ISSUE THREAD

**Issue by khushigarg1** [TusharKesarwani/Front-End-Projects#383]
**Is your feature request related to a problem? Please describe.**
HTML , CSS, JAVASCRIPT
It is a converter which converts temperature from celsius to Fahrenheit and viceversa with soem background animations.
Please assign this issue to me!

**Comment by khushigarg1** [comment]
> **Is your feature request related to a problem? Please describe.** HTML , CSS, JAVASCRIPT It is a converter which converts temperature from celsius to Fahrenheit and viceversa with some background animations.

Please assign this issue to me

**Comment by Vanshiii203** [comment]
Your issue seems to be the same as #100
