### ISSUE TITLE
Check Internet connection using html, CSS and javascript

### ISSUE THREAD

**Issue by Mridul-2003** [TusharKesarwani/Front-End-Projects#384]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Imsachin010** [comment]
I would like to work on this please provide some details and assign it to me
