### ISSUE TITLE
Tiffin Service Website

### ISSUE THREAD

**Issue by Imsachin010** [TusharKesarwani/Front-End-Projects#387]
## **Describe the project**

As everything is going online and everyone adapting & developing with Technology. This idea is to create a Online Tiffin service website (Lunch Box).
It would contain meal details and Subscription plans for monthly basis. 

## Issue Type:

- [ ] Documentation
- [ ] New Project

**Comment by Imsachin010** [comment]
please assign is to me @TusharKesarwani

**Comment by Vanshiii203** [comment]
Hey @Imsachin010 your issue seems to be same as #59

**Comment by Vanshiii203** [comment]
@Imsachin010 You can start working on this issue

**Comment by Imsachin010** [comment]
thank you for the opportunity I'll work on it.

**Comment by Imsachin010** [comment]
Hey @Vanshiii203 I was working in the same project with React JS. Do you accept it in react or do I have to submit with normal html css & Js.

**Comment by Vanshiii203** [comment]
@Imsachin010 We are not accepting React Projects

**Comment by Imsachin010** [comment]
ok I'll use Html, Css and Js
