### ISSUE TITLE
Dynamic JS quiz

### ISSUE THREAD

**Issue by Laraibnehal** [TusharKesarwani/Front-End-Projects#388]
## **Describe the project**
This Project Teaches You About Radio Buttons And How To Use JavaScript To Add Content.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by LiQuiD-404** [comment]
@Laraibnehal Assigned you the issue. Best  of Luck ✨
