### ISSUE TITLE
Random_quote_generator_using_APIs

### ISSUE THREAD

**Issue by Hanshika-Mehta** [TusharKesarwani/Front-End-Projects#390]
The Quote_generator generates the  random useful quotes using API.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

**Comment by harshit-paneri** [comment]
Hey👋🏻 @Hanshika-Mehta Now you can start the work on this issues.

**Comment by Vanshiii203** [comment]
Hey @Hanshika-Mehta someone is already working on this issue

**Comment by harshit-paneri** [comment]
Hey @Vanshiii203 , I saw that this type of issue is alredy assign but it more that 1 week that still not send any PR for on this issue, can we unassined them or ask them to send PR

**Comment by Vanshiii203** [comment]
@harshit-paneri I have asked him to create a PR before and I think it has been raised.

**Comment by harshit-paneri** [comment]
Ok so may I close there PR, bcz there PR is still open
