### ISSUE TITLE
Snake_water_gun_game_using_javascript

### ISSUE THREAD

**Issue by Hanshika-Mehta** [TusharKesarwani/Front-End-Projects#391]
## **Describe the project**
A  two player fun game using javaScript 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Hanshika-Mehta** [comment]
Snake_water_gun_game

**Comment by Vanshiii203** [comment]
Hey @Hanshika-Mehta someone is already working on this issue #342
