### ISSUE TITLE
Product Details Cards

### ISSUE THREAD

**Issue by Imsachin010** [TusharKesarwani/Front-End-Projects#392]
# Description

**Comment by Imsachin010** [comment]
please assign this project to me @TusharKesarwani

**Comment by zugzwang03** [comment]
Can you attach any screenshot of what you wish to create? @Imsachin010

**Comment by Imsachin010** [comment]
Sorry for late reply My CTS are going on I was little bit busy.....Please check.... @zugzwang03 
### ScreenShort
![Screenshot from 2023-01-29 12-06-41](https://user-images.githubusercontent.com/97721592/215309559-afccd802-93b3-4fe1-a3ad-512a146be4d9.png)

**Comment by Imsachin010** [comment]
Please assign me the same
