### ISSUE TITLE
Loan Calculator

### ISSUE THREAD

**Issue by kuldeepjoshi27** [TusharKesarwani/Front-End-Projects#394]
## **Describe the project**
It is a Loan calculator in which we have to input loan amount,intrest rate,month to pay.
i have created it using html,css,javascript.
please assign me.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

![Screenshot 2023-01-22 173238](https://user-images.githubusercontent.com/105864220/213914939-f3c5a84a-16bd-4393-ab8e-8592d8be5721.png)

**Comment by abhilipsasahoo03** [comment]
Hi @kuldeepjoshi27 are you working on this issue? If yes, please create a valid PR and link this issue. If not, let us know and we will assign someone else willing to work on it.

**Comment by kuldeepjoshi27** [comment]
yes i am uploading it today actually there is my exams so i am not able to submit but todiay i will
