### ISSUE TITLE
Build a Survey Form

### ISSUE THREAD

**Issue by Laraibnehal** [TusharKesarwani/Front-End-Projects#400]
## **Describe the project**

Every Website Needs A Form To Connect Its User To The Web Owner So Everyone Must Know That To Create A Form. This Is The Best Html Css Project For New Learners.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by AnkitAnandMastery17** [comment]
Hi, If this is not assigned can you assign to me?
