### ISSUE TITLE
Beautyzone - A website for salon

### ISSUE THREAD

**Issue by alisha722** [TusharKesarwani/Front-End-Projects#409]
## **Describe the project**
A website template made using html , css and javascript for salon and its services like spa .Overall it would be a responsive salon website with navbar and other contents like pricing etc.

## Issue Type:
- [x] New Project

## **Additional context**
A frontend design for salon website .

## **Screenshots**

-
![hairsal-free-template](https://user-images.githubusercontent.com/84632701/213936974-18c0d623-f0c5-42b0-a9d8-cffc07de64c3.jpg)

**Comment by zugzwang03** [comment]
built it solely on html, css and js. Good luck :) @alisha722

**Comment by alisha722** [comment]
Okay , sure. Thank you
