### ISSUE TITLE
Tetris Game

### ISSUE THREAD

**Issue by S-ishita** [TusharKesarwani/Front-End-Projects#412]
## **Describe the project**
Tetris is a puzzle video game.In Tetris, players complete lines by moving differently shaped pieces ([tetrominoes]), which descend onto the playing field.

## Issue Type:
- [x] New Project

![Screenshot from 2023-01-08 16-04-14](https://user-images.githubusercontent.com/104543751/214584856-0357f425-7db6-4dee-9a49-34864105a4ca.png)
![Screenshot from 2023-01-08 16-04-03](https://user-images.githubusercontent.com/104543751/214584884-90f7edb8-de1d-4ba4-8675-9c5cc3d083c7.png)

**Comment by S-ishita** [comment]
kindly assign me this issue @TusharKesarwani @Vanshiii203

**Comment by zugzwang03** [comment]
Can you add some screenshot along with it? @S-ishita
