### ISSUE TITLE
Fighting Game

### ISSUE THREAD

**Issue by S-ishita** [TusharKesarwani/Front-End-Projects#414]
## **Describe the project**
A fighting game is a genre of video game in which a gamer battles against another character controlled by another gamer.
This fighting game feature special moves that are triggered through rapid sequences of button presses.
Player 1: Controls:W A D Space F
Player 2: Controls:ArrowUp ArrowLeft ArrowRight ArrowDown Control

## Issue Type:

- [x] New Project

**Comment by S-ishita** [comment]
kindly assign me this issue @TusharKesarwani @Vanshiii203

**Comment by abhilipsasahoo03** [comment]
> kindly assign me this issue @TusharKesarwani @Vanshiii203 

Sure I'm assigning you.
