### ISSUE TITLE
Temperature Converter Application

### ISSUE THREAD

**Issue by Diptamoy-Mitra** [TusharKesarwani/Front-End-Projects#418]
## **Describe the project**
It is an temperature converter application using JS. It can convert temperature into celcius, fahrenhite and kelvin

## Issue Type:

- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
![Screenshot (19)](https://user-images.githubusercontent.com/91617575/214060597-c903034d-70ce-4b13-8c69-f42ecbccab6e.png)

**Comment by Diptamoy-Mitra** [comment]
please assign me for this issue

**Comment by Diptamoy-Mitra** [comment]
@TusharKesarwani  @Vanshiii203

**Comment by Vanshiii203** [comment]
hey @Diptamoy-Mitra someone is already working on this issue.

**Comment by Diptamoy-Mitra** [comment]
So,  i am not allow to working on this issue??😥

**Comment by abhilipsasahoo03** [comment]
> So,  i am not allow to work on this issue??😥

A similar project is already present in this repo.
