### ISSUE TITLE
Management dashboard UI

### ISSUE THREAD

**Issue by alisha722** [TusharKesarwani/Front-End-Projects#419]
## **Describe the project**
I want to design a sales management dashboard user interface . I want to create an attractive and clear minimal looking dashboard UI which can be used in sales management website 

## Issue Type:
- [x] New Project

## **Additional context**
I will create it using html , css and js .

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![dashboards_by_function_it_project_management_dashboard_slide01](https://user-images.githubusercontent.com/84632701/214381006-e7c3ca0b-aa0d-42ca-a78c-a594e97b7693.jpg)

**Comment by Vanshiii203** [comment]
can you attach a reference image for your project?

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by alisha722** [comment]
![dashboards_by_function_it_project_management_dashboard_slide01](https://user-images.githubusercontent.com/84632701/214380824-20bf57fc-3a97-454f-aebf-eaa9c43b9e15.jpg)

**Comment by alisha722** [comment]
> can you attach a reference image for your project?

yes sure , I have attached the screenshot , please have a look at it
