### ISSUE TITLE
Loan Calculator 

### ISSUE THREAD

**Issue by suryanshhh28** [TusharKesarwani/Front-End-Projects#421]
## **Describe the project**
A project using HTML, CSS and Javascript, which calculates the mortgage amount that you have to pay after lending a loan from a bank

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
Hey @suryanshhh28 Someone is already working on this issue.

**Comment by suryanshhh28** [comment]
hey, are they working till yet?
