### ISSUE TITLE
Quiz App

### ISSUE THREAD

**Issue by sanil011** [TusharKesarwani/Front-End-Projects#426]
## **Describe the project**
Quiz app using react and redux that will save the information even after the user refresh the page and timer will resume from where it stop and it also responsive.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ✅] New Project

**Comment by Vanshiii203** [comment]
Hey @sanil011 We are not accepting react projects.

**Comment by sanil011** [comment]
> Hey @sanil011 We are not accepting react projects.

then Only HTML , CSS and javascript. No framework??
