### ISSUE TITLE
Random Quotes Generator

### ISSUE THREAD

**Issue by himanshu1221** [TusharKesarwani/Front-End-Projects#428]
## **Describe the project**
this projects is based on ReactJS and thru this project we can generate random quotes using API and we can share it on twitter as well.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Random Quote Generated
![Screenshot from 2023-01-24 09-14-46](https://user-images.githubusercontent.com/32031706/214208153-fc3ccad7-a7fb-4c0a-9eb2-dd8839e2aa3f.png)

## **Screenshots**

-Generates Random Quotes And is we can share it to twitter

**Comment by Vanshiii203** [comment]
@himanshu1221 someone is already working on this issue using javascript and we are not accepting React Projects

**Comment by himanshu1221** [comment]
> @himanshu1221 someone is already working on this issue using javascript and we are not accepting React Projects 

Oh ok
