### ISSUE TITLE
Spotify Clone 

### ISSUE THREAD

**Issue by himanshu1221** [TusharKesarwani/Front-End-Projects#430]
## **Describe the project**
It's a working  spotify clone in which we can listen to songs play and pause them and change to next track too

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
![Screenshot from 2023-01-24 14-20-34](https://user-images.githubusercontent.com/32031706/214248386-75e7f9c8-761d-4b92-82aa-6c8afa488608.png)
![Screenshot from 2023-01-24 14-21-12](https://user-images.githubusercontent.com/32031706/214248487-b10da8ec-2b4c-418a-8aea-9e0ece8144d3.png)

**Comment by Vanshiii203** [comment]
Someone is already working on this issue

**Comment by himanshu1221** [comment]
> Someone is already working on this issue

can i still make a PR regarding the same ?

**Comment by Vanshiii203** [comment]
No, if they fail to complete it, it will be assigned to you and then you can raise a PR. Until then, you can raise some other issues and work on them

**Comment by Vanshiii203** [comment]
@himanshu1221 Assigned to you
