### ISSUE TITLE
Atmospheric Air Quality Checker

### ISSUE THREAD

**Issue by Amit0412** [TusharKesarwani/Front-End-Projects#431]
## **Describe the project**
This web-application takes input of geographical location from user (it can be done automatically as well as manually). Then by the help of API, the Air Quality Index of that location is provided to the user along with the exact concentration of various Air Pollutants like Carbon Monoxide, Nitrogen Monoxide, Nitrogen Dioxide, Ozone, Sulphur Dioxide, etc. Later, a user can study detailed prevention measures from the links provided in the web-application to improve Air Quality Index.

## Issue Type:

- [ ✔] New Project

**Comment by iamatifmoin** [comment]
@Vanshiii203 
I am linking a video of a web app I created that does the same task.
[Tab-1674563193856.webm](https://user-images.githubusercontent.com/97212195/214291747-4ff51f46-ef49-4a85-b074-10e197874bed.webm)

Kindly review it and tell me if I should raise a PR.

**Comment by Amit0412** [comment]
@iamatifmoin I had already raised the PR. You can check that.
