### ISSUE TITLE
Language translator using Google translate API

### ISSUE THREAD

**Issue by Harikaraja** [TusharKesarwani/Front-End-Projects#442]
In this project the text entered in the message box is translated to the specified language by the user , here API used is Google translate API

**Comment by Vanshiii203** [comment]
Hey @Harikaraja this project is already present in the repo

**Comment by Harikaraja** [comment]
ok mam , can i enhance if possible

**Comment by Vanshiii203** [comment]
Yes u can do that. Create an issue for that or change the title of this issue for the feature/changes you want to make in the project

**Comment by abhilipsasahoo03** [comment]
Hi @Harikaraja I suggest you create a fresh issue stating all the enhancements you need to make in the above said project you're looking forward to work on. I'm closing this one for now!
