### ISSUE TITLE
Search functionality on frontend projects' website

### ISSUE THREAD

**Issue by VaibhavArora314** [TusharKesarwani/Front-End-Projects#444]
**Is your feature request related to a problem? Please describe.**
We can add search functionality to the front-end projects' website. Users can enter a search query and all the related projects will only be shown.

**Describe the solution you'd like**
I will create a projects.json file which will contain all the projects to display on the website and their respective details. The projects will be dynamically loaded on the website using this JSON file. If there is any search query, then the projects will be filtered based on the search query.

**Describe alternatives you've considered**

**Additional context**

Please assign me this issue. I am willing to work on it.

**Comment by TusharKesarwani** [comment]
Go ahead
