### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by Priyanshu-Singh-1** [TusharKesarwani/Front-End-Projects#452]
## **Describe the project**
A Password Generator website that generates strong passwords for users and gives suggestions about ways to prevent your passwords from being hacked
## Issue Type:

- [ ] New Project

## **Additional context**
It is created using HTML, CSS, and JavaScript.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/107169043/214768286-7b6b704b-bdbc-4581-99d9-a4d0d5468713.png)

In this, we can add how and what should be included like numbers, alphabets upper_Case and lower_case, etc. We can also make the variable length of the password, by changing the bar.

**Comment by Priyanshu-Singh-1** [comment]
@thisisamanmishra Can you please assign me this issue

**Comment by Vanshiii203** [comment]
this project is already present in the repo

**Comment by Priyanshu-Singh-1** [comment]
Ok! Np I will make some other cool front end projects! Thanks @Vanshiii203 For giving your time!
