### ISSUE TITLE
Responsive Calender

### ISSUE THREAD

**Issue by Priyanshu-Singh-1** [TusharKesarwani/Front-End-Projects#453]
## **Describe the project**
A calendar made using HTML, CSS, and JavaScript typically consists of a table, where each cell represents a day of the month. The table is created using HTML and styled using CSS to give it a visually appealing appearance. JavaScript is used to provide interactive functionality, such as allowing users to navigate between months and years, and to select specific dates. The calendar can also include features such as highlighting today's date, displaying events, and allowing for scheduling or reservations.

## Issue Type:

- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- Working on it, still some parts are left to work upon. I will add once the website is made

**Comment by Priyanshu-Singh-1** [comment]
@thisisamanmishra @Rishikavishnoi can you please assign me this issue! I want to contribute for it

**Comment by Vanshiii203** [comment]
@Priyanshu-Singh-1 This project is already present in the repo. If you have any idea or changes for the project you can create an issue for that (project link- https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Calendar)

**Comment by Priyanshu-Singh-1** [comment]
Ok I will make some other new contribution! Thanks @Vanshiii203 for giving time
