### ISSUE TITLE
Countify

### ISSUE THREAD

**Issue by Diptamoy-Mitra** [TusharKesarwani/Front-End-Projects#455]
## **Describe the project**
It count each word and character  of a sentence.

## Issue Type:
- [x] New Project

## **Additional context**
Use HTML5,CSS3,JS.

## **Screenshots**

![Screenshot (27)](https://user-images.githubusercontent.com/91617575/215125033-b3dfb6a3-d4ae-43fc-a2d4-c9a50ea86960.png)

**Comment by Diptamoy-Mitra** [comment]
Please assign me in this project. Please.

**Comment by abhilipsasahoo03** [comment]
Can you please add a reference image of your website to the PR? @Diptamoy-Mitra

**Comment by Diptamoy-Mitra** [comment]
yes yes obviously

**Comment by Diptamoy-Mitra** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/91617575/215124856-b2e3a8cf-f716-41bd-86cb-c1b4618c8d99.png)

**Comment by Diptamoy-Mitra** [comment]
Please assign me this,  only 4 days left to complete

**Comment by Diptamoy-Mitra** [comment]
> Can you please add a reference image of your website to the PR? @Diptamoy-Mitra

Please assign me

**Comment by abhilipsasahoo03** [comment]
Okay @Diptamoy-Mitra I'm assigning you.
