### ISSUE TITLE
Order Summary Component

### ISSUE THREAD

**Issue by Vanraj8169** [TusharKesarwani/Front-End-Projects#456]
## **Describe the project**
This project is about order Summary Component Card which is designed using HTML and CSS.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.
![image](https://user-images.githubusercontent.com/87256781/214794578-0bfaf438-10a4-4f6e-a57e-375a8ee2389d.png)

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by abhilipsasahoo03** [comment]
@Vanraj8169 We already do have a Cards Component (containing similar pricing plans and stuff + uses Javascript). I'm not sure how this project will be different from the one already present in the repo.
