### ISSUE TITLE
Ezy Math- Mathematics Problem Solver 

### ISSUE THREAD

**Issue by Vanraj8169** [TusharKesarwani/Front-End-Projects#457]
## **Describe the project**
Ezy Math is a website designed to help users solve math problems with ease. The website is built using HTML, CSS and JavaScript, making it user-friendly and visually appealing. Users can input math problems and receive step-by-step solutions, as well as explanations for each step. The website also includes a variety of math topics, from basic arithmetic to advanced calculus, catering to students of all levels. Ezy Math aims to make math learning accessible and enjoyable for everyone.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
![image](https://user-images.githubusercontent.com/87256781/214799342-84f4d6aa-ed16-4edd-aaca-36c2870c8b25.png)
![image](https://user-images.githubusercontent.com/87256781/214799374-76ded311-4fb2-41b3-a4e1-53946830e196.png)
![image](https://user-images.githubusercontent.com/87256781/214799389-c5060159-8a00-4de1-8935-b5ff7c62ecd5.png)
![image](https://user-images.githubusercontent.com/87256781/214799402-2537dc99-f956-4814-a140-ae2382173074.png)
![image](https://user-images.githubusercontent.com/87256781/214799414-65351dd0-2fe4-4a57-9bb9-e709867df0df.png)
![image](https://user-images.githubusercontent.com/87256781/214799437-c515028e-3f39-4a32-9c57-c4447ef415c6.png)

- If applicable, add screenshots to help explain your problem.

**Comment by abhilipsasahoo03** [comment]
Hi @Vanraj8169. It looks great ⭐. Do you have a demo video or maybe a deployed link so that we can test it's working functionality?

**Comment by abhilipsasahoo03** [comment]
Yes looks really great! 🌟 Go ahead and make a PR. @Vanraj8169 All the best!✨
