### ISSUE TITLE
FILE UPLOADER 

### ISSUE THREAD

**Issue by himanshu1221** [TusharKesarwani/Front-End-Projects#475]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
i'll be making a website where we can uploadd our images using pure HTML CSS & JS

## **Screenshots**
![Screenshot from 2023-01-27 14-20-39](https://user-images.githubusercontent.com/32031706/215045757-5921cf6f-6317-4635-9c16-f6c9f2d316cd.png)

**Comment by zugzwang03** [comment]
Isn't the use case very minor?
It will only upload the files?
Why will anyone use this project if he or she has a laptop or a phone for storage?

**Comment by himanshu1221** [comment]
> Isn't the use case very minor? It will only upload the files? Why will anyone use this project if he or she has a laptop or a phone for storage?

yes thats true

**Comment by abhilipsasahoo03** [comment]
@himanshu1221 you can rather use this feature of file upload for something bigger such as file converter, etc. This is just a suggestion so please make sure that the project, you want to incorporate this feature into, is not already available in the repo. Good luck!

**Comment by abhilipsasahoo03** [comment]
Therefore, I'm closing this issue, you can create a new issue and state the project description there.
