### ISSUE TITLE
Tic Tac Toe project

### ISSUE THREAD

**Issue by AayushiKukreja** [TusharKesarwani/Front-End-Projects#482]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
hey @AayushiKukreja this project is already present in the repo
