### ISSUE TITLE
Corona-Tracker

### ISSUE THREAD

**Issue by kuldeepjoshi27** [TusharKesarwani/Front-End-Projects#485]
## **Describe the project**
It is a Corona-Tracker web app .In which i have used HTML,CSS,JAVASCRIPT,API.
It tracks the tracks the data between the dates and show us on screen.

## **Screenshots**

![Screenshot 2023-01-27 224758](https://user-images.githubusercontent.com/105864220/215152428-3698074c-10c7-4341-965f-30bfb2f35e07.png)

**Comment by abhilipsasahoo03** [comment]
@kuldeepjoshi27 please provide reference images or screenshots for your project.

**Comment by kuldeepjoshi27** [comment]
> @kuldeepjoshi27 please provide reference images or screenshots for your project.

![Screenshot 2023-01-27 224758](https://user-images.githubusercontent.com/105864220/215315529-1ea0a0d5-a74e-4be6-a6e0-1dbebf44196d.png)

**Comment by abhilipsasahoo03** [comment]
Ok @kuldeepjoshi27 I'm assigning.
