### ISSUE TITLE
IngredientBasedRecipes

### ISSUE THREAD

**Issue by yashkhandelwal2203** [TusharKesarwani/Front-End-Projects#494]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by yashkhandelwal2203** [comment]
Kindly Assign it to me.

**Comment by Vanshiii203** [comment]
@yashkhandelwal2203 This project is already present in the repo.
If you have any idea or changes for the existing project you can create an issue for that

**Comment by yashkhandelwal2203** [comment]
But the project that was present is different from mine. In my project you have to search all the recipes that can be made from a particular ingredient whereas in the existing one you have to search the recipes name.

**Comment by yashkhandelwal2203** [comment]
In my project you have to just place the ingredients name and all the recipes that can be made from that ingredient will be shown.

**Comment by abhilipsasahoo03** [comment]
> In my project you have to just place the ingredients name and all the recipes that can be made from that ingredient will be shown.

Maybe you can add that as an enhancement to the existing project? If you're interested in doing so, please create a new issue stating all the changes made/features added. @yashkhandelwal2203

**Comment by abhilipsasahoo03** [comment]
I'm closing this issue.
