### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by codeburn12** [TusharKesarwani/Front-End-Projects#495]
## **Describe the project**
Most of the we can't able to generate out the random password. So my project let you to build a random password including any letter (capital or small), symbols, numbers.

## Issue Type:

- [ ] New Project

## **Additional context**
Created using HTML, CSS and JavaScript with better UI , able to copy the password to the clipboard, full responsiveness

## **Screenshots**

- Demo of my project
<img width="598" alt="Screenshot_20230128_041913" src="https://user-images.githubusercontent.com/101239757/215262797-4d7c79f1-8070-49d9-9603-c37d6bf2df5a.png">

**Comment by zugzwang03** [comment]
Already present project idea PR #411
