### ISSUE TITLE
Sorting Visualizer

### ISSUE THREAD

**Issue by codeburn12** [TusharKesarwani/Front-End-Projects#500]
## **Describe the project**
This project describes all the sorting algorithm in animation form

## Issue Type:

- [ ] New Project

## **Additional context**
Tech stack used :- HTML, CSS, JavaScript
<img width="945" alt="Screenshot_20230128_080852" src="https://user-images.githubusercontent.com/101239757/215272614-8cf75711-797e-4402-96dc-a358ce0a5299.png">

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
@codeburn12 Explain your idea

**Comment by codeburn12** [comment]
@Vanshiii203 Sorting visualizer shows pictorial representation of all the sorting algorithm like merge sort, bubble sort, selection sort, insertion sort, quick sort. The bars given will run and show how any sorting algorithm run when we run it . For example , in merge sort first elements divided in two parts, sorted then combine to form original array. this all will be shown by the bars.

**Comment by codeburn12** [comment]
@Vanshiii203 Bassically you can easily configure out how the algorithm run.

**Comment by codeburn12** [comment]
@Vanshiii203 Please alligned this project as it is most interesting project of DSA and it uses HTML, CSS, JS as tech stack.

**Comment by Vanshiii203** [comment]
@codeburn12 assigned to you. Make sure you only use html,css and js for your project

**Comment by nikhilsrv** [comment]
@TusharKesarwani please assign me this task.
