### ISSUE TITLE
Reverse text 

### ISSUE THREAD

**Issue by Sanya2911** [TusharKesarwani/Front-End-Projects#502]
**Describe the project**
A website that reverses the text added in the textbox.

**Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

**Additional context**
Add any other context or screenshots about the project here.

**Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by abhilipsasahoo03** [comment]
@Sanya2911 add a reference image or screenshot of your project.

**Comment by Sanya2911** [comment]
![image](https://user-images.githubusercontent.com/120942171/215332379-945783b3-cb65-44dd-a26f-d2eda1763985.png)

It is a reference of what I would like to create using HTML,CSS,JS etc.
The idea of this project is to create a website that generates a reverse text on entering it in a textbox .

**Comment by Sanya2911** [comment]
@TusharKesarwani can u please assign this issue ?
I'm a beginner
