### ISSUE TITLE
Web chat template

### ISSUE THREAD

**Issue by alisha722** [TusharKesarwani/Front-End-Projects#503]
## **Describe the project**
This project would be a real messaging website template like whatsapp web which would be developed with pure javascript without third-party library . All chats, messages, data would be fake and  would be generated with a data-factory. 

## Issue Type:

- [x] New Project

## **Additional context**
the project would be built by using only html , css and JS

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
Your issue is same as #300. If they fail to raise a PR it will be assigned to you
