### ISSUE TITLE
Simon Game

### ISSUE THREAD

**Issue by Ayu1C** [TusharKesarwani/Front-End-Projects#504]
## **Describe the project**
This project is Simon Game. It checks the player's memory power. The game has some buttons .As the game starts, the player has to press the corresponding button displayed .As the level proceeds, the player has to click all buttons in correct order starting from the level-1 , failing to which he loses the game.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**

Tech Stack used - HTML, CSS, JS, Jquery.

## **Screenshots**

![Screenshot (71)](https://user-images.githubusercontent.com/102305307/215286184-7532fbb3-afc9-4bc6-9c9c-92fa1afd2908.png)

![Screenshot (72)](https://user-images.githubusercontent.com/102305307/215286209-5d4b1c17-56e4-4a3e-a7d9-27aca92c4e78.png)

**Comment by Ayu1C** [comment]
@TusharKesarwani @Vanshiii203 Please check this issue and assign it to me.

**Comment by Vanshiii203** [comment]
A similar game already there in the repo
