### ISSUE TITLE
Reaction Tester App

### ISSUE THREAD

**Issue by Amit0412** [TusharKesarwani/Front-End-Projects#506]
## **Describe the project**
This app is the one which can capture the reaction time of any user. It is beginner friendly project and I will be making it using Html, Css and Js.Kindly assign me this issue.Thankyou

## Issue Type:

- [✔ ] New Project

**Comment by Vanshiii203** [comment]
Hey @Amit0412 can you explain how is it different from https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Emoji%20Rating

**Comment by Amit0412** [comment]
@Vanshiii203 , So basically the project link's that you shared that is telling about emotion..but mine project is sort of like mini game which will display the images on screen randomly the more earlier u click on it , it means you r more attentive and your reaction time to any object is less..The final output is time

**Comment by Amit0412** [comment]
@Vanshiii203 Pls assign me this issue.Thankyou
