### ISSUE TITLE
Step progress bar

### ISSUE THREAD

**Issue by Harikaraja** [TusharKesarwani/Front-End-Projects#507]
A step progress bar is used to track the progress at every step . Initially all the steps are incomplete when ever a task is completed then
it is marked and moved to next step.

![image](https://user-images.githubusercontent.com/80022302/215306022-04e5e30f-a9ee-448c-af1e-6eeec190f764.png)

**Comment by harshit-paneri** [comment]
What's there uses ?

**Comment by Harikaraja** [comment]
Sir actually it is used to display the progress of our work as displayed in
the image .

When we complete some task 1 then one tick wil be placed in that way I
guess it is useful

**Comment by harshit-paneri** [comment]
okay
