### ISSUE TITLE
Drum Kit

### ISSUE THREAD

**Issue by yashkhandelwal2203** [TusharKesarwani/Front-End-Projects#511]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.
This project is based on drum kit where preesing key will generate different sounds.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Uploading Screenshot 2023-01-29 122228.jpg…]()

**Comment by yashkhandelwal2203** [comment]
![Screenshot 2023-01-29 122228](https://user-images.githubusercontent.com/84733088/215310456-835cb8b8-485b-4580-a1df-66c0e84f1c0d.jpg)

**Comment by Vanshiii203** [comment]
This project is already present in the repo. If you have any idea or changes for the existing project you can create an issue for that.
