### ISSUE TITLE
dragon_fire_ocean_game

### ISSUE THREAD

**Issue by Hanshika-Mehta** [TusharKesarwani/Front-End-Projects#529]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by LiQuiD-404** [comment]
@Hanshika-Mehta Please provide some description of your project. If possible share some screenshots of your project for reference.

**Comment by Hanshika-Mehta** [comment]
Sorry for inconvinence  as I had my university exams due to which I could not  work on my issue . Kindly open the issue

**Comment by Hanshika-Mehta** [comment]
# Dragon Fire Ocean Game  #
### A modified game in which player will defeat computer to win the game.
```
- Player will choose either Dragon or Fire or Ocean

- Computer will randomly choose Dragon Or Fire or Ocean

- Conditions :-
    > If player chooses Dragon and computer also choose Dragon - Nullify

    >If player chooses Dragon and computer choose fire - Fire will burn dragon Hence -  Player LOOSE

    > If player  chooses Dragon and computer choose ocean - Dragon will swim in it  - Hence Player WINS

    > If player choose Ocean and computer choose Dragon - Dragon will swim in it -Hence Computer WINS

    >If player choose ocean and ocean - Nullify

    >If player choose ocean and computer choose fire - Ocean  wipe off the fire - Hence player WINS

    > If player choose Fire and computer choose Dragon - Fire will burn Dragon - Hence player WINS

    >If player choose fire and Computer choose ocean - ocean will wipe off Fire - Hence Computer WINS

    >If player choose fire and Computer choose Fire - Nullify
```
Player Target is To WIN the Game

```
 -- Tech stacks 
  > HTML
  > CSS
  > JavaScript
```
## Here are some screenshots of the game ##
### Image when a player loose a Game ###
![image](https://user-images.githubusercontent.com/90273801/221187740-b9975a17-7d23-4274-9f12-c6d2c197c942.png)


### Image when a player wins a Game ###

![image](https://user-images.githubusercontent.com/90273801/221187668-21c26e9d-7119-4c78-a2b9-57f813423658.png)
