### ISSUE TITLE
Fully responsive Blog website

### ISSUE THREAD

**Issue by charu1603** [TusharKesarwani/Front-End-Projects#547]
This is a fully responsive static blogging website made from scratch . 
Tech stack used :- HTML , CSS ,JAVASCRIPT 

Deployment link :-- (https://charu1603.github.io/blog-website/)

**Comment by charu1603** [comment]
I want to contribute on this issue under swoc Kindly assign this to me

**Comment by LiQuiD-404** [comment]
@charu1603 Assigned you the issue. Best of Luck ✨
