### ISSUE TITLE
SB UI KIT Clone Website

### ISSUE THREAD

**Issue by khushimarothi** [TusharKesarwani/Front-End-Projects#554]
## **Describe the project**
It is a clone of SB UI KIT Website . with a color customizer embeded.

## Issue Type:

- [x] New Project

**Comment by Vanshiii203** [comment]
Attach a refrence image of your project

**Comment by khushimarothi** [comment]
can I provide you the deployed link?

**Comment by khushimarothi** [comment]
https://khushimarothi.github.io/Project8/SB%20UI%20KIT%20PRO/Home.html

**Comment by khushimarothi** [comment]
I already made a pr for this. #555
