### ISSUE TITLE
Flower using HTML and CSS

### ISSUE THREAD

**Issue by ojasaklechayt** [TusharKesarwani/Front-End-Projects#556]
## **Describe the project**
Adding an flower made using HTML and CSS

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by ojasaklechayt** [comment]
@TusharKesarwani can you please check it ?

**Comment by Vanshiii203** [comment]
We are not accepting such projects

**Comment by ojasaklechayt** [comment]
> We are not accepting such projects

It's a pure CSS projects which can be counted in frontend projects.
