### ISSUE TITLE
Modern credit Card form Webpage

### ISSUE THREAD

**Issue by ashadmuneer** [TusharKesarwani/Front-End-Projects#558]
## **Describe the project**
I'd like to contribute a modern credit card form webpage created with HTML, CSS, and JavaScript. 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![Screenshot 2023-01-31 232214](https://user-images.githubusercontent.com/114468676/215842991-58a27d05-c6fa-42a4-b8a5-93194de5ae8c.jpg)

**Comment by codervivek5** [comment]
I want to work on this issue

**Comment by ashadmuneer** [comment]
@TusharKesarwani assign this to me

**Comment by ashadmuneer** [comment]
@Vanshiii203 pls assign this to me

**Comment by Bishal011** [comment]
Plz assign this to me
