### ISSUE TITLE
Dynamic quotes website with tweet button using JS

### ISSUE THREAD

**Issue by Harikaraja** [TusharKesarwani/Front-End-Projects#559]
In this project dynamic quotes will be generated form an API . And the generated quote can be posted on twitter with the tweet button available for the user.

**Comment by Vanshiii203** [comment]
A PR for quote genrator project is already been raised . Once it gets merged u can create an issue if you have any idea or changes for that project

**Comment by Harikaraja** [comment]
Ok mam
