### ISSUE TITLE
Service-providing-website

### ISSUE THREAD

**Issue by charu1603** [TusharKesarwani/Front-End-Projects#560]
This is a landing page of a service providing website made using react.js. This website provides service in different domains such as making porfolios and admin pane.

Tech stack:- React.js

Deployment link :- https://your-insightsinfo.netlify.app/

Screenshots:-
![Screenshot (225)](https://user-images.githubusercontent.com/96014425/216026016-304ff73e-6726-44c7-b15e-c9d26b65028d.png)
![Screenshot (228)](https://user-images.githubusercontent.com/96014425/216026396-8d5059e3-9930-448e-a771-5469a091b7b9.png)

**Comment by Vanshiii203** [comment]
We are not accepting React Projects
