### ISSUE TITLE
Simple Frontend Responsive Coffee Shop Website

### ISSUE THREAD

**Issue by tejasri415** [TusharKesarwani/Front-End-Projects#563]
## **Coffe Shop Website**
This is a coffee shop website using HTML,CSS,Javascript.

## Issue Type:

 
- [x] New Project

## **Features Added**
User gets to choose the type of coffee he can order.

User can book a table.

Menu availability.

Contact details.

Working hours.

**Comment by tejasri415** [comment]
Please assign this issue to me

**Comment by harshit-paneri** [comment]
Now we don't accept ecommerce website
