### ISSUE TITLE
Ballon Popping Game

### ISSUE THREAD

**Issue by tejasri415** [TusharKesarwani/Front-End-Projects#568]
## **Ballon Popping Game**
 A simple ballon popping game using javascript.

## Issue Type:
- [x] New Project

## Features I will be adding:
I am still workig on the project so can't provide screenshots of it, but I can tell about the features I will be adding.
The page contains ballons ,when user takes the mouse pointer or clicks the mouse , the ballon gets popped,User can also reload to refill all the ballons.

**Comment by tejasri415** [comment]
Please assign me this issue

**Comment by Anubhavgupta14** [comment]
Attach the Screenshot or giving more details about this project.

**Comment by tejasri415** [comment]
I am still workig on the project so can't provide screenshots of it, but I can tell about the features I will be adding.
The page contains ballons ,when user takes the mouse pointer or clicks the mouse , the ballon gets popped,User can also reload to refill all the ballons.

**Comment by Anubhavgupta14** [comment]
Ok
