### ISSUE TITLE
Improve the UI of Ecommerce Landing page

### ISSUE THREAD

**Issue by alisha722** [TusharKesarwani/Front-End-Projects#570]
**Is your feature request related to a problem? Please describe.**
As the page is not responsive and it has no javascript onclick function ,I want to change the whole UI of the website , add Javascript , make responsive put some hover effects for its smooth functioning for that e-commerce landing page which is already present in the repo.

**Describe the solution you'd like**
I want to give a new look to the Ecommerce Landing Page .

**Describe alternatives you've considered**
I will create this using Html,css and Javascript

**Additional context**
![Screenshot 2023-02-04 002014](https://user-images.githubusercontent.com/84632701/216683517-55d99f89-a457-420c-916b-15b3e19b0c9d.png)

**Comment by Anubhavgupta14** [comment]
Please mention the screenshots or more details, what the things you want to change ?

**Comment by alisha722** [comment]
> Please mention the screenshots or more details, what the things you want to change ?

I have attached a screenshot You can have a look at it .
