### ISSUE TITLE
Netflix Landing Page Clone

### ISSUE THREAD

**Issue by manisha-nair28** [TusharKesarwani/Front-End-Projects#572]
## **Describe the project**
 Netflix landing page UI using only HTML, CSS and JS

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![netflix](https://user-images.githubusercontent.com/109059571/216523726-de3528ca-ca17-432f-a269-d423b5eda7e9.png)

**Comment by Srishtihere** [comment]
Can you assign me this issue ??

**Comment by manisha-nair28** [comment]
Hey, I wanted to work on this issue. That's why I created this issue.

**Comment by Srishtihere** [comment]
oh okay cool

**Comment by Vanshiii203** [comment]
Someone Is already working on this issue. If they fail to raise a PR it will be assigned to you
