### ISSUE TITLE
Movie Site UI

### ISSUE THREAD

**Issue by MridulGupta007** [TusharKesarwani/Front-End-Projects#576]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
Movie site UI for bookings
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
Someone is already working on this issue
