### ISSUE TITLE
BMI Calculator App

### ISSUE THREAD

**Issue by Srishtihere** [TusharKesarwani/Front-End-Projects#578]
## **Describe the project**
I will be building a BMI calculator app using HTML, CSS and JAVASCRIPT

## Issue Type:
- [ ] New Project

## **Screenshots**

![Screenshot (15)](https://user-images.githubusercontent.com/74984515/216683463-b41fdcbb-1c69-450e-99f1-9dd0ceae6212.png)

My prescribed website will not be fully the same as I will be using the same idea but with a different UI and different approach to Javascript.

**Comment by Vanshiii203** [comment]
This project is already present in the repo
