### ISSUE TITLE
Bill split calculator which also includes tip

### ISSUE THREAD

**Issue by Srishtihere** [TusharKesarwani/Front-End-Projects#580]
## **Describe the project**
I would like to build a webapp using HTML,CSS and Javascript which will help calculate the bill split along with the extra tip which is to be individually given
## Issue Type:

- [ ] New Project

## **Additional context**

In the following screenshot, only the tip is calculated but I will be adding a section where the individual amount according to the input of the number of guests will also be added and THE UI will be more improved 

## **Screenshots**

-![Screenshot (16)](https://user-images.githubusercontent.com/74984515/216754369-cebc54ba-48a7-49b5-ba82-97371834569b.png)

**Comment by Vanshiii203** [comment]
this project is already present in the repo https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/bill%20tip%20calculator
