### ISSUE TITLE
Star Wars Product Slider

### ISSUE THREAD

**Issue by Bishal011** [TusharKesarwani/Front-End-Projects#582]
## **Describe the project
It is project on star wars products which are arranged in several  sildes.
It is made by using HTML+CSS+JS.

## Issue Type:

- [x] New Project

## **Additional context**
Please assign me this project under SWOC23.

## **Screenshots**

![star wars](https://user-images.githubusercontent.com/105370000/216769558-a6981140-34d1-4298-a223-432ccff72b80.jpeg)

**Comment by Bishal011** [comment]
Plz assign this to me

**Comment by Vanshiii203** [comment]
Now we are not accepting ecommerce projects

**Comment by Bishal011** [comment]
Ok
