### ISSUE TITLE
Expense Tracker

### ISSUE THREAD

**Issue by Harshit-Raj-14** [TusharKesarwani/Front-End-Projects#586]
I want to make an expense tracker HTML, CSS, Javascript

**Comment by Vanshiii203** [comment]
Attach a reference image for your project

**Comment by Harshit-Raj-14** [comment]
@Vanshiii203 The screenshot of the project I made: 
![Screenshot (130)](https://user-images.githubusercontent.com/98808802/216891160-22157b8a-b551-491f-8fa1-7acb58531f95.png)
