### ISSUE TITLE
Random Joke generator 

### ISSUE THREAD

**Issue by Srishtihere** [TusharKesarwani/Front-End-Projects#587]
## **Describe the project**
I would like to create a website which will consist of a generate buttons nd it will generate some random jokes and memes, using HTML, CSS and Javascript 

## Issue Type:

- [ ] New Project

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by LiQuiD-404** [comment]
@Srishtihere Assigned you the issue. Best of Luck ✨

**Comment by Vanshiii203** [comment]
Hey @Srishtihere  this project is already present in the repo https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Meme%20Generator
