### ISSUE TITLE
Image Editor

### ISSUE THREAD

**Issue by papri24majumder** [TusharKesarwani/Front-End-Projects#590]
**Is your feature request related to a problem? Please describe.**
No, it is not related to any problem.

**Describe the solution you'd like**
I want to create an image editor using HTML, CSS, and JavaScript.

**Describe alternatives you've considered**
No alternatives

**Additional context**
Nil

**Comment by Arun9739** [comment]
Go ahead @papri24majumder

**Comment by Vanshiii203** [comment]
This project is already present in the repo

**Comment by papri24majumder** [comment]
Ok, I am closing the issue.
