### ISSUE TITLE
Razorpay Clone

### ISSUE THREAD

**Issue by Amit0412** [TusharKesarwani/Front-End-Projects#593]
## **Describe the project**

Want to make clone of Razorpay website using Html, Css ,Node etc.Kindly assign me this issue.

## Issue Type:

- [ ✔] New Project

**Comment by Arun9739** [comment]
Go ahead @Amit0412

**Comment by Amit0412** [comment]
@Arun9739 @TusharKesarwani Please delete this issue. I am not willing to contribute in this. I am working on other issue's. Thankyou

**Comment by Arun9739** [comment]
@Amit0412 Keep the issue, anyone else may work on this.

**Comment by Amit0412** [comment]
@Arun9739 ok
