### ISSUE TITLE
Whatsapp UI clone

### ISSUE THREAD

**Issue by helloshiv01** [TusharKesarwani/Front-End-Projects#597]
Describe the project:
I Want to make Whatsapp UI clone using HTML,CSS

Issue Type:
[ ✔] New Project

**Comment by Vanshiii203** [comment]
Someone is already working on this issue. If they fail to raise a PR it will be assigned to you.

**Comment by helloshiv01** [comment]
last i checked there is no such issue can you mention it here

**Comment by Vanshiii203** [comment]
#503

**Comment by helloshiv01** [comment]
any update?
