### ISSUE TITLE
Sanskrit-Quiz Web App

### ISSUE THREAD

**Issue by Amit0412** [TusharKesarwani/Front-End-Projects#598]
## **Describe the project**
A web based application that takes quiz in Sanskrit language to check knowledge of people in Sanskrit.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ✔] New Project

Teck Stack: HTML, CSS and JavaScript

Kindly assign me this issue.

**Comment by Arun9739** [comment]
@Amit0412 Interesting !! Go ahead !
