### ISSUE TITLE
COVID-Detection-Tool

### ISSUE THREAD

**Issue by Amit0412** [TusharKesarwani/Front-End-Projects#599]
## **Describe the project**

This tool is designed for two kinds of user. One with Chest X-Ray scan reports and others without that.
For users with Chest X-Ray scan, we developed a Machine Learning Algorithm using Convolutional Neural Network to detect whether the user suffers from COVID or not. User needs to input his/her chest x-ray scan in the python application as input and a dialogue box appears as the output.
For users without chest x-ray scan, we built a website that takes symptoms from the user and based upon those symptoms, the tool detects the probability of user suffering from COVID and provides them with necessary further steps and diet charts.

## Issue Type:

- [X] New Project

## **Additional context**

For Chest X-Ray scan based application: Python, ML, Tensorflow, CNN, WX
For Symptoms based website: HTML, SCSS, BootStrap, JavaScript

**Comment by Vanshiii203** [comment]
Hey @Amit0412 we are not accepting python projects
