### ISSUE TITLE
Book purchasing website

### ISSUE THREAD

**Issue by alisha722** [TusharKesarwani/Front-End-Projects#608]
**Is your feature request related to a problem? Please describe.**
No , I want to design a book purchasing website in which user can purchase book of his/her interest . It would have different features like add to cart , books available for different subjects .

**Describe the solution you'd like**
I would like to design it using html , css and js .

**Describe alternatives you've considered**
no , can use bootstrap if required

**Additional context**

**Comment by alisha722** [comment]
Please assign me this

**Comment by alisha722** [comment]
@Vanshiii203

**Comment by Vanshiii203** [comment]
Now, we are not accepting e-commerce projects
