### ISSUE TITLE
Digitalclock and calculator,Snakegame

### ISSUE THREAD

**Issue by DinkyRajpoot56** [TusharKesarwani/Front-End-Projects#609]
## **Describe the project**
I have created a weather app,todoapp,digitalclock,digitalcalculator,snakegame,dinogame to this featured project in TusharKesharwaniFeaturedprojects

## Issue Type:Please add weather app,todo app,digitalclock,digitalcalculator in this projecrt in featured project

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
All these projects are already present in the repo. If you have any idea or changes for them you can create an issue for that or create your own unique issue
