### ISSUE TITLE
Anime Website

### ISSUE THREAD

**Issue by Srishtihere** [TusharKesarwani/Front-End-Projects#615]
## **Describe the project**
An Anime themed website consisting of details of several characters and different animes will be mentioned. I will be made using React.js and react-strap

## Issue Type:

- [ ] New Project

## **Additional context**

I will be making the home page mainly which will have a search bar and type dropdown to mention to whether search about anime or a character

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
We are not accepting React Projects

**Comment by Srishtihere** [comment]
Then maybe using HTML, CSS and JS

**Comment by TusharKesarwani** [comment]
> Then maybe using HTML, CSS and JS

Go ahead
