### ISSUE TITLE
Digital agency Website Template

### ISSUE THREAD

**Issue by alisha722** [TusharKesarwani/Front-End-Projects#618]
## **Describe the project**
I want to design a digital agency website template which would have different features like Home , about , services , blog and contact us and it would be responsive 

## Issue Type:

- [x] New Project

## **Additional context**
I will design it using html , css and Javascript

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Arun9739** [comment]
@alisha722 Go ahead !
