### ISSUE TITLE
Weather app.

### ISSUE THREAD

**Issue by Vatsalmadhur** [TusharKesarwani/Front-End-Projects#619]
## **Describe the project**
A simple app that will show current weather details.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vatsalmadhur** [comment]
Please assign me this issue.

**Comment by Arun9739** [comment]
@Vatsalmadhur The weather website is alreday present. Plz look for other idea or develop the currently present website by creating new issue.
