### ISSUE TITLE
chatBot 

### ISSUE THREAD

**Issue by NaMiKA0305** [TusharKesarwani/Front-End-Projects#620]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [it is a chatbot created by html css js ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Arun9739** [comment]
@NaMiKA0305 There is already a chatbot project. You can come up with new idea or improve the already present project by creating a new issue.
