### ISSUE TITLE
Food Website Landing Page

### ISSUE THREAD

**Issue by sumitkr2000** [TusharKesarwani/Front-End-Projects#621]
## **Describe the project**
Hey, @TusharKesarwani  I want to add a landing page for a food website created using HTML, CSS, and javascript. Please assign me this issue. Thank you!

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
.

## **Screenshots**

![218267409-6d89f821-a787-4b6e-9a81-2e15e6001dd0](https://user-images.githubusercontent.com/100675296/218306506-2acd5c67-6e48-4ef5-b79c-5ef9d91a1091.png)

**Comment by Vanshiii203** [comment]
This project is already present in the repo

**Comment by sumitkr2000** [comment]
@Vanshiii203 but its totally different from the one that is present in the repo.

**Comment by Vanshiii203** [comment]
You can create an issue for improvements in the existing project

**Comment by sumitkr2000** [comment]
@Vanshiii203 leave it :(

**Comment by sumitkr2000** [comment]
bhot mehnat se banaya tha
