### ISSUE TITLE
HeartTrailAnimation

### ISSUE THREAD

**Issue by DeepanshiShimar** [TusharKesarwani/Front-End-Projects#625]
## **Describe the project**
Heart Trail Animation is an interactive animation that is built using HTML, CSS, and JavaScript, and it creates a mesmerizing trail of hearts wherever your cursor moves. The hearts are created in real-time as you move your cursor across the screen, creating a unique and personalized experience every time. The animation is designed to be lightweight and efficient, making it perfect for adding a touch of love and magic to any website or project. Whether you're looking to create a romantic atmosphere or simply want to show your appreciation for love, this heart trail animation is the perfect choice. Try it out today and spread the love! 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![image](https://user-images.githubusercontent.com/103559339/218415322-9d673669-0bd5-416a-acb4-f1c542b30bc8.png)

## Additional info
I would like to work on this issue.

**Comment by Vanshiii203** [comment]
We are not accepting such projects
