### ISSUE TITLE
memory game

### ISSUE THREAD

**Issue by NaMiKA0305** [TusharKesarwani/Front-End-Projects#626]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:
can i add a game of card flipping....

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ c] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
This project is already present in the repo
