### ISSUE TITLE
Finance dashboard

### ISSUE THREAD

**Issue by ansharora28** [TusharKesarwani/Front-End-Projects#63]
A financial dashboard to upskill your financial knowledge,get latest news,check real time crypto prices all in one platform.

Tech stack- HTML,CSS ,JS

**Comment by abhilipsasahoo03** [comment]
@ansharora28 are you working on this issue? If so, please create a PR and link the issue to it. If not, please let us know so that we can assign someone else willing to work on it.

**Comment by ansharora28** [comment]
Hi, I would not be able to work on this due to some commitments. You may assign it to someone else.Thanks!

**Comment by abhilipsasahoo03** [comment]
> Hi, I would not be able to work on this due to some commitments. You may assign it to someone else.Thanks!

Okay then I'm closing the issue!
