### ISSUE TITLE
Added a Productivity App - Chillmate

### ISSUE THREAD

**Issue by AmitSahoo45** [TusharKesarwani/Front-End-Projects#633]
## **Describe the project**
This will be a productivity app in which the client can create his/her relaxing environment using the various sounds provided by the app which include Rain, Camp Fire, Waves, Thunder, City Noise, Birds Chirping, Flowing Wind, etc. Other than that the user can also create ToDo List and Pomodoro

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
<img width="941" alt="image" src="https://user-images.githubusercontent.com/72258273/219826312-5e13626d-756f-43ab-8dae-7824225b74a8.png">
<img width="935" alt="image" src="https://user-images.githubusercontent.com/72258273/219826332-18be9658-b200-4bbe-97ef-8a08f9e22076.png">

This project is made using Next.js and Tailwind CSS
- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
We are only accepting projects of html, css and js
