### ISSUE TITLE
Demo Travel Website

### ISSUE THREAD

**Issue by ShivankK26** [TusharKesarwani/Front-End-Projects#634]
## **Describe the project**
In this Project, I've built a Demo Website using Bootstrap 5, HTML, and CSS. It is a Simple Website with a lot of features which the user can explore.

This website can be used for various purposes like making a personal portfolio or a travel website.

The link of the project is: https://shivankk26.github.io/Demo-Travel-Website/

**Comment by Vanshiii203** [comment]
This seems to be a generic template for a website. There are many such projects already present in the repo
