### ISSUE TITLE
Snack Login Form

### ISSUE THREAD

**Issue by vimarsh11** [TusharKesarwani/Front-End-Projects#636]
https://user-images.githubusercontent.com/104987339/219885198-11631d16-8dbf-44e7-918a-c08a30bd2386.mp4

## **Describe the project**
To create login form using HTML, CSS and JS with snack animation.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by harsh5902** [comment]
upload the screenshots

**Comment by vimarsh11** [comment]
> upload the screenshots

done

**Comment by Vanshiii203** [comment]
A login form project is already present in the repo
