### ISSUE TITLE
Online Food Ordering Website

### ISSUE THREAD

**Issue by DinkyRajpoot56** [TusharKesarwani/Front-End-Projects#643]
## **Describe the project**
It's a online food ordering website created through HTML,CSS and javascript.

## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.
Watch it at Loom
https://www.loom.com/share/5bc1b79a19f644a0997d8a28874dac6a

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
- 
![Screenshot (445)](https://user-images.githubusercontent.com/111672121/220118289-6a8c4ff0-92b7-44c1-8679-29c87c7cac8a.png)

![Screenshot (446)](https://user-images.githubusercontent.com/111672121/220118320-91510ee5-1a00-4ad2-bd35-eb04dcd0d173.png)
![Screenshot (447)](https://user-images.githubusercontent.com/111672121/220118371-a4c21d1c-02b9-48d0-8f65-a5e6b5c6a9c6.png)
![Screenshot (448)](https://user-images.githubusercontent.com/111672121/220118400-31dfff63-d74e-4dab-8824-63940969db57.png)
![Screenshot (449)](https://user-images.githubusercontent.com/111672121/220118428-497f08fa-1ebd-4da2-97ba-d81c8e1ca838.png)

**Comment by Vanshiii203** [comment]
This project is already present in the repo
