### ISSUE TITLE
I want to add "Zomato UI Clone Project" into your Repo as a"SWOC 3.0" Contribution .

### ISSUE THREAD

**Issue by vikastripathi707** [TusharKesarwani/Front-End-Projects#644]
## **Describe the project**
This is a FrontEnd Project which is Basically a Landing Page of Zomato.
This is made up with "HTML5, CSS3" and this is Responsive Project which makes it suitable for all Screen Devices such as Laptops, and Mobile-Phones.
 I want to contribute in "Social Winter of Code 3.0" So kindly assign this to me and mark it as SWOC3.0 
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [x] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
![image](https://user-images.githubusercontent.com/86002620/220255496-9577d100-e748-464c-bda3-1223ee88637a.png)

- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
This project is already present in the repo
