### ISSUE TITLE
I want to add "Temperature Converter" Project into your Repo under SWOC3.0

### ISSUE THREAD

**Issue by vikastripathi707** [TusharKesarwani/Front-End-Projects#646]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
This Project can convert "Temp. of one Degree into another Degree" and this is Responsive too.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
It is made up using HTML CSS JS.
Add any other context or screenshots about the project here.

## **Screenshots**
![image](https://user-images.githubusercontent.com/86002620/220584919-1aeb4bbe-9730-4f1c-8704-549aacc84323.png)

- If applicable, add screenshots to help explain your problem.

**Comment by vikastripathi707** [comment]
Please assign this to me!!

**Comment by Vanshiii203** [comment]
This project is already present in the repo
