### ISSUE TITLE
I want to add "Password Generator FrontEnd Project" into Your Repo.

### ISSUE THREAD

**Issue by vikastripathi707** [TusharKesarwani/Front-End-Projects#647]
## **Describe the project**
It is madeup using HTML_CSS_JAVASCRIPT

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

![image](https://user-images.githubusercontent.com/86002620/220597486-107f4443-b359-467d-8de1-8809f0a6896e.png)

**Comment by vikastripathi707** [comment]
Pls assign this to me!!

**Comment by Vanshiii203** [comment]
This project is already present in the repo
