### ISSUE TITLE
I want to add a webpage to track crypto currency using api and react.js

### ISSUE THREAD

**Issue by Nikhil1601** [TusharKesarwani/Front-End-Projects#648]
## **Describe the project**
Want to add a project in react.js which you can track current price of cryptocurrency using API's

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [1 ] New Project

## **Additional context**
Add any other context or screenshots about the project here.
![Screenshot_20230202_092300](https://user-images.githubusercontent.com/90842808/220712368-61079824-9c11-4a54-a506-9c44eece8bf9.png)

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Nikhil1601** [comment]
i want to contribute to your repo under SWOC3.0

**Comment by Vanshiii203** [comment]
We are not accepting React Projects
