### ISSUE TITLE
Postal code using Java Script

### ISSUE THREAD

**Issue by Harikaraja** [TusharKesarwani/Front-End-Projects#651]
**Is your feature request related to a problem? Please describe.**
Postal code application is used to search for all the locations that are having the postal code entered by the user. Here the user should enter the postal code in the given search box and click on search button , then all the areas/locations under the mentioned postal pin will be displayed. 

**Describe the solution you'd like**
I would like to use an API for this purpose.

**Comment by Vanshiii203** [comment]
This project is already present in the repo
https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Pincode%20checker
