### ISSUE TITLE
Spiderman

### ISSUE THREAD

**Issue by sumitkr2000** [TusharKesarwani/Front-End-Projects#664]
## **Describe the project**
Hey, @TusharKesarwani  I want to add a project which is created using HTML, CSS, and javascript. Please assign me this issue. Thank you!

## Issue Type:

- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![spiderman](https://user-images.githubusercontent.com/100675296/221918165-3e87522f-4681-4285-b3ed-f8785c8712ce.png)

**Comment by Vanshiii203** [comment]
Explain your idea in detail

**Comment by sumitkr2000** [comment]
It is a very simple project made using HTML CSS and jquery.
