### ISSUE TITLE
Crypto Tracker App

### ISSUE THREAD

**Issue by ShivankK26** [TusharKesarwani/Front-End-Projects#665]
## **Describe the project**
It is a website which tracks the value of various crypto currencies at the present moment. It also tells if their value is appreciating or depreciating.

Website Link:

https://shivankk26.github.io/Crypto-Tracker-App/

**Comment by Vanshiii203** [comment]
This project is already present in the repo
https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Crypto%20Dashboard
