### ISSUE TITLE
I would like to create a Recipe webiste using mealdb API

### ISSUE THREAD

**Issue by Keegan-20** [TusharKesarwani/Front-End-Projects#670]
## **Describe the project**
 I would like to create a Recipe website that allows you to search for specific dishes and view their respective recipes along with quantity for ingredits. it will also show the region where the dish is originated from.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
This project is already present in the repo

**Comment by Keegan-20** [comment]
Could u provide me the issue number? Just to check out

**Comment by TusharKesarwani** [comment]
> Could u provide me the issue number? Just to check out

Recipe website is already present in the repo
Create unique projects and raise issue according to that
