### ISSUE TITLE
Movie Guide App

### ISSUE THREAD

**Issue by ShivankK26** [TusharKesarwani/Front-End-Projects#672]
## **Describe the project**
In this Project, I've built a Movie Guide App using omdb API through which you can search for any movie and get all the information related to it. The Tech Stacks used are: HTML, CSS, JavaScript.

## **Screenshots**
![Screenshot 2023-03-04 at 12 55 54 AM](https://user-images.githubusercontent.com/115289871/222809243-be5aaf63-2c21-4014-babd-4cbe1d3dcb82.png)

**Comment by Vanshiii203** [comment]
This project is already present in the repo
