### ISSUE TITLE
Dynamic Star Rating

### ISSUE THREAD

**Issue by vimarsh11** [TusharKesarwani/Front-End-Projects#675]
## **Describe the project**
I want to create Dynamic Star Rating using HTML, CSS and JS.
so, please assign me this project.

## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot 2023-03-05 131650](https://user-images.githubusercontent.com/104987339/222948492-1dc4a946-f546-4903-a5de-50a258774717.png)

**Comment by Vanshiii203** [comment]
We are not accepting such projects
