### ISSUE TITLE
SPOTITY CLONE

### ISSUE THREAD

**Issue by DHRUVKHANDELWAL00** [TusharKesarwani/Front-End-Projects#680]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
I would be using react and css to make a spotify clone. 
## Issue Type:

- [x] Bug Report
- [x] Feature Request
- [x] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by DHRUVKHANDELWAL00** [comment]
hey @TusharKesarwani  assign me usnder swoc

**Comment by Vanshiii203** [comment]
this project is already present in the repo
