### ISSUE TITLE
<Open graph image>

### ISSUE THREAD

**Issue by Nakamcode** [TusharKesarwani/Front-End-Projects#691]
**Is your feature request related to a problem? Please describe.**
An Open Graph image is an image that is associated with a webpage and is used when the webpage is shared on social media platforms like Facebook, Twitter, LinkedIn, etc. Open Graph images are also called social sharing images or social media images.

**Describe the solution you'd like**
Create an Open Graph image. 
having an open graph image increases the click-through rate of a website link when share across social media.

**Comment by Vanshiii203** [comment]
Add a reference image for your project

**Comment by Nakamcode** [comment]
Ok, I will work on it
