### ISSUE TITLE
Memory Card Game

### ISSUE THREAD

**Issue by vimarsh11** [TusharKesarwani/Front-End-Projects#693]
## **Describe the project**
I want to create Memory Card Game using HTML, CSS and Js.
please assign it .

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vanshiii203** [comment]
This project is already present in the repository. Also, we are not accepting gaming-related projects anymore.
