### ISSUE TITLE
My personal Portfolio Website

### ISSUE THREAD

**Issue by Diptamoy-Mitra** [TusharKesarwani/Front-End-Projects#694]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
![Screenshot (32)](https://user-images.githubusercontent.com/91617575/224529040-ade89410-b956-4750-a0c1-9c187e274258.png)

- If applicable, add screenshots to help explain your problem.

**Comment by Diptamoy-Mitra** [comment]
Kindly Assign me

**Comment by TusharKesarwani** [comment]
Check pinned messages on the discord group then create issues
