### ISSUE TITLE
Insect Catch Game

### ISSUE THREAD

**Issue by vimarsh11** [TusharKesarwani/Front-End-Projects#695]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot 2023-03-12 121918](https://user-images.githubusercontent.com/104987339/224529124-94a96f9c-60f9-4940-a152-fa5e2c851310.png)
![Screenshot 2023-03-12 121826](https://user-images.githubusercontent.com/104987339/224529128-94b9b971-d079-4540-a96e-13e7f75e5c54.png)
![Screenshot 2023-03-12 121745](https://user-images.githubusercontent.com/104987339/224529129-24f3fc2c-f239-4614-890e-1971905cba50.png)

**Comment by Vanshiii203** [comment]
We are not accepting gaming-related projects anymore.
