### ISSUE TITLE
Feedback Ui design

### ISSUE THREAD

**Issue by vimarsh11** [TusharKesarwani/Front-End-Projects#697]
## **Describe the project**
I want to create Feedback Ui design using HTML, CSS and Js.
please assign this.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot 2023-03-14 184053](https://user-images.githubusercontent.com/104987339/225011917-94632626-94c3-457d-90f3-ce9642509296.png)
![Screenshot 2023-03-14 184018](https://user-images.githubusercontent.com/104987339/225011931-ce525aac-8b57-4581-8e8f-5167f6aa6ecb.png)

**Comment by TusharKesarwani** [comment]
Attach screenshot of the project

**Comment by vimarsh11** [comment]
> Attach screenshot of the project

@TusharKesarwani done!
![Screenshot 2023-03-14 184053](https://user-images.githubusercontent.com/104987339/225011583-054ce378-8de9-4b33-8444-abb26f7bed7b.png)
![Screenshot 2023-03-14 184018](https://user-images.githubusercontent.com/104987339/225011590-3d89400f-146e-4dff-b2e1-7a1c72e55765.png)
