### ISSUE TITLE
Auto Text Speed Controller

### ISSUE THREAD

**Issue by vimarsh11** [TusharKesarwani/Front-End-Projects#698]
## **Describe the project**
I want to create Auto Text Speed Controller using HTML, CSS and Js.
Please assign it to me.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot 2023-03-14 184646](https://user-images.githubusercontent.com/104987339/225012905-713ec7a0-0e87-4e49-a1a1-df70bc0001d3.png)

**Comment by TusharKesarwani** [comment]
Attach screenshot of the project

**Comment by vimarsh11** [comment]
> Attach screenshot of the project

@TusharKesarwani Done!
