### ISSUE TITLE
Tindog website using bootstrap

### ISSUE THREAD

**Issue by ManavLohia945** [TusharKesarwani/Front-End-Projects#7]
So this is one of my recent projects which I would like to contribute to this repository as a part of Social winter of code(SWOC). The website is build using Html,Css and bootstap. So for some elements I have used CSS to make it more attractive. And I have used Bootstrap carousel, Bootstrap cards and the bootstrap grid.

**Comment by ManavLohia945** [comment]
So sir you can assign me this issue now!!

**Comment by TusharKesarwani** [comment]
Go ahead @ManavLohia945
