### ISSUE TITLE
Vertical Card Sliding Animation

### ISSUE THREAD

**Issue by Abhi270303** [TusharKesarwani/Front-End-Projects#701]
## **Describe the project**
Vertical Card Sliding Animation using only HTML & CSS

## Issue Type:

- [ ] New Project

## **Additional context**
In this Vertical Card Slider Animation, there are five minimal cards with profile image, username, user profession, and a follow button. All these cards slide vertically and appear one by one. On the webpage, there are only three cards that appear out of five, and only the center one card has full opacity.

**Comment by TusharKesarwani** [comment]
Already present in the repo
