### ISSUE TITLE
A Markdown Blog/Note Editor

### ISSUE THREAD

**Issue by vedprakashnautiyal** [TusharKesarwani/Front-End-Projects#702]
## **Describe the project**
A blog/note editor that also supports markdown editing for all the bloggers out there.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
I would like to work on this issue under SWOC 3.0, please assign it to me at the earliest. This project also has a well written documentation for the other contributors to contribute to later. Thanks

## **Screenshots**
<img width="1680" alt="Screenshot 2023-03-13 at 8 03 02 AM" src="https://user-images.githubusercontent.com/71223796/224595420-f65aef38-63b0-4a04-9276-83fcaf1a2410.png">
<img width="1680" alt="Screenshot 2023-03-13 at 8 03 07 AM" src="https://user-images.githubusercontent.com/71223796/224595451-40cfcea0-d599-4fbe-ac0b-da574e8e1295.png">
<img width="1680" alt="Screenshot 2023-03-13 at 8 03 10 AM" src="https://user-images.githubusercontent.com/71223796/224595458-a4d8f9f1-619f-4602-82d6-fa3785debdd1.png">

## **Working Explanation**
 

https://user-images.githubusercontent.com/71223796/224595747-3a66a199-fe0e-4041-817a-14e2b75a6cd4.mov

**Comment by TusharKesarwani** [comment]
Already present in the repo

**Comment by vedprakashnautiyal** [comment]
Okay..
