### ISSUE TITLE
Particles Button

### ISSUE THREAD

**Issue by vimarsh11** [TusharKesarwani/Front-End-Projects#707]
## **Describe the project**
I want to create Particles Button using HTML, CSS, and Js.
Please assign it to me.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/104987339/225016096-5b097655-41b2-49d8-ab9e-b95de8b34c56.mp4

**Comment by TusharKesarwani** [comment]
You shouldn't work on this type of project 
We accept only creative webpages
