### ISSUE TITLE
Split Landing Page

### ISSUE THREAD

**Issue by vimarsh11** [TusharKesarwani/Front-End-Projects#710]
## **Describe the project**
I want to create Split Landing Page using HTML, CSS, and Js.
A split landing page, also known as an A/B test landing page or a multivariate landing page, is a web page that has been designed to test different versions of the same content or elements. The page is split into multiple versions, with each version containing a different variation of the design, copy, layout, or call-to-action. They can also be used in website optimization to increase the effectiveness of a website's overall design and user experience.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot 2023-03-15 011350](https://user-images.githubusercontent.com/104987339/225119349-ac545bc5-6650-4485-85be-cdc74f555681.png)
![Screenshot 2023-03-15 011305](https://user-images.githubusercontent.com/104987339/225119362-bc4f9e32-557f-41f6-b709-5489653fcba1.png)

**Comment by TusharKesarwani** [comment]
Describe your project
