### ISSUE TITLE
Add a Notes Making App

### ISSUE THREAD

**Issue by Swap-nil-2003** [TusharKesarwani/Front-End-Projects#716]
## **Describe the project**
A notes making app made with HTML,CSS and Vanilla JavaScript. Local storage has been used to save the notes on the browser, once created.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

![Screenshot (70)](https://user-images.githubusercontent.com/93329536/232197077-1c86db5f-d5c8-4f93-9299-685d52a573f1.png)

**Comment by TusharKesarwani** [comment]
Go ahead
