### ISSUE TITLE
Login Page Glassmorphism Design

### ISSUE THREAD

**Issue by MohamedMafaz** [TusharKesarwani/Front-End-Projects#718]

**Comment by TusharKesarwani** [comment]
Add screenshot of the project

**Comment by MohamedMafaz** [comment]
![Screenshot (121)](https://user-images.githubusercontent.com/113255500/233385023-e3118a55-ef35-411b-9736-502242827c8b.png)

**Comment by TusharKesarwani** [comment]
Go ahead
