### ISSUE TITLE
DSA Coach - A DSA practicing website

### ISSUE THREAD

**Issue by Sampad-Adhikary** [TusharKesarwani/Front-End-Projects#719]
## **Describe the project**
DSA Coach is a progress tracker and manager for all the college students and professionals who are willing to learn Data Structures and Algorithm they can visit this website. It has Love Babbar's sheet of 450 DSA questions. The website is up and running. I am planning to add features like:
1. Progress tracker
2.  streaks
3. Let user uplaod their own set of questions and then practice, so that they can follow any sheet they want.
Currently it is a frontend Project built with React, but I will convert it into a MERN stack application.

## Issue Type:

- [ ] New Project

## **Screenshots**
![Screenshot (43)](https://user-images.githubusercontent.com/71624934/233567790-5a1c956d-bd68-44bf-b6d5-df57e21e4ed7.png)
![Screenshot (42)](https://user-images.githubusercontent.com/71624934/233567801-f882407a-cb55-4673-bf02-4942368a1bb8.png)
![Screenshot (41)](https://user-images.githubusercontent.com/71624934/233567809-c813696c-2674-4d0a-b78c-f46e5f587b24.png)
![Screenshot 2023-04-21 124601](https://user-images.githubusercontent.com/71624934/233567813-ce697435-0ded-4811-be85-e365f2321078.png)

- If applicable, add screenshots to help explain your problem.

**Comment by TusharKesarwani** [comment]
Go ahead

**Comment by Sampad-Adhikary** [comment]
I have made the PR kindly preview

**Comment by TusharKesarwani** [comment]
> I have made the PR kindly preview

Ok I will review it soon

**Comment by princekumarg** [comment]
Assigne the issues
