### ISSUE TITLE
ccalculator problem take two operation at the time

### ISSUE THREAD

**Issue by mkos11** [TusharKesarwani/Front-End-Projects#725]
**Is your feature request related to a problem? Please describe.**
Ned to add only one operation after Number is put
**Describe the solution you'd like**
only put one operatin after one number
![Screenshot 2023-05-17 234033](https://github.com/TusharKesarwani/Front-End-Projects/assets/84587772/23d1aa94-ea00-4f3f-bc12-84a50a8778e6)

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/84587772/d12077f3-ddee-45df-acc0-6d81e99a6ce1)
![Screenshot 2023-05-17 234033](https://github.com/TusharKesarwani/Front-End-Projects/assets/84587772/9a170c61-d4f6-4a30-9330-317ac3f667f3)

**Comment by priyanshu2k3** [comment]
hey can you assign this to me

**Comment by SaiAryan1784** [comment]
can i work on this issue?

**Comment by SomilRathore01** [comment]
Hey! @TusharKesarwani I would like to resolve this issue, so please assign this task to me as it will help me to increase my score in SSOC'23.

**Comment by TusharKesarwani** [comment]
Create the fresh issue after 1st June

**Comment by Abhishantpadam** [comment]
OK i will create a fresh issue on June 1st  and also send the pull request for that issue also.
