### ISSUE TITLE
Guess The Number Game

### ISSUE THREAD

**Issue by shantanunautiyal** [TusharKesarwani/Front-End-Projects#726]
![game](https://github.com/TusharKesarwani/Front-End-Projects/assets/56751285/a904c41d-2c75-4444-be69-b968fa081cf4)

**Comment by devender15** [comment]
Hello, i didn't get what's the issue here?

**Comment by Mani1881** [comment]
hey @shantanunautiyal i want to change background colour.will u please assign this to me?
