### ISSUE TITLE
Footer Section

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [TusharKesarwani/Front-End-Projects#729]
I want to enhance the footer now it is simple but i can make it good please assign this to me under SSOC

**Comment by Kali-Decoder** [comment]
Can i take this

**Comment by MeenuyD** [comment]
I would like to work on this assign it to me ssoc

**Comment by SomilRathore01** [comment]
Hey! @TusharKesarwani, I would like to work on this issue as I am competing in SSOC'23 and I will enhance the UI/UX design of footer section.

**Comment by sumit851** [comment]
hey can you assign this issue under ssoc 2023

**Comment by chaitanyarai19** [comment]
Hi @TusharKesarwani, 
As a participant of the SSOC 2023 program kindly consider me for this issue because I have experience in web design, frontend development, and user interface enhancement.

**Comment by Ayushmaan-dev** [comment]
Hey I can handle this issue easily I have experience in UX and web dev

**Comment by 07-Atharv** [comment]
Hey @TusharKesarwani 
Will you assign these task to me ??

**Comment by TusharKesarwani** [comment]
Create the fresh issue after 1st June
