### ISSUE TITLE
I want to add a "About us" section on this website.

### ISSUE THREAD

**Issue by Praveenkumar07007** [TusharKesarwani/Front-End-Projects#731]
![about us section](https://github.com/TusharKesarwani/Front-End-Projects/assets/115071711/708a57a6-a577-4d96-b8ac-93fb84a45cfe)

### >I want to add about us section using html and css .

>The about us section could be implemented by adding a new page to the website or by adding a section to the footer. The section could include the following information:
1.Company name
2.Mission statement

>I believe that adding an about us section to the website would be a valuable addition that would benefit both the company and its customers.

>Thank you for your consideration.

**Comment by ano1herengineer** [comment]
I would like to work on this issue, please assign this issue to me

**Comment by Kali-Decoder** [comment]
Can i take this

**Comment by SomilRathore01** [comment]
Hey! @TusharKesarwani, I would like to contribute in this issue, so please assign this issue to me for competing in SSOC'23.

**Comment by Praveenkumar07007** [comment]
Hey! @TusharKesarwani , I have resolve this issue and pull requested have not done yet could you please review this issue .
