### ISSUE TITLE
Improvement : Enhance UI and User Experience of "Dynamic js Quiz" Project

### ISSUE THREAD

**Issue by Divyanshu9822** [TusharKesarwani/Front-End-Projects#733]
### Overview
The current state of the Quiz project's UI and user experience is suboptimal and could benefit from significant improvements. This issue aims to address the following areas of concern: enhancing the visual design, improving the layout and alignment, fixing the behaviour of radio buttons, and overall refining the user experience.

### Current State : 
[![](https://user-images.githubusercontent.com/95610027/214227368-5a49d70c-c101-4eb8-aee5-7dad0a60dcee.png)
](url)

**Comment by Divyanshu9822** [comment]
### Assign this raised issue to me under SSoC '23 as I can solve it by doing following explained process  

### How I will do it (Expected Changes)

1.  Visual Design:

- Revise the CSS to create an appealing and visually consistent design.
- Optimize the color scheme, typography, and overall styling to ensure readability and aesthetic appeal.
- Apply suitable spacing and alignment to enhance the visual hierarchy and organization of elements.

2. Radio Buttons:
- Radio button should be hidden to make it more attractive.

3. Code Refactoring:
- I will evaluate the existing codebase and refactor the CSS and HTML as needed.
- Optimize code structure and eliminate any redundant or unnecessary code to enhance maintainability and performance.

**Comment by SomilRathore01** [comment]
Hey! @TusharKesarwani please assign this issue to me for competing in SSOC'23. I will enhance UI/UX of this project.

**Comment by Divyanshu9822** [comment]
😗 go find your own issue and do that ..don't just jump in other's

**Comment by Divyanshu9822** [comment]
### Hey! @TusharKesarwani  Assign this raised issue to me under SSoC '23 as I have looked into this problem and I believe I can solve it by doing following explained process

How I will do it (Expected Changes)

1. Visual Design:
- Revise the CSS to create an appealing and visually consistent design.
- Optimize the color scheme, typography, and overall styling to ensure readability and aesthetic appeal.
- Apply suitable spacing and alignment to enhance the visual hierarchy and organization of elements.

2. Radio Buttons:
- Radio button should be hidden to make it more attractive.
3. Code Refactoring:
- I will evaluate the existing codebase and refactor the CSS and HTML as needed.
- Optimize code structure and eliminate any redundant or unnecessary code to enhance maintainability and performance.

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
