### ISSUE TITLE
Projects card's enhancement

### ISSUE THREAD

**Issue by jainamthakkar** [TusharKesarwani/Front-End-Projects#734]
**Describe the bug**

The first thing is to increase font size in cards
second is to provide margin between technology's name 
and we can give some border radius and and shadow to these cards of products

**Screenshots**

![Screenshot (522)](https://github.com/TusharKesarwani/Front-End-Projects/assets/105544028/de89f675-0a8d-499c-86b0-64d779a7cae3)

**Comment by Aarize29** [comment]
I would like to take ownership of this issue and work on implementing the necessary changes. Please assign it to me, and I'll start working on it right away.

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
