### ISSUE TITLE
Top News Headlines

### ISSUE THREAD

**Issue by Rishav1707** [TusharKesarwani/Front-End-Projects#736]
## **Describe the project**
Introducing a dynamic news website that brings you the latest and most relevant news stories from around the world in real-time. With the use of a cutting-edge news API, this website ensures that you stay up-to-date with the most current headlines from various reputable news sources. Whether it's breaking news, politics, sports, or entertainment, this website is your go-to destination for all the latest happenings from across the globe. Stay informed and ahead of the curve with our constantly updating news feed, available to you 24/7.

## Issue Type:
- [x] New Project

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/97666287/03189946-56bb-4ccd-b5f0-f2d374eff86d)

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
