### ISSUE TITLE
Random Quote Generator

### ISSUE THREAD

**Issue by Rishav1707** [TusharKesarwani/Front-End-Projects#737]
## **Describe the project**

*The **Quote Generator** is an innovative React project designed to generate inspirational, thought-provoking, or motivational quotes at the click of a button. This interactive web application utilizes React's component-based architecture to create a seamless user experience. With the Quote Generator, users can access a vast collection of carefully curated quotes from various sources, including famous authors, philosophers. The application fetches quotes from a reliable API and dynamically displays them on the screen, ensuring a fresh and engaging experience each time.*

## Issue Type:

- [x] New Project

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/97666287/817b1ecb-ccb5-4a14-a6b2-f03d1a3d3c1f)

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by rudra016** [comment]
I am sure I can work on this issue, Please assign me this.

**Comment by devender15** [comment]
Hello there, I want to work on this issue. Please assign this to me.

**Comment by RAJharsh02** [comment]
Hey , @TusharKesarwani  I would really like to work on this issue once the contribution phase starts .

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
