### ISSUE TITLE
Rishify

### ISSUE THREAD

**Issue by Rishav1707** [TusharKesarwani/Front-End-Projects#738]
## **Describe the project**
***Rishify** is a music streaming platform that allows users to access a wide range of music tracks and playlists from around the world. With its user-friendly interface and seamless navigation, Rishify makes it easy for users to find their favorite songs and discover new ones. The platform requires user authentication to provide a personalized experience, showing the top 5 tracks that the user has been listening to over the last 30 days. With its extensive music library and innovative features, Rishify is the ultimate music streaming platform for music lovers everywhere.*

## Issue Type:

- [x] New Project

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/97666287/9012e779-5353-4334-8b73-58f7d359f7e5)

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
