### ISSUE TITLE
Movie Search App

### ISSUE THREAD

**Issue by money8203** [TusharKesarwani/Front-End-Projects#74]

**Comment by amitjimiwal** [comment]
Assign me this Project

**Comment by money8203** [comment]
Sure you can work on this!

**Comment by Vanshiii203** [comment]
@money8203 Are you still working on this issue?

**Comment by money8203** [comment]
Currently I'm working on the Twitter UI part, after that I'll hope onto this one.

**Comment by abhilipsasahoo03** [comment]
@money8203 is this issue still being worked upon?

**Comment by money8203** [comment]
Yes I'll sumbit it by tomorrow
