### ISSUE TITLE
Food-Menu Search

### ISSUE THREAD

**Issue by Rishav1707** [TusharKesarwani/Front-End-Projects#740]
## **Describe the project**
A food menu is a list or a board that displays the different food and drink items that a restaurant or a food establishment offers. The menu typically includes the names of the dishes, their descriptions, and their prices. Some menus may also indicate the ingredients, cooking methods, or nutritional information of the dishes. A well-designed food menu should be easy to read, visually appealing, and reflect the restaurant's brand and style. In addition to its practical purpose of informing customers about the available food options, a food menu can also serve as a marketing tool, enticing customers to try new dishes or promoting special deals and promotions.

## Issue Type:

- [x] New Project

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/97666287/3e16f780-b2ab-497e-b566-86d380159b0d)

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by Rishav1707** [comment]
> I haven't understood the issue properly but I would like to work on it.

I would like to add this project to this repo, that's why I created this issue.

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
