### ISSUE TITLE
[SSoC '23] {Tourism Project} Change the photo crop out in various sections and add new pages for footer links in

### ISSUE THREAD

**Issue by PoulavBhowmick03** [TusharKesarwani/Front-End-Projects#741]
**Is your feature request related to a problem? Please describe.**
1. The navbar has no hover effects.
2. In the header section, the top part has no padding, leading to the images crop out.
3. There is no image slider, and the image gets cut out side wise in many places
4. There are no external websites to T&C, privacy, Need help section. 

**Describe the solution you'd like**
1. I would like to add some animations to the navbar.
2. Add padding to the top part of the website so that the upper part of the website is visible.
3. Add image slider to the parts where image is cut out.
4. Add new pages for the same and link them to respective sections in the footer.
![issue 3](https://github.com/TusharKesarwani/Front-End-Projects/assets/133862694/549e800e-8cbe-4866-acfc-cb27a9b61fa6)

![bug 2](https://github.com/TusharKesarwani/Front-End-Projects/assets/133862694/4755fa1e-8a02-4e02-9f49-bb0afa72e1eb)

![img issue1](https://github.com/TusharKesarwani/Front-End-Projects/assets/133862694/19e80646-ea86-451d-8ba0-48acafa40ea5)

I would be happy to work on these from 1st June for SSoC @TusharKesarwani

**Comment by Praveenkumar07007** [comment]
I want to work on this issue could you please assign it to me @TusharKesarwani .
