### ISSUE TITLE
Pathfinding Visualizer and Sorting Visualizer

### ISSUE THREAD

**Issue by VardaPanchal005** [TusharKesarwani/Front-End-Projects#742]
These projects are completely based on the implementation of 2 types of algorithm that is :

Pathfinding Visualizer
This contains all types of algorithm like Dijkshitra,A*,Swarm,BFS,DFS etc the purpose of this project is to create a playful interface to help understand the concepts of DSA better with the help of HTML,CSS,Javascript and React JS.
![Screenshot (115)](https://github.com/TusharKesarwani/Front-End-Projects/assets/114830938/fb970bc3-cba1-4103-b5cb-119e9c68210a)

Sorting Visualizer
This contains all types of algorithm like Merge sort,heap sort,bubble sort etcthe purpose of this project is to create a playful interface to help understand the concepts of DSA better with the help of HTML,CSS,Javascript and React JS.
![Sorting Visualizer](https://github.com/TusharKesarwani/Front-End-Projects/assets/114830938/9c48dbf6-c5da-4151-850e-d88d3ad91681)

Please assign this issue to me.

@TusharKesarwani

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
