### ISSUE TITLE
Make website responsive 

### ISSUE THREAD

**Issue by gaurav-2-0-0-2** [TusharKesarwani/Front-End-Projects#744]
**Make it mobile responsive**
Your site is not responsive

**Comment by vaibhav-xt** [comment]
I can work on this issue and I am a contributor of SSOC 2.0

**Comment by chaitanyarora** [comment]
I can work on this issue as well.

**Comment by ojanshu** [comment]
I would like to work on this issue.

**Comment by Ayushmaan-dev** [comment]
Your website is not responsive I can work on it and make it responsive according to mobile I have worked earlier into making websites responsive. You can assign this issue to me.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under SSoC'23.

**Comment by komalk15** [comment]
I know how to make a website responsive please assign me this issue

**Comment by komalk15** [comment]
I know how to make a website responsive please assign me this issue.

**Comment by rudra016** [comment]
i can work on this, please assign me this.

**Comment by RAJharsh02** [comment]
Hey , @TusharKesarwani  I would really like to work on this issue once the contribution phase starts .

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
