### ISSUE TITLE
Zomato landing page(images not loads)

### ISSUE THREAD

**Issue by imranah10** [TusharKesarwani/Front-End-Projects#745]
**Describe the bug**
neither any images loads nor logo loads...

**To Reproduce**

**Expected behavior**

**Screenshots**
![Zomato-Clone](https://github.com/TusharKesarwani/Front-End-Projects/assets/95746830/784289fd-4f3c-4911-a520-3fc39089b1eb)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by imranah10** [comment]
I want to put supporting images. Please assign me.

**Comment by Abhishantpadam** [comment]
Can you please explain this to me I'm unable to understand this. Please write it clearly what is the issue here.

**Comment by imranah10** [comment]
> Can you please explain this to me I'm unable to understand this. Please write it clearly what is the issue here.

open the zomato landing page from the front end project & check the project output, all the contents loads except images..
![Zomato-Clone](https://github.com/TusharKesarwani/Front-End-Projects/assets/95746830/3b0ebdcd-0108-4b96-9b9b-3e6abae63b7c)

**Comment by Abhishantpadam** [comment]
No its working in google chrome. I thinks it's the problem in your side. try changing browser.
<img width="1440" alt="Screenshot 2023-05-25 at 7 57 02 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/46023761/3ccdd149-ba00-4426-bf31-3988d9dbadf3">
<img width="1440" alt="Screenshot 2023-05-25 at 7 56 41 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/46023761/6ce6bd81-0ff3-4f1d-a119-ddd27a523de8">

**Comment by Abhishantpadam** [comment]
Also working in Safari Browser it looks fine to me. 

<img width="1299" alt="Screenshot 2023-05-25 at 8 00 07 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/46023761/17628e06-ab39-4b16-8953-83b4ff2d45ec">
<img width="1301" alt="Screenshot 2023-05-25 at 8 00 18 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/46023761/2ccef418-ad79-4ab4-9b9e-a27031e0abba">

**Comment by SKSADIRUDDIN** [comment]
pls assign me

**Comment by devender15** [comment]
Hello there, i want to work on this issue. Please assign this to me.

**Comment by RAJharsh02** [comment]
HII, I want to work on this issue . please assign me

**Comment by Gungun1643** [comment]
How can we contribute to it ?Will the mentor assign it or we need to voluntarily do it ?

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June

**Comment by Gungun1643** [comment]
so we need to find an issue then fix it or it is like the ssoc team will be
assigning us the issues ..
I haven't received the pass yet
