### ISSUE TITLE
Issue: Add Dark Mode

### ISSUE THREAD

**Issue by Aarize29** [TusharKesarwani/Front-End-Projects#746]
### Description
Currently, our application only supports a light mode theme. To provide a more versatile and user-friendly experience, we should implement a dark mode option. Dark mode is becoming increasingly popular and is expected by many users. This will allow users to switch between light and dark themes based on their preferences and reduce eye strain in low-light environments.

### Proposed Solution
To add dark mode, we need to update the application's styling and color scheme to support the new theme. This includes modifying the CSS or stylesheets to provide a visually pleasing dark color palette for backgrounds, text, buttons, and other UI elements. Additionally, we may need to adjust the contrast and visibility of certain elements to ensure readability in both light and dark modes.

### Tasks
- Update the CSS or stylesheets to include new styles for dark mode.
- Modify the color palette to create a visually appealing dark theme.
- Adjust the contrast and visibility of UI elements for optimal readability.
- Implement a toggle or switch in the user interface to allow users to switch between light and dark modes.
- Test the dark mode implementation across different browsers and devices to ensure compatibility and consistency.

### Acceptance Criteria
- The application should have a visually pleasing and consistent dark mode theme.
- Users should be able to switch between light and dark modes easily.
- Text and UI elements should have appropriate contrast and visibility in both light and dark modes.
- The dark mode implementation should be tested thoroughly and work consistently across different platforms.

### Labels
Please add the label "enhancement" to this issue.

**Comment by MeenuyD** [comment]
I would like to work on this issue assign it to me

**Comment by sanjaygupta972004** [comment]
@TusharKesarwani Sir Can I work on this project? I am interested to work on this issue, please assign me

**Comment by manu31shukla** [comment]
interested to work on this.

**Comment by alpesh677** [comment]
I'm interested to work on this please assign this to me.

**Comment by RAJharsh02** [comment]
Hey , @TusharKesarwani  I would really like to work on this issue once the contribution phase starts .

**Comment by NaveenChandraAdhikari** [comment]
I'm interested @TusharKesarwani to work on this issue

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
