### ISSUE TITLE
Change SWOC entry pass to SSOC entry pass

### ISSUE THREAD

**Issue by samyakjain1908** [TusharKesarwani/Front-End-Projects#747]
In the README.md file of the project, replace the old entry pass of SWOC with the new SSOC pass at the start of the file. 
<img width="830" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/89599623/fee71c8b-b514-4e31-8a2d-f6e91c2a8284">

**Comment by VedantDomadiya** [comment]
please assign me this issue

**Comment by Mahendra-Lohar** [comment]
PLease assign me this issue
