### ISSUE TITLE
Improving the readme file 

### ISSUE THREAD

**Issue by harshsingh32** [TusharKesarwani/Front-End-Projects#748]
I would like to work on improving the readme file of this project [Projects](https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects)
/chess. This would increase the engagement of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under SSoC'23.

**Comment by RAJharsh02** [comment]
Hey!! I want to work on this issue please assign it to me

**Comment by arpy8** [comment]
I would like to work on this issue too!!

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
