### ISSUE TITLE
New Project In Place of COMING SOON!!

### ISSUE THREAD

**Issue by GeekWolf007** [TusharKesarwani/Front-End-Projects#749]
## **Describe the project**
I want to add a new project in the place of coming soon. 
![Screenshot 2023-05-26 200933](https://github.com/TusharKesarwani/Front-End-Projects/assets/126271100/7288a55c-180d-47b4-888f-2423a368e302)

The project is a job listing web app. The users also have the option to add new jobs. Users can also search jobs via country, state, job company, job requirements, etc. 

I have built this project using only HTML , CSS and JavaScript. This is a great learning for people who thinks we can only add new jobs via backend technologies. This project helps in exceeding the limit of the developer and is a great learning project.

Please assign me this issue so that I can add this project and add my contribution to this community.

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
