### ISSUE TITLE
Adding the projects in the User Interface and improving the organization of items

### ISSUE THREAD

**Issue by dishamodi0910** [TusharKesarwani/Front-End-Projects#750]
Problem: All the projects are not visible on the front home page. It's very difficult to get the project details.

Solution: Arranging the projects category-wise on the home page.

**Comment by dishamodi0910** [comment]
@TusharKesarwani Sir, please assign me this issue, I would like to work on this under SSOC 2.0

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
