### ISSUE TITLE
A Crypto Info Website Using CoinGecko Api

### ISSUE THREAD

**Issue by rudra016** [TusharKesarwani/Front-End-Projects#751]
Project Description: Crypto Info React App using CoinGecko API

The Crypto Info React App is a web application designed to provide users with up-to-date information and insights on various cryptocurrencies. The app utilizes the CoinGecko API, a comprehensive cryptocurrency data platform, to fetch real-time data, including market prices, market capitalization, trading volumes, historical data, and more.

The main goal of the app is to present cryptocurrency information in a user-friendly and intuitive manner, allowing users to quickly access essential details about their favorite digital assets. The Crypto Info React App employs React, a popular JavaScript library for building user interfaces, to create a dynamic and interactive experience for users.

Key Features:

1. Cryptocurrency Listings: The app fetches a list of cryptocurrencies from the CoinGecko API and displays them in a well-organized manner. Users can view essential details such as the name, symbol, current price, and market cap of each cryptocurrency.

2. Search and Filter: The app provides a search functionality that enables users to find specific cryptocurrencies by name or symbol. Additionally, users can filter the cryptocurrency list based on various criteria such as price, market cap, and trading volume to narrow down their search.

3. Detailed Coin Information: When a user selects a particular cryptocurrency from the list, the app retrieves comprehensive details about the selected coin from the CoinGecko API. This information may include the coin's historical price chart, market dominance, circulating supply, and links to official websites and social media accounts.

4. Favorite Coins: Users can mark their favorite cryptocurrencies within the app and create a personalized watchlist. The app saves these preferences locally, allowing users to easily track and monitor the performance of their preferred coins.

5. News and Market Updates: The Crypto Info React App incorporates the CoinGecko API's news and market update features. Users can access the latest news articles, market analysis, and industry trends related to cryptocurrencies, helping them stay informed about the market developments.

6. Responsive Design: The app is designed to be responsive and adaptable to different screen sizes and devices. Whether accessed from a desktop computer, tablet, or mobile phone, users will have a seamless experience and enjoy full functionality.

Overall, the Crypto Info React App provides a comprehensive solution for cryptocurrency enthusiasts and investors to stay informed about the ever-evolving world of digital assets. By leveraging the power of the CoinGecko API and utilizing React's flexibility, the app delivers real-time data, interactive visualizations, and personalized tracking features, making it an invaluable tool for anyone interested in cryptocurrencies.

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/94120092/ccf7f2fc-109d-4c42-ad0a-38dd5197bd08)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/94120092/ef899b59-84b2-4042-ba59-346b8754c1f9)

**Comment by rudra016** [comment]
I believe this project can add a good exposure to the repo. This is in its initial stage, i can work on it to make it more cool.
please assign if found helpful

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
