### ISSUE TITLE
ShowRizz (shows app that displays a list of shows and their details. It allows users to view their details, and book tickets for the show.

### ISSUE THREAD

**Issue by manu31shukla** [TusharKesarwani/Front-End-Projects#752]
## **Describe the project**
This is a movie app that displays a list of movies and their details. It allows users to scroll and search for movies, view their details, and book tickets for the samet.
Made using [tvmaze api](https://api.tvmaze.com/search/shows?q=all)

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**

- React JS application.
- Implementation of the API and not just hardcode data from the API.
- It has 2 screens at a minimum. One to display a few data and an image and another screen to show it’s summary.
- The second screen has a button to book a movie ticket which will open a form with the movie name already present and a few relevant details.
(Reload would not happen)
(Use of local/session storage for storing user details)
- Proper Component file structure.

## **Screenshots**

- Home page 
![Show Rizz - Google Chrome 27-05-2023 19_25_04](https://github.com/TusharKesarwani/Front-End-Projects/assets/82714021/c5f99c50-39c5-48ae-a5b9-f172c7164c76)

- Show details page
![Show Rizz - Google Chrome 27-05-2023 19_25_20](https://github.com/TusharKesarwani/Front-End-Projects/assets/82714021/a0ac0d41-8d9d-49ec-982a-255cb92bb9bf)

- Book ticket page
![Show Rizz - Google Chrome 27-05-2023 19_25_30](https://github.com/TusharKesarwani/Front-End-Projects/assets/82714021/7655d797-3ac8-49b2-919f-beec5d78b995)

- About page
![Show Rizz - Google Chrome 27-05-2023 19_25_38](https://github.com/TusharKesarwani/Front-End-Projects/assets/82714021/c2c60fa3-8903-4d2f-9102-53b40ab3288b)

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June

**Comment by manu31shukla** [comment]
Okay !
