### ISSUE TITLE
Enhancing UI/UX of E-commerce landing webpage

### ISSUE THREAD

**Issue by SomilRathore01** [TusharKesarwani/Front-End-Projects#754]
**Is your feature request related to a problem? Please describe.**
Site does not have good user interface and required some styling and impressive designs in it.

**Describe the solution you'd like**
I will enhance the UI of this site, I will some gradient colors, many more styles and animations to make it quite responsive with HTML, CSS & JavaScript.
@TusharKesarwani 
Please assign this issue to me for competing in SSOC'2023.

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
