### ISSUE TITLE
A Job Opening Website User May apply job with Resume 

### ISSUE THREAD

**Issue by rajeev35** [TusharKesarwani/Front-End-Projects#755]
## **Describe the project**

A job opening website which is build using HTML and CSS only  this web page helps to apply for job with resume as well as job section.

## Issue Type:

- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.
![img1](https://github.com/TusharKesarwani/Front-End-Projects/assets/92223076/d356a7a4-c4d1-4cc2-b06e-9f3e43872909)
![img2](https://github.com/TusharKesarwani/Front-End-Projects/assets/92223076/96fc06ce-af82-4de4-befd-13d8ead4a0fe)
![img3](https://github.com/TusharKesarwani/Front-End-Projects/assets/92223076/83a004f6-01bc-47b7-8fef-7d7499444775)

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
