### ISSUE TITLE
Updating Readme

### ISSUE THREAD

**Issue by dishamodi0910** [TusharKesarwani/Front-End-Projects#758]
Updating Readme with the projects that are already available on the site in order to ease the idea for everyone to find the new project requests.
This would help to :
1. Go through projects.
2. We will be attaching the links of projects in the readme so if one wants to do enhancement, he/she can easily find out the project.
3. Keeping the track of project would be easy.

**Comment by dishamodi0910** [comment]
@TusharKesarwani 
I would request you to assign this issue to me.

**Comment by TusharKesarwani** [comment]
Go ahead

**Comment by TusharKesarwani** [comment]
Create a fresh issue because it is created before 1st June
