### ISSUE TITLE
Add a new List App-React.js

### ISSUE THREAD

**Issue by Aishjahan** [TusharKesarwani/Front-End-Projects#759]
## **Describe the project**
I want to add a React.js project named LIST APP . It uses React.js, HTML, and CSS.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

![LA-1](https://github.com/TusharKesarwani/Front-End-Projects/assets/105747510/a2f64419-e4d2-4cec-a878-e9170dc31d4b)
![LA-2](https://github.com/TusharKesarwani/Front-End-Projects/assets/105747510/ad59a280-5ad8-40d4-8e2d-ce9eeca3f7a9)
![LA-3](https://github.com/TusharKesarwani/Front-End-Projects/assets/105747510/95b8b21e-11bf-476b-8bcb-ddbd77d7a59c)

Please assign me this issue.

**Comment by MisterMickey** [comment]
@TusharKesarwani I want to work on this issue under SSOC, kindly assign me this issue.

**Comment by Smit1324** [comment]
@TusharKesarwani I would love to work on this. I already have experience in this task. So, kindly assign me this task under SSoC '23.

**Comment by hetsonii** [comment]
I would like to work on this issue. I will be using Framer Motion and TailwindCSS for efficient animations.

**Comment by prithadc** [comment]
I would like to work on it under SSOC'23, please assign it to me and oblige. Thank you.

**Comment by Aryankr-24** [comment]
I would like to work on this project. I have done similar kind of project kindly assign it  to me.

**Comment by nandanchebbi560** [comment]
I would like to contribute to this project, Please assign me this project.

**Comment by TusharKesarwani** [comment]
React projects are not accepted

**Comment by KeshavAgrawal18** [comment]
Okay @TusharKesarwani, please assign me this issue, I can work on it with only **HTML**, **CSS**, **Javascript**.
Thank You.
