### ISSUE TITLE
Add a new movie app

### ISSUE THREAD

**Issue by Aishjahan** [TusharKesarwani/Front-End-Projects#760]
## **Describe the project**
 want to add a movie app that fetches and displays the name of movies. It uses React.js , HTML, CSS and an API.
It fetches details about the movies.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

![movieapp-1](https://github.com/TusharKesarwani/Front-End-Projects/assets/105747510/ce5f59c2-9572-4f41-b3bc-0c8a30587e57)
![movieaoo-2](https://github.com/TusharKesarwani/Front-End-Projects/assets/105747510/d56f5558-fe6d-4aba-8eb6-8289f00c7a5c)

Please assign me this issue.

**Comment by PiyushBhatnagar09** [comment]
hey ,i like to work on this movie app

**Comment by PiyushBhatnagar09** [comment]
please assign me this issue

**Comment by PiyushBhatnagar09** [comment]
Please assign me this issue, i will be using imdb api to fetch movies and also i will improve the front end of this project. The suggested movies will be visible whenever we write anything in search box.

**Comment by Smit1324** [comment]
@TusharKesarwani I would love to work on this as I have knowledge in web development and excels at working with API. I have also worked on similar project. So, kindly assign me this task under SSoC '23.

**Comment by sripesh** [comment]
I am new to open source, but I have a sound knowledge of MERN stack web development. For this issue, I can fetch data regarding movies from websites using API, and display it to the end users using an interactive React app with good CSS.

So, Please assign me this issue.

**Comment by PranavMehta15** [comment]
I would like to work on this issue. I will fetch the data using TvMaze API and also make a good front end for this project.

**Comment by 234Kavya** [comment]
I would like to work in this. Please assign me

**Comment by Aryankr-24** [comment]
I have used api in projects. So i have quite experience in this field kindly assign it to me.

**Comment by apru02** [comment]
I would like to work in creating this Movie fetching app. I have some experience working with react.js and fetching APIs. Kindly assign this project to me under #SSoC'23.

**Comment by TusharKesarwani** [comment]
React projects are not accepted
