### ISSUE TITLE
Add a weather app.

### ISSUE THREAD

**Issue by Aishjahan** [TusharKesarwani/Front-End-Projects#761]
## **Describe the project**
I want to add a weather app made using HTML, CSS , JAVASCRIPT and API.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

![Screenshot 2023-05-31 004642](https://github.com/TusharKesarwani/Front-End-Projects/assets/105747510/afbd32ac-9551-4653-b55e-bf6489a27774)

Please assign me this issue.

**Comment by MisterMickey** [comment]
@TusharKesarwani I want to work on this issue under SSOC 2.0, Kindly assign me this issue.

**Comment by Aditya-Lawate-codez** [comment]
I can create a weather app in react kindly assign me this issue

**Comment by Smit1324** [comment]
I want to work on this as I have knowledge and experience in what you are asking for. So, kindly assign me this task.

**Comment by Courage003** [comment]
I can contribute to this using HTML,CSS,JS and API .Please assign this to me as I can also provide it a good UI design as well...under SSOC'2023

**Comment by ncharanaraj** [comment]
Hi @TusharKesarwani I would like to work on this weather app. Can you assign me this task under SSOC'23?

**Comment by itzpranayy** [comment]
Hello @TusharKesarwani  I have build some weather apps using html ,css  , js and some using react . Can you please assign me this issue...

**Comment by Thejasbshetty** [comment]
Hiii sir I want to contribute to this issue . So please  assign me this task.

**Comment by Tusharjoshi1703** [comment]
Hey, I want to work on it as I already created it and want to brush my skills.Please assign it to me .

**Comment by anshul-kh** [comment]
Hello @TusharKesarwani , I am mentee under SSOC program. I want to work on this issue. So , please assign issue to me .

**Comment by prithadc** [comment]
I would like to work on this under SSOC'23. Please assign it to me and oblige. Thank you.

**Comment by Shubham071122** [comment]
Hey @TusharKesarwani  ,i have made some clone using HTML ,CSS , JS and Api and i would like to work on this issue , can you please assign it to me?

**Comment by princekumarg** [comment]
@TusharKesarwani assign this issue to me.

**Comment by princekumarg** [comment]
@TusharKesarwani assigne this issue to under ssoc2.023

**Comment by 234Kavya** [comment]
I am excited to solve this issue using HTML,CSS,Javascript,Apis. please Assign me

**Comment by apru02** [comment]
Hello @TusharKesarwani ! I would want to work on this weather app. I would be using React and APIs from weatherapi.com. Please assign me this issue. #SSoC'23

**Comment by AditiSingh06** [comment]
I would like to  work on this using HTML,CSS,JS and API .Please assign  me under SSOC'2023

**Comment by ankushdhavale** [comment]
assign this issue am work on Weather app so you assign me under SSOC 2.0

**Comment by SayandeepDutta14** [comment]
Hi @TusharKesarwani, this is Sayandeep Dutta, a Frontend Developer with prior experience of more than 1 year and this year participating in SSOC'2023. I would like to work on this project. Assign me to get the best result. Thank you.

**Comment by nandanchebbi560** [comment]
I would like to work on this project, Please assign me this issue.

**Comment by mdvadiyatnaqvi** [comment]
Hey @TusharKesarwani ,
I'm Md Vadiyat Naqvi.
Kindly assign this issue to me, i'm proficient in HTML, Css and JavaScript and the main thing is like this projects i had done earlier, i believe i'll complete this issue with more fun and learning new things like this prjects i had done earlier also you may check my GitHub account and see the images attached to this comment !

Github Link : https://github.com/mdvadiyatnaqvi/weatherApp

![weather](https://github.com/TusharKesarwani/Front-End-Projects/assets/127572794/4763932a-224f-47c1-aaeb-c30023ee4a55)

**Comment by vink08** [comment]
Hi @TusharKesarwani I want to work on this project I will work on this project by using React Js and weather api . Please assign me under the label of SSOC 2.0

**Comment by ArpitAggarwal10** [comment]
Hey @TusharKesarwani
I Would Love To Work On This
So , Please Assign It To Me Under SSoC'23

**Comment by panjyar** [comment]
Hello @TusharKesarwani I can build  weather apps using HTML, CSS , JAVASCRIPT and API.  . Can you please assign me this issue...

**Comment by Vidip-Ghosh** [comment]
Hi @TusharKesarwani I would like to work on this issue. Please assign this issue under SSOC'23.

**Comment by anamithrak15** [comment]
Hi @TusharKesarwani,  I would like to contribute to this. Please assign me this issue.

**Comment by champati-v** [comment]
Hi @TusharKesarwani I have already created a weather app as one of my personal projects. Please assign this issue to me. I can make modifications to the existing project as well. 
![weather screenshot](https://github.com/TusharKesarwani/Front-End-Projects/assets/108168139/369856a8-9893-45fd-9a1e-931a335b54f6)
