### ISSUE TITLE
New Project Request 

### ISSUE THREAD

**Issue by Gaurang1602** [TusharKesarwani/Front-End-Projects#763]
## Quiz App  
A quiz App which is created using Html , CSS and  Javascript in which there are questions which has four options and you have to mark the correct answer and at last you can check you score.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project 

## **Additional context**

- It is a very Interesting and enjoyable game. 
- In this a person get knowledge about Html , CSS , Javascript and python basics.

## **Screenshots**

- Is is a front UI of Quiz game .

![Quiz Page](https://github.com/TusharKesarwani/Front-End-Projects/assets/99584477/624bdd7b-17b2-4b53-9817-28acb6a74a66)

- It is the final score page.

![Final Score](https://github.com/TusharKesarwani/Front-End-Projects/assets/99584477/5589c824-d6b6-4f56-858f-39347aa84803)

It is very Interesting game .
So , please assign it to me under SSOC ' 23 .

**Comment by MisterMickey** [comment]
@TusharKesarwani I want to work on this issue under SSOC 2.0, Kindly assign me this issue.

**Comment by yashhhhh1** [comment]
@TusharKesarwani I am interested in this project Please can you assign me

**Comment by Smit1324** [comment]
@TusharKesarwani I would love to work on this as I also have knowledge in this field as well. So, kindly assign me this task under SSoC '23.

**Comment by itsgauravv** [comment]
I would like to work on this issue. This is how we'll proceed:

To begin with, we'll create a basic HTML structure for the website.
Then we'll add some beautiful CSS to style it.
By using javascript we'll check whether the answer selected is correct or not.
In the end, we'll show the final score, scored by the user.
Furthermore we can add more features to make it more user interactive.

I think I have the skills to complete this issue and I'll love to work for this one. So, kindly please assign me this task under SSoC 2.0.

**Comment by KritikaRawat** [comment]
I am interested in this project. Kindly assign this to me

**Comment by ayushi-ras** [comment]
I am interested in this project please assign me

**Comment by 234Kavya** [comment]
I am excited to contribute in this please assign me

**Comment by mdvadiyatnaqvi** [comment]
Hey @TusharKesarwani 
I am Md Vadiyat Naqvi. 
I want to do this issue as am proficient in HTML, CSS and JavaScript.

**Comment by ArpitAggarwal10** [comment]
Hey @TusharKesarwani 
I Would Love To Work On This 
So , Please Assign It To Me Under SSoC'23

**Comment by Roudranilk** [comment]
@TusharKesarwani kindly assign me this since I can make some changes to UI and make it look more good using threejs and react components to design yhe the overall frontend.

**Comment by Gaurang1602** [comment]
> Create a fresh issue because it is created before 1st June

Okk @TusharKesarwani I have created a new issue on this same project so , please now assign it to me under SSOC23.
