### ISSUE TITLE
To-Do List Project

### ISSUE THREAD

**Issue by aarushiksk** [TusharKesarwani/Front-End-Projects#764]
## **Describe the project**
This project aims at providing the user with a To-Do List wherein the user can add or delete tasks as per convenience.

## Issue Type:

-Bug Report
-Feature Request

## **Screenshots**

<img width="619" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/92772439/93338ea5-8d2e-4450-ae3c-225ada1c6d3c">

##**Improvements**
-Better UI
-Add new features to do list like categories (Example: Work, School, Leisure Time)

**Comment by rafiya2003** [comment]
can you please assign me?

**Comment by hetsonii** [comment]
Can you assign this to me please? I will be using ReactJS, TailwindCSS and framer motion to achieve the best animations.

**Comment by wittysam8382** [comment]
Will you please assign this to me?

**Comment by rafiya2003** [comment]
I will be using HTML, CSS and JS. Since I am a newbie(first year UG student). I still have a lot to learn

**Comment by Bulbuls-0510** [comment]
Sir will you please assign me this project?

**Comment by mfatima1010** [comment]
Sir will you please assign this to me under SSOC 23?
