### ISSUE TITLE
Add an AI Image Generator 

### ISSUE THREAD

**Issue by tapan31** [TusharKesarwani/Front-End-Projects#765]
## **Describe the project**
An AI image generator using React and node.js using openai API

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by rafiya2003** [comment]
can you please assign me?

**Comment by ayushi-ras** [comment]
Please assign this issue to me

**Comment by vivekelle** [comment]
I would like to work on this project. I will be using react and node.js with openai API.

**Comment by rafiya2003** [comment]
I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student).

**Comment by codingwithveer18** [comment]
I have good commands in the mentioned domains and will definitely create a best Framework for the AI image generator.

**Comment by dirwolf** [comment]
I would like to work on this project , please assign it to me

**Comment by Vidip-Ghosh** [comment]
I would like to work on this project, please assign me under SSOC'23.

**Comment by TusharKesarwani** [comment]
Create a fresh issue because it is created before 1st June

**Comment by tapan31** [comment]
I don't understand why people are asking to assign the issue, I have made request for a new project and I will work on it.
