### ISSUE TITLE
A Crypto Info Website Using CoinGecko Api 

### ISSUE THREAD

**Issue by rudra016** [TusharKesarwani/Front-End-Projects#771]
## **Describe the project**
Project Description: Crypto Info React App using CoinGecko API

The Crypto Info React App is a web application designed to provide users with up-to-date information and insights on various cryptocurrencies. The app utilizes the CoinGecko API, a comprehensive cryptocurrency data platform, to fetch real-time data, including market prices, market capitalization, trading volumes, historical data, and more.

The main goal of the app is to present cryptocurrency information in a user-friendly and intuitive manner, allowing users to quickly access essential details about their favorite digital assets. The Crypto Info React App employs React, a popular JavaScript library for building user interfaces, to create a dynamic and interactive experience for users.

Key Features:

Cryptocurrency Listings: The app fetches a list of cryptocurrencies from the CoinGecko API and displays them in a well-organized manner. Users can view essential details such as the name, symbol, current price, and market cap of each cryptocurrency.

Search and Filter: The app provides a search functionality that enables users to find specific cryptocurrencies by name or symbol. Additionally, users can filter the cryptocurrency list based on various criteria such as price, market cap, and trading volume to narrow down their search.

Detailed Coin Information: When a user selects a particular cryptocurrency from the list, the app retrieves comprehensive details about the selected coin from the CoinGecko API. This information may include the coin's historical price chart, market dominance, circulating supply, and links to official websites and social media accounts.

Responsive Design: The app is designed to be responsive and adaptable to different screen sizes and devices. Whether accessed from a desktop computer, tablet, or mobile phone, users will have a seamless experience and enjoy full functionality.

Overall, the Crypto Info React App provides a comprehensive solution for cryptocurrency enthusiasts and investors to stay informed about the ever-evolving world of digital assets. By leveraging the power of the CoinGecko API and utilizing React's flexibility, the app delivers real-time data, interactive visualizations, and personalized tracking features, making it an invaluable tool for anyone interested in cryptocurrencies.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/94120092/aebf90d7-8912-4e1e-a20f-da2820f90b49)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/94120092/dc045362-c15d-4035-b0ef-3cd1cad2a217)

**Comment by Smit1324** [comment]
@TusharKesarwani I would love to work on this as I also have knowledge in both web development, working with API as well as in blockchain and crypto. So, kindly assign me this task under SSoC '23.

**Comment by vink08** [comment]
Hi @TusharKesarwani I want to work on this project I have a great knowledge working with API . I have already done this type of projects .Please assign me under the label SSOC '23

**Comment by TusharKesarwani** [comment]
Create a fresh issue because it is created before 1st June

**Comment by rudra016** [comment]
> Create a fresh issue because it is created before 1st June
Sir, I initially created the issue before June 1st, but it was closed, so I created it again on June 1st.
