### ISSUE TITLE
A Trivia Application 

### ISSUE THREAD

**Issue by harshita-kaushik2** [TusharKesarwani/Front-End-Projects#772]
### Description :
- Trivia It is a fun application that is based on questions from famous RomComs and Movies. 
- Made using **HTML, CSS and JavaScript**

### Features:
- Rules manual to explain the flow of the game to the user
- A timer that counts down to 15 seconds.
- Hints are given for reference in each question to help the player
- When the timer goes off or the user makes an incorrect answer, the correct answer is automatically displayed
- There points are = +1 for each correct answer, 0 for incorrect/no answer.
- At the end, the total score of the game is displayed
- The user is presented with option to replay or exit the quiz.

Attached are images for reference : 

<img width="911" alt="rules" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/112249538/afb454ee-abdf-4056-8c51-3f8add411c3d">

<img width="960" alt="page" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/112249538/6304549b-89bb-46d1-92e3-523809e11d99">

Can you please assign it to me under SSoC '23 ?
Thank you :)

**Comment by rafiya2003** [comment]
can you please assign me?

**Comment by vershat** [comment]
I am interested in this project

**Comment by TusharKesarwani** [comment]
Go ahead
