### ISSUE TITLE
Candy Crush Game

### ISSUE THREAD

**Issue by harshita-kaushik2** [TusharKesarwani/Front-End-Projects#773]
### Description:
- The goal is to match at least three candies of the same color and type in a row or column to clear them from the board. 
- With each successful match, players earn points.
- This project using **HTML, CSS and JavaScript.**

### Functionality
- Scoring system to make it interactive
- Responsive design.
- Random candy generation.

Here is an image for reference : 

<img width="458" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/112249538/e227f406-f9c9-4a9d-b0cd-ecfe664e236e">

I would love working on this issue. Can you assign it to me under SSoC '23 ?
Thank You :)

**Comment by princekumarg** [comment]
@TusharKesarwani I would love working on this issue under ssoc23.

**Comment by Gungun1643** [comment]
Hi...I am a mern stack developer and love opensourcing. I found this project interesting and would like to contribute under the ssoc23.

**Comment by TusharKesarwani** [comment]
Do not add games
