### ISSUE TITLE
Improvement : Enhance UI and User Experience of "Dynamic js Quiz" Project

### ISSUE THREAD

**Issue by Divyanshu9822** [TusharKesarwani/Front-End-Projects#774]
### Overview

The current state of the Quiz project's UI and user experience is suboptimal and could benefit from significant improvements. This issue aims to address the following areas of concern: enhancing the visual design, improving the layout and alignment, fixing the behaviour of radio buttons, and overall refining the user experience.

### Current State :

![](https://user-images.githubusercontent.com/95610027/214227368-5a49d70c-c101-4eb8-aee5-7dad0a60dcee.png)

**Comment by Mudassirkhan2** [comment]
can you assign this issur to me
 @Divyanshu9822  under SSOC 2023

**Comment by Divyanshu9822** [comment]
Sorry but i found this issue and i must work first, if i couldn't solve the problem(which not gonna happen) you can ask.

**Comment by Divyanshu9822** [comment]
### Hey! [@TusharKesarwani](https://github.com/TusharKesarwani) I have found this problem and looked into it and I believe I can solve it by doing following explained process.

### How I will do it (Expected Changes)
_1. Visual Design:_
* Revise the CSS to create an appealing and visually consistent design.
* Optimize the color scheme, typography, and overall styling to ensure readability and aesthetic appeal.
* Apply suitable spacing and alignment to enhance the visual hierarchy and organization of elements.

_2. Radio Buttons:_
* Radio button should be hidden to make it more attractive.

_3. Code Refactoring:_
* I will evaluate the existing codebase and refactor the CSS and HTML as needed.
* Optimize code structure and eliminate any redundant or unnecessary code to enhance maintainability and performance.

**Comment by TusharKesarwani** [comment]
Go ahead

**Comment by Divyanshu9822** [comment]
This issue is resolved and PR is also approved and tagged with ready to merge by @harshit-paneri
