### ISSUE TITLE
Content isn't align properly

### ISSUE THREAD

**Issue by villAsh** [TusharKesarwani/Front-End-Projects#775]
**Is your feature request related to a problem? Please describe.**
The content on the mobile screen is not centered properly which is bad for the user experience.

Have a look

![IMG_20230601_114121](https://github.com/TusharKesarwani/Front-End-Projects/assets/50195101/5aee8aed-d1a5-4031-b286-8238ce5030c2)

**Describe the solution you'd like**
I can improve this and make it more responsive.
please assign me this under SSoC'23.

**Comment by KritikaRawat** [comment]
I can work on this project. Please assign it to me.

**Comment by Tusharjoshi1703** [comment]
I can solve it .Please assign it to me.

**Comment by Gungun1643** [comment]
Hi..I am a full stack web developer and love making projects.I found this issue interesting .Could you please assign it to me.

**Comment by TusharKesarwani** [comment]
Go ahead
