### ISSUE TITLE
Add Dark Mode to the Landing Page 

### ISSUE THREAD

**Issue by dakshsinghrathore** [TusharKesarwani/Front-End-Projects#780]
**Is your feature request related to a problem? Please describe.**
Adding dark mode to a website enhances user experience by reducing eye strain and improving readability in low-light environments.

**Describe the solution you'd like**
After adding dark mode to the landing page it would look like something like this 👇
![Screenshot 2023-05-31 at 22-45-05 Front-End Projects Home Page](https://github.com/TusharKesarwani/Front-End-Projects/assets/115932772/7070a4c8-488c-4528-88fe-1deb3d34effd)

**Describe alternatives you've considered**

**Additional context**
Will do the following 3 things inorder to achieve the stated goal . 👇
 1. ***Create a CSS class for dark mode***
 2. ***Add a toggle switch***
 3. ***Add JavaScript functionality***

**Comment by Tusharjoshi1703** [comment]
Hey I want to make this .Please assign it to me.

**Comment by itsgauravv** [comment]
I would like to work on this issue. This is how we'll proceed:

To begin with, we'll add a toggle switch and by using JS, we'll add the functionality to the toggle switch which will, with the help of CSS, make the light parts dark,  keep some parts same and enhance some dark parts. 

I think I have the skills to complete this issue and I'll love to work for this one. So, kindly please assign me this task under SSoC 2.0.

**Comment by starkver23** [comment]
Hey, I want to try it as it will be my first contribution. So, if you can please assign it to me

**Comment by Gungun1643** [comment]
Hi.. I am a mern stack developer and quite good at building the ui of the website . I found this issue interesting.Could you please assign it to me.

**Comment by TusharKesarwani** [comment]
Go ahead
