### ISSUE TITLE
Adding a Profile Links in the contribution section of landing page

### ISSUE THREAD

**Issue by Mayuresh-22** [TusharKesarwani/Front-End-Projects#782]
**Is your feature request related to a problem? Please describe.**
Currently, as we can see, we have a pretty good landing page that briefly describes the Repo/projects and has a separate section for the contributors. But it doesn't has a link through which user can navigate to their profiles.

**Describe the solution you'd like**
Therefore I would like to propose the idea of adding profile links for the contributors which can navigate users to their profiles. As I have seen the codebase and have figured out how can I implement this change.

I hope it will surely enhance the landing page which is the face of this Repo
Thank You.

**Comment by Deepak0320Singhal** [comment]
Hey @Mayuresh-22 I would love to work on this issue can you assign this to me.

**Comment by TusharKesarwani** [comment]
Go ahead
