### ISSUE TITLE
Issue in Calculator project

### ISSUE THREAD

**Issue by Abhishantpadam** [TusharKesarwani/Front-End-Projects#783]
**Describe the bug**
It is taking multiple operators 

**To Reproduce**
1. Go to 'Front-End-Projects Repository'
2. Click on 'Projects'
3. Scroll down to 'Calculator' and then run it.
4. Type some digits and put operator it takes Multiple operators as input.
5. See error

**Expected behavior**
It should take only 1 Arithmatic operation after we add a number.

**Screenshots**
<img width="1045" alt="Screenshot 2023-06-01 at 3 25 35 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/46023761/abf3597f-90b4-4496-8a58-a1630b3773ba">

**Desktop (please complete the following information):**
 - OS: [IOS]
 - Browser [chrome]

Name - Abhishant Padam
SSOC Participant

**Comment by Abhishantpadam** [comment]
Please Assign this issue to me. i have solution for this issue and want to update this issue.

**Comment by 2020B1531074** [comment]
please assigned me this issue

**Comment by komalk15** [comment]
Please assign me this issue , I will work  to resolve this issue.

**Comment by Tusharjoshi1703** [comment]
I can solve this issue and make it as a proper calculator by taking only one operator . Please assign it to me.

**Comment by TusharKesarwani** [comment]
Go ahead

**Comment by 2020B1531074** [comment]
Okk sir

**Comment by Abhishantpadam** [comment]
Hello Sir i have send the pull request to you, but i want to ask how it will get me score in quine.sh because it is not listed there. Please list this issue there. and then merge the pull request.
