### ISSUE TITLE
add a gaming website (Valorant) clone

### ISSUE THREAD

**Issue by kadambari68** [TusharKesarwani/Front-End-Projects#784]
Describe the project you want to add to the tech stack
A valorant clone created using HTML CSS JavaScript Bootstrap.

Expected behavior
I tried my best to clone Valorant's home page and added a new section to view all agents which is a bit different but still attractive where you can check out every character's abilities and background by clicking on their image. Here is the live version (https://sweet-salmiakki-d1a1de.netlify.app/)

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/112871361/f43de85a-3f9d-4d36-ba94-0d2f1bd8fb9a)

**Additional context (optional )
I have also added a Play now button which will take us to a sign up form which I connected with PHP but I haven't deployed that version cause the AWS EC2 instance service was free for a limited time only.

**Comment by rafiya2003** [comment]
I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student). I want to learn and grow. please give me the opportunity to learn and experience

**Comment by Deepak0320Singhal** [comment]
@kadambari68 I Want to know, you want someone to create a Valorant website clone 
(*if yes) Please assign me the task I have some experience and I can create one

**Comment by kadambari68** [comment]
@Deepak0320Singhal I have created it already only need to add it in the list but thanks for asking

**Comment by kadambari68** [comment]
@rafiya2003 good to know but I am already done with most part but thanks for asking

**Comment by TusharKesarwani** [comment]
Game projects are not accepted currently
