### ISSUE TITLE
Pathfinding Visualizer and Sorting Visualizer

### ISSUE THREAD

**Issue by VardaPanchal005** [TusharKesarwani/Front-End-Projects#785]
These projects are completely based on the implementation of 2 types of algorithm that is :

Pathfinding Visualizer
This contains all types of algorithm like Dijkshitra,A*,Swarm,BFS,DFS etc the purpose of this project is to create a playful interface to help understand the concepts of DSA better with the help of HTML,CSS,Javascript and React JS.
![Pathfinding visualizer](https://github.com/TusharKesarwani/Front-End-Projects/assets/114830938/10fcd175-2090-4dce-9995-af39d4f1f3c1)

Sorting Visualizer
This contains all types of algorithm like Merge sort,heap sort,bubble sort etcthe purpose of this project is to create a playful interface to help understand the concepts of DSA better with the help of HTML,CSS,Javascript and React JS.
![Sorting Visualizer](https://github.com/TusharKesarwani/Front-End-Projects/assets/114830938/a211c5a2-4c27-4c96-98a0-d08474d3fd78)

@TusharKesarwani  please assign this issue to me

**Comment by rafiya2003** [comment]
I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student). I want to learn and grow. please give me the opportunity to learn and experience

**Comment by VardaPanchal005** [comment]
> I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student). I want to learn and grow. please give me the opportunity to learn and experience

You can create a new issue and the PA will assign it to you
