### ISSUE TITLE
Enhance CONTRIBUTING.md file

### ISSUE THREAD

**Issue by MisterMickey** [TusharKesarwani/Front-End-Projects#786]
**Describe the bug**
The CONTRIBUTING.md file doesn't clearly clarify all the steps to contribute.

**To Reproduce**
I want to remake the CONTRIBUTING.md file adding all the necessary steps to contribute to the repo.

![Screenshot from 2023-06-01 15-29-58](https://github.com/TusharKesarwani/Front-End-Projects/assets/93720428/10c16d19-fcd4-4b07-9302-9d2a56bffb78)

**Comment by MisterMickey** [comment]
@TusharKesarwani Kindly assign me this issue.

**Comment by mfatima1010** [comment]
Can you assign me this issue?

**Comment by TusharKesarwani** [comment]
Go ahead
