### ISSUE TITLE
issue in truth table generator

### ISSUE THREAD

**Issue by Swapnalighadge** [TusharKesarwani/Front-End-Projects#787]
i would like to work on this as i can make it more attractive using html and css under SSOC

**Comment by Swapnalighadge** [comment]
#787

**Comment by SarthakJaindebugger** [comment]
I've work experience of front end tech in a startup as a Intern. Pls allot this issue to me!

**Comment by TusharKesarwani** [comment]
Describe the issue in detail @Swapnalighadge

**Comment by Swapnalighadge** [comment]
i can add attractive background and i can change the button style and font  of  truth table generator

**Comment by SarthakJaindebugger** [comment]
@TusharKesarwani please provide me with this opportunity as I've real time hands on practice in Web Technologies. Will surely contribute to the best of my knowledge.

**Comment by Swapnalighadge** [comment]
#787

**Comment by Swapnalighadge** [comment]
@TusharKesarwani i have added description #787
