### ISSUE TITLE
Connect the dots game

### ISSUE THREAD

**Issue by kadambari68** [TusharKesarwani/Front-End-Projects#788]
**Describe the project**
The Connect the dots game is to check if the user can make the right connections that is can connect the adjacent dots or not. It gives the right connection message when connected correctly wrong connection on the wrong ones and no connection message when checked before making any connections.

It is a simple game made by using HTML CSS and JavaScript

 Issue Type:

- [ ] New Project

https://kadambari68.github.io/Task2_VirtualLabs_IITR/

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/112871361/7028f105-bbf8-4528-9edd-b07e586648ca)

**Comment by rafiya2003** [comment]
I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student). I want to learn and grow. please give me the opportunity to learn and experience

**Comment by SurbhiMotwani23** [comment]
hey  I also want to learn ,I am a newbie.It would be great of you to assign this issue to me.
