### ISSUE TITLE
adding a placeholder in course goal box

### ISSUE THREAD

**Issue by 2020B1531074** [TusharKesarwani/Front-End-Projects#789]
![Screenshot (146)](https://github.com/TusharKesarwani/Front-End-Projects/assets/98419710/ff7a71a5-e37c-4eac-b577-83604438eb54)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 2020B1531074** [comment]
please assigned me this issue

**Comment by Uma-Shankar0927** [comment]
@TusharKesarwani I want to solve the issue.

**Comment by TusharKesarwani** [comment]
Create a new issue with a proper description
