### ISSUE TITLE
To enhance the UI of ping pong game

### ISSUE THREAD

**Issue by Abhishek2nayak** [TusharKesarwani/Front-End-Projects#790]
**Is your feature request related to a problem? Please describe.**
I just visit the ping-pong game and found that UI experience is not good  like color scheme mismatch, scroll behavior and so on.

**Describe the solution you'd like**
I want to enhance the UI of ping-pong game by adding nice color scheme , fix the UI fault and add some sound whenever ball hits the bat.

**Comment by Abhishek2nayak** [comment]
@TusharKesarwani  please assign this issue to me.

**Comment by bhaveshgarg2000** [comment]
@TusharKesarwani Please assign me this issue I have a good knowledge of HTML, CSS, and JS. I'll make it look better & an attractive UI.

Thank You
