### ISSUE TITLE
A 3D website with parallax effect made with HTML, CSS and Javascript 

### ISSUE THREAD

**Issue by Romit77** [TusharKesarwani/Front-End-Projects#791]
## **Describe the project**

This website is made with the Html CSS and Vanilla Javascript. It has a parallax scrolling effect in which the images move with the movement of the cursor which creates a amazing 3D parallax effect.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/112157668/3e3423d2-fe24-497d-8079-741091c010c4)

**Comment by rafiya2003** [comment]
I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student). I want to learn and grow. please give me the opportunity to learn and experience

**Comment by AditiSingh06** [comment]
I'm interested in this project  and I would be grateful if you could consider assigning me to this project under SSOC'23.
