### ISSUE TITLE
Adding a remove all button after a task 

### ISSUE THREAD

**Issue by 2020B1531074** [TusharKesarwani/Front-End-Projects#792]
![Screenshot (146)](https://github.com/TusharKesarwani/Front-End-Projects/assets/98419710/460469a4-3bd5-437a-a5ae-1ba8f0fe5fc0)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 2020B1531074** [comment]
#792 please assigned me this issue. I want to add button remove all from which when the user want task can be removed.

**Comment by TusharKesarwani** [comment]
Create a new issue with a proper description
