### ISSUE TITLE
README.md file 

### ISSUE THREAD

**Issue by himadribh07** [TusharKesarwani/Front-End-Projects#793]
@TusharKesarwani  In the readme file the link for **cloning a repo** is actually redirecting to **Creating a pull request**. Please assign the task to me so that I can make the changes  !

**Comment by harshit7045** [comment]
Hello,@Kumar-laxmi

My name is Harshit Mishra, and I am a student at IIIT Una. I possess a strong understanding of data structures and algorithms and have the ability to write optimized code with explanatory comments. I kindly request to be assigned this issue.
Thank you.

**Comment by himadribh07** [comment]
Hi @TusharKesarwani have made the changes #977, review and close the PR.
