### ISSUE TITLE
[SSOC 2.0] README.md not properly aligned

### ISSUE THREAD

**Issue by MisterMickey** [TusharKesarwani/Front-End-Projects#794]
**Describe the bug**
The Heading section of README.md is not center-aligned like other sections which is making the README file irregular.

**To Reproduce**
I want to centre-align the Heading Section.

SSOC 2.0

**Comment by MisterMickey** [comment]
@TusharKesarwani Kindly assign me this issue under SSOC 2.0

**Comment by rafiya2003** [comment]
I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student). I want to learn and grow. please give me the opportunity to learn and experience
