### ISSUE TITLE
want to add scroll bar button in website

### ISSUE THREAD

**Issue by Lovegupta112** [TusharKesarwani/Front-End-Projects#795]
I want to create scrollbar button on website 
The scrollbar button on a website will  navigate through the content within a scrollable area

![Screenshot from 2023-06-01 16-00-41](https://github.com/TusharKesarwani/Front-End-Projects/assets/90507983/ca0c705d-52d4-4c03-88e3-d7284c4ca5ec)

 so please assign me this under ssoc 23

**Comment by weaklogics** [comment]
assign me the issue i can make it work with a proper functioning of scrollbar
