### ISSUE TITLE
FlipCard : Want to add flipcard game to the repo.

### ISSUE THREAD

**Issue by MisterMickey** [TusharKesarwani/Front-End-Projects#796]
## **Describe the project**

**About the Game:**
FlipCard-Memory Game is a modern version of the classical flip card game in which the user has to pull a card
and remember what is the symbol in that card when two cards having the same symbol are flipped then those cards vanish.

## Issue Type:
- [x] New Project

## **Additional context**
The Flipcard Memory Game is a classic memory-matching game where the player's goal is to flip cards and find matching pairs within a certain time limit. Here are the detailed features of the game:

Landing Page: There will be 4 cards labelled as F, L, I, & P at the beginning of the game and 3 of them(F, I,&P) will be flippable and 'L' will not be. Flipping 'F' will show Figures(stats including the best score of all three modes, total flips, matched flips and wrong flips), flipping 'I' will show game instructions and flipping 'P' will let us choose between difficulty mode(casual, medium, or hard) after selecting any of the mode game will begin.

Game Board: The game board consists of a grid of face-down cards. The number of cards and the grid size can vary depending on the difficulty level or customization options.

Card Flipping: The player can select any two face-down cards to flip them face-up. This allows the player to see the images or symbols on the cards.

Matching Pairs: The objective is to find matching pairs of cards. When the player flips two cards and they match, both cards vanish from the game board. If the cards don't match, they are flipped back face-down, and the player will continue flipping other cards.

Time Limit: The game is played against the clock, meaning there is a time limit for completing the game. The player must match all the pairs before time runs out to win the game. The time limit will be set based on the game's difficulty level or adjustable by the player.

Difficulty Levels: The game offers multiple difficulty levels to cater to players of different skill levels. Higher difficulty levels have larger grids and more cards, making it harder to remember the card placements.

Scoring: The game can track the player's score based on their performance. Points will be awarded for each successful match.

Progress Tracking: The game will keep track of the player's progress and will be displayed to the player by flipping the 'F' card at the end or beginning of the game.

These are some of the core features of a Flipcard Memory Game.

## **Screenshots**
![Screenshot from 2023-05-29 22-34-31](https://github.com/TusharKesarwani/Front-End-Projects/assets/93720428/3f132566-fffc-449b-b5b9-59ff912130a5)
![Screenshot from 2023-05-29 22-34-20](https://github.com/TusharKesarwani/Front-End-Projects/assets/93720428/b3540715-0437-4e69-b4f7-392433993110)
![Screenshot from 2023-05-29 22-34-17](https://github.com/TusharKesarwani/Front-End-Projects/assets/93720428/4e01f8db-d95f-427b-94a0-f435407f6785)
![Screenshot from 2023-05-29 22-34-09](https://github.com/TusharKesarwani/Front-End-Projects/assets/93720428/110e1de5-6959-43e2-9eb3-1ccaecda9e12)
![Screenshot from 2023-05-29 22-33-59](https://github.com/TusharKesarwani/Front-End-Projects/assets/93720428/74140094-e7a7-4cd0-a8a5-3498c3ad27e2)
![Screenshot from 2023-05-29 22-34-04](https://github.com/TusharKesarwani/Front-End-Projects/assets/93720428/0e6f55cd-c7e1-425b-ac88-ebd3168f2717)

**Comment by rafiya2003** [comment]
I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student). I want to learn and grow. please give me the opportunity to learn and experience

**Comment by Arun9739** [comment]
@MisterMickey Game websites are not accepted

**Comment by MisterMickey** [comment]
@Arun9739 Thanks for letting me know.
