### ISSUE TITLE
Google Clone

### ISSUE THREAD

**Issue by ayan-joshi** [TusharKesarwani/Front-End-Projects#798]
## **Describe the project**
I want to add Google clone made with simple html and css. 
So it will be a good beginner front end project to add in the repository , 

## Issue Type:

- [ ] New Project

## **Additional context**
I will also add Google images and Google advanced search page to make it a complete clone 

## **Screenshots**

![Screenshot (175)](https://github.com/TusharKesarwani/Front-End-Projects/assets/96243602/906acd4c-8a06-4df3-9274-6985d22fe53b)

![Screenshot (176)](https://github.com/TusharKesarwani/Front-End-Projects/assets/96243602/7862ee58-d16f-4186-840d-7563cdb5a462)

![Screenshot (177)](https://github.com/TusharKesarwani/Front-End-Projects/assets/96243602/6fad2e43-8232-4e48-9a24-0a7ffc68ca8c)

**Comment by ayan-joshi** [comment]
I am a SSOC contributor please assign me this issue @TusharKesarwani

**Comment by RS-labhub** [comment]
Assign me this issue under SSoC @TusharKesarwani

**Comment by Arun9739** [comment]
@ayan-joshi Already it is there

**Comment by ayan-joshi** [comment]
okay my bad
