### ISSUE TITLE
Adding New Front End Web Application for Car Website

### ISSUE THREAD

**Issue by Priyanshu-Singh-1** [TusharKesarwani/Front-End-Projects#8]

**Comment by Priyanshu-Singh-1** [comment]
If you like this, can you assign me this issue?

I would be happy to work on this project

**Comment by TusharKesarwani** [comment]
Go ahead @Priyanshu-Singh-1

**Comment by Priyanshu-Singh-1** [comment]
@TusharKesarwani I have added the PR for this respective issue. 

Hope you would like this contribution.

**Comment by Priyanshu-Singh-1** [comment]
@TusharKesarwani you can close this issue as you have merged my PR.
I will be contributing more by creating them as issue and then after your approval I will start working
