### ISSUE TITLE
on the component section wind info,humidtiy info,temperature i want to add a hover

### ISSUE THREAD

**Issue by 2020B1531074** [TusharKesarwani/Front-End-Projects#800]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Gyanthakur** [comment]
assign me this issue,I want to work on this issue

**Comment by Gyanthakur** [comment]
#800 weather app done, merge this code
<img width="959" alt="Screenshot 2023-06-09 152703" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/98226958/ec9f4363-9251-4557-a648-f68f4c48e357">

**Comment by TusharKesarwani** [comment]
Create a fresh issue with proper description
