### ISSUE TITLE
Propoplex - Your Freelancing Partner

### ISSUE THREAD

**Issue by MohamedMafaz** [TusharKesarwani/Front-End-Projects#801]
## **Describe the project**
Propoplex is a website which allows users to generate proposals for freelancing sites with the help of AI. The backend work was completed. But, I don't know how to deploy it

## Issue Type:
- [ ] New Project

**Comment by devender15** [comment]
Hey there, have you written the backend in nodejs or python?

**Comment by MohamedMafaz** [comment]
python flask

**Comment by devender15** [comment]
You can assign this issue to me and your work will be done.

**Comment by MohamedMafaz** [comment]
What issue? Issue opened in Propoplex?

**Comment by MohamedMafaz** [comment]
https://github.com/MohamedMafaz/Propoplex/issues/11 Just head over to the repo. And comment anythin. So, that I can assign you the task.

**Comment by devender15** [comment]
okay

**Comment by MohamedMafaz** [comment]
Hey @devender15 
Can I assign you the issue?

**Comment by devender15** [comment]
yes please

**Comment by MohamedMafaz** [comment]
Just comment on that issue bro

**Comment by Garvanand** [comment]
@MohamedMafaz i can deploy the website can you assign the issue to me

**Comment by Garvanand** [comment]
Hi, it's deployed at
https://propoplex-deployment-zeta.vercel.app/

**Comment by MohamedMafaz** [comment]
Hey @Garvanand 
When I see it, it download something. I can't able to see anything? May I know how to see it?

**Comment by MohamedMafaz** [comment]
https://github.com/TusharKesarwani/Front-End-Projects/assets/113255500/14145f01-0d3e-44f1-9bc3-3d483182a1eb

**Comment by devender15** [comment]
don't open that file

**Comment by MohamedMafaz** [comment]
Hey! How can I see the website?

**Comment by devender15** [comment]
I am deploying your site. Is this repo contains complete code of your site??

**Comment by Garvanand** [comment]
It is being downloaded because of source code only but it is deployed
correctly,can you reshare the source code.

**Comment by Garvanand** [comment]
Please share the full source code of the website in a git repo correctly as deployment is running absolutely fine

**Comment by MohamedMafaz** [comment]
https://github.com/MohamedMafaz/Propoplex-Deployment/

**Comment by Garvanand** [comment]
Hi,
the deployment is going perfectly correct but there is an issue with source
code which is also not running properly when tested locally, pleathe se
check the source code once again and update the repo so that it can be
deployed.

**Comment by Arun9739** [comment]
@MohamedMafaz only front-end projects are allowed
