### ISSUE TITLE
adding a image in which good weather look show so that website make attractive

### ISSUE THREAD

**Issue by 2020B1531074** [TusharKesarwani/Front-End-Projects#802]
![Screenshot (147)](https://github.com/TusharKesarwani/Front-End-Projects/assets/98419710/6b260708-f97e-47fe-85e2-221e1539189e)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 2020B1531074** [comment]
please assign me under SSOC2.0

**Comment by harshit7045** [comment]
Hello,

My name is Harshit Mishra, and I am a student at IIIT Una. I possess a strong understanding of data structures and algorithms ,HTML,CSS and have the ability to write optimized code with explanatory comments. I kindly request to be assigned this issue.
Thank you.

**Comment by Arun9739** [comment]
@2020B1531074 Go ahead

**Comment by 2020B1531074** [comment]
Sir, i have make pr .please add the level of SSOC

**Comment by 2020B1531074** [comment]
please review my pr
