### ISSUE TITLE
I want to remove the bug to count word in countify project.

### ISSUE THREAD

**Issue by anrgsh33** [TusharKesarwani/Front-End-Projects#803]
**Describe the bug**
In snapshot you can see total words are 10 but it is showing only 9 words.
It is not showing correct count of words.

**To Reproduce**
1. Go to 'Front-End-Projects Repository'
2. Click on 'projects'
3. Scroll down to 'countify' then run it
4. Type some words
5. See count

**Expected behavior**
It is expected to show correct count.

[
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/87533605/c5da1ea8-b2fd-4264-94f5-b297285aa3e0)
]([**Screenshots**]([url]([url](![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/87533605/d6ba59ea-3760-4536-8c17-83a3923b74c1)))))

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser [e.g. Brave]

Please assign this issue to me, i can remove the bug.

**Comment by Rohith1816** [comment]
@anrgsh33  I want to work on this becuase I have a knowledge of javascript and I am sure that I can fix the bug .
So please assign this to me
