### ISSUE TITLE
number_guessing_game:UI Enhancements: Text, Color, and New Game/Try Again Button

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [TusharKesarwani/Front-End-Projects#808]
hey @TusharKesarwani I would like to propose some UI enhancements for the website, including improvements to text and color, as well as the addition of a 'New Game' or 'Try Again' button. Furthermore, I suggest incorporating a visual reaction when the player wins to enhance the overall user experience.

Specifically, I recommend the following changes:
    1.Text and Color: Standardize and optimize the text styles and color palette across the website for consistency and visual appeal.

   2. New Game/Try Again Button: Introduce a dedicated button,,positioned on the page, to allow the user to start a new game or retry the current game. This will provide a clear and intuitive way for users to initiate a fresh game session.

  3.  Winning Reaction: Implement a visual reaction or feedback when the player successfully wins a game. This can be achieved through animations, confetti effects, or any other appropriate means, to celebrate the victory and engage the player.

These UI enhancements aim to improve the overall aesthetics and usability of the website, creating a more enjoyable and engaging experience for users.

I am willing to contribute to this issue  under SSOC '23 by working on the necessary code changes. Any guidance or suggestions regarding the implementation of these UI fixes would be greatly appreciated.

**Comment by TusharKesarwani** [comment]
Game projects are not accepted
