### ISSUE TITLE
To adding a day and date part when the task are written

### ISSUE THREAD

**Issue by 2020B1531074** [TusharKesarwani/Front-End-Projects#810]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 2020B1531074** [comment]
when we enter the task and submit it then to show the day and date so that anyone can know this task is given on this date .
please assign me under SSOC2.0

**Comment by Divyanshu9822** [comment]
pls specify the name of project and give reference with screenshots so that i can work on this issue.

**Comment by TusharKesarwani** [comment]
Create a fresh issue with proper description
