### ISSUE TITLE
i also to convert in kelvin,centigrade,Rankine

### ISSUE THREAD

**Issue by 2020B1531074** [TusharKesarwani/Front-End-Projects#811]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 2020B1531074** [comment]
In temperature conversion project there is only conversion of celsius to faherneit .I want to add a another temerature type such as kelvin,centigrade,kelvin so that user can get more information on this
please assigned me this issue under SSOC2.0

**Comment by Divyanshu9822** [comment]
Hey @TusharKesarwani , Assign this issue #811 to me as I can add new temperature scales and also can improve the UI which is not so good now.

**Comment by 2020B1531074** [comment]
I have solved this issue
![Screenshot (150)](https://github.com/TusharKesarwani/Front-End-Projects/assets/98419710/85728f62-d7f9-4702-88f5-c30a3e78463c)
in this image you can see that i added new temperature scale like kelvin,rankine.
please assigned me this issue #811

**Comment by Mohit2043** [comment]
Hey @TusharKesarwani , Assign me the issue #811 . I can add other temperature scales and improve UI also

**Comment by 2020B1531074** [comment]
***@***.*** This is issue created by me and I have a solution of it
and waiting for assigning. Please assigned me this issue.

**Comment by 2020B1531074** [comment]
@TusharKesarwani/Front-End-Projects
***@***.***>  please
assigned me this issue

**Comment by Arun9739** [comment]
@Divyanshu9822 Instead of adding new one, improve present one itself.

**Comment by 2020B1531074** [comment]
Sir, i have a make pr of it .please add the level of SSOC in it.

**Comment by 2020B1531074** [comment]
Please review my pr
