### ISSUE TITLE
Simon Game

### ISSUE THREAD

**Issue by patnaikankit** [TusharKesarwani/Front-End-Projects#813]
## **Describe the project**
1. Simon is an electronic memory game with colored buttons. Repeat the sequence of lights and sounds to advance and test your memory skills.
2. This project will be made using HTML, CSS and Javascript 

## **Functionality**
1. Sequence generationScoring
2. Button activation
3. Scoring 

I would love to work on this issue. Can you please assign it to me under SSoC '23 ?
Thank You :)

**Comment by mdvadiyatnaqvi** [comment]
Hey @TusharKesarwani 

I would love to work on this issue. Can you please assign it to me under SSoC '23 ?
Thank You :)

It would be more understandable it you could provide some kind of pictures and other stuff for this project.

**Comment by Arun9739** [comment]
@patnaikankit games are not allowed
