### ISSUE TITLE
[BMI Calculator -> Bug] : Images not displayed on clicking "Get BMI" button

### ISSUE THREAD

**Issue by Divyanshu9822** [TusharKesarwani/Front-End-Projects#814]
### Issue Description:
Upon testing the "BMICalculator" project, I encountered an issue where the expected images related to BMI are not displayed when clicking the "Get BMI" button. The absence of these images makes it difficult for users to visually understand their calculated BMI.

### Steps to Reproduce:

1. Open the BMICalculator application.
2. Enter the required information (height, weight, etc.) to calculate BMI.
3. Click on the "Get BMI" button.

###  Expected Behavior:
After clicking the "Get BMI" button, the application should display relevant images associated with the calculated BMI on the user interface. These images play a vital role in helping users understand their BMI category visually.

### Actual Behavior:
Currently, upon clicking the "Get BMI" button, no images are displayed on the interface. This omission hinders the user experience and makes it challenging for users to interpret their BMI results accurately.

### Screenshot :
<img width="1440" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/90151736/45c8fd88-db1c-451a-8392-be0f13a7f5ae">

**Comment by Divyanshu9822** [comment]
### Hey! [@TusharKesarwani](https://github.com/TusharKesarwani) I have looked into this project found this problem and  I've already came up with the solution. So kindly assign this to me.

**Comment by 2020B1531074** [comment]
please assigned me this issue #814 and i already solved this

**Comment by 2020B1531074** [comment]
![Screenshot (148)](https://github.com/TusharKesarwani/Front-End-Projects/assets/98419710/6c14e1f9-6fe4-4aac-826a-1473201c486b)
please assigned me I have a solution of this you can see in this image
