### ISSUE TITLE
There is adding a box after clicking check button answer is shown 

### ISSUE THREAD

**Issue by 2020B1531074** [TusharKesarwani/Front-End-Projects#816]
![Screenshot (149)](https://github.com/TusharKesarwani/Front-End-Projects/assets/98419710/69a0f09d-8007-4484-8967-05497f7401b2)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 2020B1531074** [comment]
![Screenshot (149)](https://github.com/TusharKesarwani/Front-End-Projects/assets/98419710/42ba9c2f-c22f-4f12-9d10-404c56b9b47d)
in the image we can see the result not a armstong numer is not inside the box which don't look good . so please assigned me this under ssoc2.0

**Comment by sudhircode02** [comment]
@TusharKesarwani please assign #816 problem to me. 
I do my best to improve UI and all other error in minimal time.
