### ISSUE TITLE
I want to remove the bug in Palindrome project.

### ISSUE THREAD

**Issue by anrgsh33** [TusharKesarwani/Front-End-Projects#817]
**Describe the bug**
Logic is not correct for ex- "()" is not a palindrome but website is showing that it is a palindrome.

**To Reproduce**
1. Go to 'Front-End-Projects Repository'
2. Click on 'projects'
3. Scroll down to 'Palindrome' then run it
4. Type some string - ()
5. See result

**Expected behavior**
It is expected to show that a string is palindrome or not.
[
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/87533605/983162e2-5a24-4db5-83c0-14ffa4614170)
](url)

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser [e.g. Brave]

Please assign this issue to me, i have written the correct logic to remove the bug.

**Comment by Mohit2043** [comment]
Please assign me this issue .
I want to remove the bug in Palindrome project. #817
