### ISSUE TITLE
A Car Race Game

### ISSUE THREAD

**Issue by PoulavBhowmick03** [TusharKesarwani/Front-End-Projects#820]
## **Describe the project**
A car race game made using HTML, CSS and Javascript
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
User gets to start the game and then dodge the obstacles to complete the race

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/133862694/97629a20-b693-4640-8ac2-5f8781841808)

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/133862694/8481017b-ff6d-46da-8af2-dca3b11e588b)

**Comment by PoulavBhowmick03** [comment]
@TusharKesarwani Check out this game add request

**Comment by Chiranjeeb024** [comment]
Yes, I can do this project. If you want I can do this with Unity 3D with better visuals and effects. Which will more interactive. Also I can build this game in Unity for WEBGL format and HTML5. Which will easier to plug in to any where in codes.
Name-Chiranjeeb Garnayak
GITHUB:-https://github.com/Chiranjeeb024
