### ISSUE TITLE
Validation in student enrollment form and improve UI of page 

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [TusharKesarwani/Front-End-Projects#821]
**Describe the bug**
no validation in email and image link 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/112896644/41f653cc-d2b6-4ef6-a258-0608509095d4)

**Desktop (please complete the following information):**
 - OS: [windows11]
 - Browser [firefox]

**Additional context**

**Comment by Shu12388y** [comment]
@shivaniyuvrajyadav can you assign this issue to me

**Comment by shivaniyuvrajyadav** [comment]
Hey @Shu12388y I'm also contributor not a project admin or mentor.

**Comment by Shu12388y** [comment]
@TusharKesarwani  can you assign this issue to me
