### ISSUE TITLE
in celsius convertor button css used in only celsius button not on faherneit button 

### ISSUE THREAD

**Issue by 2020B1531074** [TusharKesarwani/Front-End-Projects#822]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 2020B1531074** [comment]
in temperature convertor projects css used in only celsius button when the result is formed the celsius temperature in bold but not faherenheit. I already improve this please assigned me this issue #822
you can see in this screenshot that i has solved this issue
![Uploading Screenshot (150).png…]()

**Comment by sudhircode02** [comment]
I want to work on #822 and I will solve the problem as well as improve UI as well.

I do have some good knowledge of making Good Looking website.
