### ISSUE TITLE
Some bugs in the Tourism Project

### ISSUE THREAD

**Issue by PoulavBhowmick03** [TusharKesarwani/Front-End-Projects#823]
**Describe the bug**
1. The navbar has no hover effects.
2. In the header section, the top part has no padding, leading to the images crop out.
3. There is no image slider, and the image gets cut out side wise in many places
4. There are no external websites to T&C, privacy, Need help section. I would like to work on these

**To Reproduce**
1. Go to 'Tourism Website index.html'
2. Click on Navbar, or go to any image section

**Expected behavior**

**Screenshots**

![](https://cdn.discordapp.com/attachments/1109832019929726986/1109834183578230906/bug_2.jpg)

![](https://cdn.discordapp.com/attachments/1109832019929726986/1109834183842484357/img_issue1.jpg)

![](https://cdn.discordapp.com/attachments/1109832019929726986/1109834184081555466/issue_3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: - Chrome

**Comment by komalk15** [comment]
Please assign me this issue .

**Comment by Manishkr1007** [comment]
Hello @TusharKesarwani I can work on this project . Can you please assign me this issue...

Please assign this to me under @SSOC2.0

**Comment by PoulavBhowmick03** [comment]
Hey @harshit-paneri 
Can this be assigned? I authored the issue... and these are existing bugs in the website

**Comment by harshit-paneri** [comment]
Start work on it.

**Comment by Niranjan-Kumar-Singh** [comment]
Can you please assign me this issue to me.
