### ISSUE TITLE
[Improvement] : Poor User Interface (UI) and Inefficient Result Presentation in "Air-Quality" Project

### ISSUE THREAD

**Issue by Divyanshu9822** [TusharKesarwani/Front-End-Projects#827]
### Issue Description:
While exploring the "Air-Quality" project, I encountered significant issues related to the User Interface (UI) that severely impact the overall user experience. 

The primary concerns include:

1. **Unpleasant Color Scheme and Theme**: The current color scheme and theme used in the project are visually unappealing and strain the eyes. The combination of colors does not provide a harmonious and comfortable viewing experience for users.
2. **Misaligned Text and Coordinates Search UI**: The text alignment and layout of the coordinates search component are not properly aligned. This misalignment creates a sense of disorder and confusion, making it challenging for users to input the desired coordinates accurately.
3. **Inefficient Result Presentation**: Upon clicking the "search" button after entering the coordinates, the results are displayed below on the page. This approach forces users to scroll down to view the results, which is inconvenient and adversely affects the usability of the application.
4. **Unattractive Section Layout**: The other sections within the page lack an attractive design and fail to engage users. The current font size and style also do not contribute to an aesthetically pleasing appearance.

Screenshots :
<img width="1440" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/90151736/b2c4dd48-89c4-4158-9030-4ae43272fa3f">
<img width="1440" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/90151736/48e564ee-1736-4f1f-818b-f26b047625bd">

### Proposed Solutions:
To address these issues and enhance the user experience, I recommend the following solutions:

1. Redesign the Theme and Color Scheme: Give the entire page a new theme and color scheme that is visually appealing and comfortable for users. Choose a harmonious combination of colors that not only looks pleasing but also enhances readability and usability.
2. Optimize Result Presentation: Instead of displaying the results below the page, present them in a modal form. After clicking the "search" button, a modal window should appear, containing the relevant results. This approach eliminates the need for scrolling, providing a more efficient and intuitive way for users to view the data.
3. Enhance Section Layout and Typography: Improve the overall design of the page by giving attention to the layout and typography. Consider using an appropriate font size, style, and spacing to create a visually appealing and readable interface. Ensure that the sections are visually distinct and engaging for users.

**Comment by Divyanshu9822** [comment]
### Hey! [@TusharKesarwani](https://github.com/TusharKesarwani) I have found this problem and looked into it and I believe I can solve it by doing all the explained process.

**Comment by Divyanshu9822** [comment]
@harshit-paneri pls assign me this issue as i have found this problem and looked into it and I believe I can solve it by doing all the explained process.

**Comment by harshit-paneri** [comment]
@Divyanshu9822 , start work on it.

**Comment by Divyanshu9822** [comment]
@harshit-paneri hey sir i started working on this project and i got to know it's not telling AQI (Air quality index), it is basically telling about Air pollution. So it's name should change and also wherever it's written air quality index. So can i change this?
