### ISSUE TITLE
Unit Converter

### ISSUE THREAD

**Issue by starkver23** [TusharKesarwani/Front-End-Projects#828]
## **Describe the project**
As a part of SSOC'23, I would like to add a unit conversion calculator in the list of projects. It is made by using HTML, CSS and Javascript.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [✅ ] New Project

## **Screenshots**
<img width="1440" alt="unit_convert" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/96279472/1f3a83ae-4df8-4318-ae0a-59c1bf18a781">

**Comment by starkver23** [comment]
@TusharKesarwani please assign this to me. Thank you

**Comment by Tusharjoshi1703** [comment]
Please assign it to me. I have already done this project and idea about it.

**Comment by Arun9739** [comment]
@starkver23 The project already exists.
