### ISSUE TITLE
Snake Game using Javascript.

### ISSUE THREAD

**Issue by AnkitGupta03** [TusharKesarwani/Front-End-Projects#829]
## **Describe the project**
A recreation of the classic snake game, using HTML, CSS and JavaScript.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
This game consists of two webpages.
1. The welcome page which has a "change difficulty level" feature, which changes the speed of the game accordingly.
2. The game page which renders the animation of the game.

## **Screenshots**
![img2](https://github.com/TusharKesarwani/Front-End-Projects/assets/96652394/04f38ca7-5197-4a90-9d59-4cb92afc0d69)
![img1](https://github.com/TusharKesarwani/Front-End-Projects/assets/96652394/83dc5e5f-5fc1-48d6-88e9-7556dc003d21)

Kindly, assign me this issue.

**Comment by princekumarg** [comment]
Please assign this issue to me @TusharKesarwani under ssoc2.0.

**Comment by ManmayGhosh** [comment]
Please assign this issue to me @TusharKesarwani under ssoc2.0. I have done this kind of projects.

**Comment by Arun9739** [comment]
@SarthakJaindebugger Game projects are not allowed
