### ISSUE TITLE
To add keyboard input in the calculator app

### ISSUE THREAD

**Issue by moh1t-do** [TusharKesarwani/Front-End-Projects#830]
**Is your feature request related to a problem? Please describe.**
Using the calculator on a desktop can be tedious when relying solely on the mouse. Therefore, I would like to incorporate keyboard input functionality to improve the user experience.

**Describe the solution you'd like**
Add support for keyboard input by taking advantage of the keyboard event listeners.

**Describe alternatives you've considered**

**Additional context**

**Comment by Siya8een** [comment]
pls assign this issue to me
