### ISSUE TITLE
Sticky Notes

### ISSUE THREAD

**Issue by AnkitGupta03** [TusharKesarwani/Front-End-Projects#831]
## **Describe the project**
A note-taking app using React.js

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Additional features include:
1. Toggle dark mode.
2. Search bar for finding saved notes.

## **Screenshots**
![Web capture_1-6-2023_204830_localhost](https://github.com/TusharKesarwani/Front-End-Projects/assets/96652394/c7475cb4-df69-46c6-8c7f-e904715c95a5)

Kindly assign me this issue.

**Comment by anamithrak15** [comment]
Hi @AnkitGupta, I would love to work on this task. Kindly, assign me this.

**Comment by anamithrak15** [comment]
hi @TusharKesarwani, I would like to contribute to this issue. Kindly assign me this.
idea- I would like to make interface features using glassmorphism css.

**Comment by mdvadiyatnaqvi** [comment]
hey @TusharKesarwani 
kindly assign this issue to me, i would and like to solve this issue with my best.

**Comment by Arun9739** [comment]
@AnkitGupta03 project alreday exists.
