### ISSUE TITLE
Resume Creator using Basic JavaScript

### ISSUE THREAD

**Issue by dev-AshishRanjan** [TusharKesarwani/Front-End-Projects#832]
## **Describe the project**
This project uses Basic HTML, CSS, JavaScript to create a basic Resume Creator, where you can create your resume and most important download the created Resume.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
Created using HTML, CSS, JS only

## **Screenshots**
| Edit View | Download View |
|----- | ----- |
|![Screenshot_20221224_152627](https://github.com/TusharKesarwani/Front-End-Projects/assets/94990764/0f5fb81c-158c-4458-9953-18ff5c52aebc) |![Screenshot_20221224_150727](https://github.com/TusharKesarwani/Front-End-Projects/assets/94990764/3158f7a4-be06-41e5-b540-37d279712491) |

**Comment by dev-AshishRanjan** [comment]
Please Assign me this issue so, I can work on it

**Comment by itsnishant17** [comment]
I recently came across the Resume Creator project you have developed using HTML, CSS, and JavaScript. After reviewing the project description and its requirements, I am excited about the opportunity to contribute to this project and would like to request that you consider assigning the work to me.

I have a strong background in web development and I am confident that I possess the necessary skills and expertise to make meaningful contributions to the project. I have extensive experience working with HTML, CSS, and JavaScript, and I have previously developed similar interactive forms and document generation features.

I would be grateful for the chance to contribute to the Resume Creator project and further develop my skills in web development. Thank you for considering my request. I am available for any further discussions or interviews to discuss my qualifications and how I can be an asset to your project.

**Comment by dev-AshishRanjan** [comment]
Hi @Arun9739 ,
*I have open this issue and haven't been assigned (to me) till now.*

**Can you look into the matter if you have time**
