### ISSUE TITLE
Next Generation version of List App

### ISSUE THREAD

**Issue by nandanchebbi560** [TusharKesarwani/Front-End-Projects#833]
**Is your feature request related to a problem? Please describe.**
 I will use bootstraps and material UI to create a much better-looking and animated List App.

**Describe the solution you'd like**
With the help of Material UI, Basics of Web Dev technology (HTML, CSS, Javascript), and Responsive design, I want to build a to-do list app where first it can resizable across all kinds of devices, a reminder alarm function where it reminds you what to do and when, connection with google calendar.

**Describe alternatives you've considered**
As of now, no alternatives
**Additional context**
as of now, No.

**Comment by Arun9739** [comment]
@nandanchebbi560 Project already exists
