### ISSUE TITLE
Next Generation Weather Map

### ISSUE THREAD

**Issue by nandanchebbi560** [TusharKesarwani/Front-End-Projects#834]
**Is your feature request related to a problem? Please describe.**
with Bangalore weather, the weather app will play a crucial role while navigating through the city. For this day and age, the weather app needs to beautiful and easy-to-understand UI.

**Describe the solution you'd like**
With the help of Material UI, Bootstrap, Basics of web dev technologies, and responsive UI I will create a very easy-to-understand user interface that shows as much as information possible and make it as easy to understand as possible.

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by Arun9739** [comment]
@nandanchebbi560 Project already exists
