### ISSUE TITLE
Need to Add 2048 Game Front End Project

### ISSUE THREAD

**Issue by MohamedMafaz** [TusharKesarwani/Front-End-Projects#835]
## **Describe the project**
I'd like to add my 2048 game into this repo

## Issue Type:

- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by MohamedMafaz** [comment]
please assign me this issue

**Comment by Arun9739** [comment]
@MohamedMafaz Games are not allowed
