### ISSUE TITLE
Spotify Clone- Want to Add new features in website 

### ISSUE THREAD

**Issue by MohdSultanGit** [TusharKesarwani/Front-End-Projects#836]
**Is your feature request related to a problem? Please describe.**
1. Here in this spotify clone all songs have same duration while actually they don't have same duration. All songs have different different durations.
2.  Also their is nothing in Home section like if we click on 'Home' nothing is coming.
3.  Like Home section there is nothing in About section also .

**Describe the solution you'd like**
1. I will change the previous time stamp and make the correct time stamp of all 
![Screenshot (150)](https://github.com/TusharKesarwani/Front-End-Projects/assets/132590302/aa814d97-824b-49f4-b7a5-b71c9b5c527a)
.
2.  I will add some random songs which will going to appear on Home page .
3. I would to tell about myself in About section .

**Describe alternatives you've considered**

**Additional context**
I am very proficient in HTML, CSS, and javascript and I can make this website to look a way more beautiful than before . I will glad if i got to this and I will definitely want to work with this issue .

**Comment by ShreyoPaul** [comment]
I would like to contribute to this issue. Please assign this to me.

**Comment by Pradeepyadav210** [comment]
I would  like to contribute to this issue. Please assign this to me.
[https://github.com/TusharKesarwani/Front-End-Projects/issues/836#issue-1736700291](url)

**Comment by Arun9739** [comment]
@ShreyoPaul Project alreday exists
