### ISSUE TITLE
Adding a web for fetching mems from Reddit

### ISSUE THREAD

**Issue by vink08** [TusharKesarwani/Front-End-Projects#837]
## Memes Fetch
This project will fetch the Memes from the Reddit API. This web is made up with the HTML, CSS , JAVASCRIPT

## Issue Type:

- [ ] New Project

## **Additional context**
This web fetching memes from Reddit API

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/110723566/66a5d6bb-e0f9-4ff4-bc0f-7caeeb21e23f)

@TusharKesarwani please assign me this project under the label of SSOC'23

**Comment by panjyar** [comment]
Hello @vink08 I can build this projects using HTML,CSS,JAVASCRIPTS  and fetching memes from Reddit API . Can you please assign me this issue...

Please assign this to me under @SSOC23
