### ISSUE TITLE
Home Page of Newsletter Website

### ISSUE THREAD

**Issue by SomilRathore01** [TusharKesarwani/Front-End-Projects#838]
## **Describe the project**
I want to create homepage of newsletter website.
It will display some news content and many other facilities on that homepage.
That will be only front-end part. 
I will use HTML, CSS & JavaScript in this project. I will complete this project with great UI/UX by adding required styles and animation in it.

## Issue Type:
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by SomilRathore01** [comment]
Hey! @TusharKesarwani , please assign this issue to me for competing in SSOC 2.0

**Comment by panjyar** [comment]
Hello @TusharKesarwani  I can work on this project  . Can you please assign me this issue...

Please assign this to me under @SSOC2.0

**Comment by Manishkr1007** [comment]
Hello @TusharKesarwani I can work on this project  . I can make this more efficiently ,Can you please assign me this issue...

Please assign this to me under @SSOC2.0

**Comment by SomilRathore01** [comment]
@TusharKesarwani please assign this issue to me so that I can raise my PR for SSOC 2.0

**Comment by SomilRathore01** [comment]
@TusharKesarwani please check my pull request that I have raised now and please merge it.
