### ISSUE TITLE
Enhancement of UI/UX Home Page of Spotify Clone

### ISSUE THREAD

**Issue by SomilRathore01** [TusharKesarwani/Front-End-Projects#839]
**Is your feature request related to a problem? Please describe.**
I will enhance the UI/UX of homepage in this project by adding some more buttons and options on this page, so that it looks more interactive and interesting to user.

**Describe the solution you'd like**
I will use HTML, CSS & JavaScript for adding some buttons and new features as front-end interface which will show more options on this page.

**Comment by SomilRathore01** [comment]
Hey! @TusharKesarwani , please assign this issue to me for competing in SSOC 2.0

**Comment by khushi-shrama** [comment]
Hi @TusharKesarwani 

I'd like to contribute to this project and I'm interested in working on the issue #839. I believe I can add value to this problem. If possible, could you assign this issue to me? I'm excited to collaborate and compete in SSOC2.0.


Thank you for your consideration!

**Comment by SomilRathore01** [comment]
@TusharKesarwani please assign this issue to me so that I can raise my PR for SSOC 2.0
