### ISSUE TITLE
Rock Paper Scissors

### ISSUE THREAD

**Issue by pancham1305** [TusharKesarwani/Front-End-Projects#840]
## **Describe the project**
A game of Rock Paper Scissors between you v/s the Computer based on Math.random .
## Issue Type:
- [ ] New Project

## **Additional context**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/63814443/7185c292-84e5-4342-9236-2a73c0ee384d)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/63814443/709e865e-714d-47aa-9404-5fef857282fb)

Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
- Need for a good UI for it.

**Comment by panjyar** [comment]
Hello @pancham1305  I can build game of Rock Paper Scissors between you v/s the Computer using  Math.random . Can you please assign me this issue...


Please assign this to me under @SSOC23

![Screenshot from 2023-06-02 03-19-47](https://github.com/TusharKesarwani/Front-End-Projects/assets/121200924/96a12a5c-9374-4f73-8354-71cc4ec29fc3)

I can improve the UI if you  want more good then these
 
My Github repo:  https://panjyar.github.io/stone-paper-scissors/

**Comment by Tusharjoshi1703** [comment]
Hello @pancham1305 I have already built a game like this using math.random between user and computer and have updated the score respectively. Please assign it to me.
My GitHub repo: https://tusharjoshi1703.github.io/rockpaperscissor/
![IMG_20230602_132100](https://github.com/TusharKesarwani/Front-End-Projects/assets/103979298/af26982d-b2f6-48fc-9423-0f0028f5e033)

**Comment by Shraddha16092002** [comment]
@TusharKesarwani I can improve the UI of this project. please assign it to me

**Comment by SwapnilGanguly** [comment]
@TusharKesarwani I can contribute to this project. Can you please assign it to me?

**Comment by Udit-Gogia** [comment]
@TusharKesarwani, I would like to contribute to this project by focusing on good coding practices and a good User Interface. Can you please assign it to me?

**Comment by Arun9739** [comment]
@SwapnilGanguly games are not allowed
