### ISSUE TITLE
Hidden Search actually having functionality

### ISSUE THREAD

**Issue by pancham1305** [TusharKesarwani/Front-End-Projects#841]
**Is your feature request related to a problem? Please describe.**
At the moment the is purely static and doesn't actually have any functionality in it.
That what i wanted to focus on.

**Describe the solution you'd like**
I want to make this a search engine that gives the top 10 search results of all the search engines.

**Describe alternatives you've considered**
At the moment I plan to first add the duckduckgo searching capabilities then move on to other search engines.

**Comment by TusharKesarwani** [comment]
Create a fresh issue with proper description
