### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by pancham1305** [TusharKesarwani/Front-End-Projects#842]
**Is your feature request related to a problem? Please describe.**
A purely static site which i would like to make dynamic so that it can play any song you have searched for.
**Describe the solution you'd like**
I want the functionality of searching for a song and want to use the media player built to listen to it.

**Describe alternatives you've considered**
I will use apis which will generate a link to the song which can then be put in the source of the media and will be therefore played and we will be able to listen to it.

Hi @TusharKesarwani please assign me this issue so that i can start working as soon as possible

**Comment by anshul-kh** [comment]
Hi @TusharKesarwani ,I can work on this issue under SSOC mentorship program. Please assign this issue to me so that I can start working on it as soon as possible.

**Comment by ShreyoPaul** [comment]
@TusharKesarwani I would like to contribute this issue. If possible assign me this task.

**Comment by Siya8een** [comment]
Hi @TusharKesarwani, I can work on this issue under the SSOC mentorship program. Please assign this issue

**Comment by Ranjana993** [comment]
hello, @TusharKesarwani I would like to work on this issue, Plz assigns this to me.
thanks :)

**Comment by Arun9739** [comment]
@pancham1305 Project already exists
