### ISSUE TITLE
Projects/Whack-A-Mole

### ISSUE THREAD

**Issue by pancham1305** [TusharKesarwani/Front-End-Projects#843]
**Is your feature request related to a problem? Please describe.**
To make this a PWA.

**Describe the solution you'd like**
people will be able to install it in mobile phones, desktop and use it as a website too.

**Describe alternatives you've considered**
making of a icon and making a manifest.json.

 Hi @TusharKesarwani please assign me this issue so that i can start working as soon as possible

**Comment by TusharKesarwani** [comment]
Create a fresh issue with a proper description
