### ISSUE TITLE
Adding Download Feature : Qr Code Generator

### ISSUE THREAD

**Issue by Rushabt11** [TusharKesarwani/Front-End-Projects#844]
**Is your feature request related to a problem? Please describe.**
I have seen various QR Code Generators with download options. But In Qr Code Project, There is no download option available, I would like to add an option of downloading the QR code as jpg or png. Hence, These QR Images will help users to share their QR Codes for scanning and networking purposes.

**Describe the solution you'd like**
When the QR Code will be generated, I want to use functions for the generation of images for QR Codes. I want to fetch image data from the API and then want to save it as a jpg or png. 

**Additional context**
Instead of giving user download options. we can give users a sharing option where the user can share their QR code to Gmail, save it to Drive, save QR as Pdf, etc.

**Comment by panjyar** [comment]
Hello @Risht11  I can work on this project  . Can you please assign me this issue...

Please assign this to me under @SSOC23
