### ISSUE TITLE
[SSOC] New Project In Place of COMING SOON!!

### ISSUE THREAD

**Issue by GeekWolf007** [TusharKesarwani/Front-End-Projects#845]
I want to add a new project in the place of coming soon.
![241249946-7288a55c-180d-47b4-888f-2423a368e302](https://github.com/TusharKesarwani/Front-End-Projects/assets/126271100/93dbbf75-a338-4996-b821-de71d6192cae)

The project is a job listing web app. The users also have the option to add new jobs. Users can also search jobs via country, state, job company, job requirements, etc.

I have built this project using only HTML , CSS and JavaScript. This is a great learning for people who thinks we can only add new jobs via backend technologies. This project helps in exceeding the limit of the developer and is a great learning project.

Please assign me this issue so that I can add this project and add my contribution to this community.

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue under SSOC 2.0
