### ISSUE TITLE
Minesweeper game

### ISSUE THREAD

**Issue by moh1t-do** [TusharKesarwani/Front-End-Projects#847]
## **Describe the project**
To make Minesweeper using HTML, CSS and Javascript. In the game of Minesweeper, players are required to determine the positions of hidden mines (or bombs) within a field.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Minesweeper rules are very simple. The board is divided into cells, with mines randomly distributed. To win, you need to open all the cells. 

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/100019828/746d0537-2049-4403-b7bb-9c0841004129)

**Comment by Roudranilk** [comment]
@TusharKesarwani kindly assign me this project since I have a good grasp on frontend technologies and python hence using python it will be easier for me to build the game.

**Comment by Vi-vek9135** [comment]
@TusharKesarwani Please assign this issue to me.
I am a beginner in open-source fields so I would like to start my contribution with HTML, CSS, and Javascript.

**Comment by Arun9739** [comment]
@Vi-vek9135 Games are not allowed
