### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by SwapnilGanguly** [TusharKesarwani/Front-End-Projects#848]
## **To Do List**
This project focuses on a To Do List. We can add new items, delete them and edit them. 

## Issue Type:
- New Project

## **Screenshots**

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/43022717/7618d17e-b257-4018-9adf-894a93350c49)

**Comment by anamithrak15** [comment]
I would like to work on this issue. Please assign me this @SwapnilGanguly

**Comment by SwapnilGanguly** [comment]
> I would like to work on this issue. Please assign me this @SwapnilGanguly

Sure, but I'm new to this. So if you could guide me on how to assign, I would surely do so.

**Comment by SwapnilGanguly** [comment]
@TusharKesarwani Can you please assign this issue

**Comment by Gyanthakur** [comment]
I am full stack developer, please assign me this issue

**Comment by KeshavAgrawal18** [comment]
Hey @TusharKesarwani, I am a **MERN stack Developer** and previously worked on this type of projects. I want to work on this issue. I request you, please assign me this issue.
I would provide you **neat** and clean, **nicely commented code**.
You can look at my profile at [LinkedIn](https://www.linkedin.com/in/keshav-agrawal-ka/)

**Comment by Ananya01Agrawal** [comment]
Please assign this project to me , I want to work on this project

**Comment by harshit-paneri** [comment]
**_Already Created_** @SwapnilGanguly

**Comment by Gyanthakur** [comment]
Please assign this project to me , I want to work on this project, i'm full stack devloper

**Comment by harshit-paneri** [comment]
> Please assign this project to me , I want to work on this project, i'm full stack devloper

Already in the projects please make unique.

**Comment by Gyanthakur** [comment]
> > Please assign this project to me , I want to work on this project, i'm full stack devloper
> 
> Already in the projects please make unique.

ohky

**Comment by Niranjan-Kumar-Singh** [comment]
Allow me to make it in unique way, assign it to me
