### ISSUE TITLE
TIC-TAC-TOE

### ISSUE THREAD

**Issue by komalk15** [TusharKesarwani/Front-End-Projects#849]
**Describing the bug**
In this project when the first player which is X plays his turn "Player 0 turn" is displayed on the screen, but the second time when player 0  plays if he clicks In the position where player X had already responded still "Player X turn" is displayed.

**Expected behavior**
The expected behavior should be that when the next player clicks on the previously responded place the message below about the next turn of the player should not change. 
Also, this would be better if the player clicks on the previously responded place a warning should be displayed on the screen that
 "This block had already received the response please click in an empty block".

**Screenshots**

![Image(1)](https://github.com/TusharKesarwani/Front-End-Projects/assets/114974499/64b6e6dc-0a21-48ae-b5f2-45aa25bae617)
![image(2)](https://github.com/TusharKesarwani/Front-End-Projects/assets/114974499/6b10d3aa-6e4c-4c09-89b9-1c97df99209e)
@TusharKesarwani  please assign me this I issue I want to work on it.

**Comment by Roudranilk** [comment]
@TusharKesarwani kindly assign me this project since I am quite proficient in building such projects using my frontend knowledge, moreover I can give a 3d look to this project using threejs

**Comment by komalk15** [comment]
Hey @TusharKesarwani  please assign this issue to me

**Comment by Arun9739** [comment]
@TusharKesarwani Games are not allowed

**Comment by komalk15** [comment]
@Arun9739 This is not my project I was just trying to solve a bug

**Comment by Arun9739** [comment]
@komalk15 Okay go ahead
