### ISSUE TITLE
2048 Online game 

### ISSUE THREAD

**Issue by Aditya-Lawate-codez** [TusharKesarwani/Front-End-Projects#851]
# 2048 Game

- Many Individuals are interested in playing the 2048 game in their pcs, and this is also their project.
- Making a 2048 game for such individuals is a treat.
- Also this game helps build logic for using various key commands from the keyboard using event listeners and keycodes.
- I will be implementing using javascript, although if it's required, ill be adding some features of React.
- The up down left and right features would be on click 
- and there would be first page where you can select the grid size

signing off, 
**Aditya Lawate**
[GitHub](https://github.com/aditya-lawate-codez)
[LinkedIn](https://linkedin.com/in/aditya-lawate)

**Comment by MohamedMafaz** [comment]
Hey @Aditya-Lawate-codez 
I already opened the same issue 20 Hours ago. https://github.com/TusharKesarwani/Front-End-Projects/issues/835

**Comment by Aditya-Lawate-codez** [comment]
Oh ok I saw now
