### ISSUE TITLE
Dynamic Invoice Generator

### ISSUE THREAD

**Issue by SiriAmarlapudi** [TusharKesarwani/Front-End-Projects#852]
## **Describe the project**
In this project Iam going to build a  dynamic invoice generator using HTML, CSS, and JavaScript.
this not only automates the invoice generation process but also enhances its functionality.
With dynamic invoice generation, you can eliminate the need for manual calculations, minimize errors.

## Issue Type:
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

![Screenshot (591)](https://github.com/TusharKesarwani/Front-End-Projects/assets/133572565/17c6f419-5b7d-4b9c-ab61-d0c508498bc0)

**Comment by Pranay38** [comment]
Hey! I would like to work on this issue
