### ISSUE TITLE
change the description of hangman game 

### ISSUE THREAD

**Issue by SurbhiMotwani23** [TusharKesarwani/Front-End-Projects#853]
Hey I wanna change the description of hangman game 
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/91596996/2b876030-8491-478e-a9cf-4a332c251960)

**Comment by panjyar** [comment]
Hey I can change the description of hangman game.  can you please assign me this  under SSOC2.0.....

**Comment by ivedmohan** [comment]
Assign me this issue i wanna work on this

**Comment by SurbhiMotwani23** [comment]
Hey I have raised this issue ,Please @TusharKesarwani assign me this ,this willbe my first contribution.

**Comment by shravanii2308** [comment]
hey @SurbhiMotwani23 i can come up with a great description that can sound formal but cool at the same time can you assign me this issue?

**Comment by SurbhiMotwani23** [comment]
sorry @shravanii2308  I have been trying since a long time,and this would be my 1st issue if assigned.

**Comment by shravanii2308** [comment]
@SurbhiMotwani23 ok np

**Comment by SurbhiMotwani23** [comment]
hey @TusharKesarwani  plz assign the issue.

**Comment by SurbhiMotwani23** [comment]
@Arun9739 hey I cant see the hangman project now
