### ISSUE TITLE
Zomato Landing Page

### ISSUE THREAD

**Issue by minion2104** [TusharKesarwani/Front-End-Projects#854]
**Is your feature request related to a problem? Please describe.**
The UI is not perfect according to me and I want to add Javascript to the login and sign up buttons so that any user can login or signup and redirect to different page.

**Describe the solution you'd like**
I will add carousel by using bootstrap and use different css styles to make the web page more attractive and add javascript to  make the login and signup buttons responsive.

**Comment by Roudranilk** [comment]
@TusharKesarwani kindly assign me this project under SSOC so that I can contribute to more of upcoming open source issues and learn from it, since I have created landing pages in the past, it will be easy for me to implement my knowledge and start working on it.

**Comment by minion2104** [comment]
Thank you for assigning the project. I'm excited to start and will do my
best to deliver excellent results.
