### ISSUE TITLE
New Project Addition

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [TusharKesarwani/Front-End-Projects#855]
## **Describe the project**
A simple todo app using HTML, CSS and JavaScript.
It is a temporary app which stores the todos temporarily as no backend is used.

If the todo list is already in the projects, i have another project event-keycodes which displays the key pressed key code and key name with some UI. Please assign one of the projects above.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
This is my first issue.
Please assign this to me under SSOC23

**Comment by Arun9739** [comment]
@OMKAR-KALEPU Project already exists
