### ISSUE TITLE
Landing Page for Beauty Product Startup

### ISSUE THREAD

**Issue by bhavyasingh75** [TusharKesarwani/Front-End-Projects#856]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
My project aims to provide a starter landing page for startups focusing on beauty products.

**Comment by Shu12388y** [comment]
@bhavyasingh75  @TusharKesarwani I want to work on this issue can you assign this issue to me

**Comment by Harshu34** [comment]
Hey! @TusharKesarwani , I go through your project of "landing page for beauty project startup" , I really liked your idea of the that startup and looking forward to contribute more in this project to upskill the project to another level. I will be happy if you assign that issue to me. Waiting for your kind response.

**Comment by bhavyasingh75** [comment]
on it
