### ISSUE TITLE
I want to add a weather app made using HTML, CSS , JAVASCRIPT and API.

### ISSUE THREAD

**Issue by Aishjahan** [TusharKesarwani/Front-End-Projects#857]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
I want to add a weather app made using HTML, CSS , JAVASCRIPT and API.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

![Screenshot 2023-05-31 004642](https://github.com/TusharKesarwani/Front-End-Projects/assets/105747510/90b1b594-d96c-4269-9bc7-9b59e3204373)

- If applicable, add screenshots to help explain your problem.

**Comment by Roudranilk** [comment]
@TusharKesarwani kindly assign me this project and mention if any changes needs to be made in the UI or API fetch or anything.

**Comment by Arun9739** [comment]
@ashutoshgithubs Proect already exists
