### ISSUE TITLE
Ecommerce Website using HTML, CSS, JS

### ISSUE THREAD

**Issue by Vidip-Ghosh** [TusharKesarwani/Front-End-Projects#858]
## **Describe the project**
I want to add a Ecommerce Website built using HTML, CSS, JS. 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Please assign this issue under SSOC'23. 

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by ManmayGhosh** [comment]
I have created an E-commerce website using this stack, so please assign this to me and explain if any additional features need to be added.

**Comment by Garvanand** [comment]
I have created ecommerce website using php and my sql as well as mern stack please assign this issue to me

**Comment by shravanii2308** [comment]
please assign me this issue @TusharKesarwani

**Comment by Arun9739** [comment]
@Garvanand project already exists
