### ISSUE TITLE
Complete Zomato Landing Page clone

### ISSUE THREAD

**Issue by Tusharjoshi1703** [TusharKesarwani/Front-End-Projects#860]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I would like to complete the landing page clone of Zomato as I have proper knowledge of html and css .Please assign it to me @TusharKesarwani

**Comment by Deepak0320Singhal** [comment]
Hey @Tusharjoshi1703 I can do this can you please assign this task to me.
I have knowledge of Html5 and CSS3.
