### ISSUE TITLE
AI Image Generator

### ISSUE THREAD

**Issue by tapan31** [TusharKesarwani/Front-End-Projects#861]
## **Describe the project**
Creating an AI image generator using Reactjs, nodejs and openai API

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Manoj-2702** [comment]
@tapan31 I have already worked on this project and I know how to create this website.
Can you please assign me this issue?

mail:[hsmanojkumar2003@gmail.com](hsmanojkumar2003@gmail.com)
github link: [https://github.com/Manoj-2702](https://github.com/Manoj-2702)

**Comment by harshit-paneri** [comment]
React project is not allow.
