### ISSUE TITLE
regarding profile card

### ISSUE THREAD

**Issue by weaklogics** [TusharKesarwani/Front-End-Projects#862]
this new issue that i am thinking of is the developer's profile card profile is that one thing that should be appealing and should let the person know(who u are wanting to send) that they have something better up their sleeve i want to make the profile card better and attractive so that when people get a glimpse of it they'd be wanting to check what is that all about
I would like to request the project admin to assign this issue to me
I will make it better and will try with full determination to improve some aspects of it 
Thank you

**Comment by Arun9739** [comment]
@weaklogics project already exists
