### ISSUE TITLE
Crossy Road Game Clone

### ISSUE THREAD

**Issue by SiriAmarlapudi** [TusharKesarwani/Front-End-Projects#869]
## **Describe the project**
Crossy Road is a highly popular mobile game that offers a fun and challenging experience to players of all ages.
 The process of creating our own Crossy Road game clone using HTML, CSS, and JavaScript Three.js.

## Issue Type:

- [ ] New Project

## **Additional context**
Crossy Road takes a simple concept and turns it into an addictive gameplay experience. The objective of the game is to navigate a character across a busy road filled with moving vehicles, rivers with floating logs, and other obstacles. The player must carefully time their movements to avoid colliding with these hazards while also collecting rewards and power-ups along the way.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
- 
![Screenshot (592)](https://github.com/TusharKesarwani/Front-End-Projects/assets/133572565/f2633a76-9f1a-4796-b845-1aadb6304bf7)

**Comment by Arun9739** [comment]
@SiriAmarlapudi Games are not allowed
