### ISSUE TITLE
Air Quality UI enhancement

### ISSUE THREAD

**Issue by 0plaze0** [TusharKesarwani/Front-End-Projects#870]
## <p>I will enhance the UI/UX of homepage in this project, so that it looks more interactive and interesting to user.</p>

<br>

![Air Quality](https://user-images.githubusercontent.com/59620280/214479823-64dee5f7-2d68-46a1-b1be-735126a747ff.png)

[link](https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Air-Quality)

<hr>

### Type
- [x] UI/UX enhancement
- [x] New feature (non-breaking change which adds functionality)

<hr>

###  Checklist:
- [ ] My code follows the style guidelines of this project
 - [ ] I will performed a self-review of my own code
 - [ ] I will commented my code, particularly in hard-to-understand areas

**Comment by 0plaze0** [comment]
Hello, @TusharKesarwani  can you assign me this issue

**Comment by 0plaze0** [comment]
## Hey! [@TusharKesarwani](https://github.com/TusharKesarwani) I have found this problem and looked into it and I believe I can solve it by doing following explained process.
How I will do it (Expected Changes)

### 1. Visual Design:

<i>Revise the CSS to create an appealing and visually consistent design.
Optimize the color scheme, typography, and overall styling to ensure readability and aesthetic appeal.
Apply suitable spacing and alignment to enhance the visual hierarchy and organization of elements.</i>

### 3. Code Refactoring:

<i>I will evaluate the existing codebase and refactor the CSS and HTML as needed.
Optimize code structure and eliminate any redundant or unnecessary code to enhance maintainability and performance.<i>

**Comment by 0plaze0** [comment]
Hey @TusharKesarwani  can you assign me this issue

**Comment by Divyanshu9822** [comment]
Hey @TusharKesarwani this issue is already raised in issue #827 and all this issue description and changes even the comment is copied from the existing issue. Pls look into issue #827
