### ISSUE TITLE
Color gradient generator using react

### ISSUE THREAD

**Issue by ShreyoPaul** [TusharKesarwani/Front-End-Projects#873]
I will like add color gradient generator project with copy style functionality. I will like to use basic html, CSS, JavaScript for this project. please assign me  this project sir.

## Issue Type:
- [x] New Project

![Screenshot (48)](https://github.com/TusharKesarwani/Front-End-Projects/assets/90982938/d405b00e-7762-47ec-9847-5dc15606e051)
 please assign me this task under SSOC'23.

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue under SSOC 2.0

**Comment by harshit-paneri** [comment]
React project is not allow.
