### ISSUE TITLE
Zomato Landing Page Clone

### ISSUE THREAD

**Issue by Swapnalighadge** [TusharKesarwani/Front-End-Projects#874]
Here on the Zomato Landing Page i would like to add validations for email id and phone number using Js and also the button of share app link doesn't show any movement after clicking i would like to work on that to
Kindly assign it to me under SSOC
<img width="936" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/102608194/8e6e10ae-b7ec-47b0-9fea-db4dd86f79bf">

**Comment by Swapnalighadge** [comment]
#874

**Comment by cshovik** [comment]
I want to integrate razorpay in this platform to open donate option . when anyone want to order from this platform , they can donate any amount which we can use for needy people who can't buy their basic food . #940

**Comment by dpvasani** [comment]
Use Buy me coffee
