### ISSUE TITLE
Weather App using HTML,CSS, JS , APIs and UI/UX

### ISSUE THREAD

**Issue by Courage003** [TusharKesarwani/Front-End-Projects#875]
**Is your feature request related to a problem? Please describe.**
Here the issue I have to deal with is to make a weather app using front end technologies.

**Describe the solution you'd like**
Everyone would be dealing with the traditional way of framing the app. I would try to add on and work more on the appealing site.

**Describe alternatives you've considered**
Will use HTML, CSS and JS for the basic coding of the app. Apart from that APIs will play a huge role in this. Will try to give site a more appealing site by applying experience in UI/UX designing as well.

**Additional context**
Please assign this task to me under SSOC'2023 @TusharKesarwani  
![Mowgli Vloggers!!](https://github.com/TusharKesarwani/Front-End-Projects/assets/111676377/1b7919e2-83b8-46fa-b95f-3a3978066a97)

**Comment by abhyuday1212** [comment]
Please assign this task to me under SSOC'2023 @TusharKesarwani

**Comment by nikhill28** [comment]
Hello sir ,i m nikhil 
Please assign this task to me under SSOC'2023 @TusharKesarwani

**Comment by Courage003** [comment]
May i start working on it @TusharKesarwani

**Comment by Arun9739** [comment]
@Courage003 project already exists
