### ISSUE TITLE
Add Responsiveness and Improve UI of "TaskList" project

### ISSUE THREAD

**Issue by Aryaman3007** [TusharKesarwani/Front-End-Projects#876]
**Is your feature request related to a problem? Please describe.**
Add responsiveness in the project and improve the user interface.

**Describe the solution you'd like**
It is crucial to make our project responsive across different screen sizes and resolutions with the help of CSS and add a feature so that the tasks are not removed after refreshing till the user delete the task.

**Describe alternatives you've considered**
Will use media screen in CSS to change the responsiveness and improve the UI. Will change the JS to improve the functionality of the task list.

**Additional context**
Please assign this issue to me under SSOC 2023 @TusharKesarwani

**Comment by Aryaman3007** [comment]
@TusharKesarwani Could you please assign this issue to me.

**Comment by priyanka-6675** [comment]
plz assign to me

**Comment by TusharKesarwani** [comment]
The project is already present in the repo
