### ISSUE TITLE
AI Module Website

### ISSUE THREAD

**Issue by itsgauravv** [TusharKesarwani/Front-End-Projects#877]
## **Describe the project**
This website provides with the information about the AI world and its top AI modules.
With an industry hot trending blog section, this website gives you all you need about AI.

## Issue Type:

- [x] New Project

## Tech Stats:

- [x] HTML
- [x] CSS 
- [x] JS 

## **Screenshots**
Welcome Page:
<img width="1440" alt="Screenshot 2023-06-02 at 6 08 26 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/95155509/da528ab4-0649-4ed5-ac25-cb321cfdf177">
<br>
Article/Blog Section:
<img width="1440" alt="Screenshot 2023-06-02 at 6 08 59 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/95155509/7238428b-a3cf-43f8-a2d5-315790b52711">
<br>
Top AI Module List:
<img width="1440" alt="Screenshot 2023-06-02 at 6 09 29 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/95155509/990ff36d-4763-47a7-9549-19c2d8962a94">

**Comment by itsgauravv** [comment]
@TusharKesarwani  Please assign this issue to me for SSoC 23. It will be a great push for my starting of open source.

**Comment by harshit-paneri** [comment]
> @TusharKesarwani Please assign this issue to me for SSoC 23. It will be a great push for my starting of open source.

Start Work on it.
