### ISSUE TITLE
Restyling the project card

### ISSUE THREAD

**Issue by uvthegreat** [TusharKesarwani/Front-End-Projects#878]
**Is your feature request related to a problem? Please describe.**

Style of the project card is not user friendly. the font size of content is too small and even the size of the card does not look good.
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/112636859/8630a971-4d5d-41a5-bda0-926dd68258ac)

**Describe the solution you'd like**

I would like to restyle the project card to solve the issue I listed above. It will not only make it user friendly but also make the overall website Attractive.

**Comment by ritik48** [comment]
I would like to work on this issue under SSOC 2.0.

**Comment by uvthegreat** [comment]
I have made the pull request for this issue. Kindly review my request.
