### ISSUE TITLE
Making the Home Page Responsive [SSOC 2.0]

### ISSUE THREAD

**Issue by ritik48** [TusharKesarwani/Front-End-Projects#879]
**Is your feature request related to a problem? Please describe.**
The website is not responsive on small screens, the contents overflow and not displayed properly.

![frontend project responsive uissue](https://github.com/TusharKesarwani/Front-End-Projects/assets/84488726/f207f2b7-a45b-4261-bb58-0e2dc90f712d)

**Describe the solution you'd like**
I would like to make the home page responsive so that it's interactible on all devices.

**Comment by 0plaze0** [comment]
# Hey! [@TusharKesarwani](https://github.com/TusharKesarwani)I believe I can Improve the responsive UI by doing following explained process.
How I will do it (Expected Changes)

- ### 1. Visual Design:
- [ ] Revise the CSS to create an appealing and visually consistent design.
- [ ] Optimize the color scheme, typography, and overall styling to ensure readability and aesthetic appeal.
- [ ] Apply suitable spacing and alignment to enhance the visual hierarchy and organization of elements.
- [ ] Adding interactive button and nav bar

- ### Code Refactoring:
- [ ] I will evaluate the existing codebase and refactor the CSS and HTML as needed.
- [ ] Optimize code structure and eliminate any redundant or unnecessary code to enhance maintainability and performance.

**Comment by rahulrana701** [comment]
hi @TusharKesarwani I would like to work on this issue..

**Comment by tab21** [comment]
Hey is anyone working on this? 
If not can this be assigned to me please

**Comment by ritik48** [comment]
@TusharKesarwani please assign this issue to me

**Comment by ritik48** [comment]
@TusharKesarwani please assign this issue to me

**Comment by ritik48** [comment]
@TusharKesarwani please assign this issue to me

**Comment by Samratghosh2004** [comment]
Hey @TusharKesarwani , I am Samrat Ghosh
Can I be added in this project? I made many responsive sites as my own projects. I am excited to work on it, hope it becomes true, Thank you.

**Comment by arnab236** [comment]
Hello Sir,I want  to be assigned in this project and I am a beginner and recently learnt about this,so I want to do this project to show and polish my skills.Thank You.

**Comment by HarshP64896** [comment]
@TusharKesarwani, I would like to work on this issue, Can you assign it to me?
