### ISSUE TITLE
Tindog Website rebuild

### ISSUE THREAD

**Issue by Roudranilk** [TusharKesarwani/Front-End-Projects#881]
## **Describe the project**
The design of the tindog website will look similar to a Tinder application except for the fact that it will have images of dogs to be adopted or can be bought with the name of the dog, address from where they can be adopted or bought. The project can be made using HTML, CSS and JAVASCRIPT.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![Tindog](https://github.com/TusharKesarwani/Front-End-Projects/assets/109891452/64881aaf-c0f3-41de-bf3d-820d15fdeb40)

Kindly assign me this project so that I can build it as I have built a tinder clone previously.

**Comment by souvikpramanikgit** [comment]
I have already created many websites using html, css, javascript. And the websites are also responsive.
This is my certificate => https://coursera.org/share/c0d189bcf46cbf074ff3811c50b1bda7
So please assign it to me.

**Comment by souvikpramanikgit** [comment]
Also, I already did this type of website in a udemy course so if you gave me I can do it responsive.
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/123581988/432e859f-d71c-4250-9840-65080c6622aa)

**Comment by souvikpramanikgit** [comment]
why you closed this

**Comment by Niranjan-Kumar-Singh** [comment]
Could you assign this issue to me.

**Comment by souvikpramanikgit** [comment]
could me assign this to me
