### ISSUE TITLE
Improvement in UI and adding new features in Registration Form

### ISSUE THREAD

**Issue by aarushiksk** [TusharKesarwani/Front-End-Projects#882]
**Is your feature request related to a problem? Please describe.**
This registration form looks extremely dull and non-responsive, there are limited options to add as well.

**Describe the solution you'd like**
-Better UI
-A Progress Indicator which indicates how much the form is filled

**Additional context**

<p style="center">A Progress tracker Example</p>
<img src="https://github.com/TusharKesarwani/Front-End-Projects/assets/92772439/b3551bb0-5bb0-4732-9ded-229a316e5d33">
<br>

<p><b> UI must be creative, responsive and visually appealing</b></p>

**Comment by abhyuday1212** [comment]
@TusharKesarwani assign this issue to me

**Comment by abhyuday1212** [comment]
Please assign this task to me under SSOC'2023 @TusharKesarwani
