### ISSUE TITLE
New Project - A Travel Website

### ISSUE THREAD

**Issue by Harshawasthi14** [TusharKesarwani/Front-End-Projects#883]
## **Describe the project**
It is going to be a travel website for tourists for their reservation of hotels , trains  ,flights etc.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by PoulavBhowmick03** [comment]
It already exists...

**Comment by Harshawasthi14** [comment]
I didn't notice that
can I generate a new issue

**Comment by PoulavBhowmick03** [comment]
You'll get notified. Check your notifications

**Comment by Harshawasthi14** [comment]
..
