### ISSUE TITLE
Social Media Reference Landing Page Project

### ISSUE THREAD

**Issue by AnupK1234** [TusharKesarwani/Front-End-Projects#884]
## **Description :**
A social media reference landing page is a webpage that is specifically designed to showcase an individual's social media presence. It typically includes links to an individual's profiles on various social media platforms, as well as information about their content, and engagement.
Everything you are. In one, simple link in bio. 
𝗧𝗲𝗰𝗵 𝗦𝘁𝗮𝗰𝗸 : HTML5, CSS3

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**
![img](https://github.com/TusharKesarwani/Front-End-Projects/assets/94510566/3238e764-ced7-4dc0-93d9-c166935b6dec)

Hello  @TusharKesarwani  @harshit-paneri ,
I'm interested in adding this project and would like to contribute. Could you please assign it to me under the SSOC'23. I'm looking forward to collaborating on this project.
Thank you!

**Comment by Gungun1643** [comment]
Hi..I am Gungun..I am a mern stack developer and proficient in ui and ux.Found this issue interesting could you please assign it to me ...I would like to add a tick mark button which will indicate the link has been saved successfully

**Comment by Gungun1643** [comment]
???

**Comment by Gungun1643** [comment]
I would like to add a drop down menu to chose from the different websites..

**Comment by rahulrana701** [comment]
hi @AnupK1234 I would like to work on this issue , please assign it to me....

**Comment by Pradeepyadav210** [comment]
I would like to work on this issue , please assign it to me....
[https://github.com/TusharKesarwani/Front-End-Projects/issues/884#issue-1738296852](url)

**Comment by AnupK1234** [comment]
Hello @TusharKesarwani , Please assign me this issue.

**Comment by harshit-paneri** [comment]
> Hello @TusharKesarwani , Please assign me this issue.



I think its already created.

**Comment by harshit-paneri** [comment]
> > > Hello @TusharKesarwani , Please assign me this issue.
> > 
> > 
> > I think its already created.
> 
> @harshit-paneri I checked the Project folder, this project isn't there.

okay
