### ISSUE TITLE
Addition of Keyboard input in the calculator App

### ISSUE THREAD

**Issue by Harshu34** [TusharKesarwani/Front-End-Projects#886]
**Is your feature request related to a problem? Please describe.**
Yes, i have worked upon the calculator app earlier where i added the keyboard input functionality, so i can also add this functionality to this project.

**Describe the solution you'd like**
I will use the event listners of keyboard and trying to access the  value of the keys from input.

**Comment by Harshu34** [comment]
Hey, @TusharKesarwani , I would like to add the functionality in the calculator app (i.e keyboard input). I would be happy if you assign that issue to me. Waiting for your positive response.

**Comment by harshit-paneri** [comment]
> Hey, @TusharKesarwani , I would like to add the functionality in the calculator app (i.e keyboard input). I would be happy if you assign that issue to me. Waiting for your positive response.

Hey @Harshu34 Can you describe the feature you want to add.

**Comment by Harshu34** [comment]
> > Hey, @TusharKesarwani , I would like to add the functionality in the calculator app (i.e keyboard input). I would be happy if you assign that issue to me. Waiting for your positive response.
> 
> Hey @Harshu34 Can you describe the feature you want to add.

I will add the key board functionality to it, which was not there i.e if user wan to give the input from their system keyboard so it can give easily this would make the website user friendly, because we know clicking the operators or numbers in the website repeatedly so it takes lot of time to get the result, so i will add some event listeners to it so that website might stand up at one level higher than before.
