### ISSUE TITLE
Finance Tracker

### ISSUE THREAD

**Issue by AMRIT456** [TusharKesarwani/Front-End-Projects#887]
## **Describe the project**
Create a web-based personal finance tracker using JavaScript, HTML, and CSS. The application should allow users to add, edit, and delete income and expense transactions and display the current balance. 
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [* ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/67870234/1094de0a-8844-4b6b-acef-48509053a9b1)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/67870234/ff7679dd-6a02-4221-83f8-ddfdc0f4e796)

**Comment by harshit-paneri** [comment]
> Kindly assign me this project under ssoc 2k23

Now You can start work on it.

**Comment by harshit-paneri** [comment]
> @harshit-paneri you did not assign it to me

Ohh, Yes I just confused, it's good if you can share more information like above issue

**Comment by Roudranilk** [comment]
@harshit-paneri 
The finance tracker will consist of several key components:

User interface: We will use HTML and CSS to design and style the user interface for our budget tracker.

Input forms: We will use HTML forms to allow users to input their income and expenses.

Local storage: We will use a browser’s local storage to store the user’s budget data.

Calculation logic: We will use JavaScript to calculate the user’s total income, expenses, and budget balance.
By adding these essential components, we will be able to create a functional budget tracker that allows users to easily input, store, and view their budget data. We will now go through the process of implementing each of these features in our budget tracker application.

**Comment by harshit-paneri** [comment]
Hey @AMRIT456 are you doing this issue ?

**Comment by AMRIT456** [comment]
> Hey @AMRIT456 are you doing this issue ?

yes sir @harshit-paneri  i am doing this issue

**Comment by AMRIT456** [comment]
> > Hey @AMRIT456 are you doing this issue ?
> 
> yes sir @harshit-paneri i am doing this issue

you have assigned it to me?

**Comment by harshit-paneri** [comment]
> > > Hey @AMRIT456 are you doing this issue ?
> > 
> > 
> > yes sir @harshit-paneri i am doing this issue
> 
> you have assigned it to me?

Already assigned you

**Comment by harshit-paneri** [comment]
> @harshit-paneri The finance tracker will consist of several key components:
> 
> User interface: We will use HTML and CSS to design and style the user interface for our budget tracker.
> 
> Input forms: We will use HTML forms to allow users to input their income and expenses.
> 
> Local storage: We will use a browser’s local storage to store the user’s budget data.
> 
> Calculation logic: We will use JavaScript to calculate the user’s total income, expenses, and budget balance. By adding these essential components, we will be able to create a functional budget tracker that allows users to easily input, store, and view their budget data. We will now go through the process of implementing each of these features in our budget tracker application.

Grear @Roudranilk but this issue first raise by other so we assigned it to someone else, if the not send PR in next 3-4 days then I will assigned you, meanwhile you can explore more or work on other issues or create your own issues.
Thankyou
