### ISSUE TITLE
A responsive movie/web-series web application

### ISSUE THREAD

**Issue by Roudranilk** [TusharKesarwani/Front-End-Projects#890]
## **Describe the project**
The goal of this project is to create a movie website using HTML, CSS, and JavaScript. The website will provide information about movies, including their titles, descriptions, genres, and ratings. Users will be able to browse movies, search for specific movies, and view additional details about each movie.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Homepage: The homepage will display featured movies, allowing users to quickly access popular or recommended films. It will also include a navigation menu for easy navigation throughout the website.

Movie Listing: The website will have a movie listing page where users can browse through a collection of movies. Each movie will be represented by a thumbnail image and its title.

Movie Details: Clicking on a movie thumbnail will take the user to a page displaying detailed information about the movie. This page will include the movie's title, description, genre, release date, and rating. Users will also have the option to watch a trailer or read reviews.

Responsive Design: The website will be designed to be responsive, ensuring a seamless user experience across different devices and screen sizes.

Kindly assign me this project under SSOC 2k23 @TusharKesarwani @harshit-paneri

**Comment by harshit-paneri** [comment]
Start work on it.
