### ISSUE TITLE
Add New Project ( A Quiz App )

### ISSUE THREAD

**Issue by Gaurang1602** [TusharKesarwani/Front-End-Projects#893]
## Quiz App  
A quiz App which is created using Html , CSS and  Javascript in which there are questions which has four options and you have to mark the correct answer and at last you can check you score.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project 

## **Additional context**

- It is a very Interesting and enjoyable game. 
- In this a person get knowledge about Html , CSS , Javascript and python basics.

## **Screenshots**

- Is is a front UI of Quiz game .

![Quiz Page](https://github.com/TusharKesarwani/Front-End-Projects/assets/99584477/624bdd7b-17b2-4b53-9817-28acb6a74a66)

- It is the final score page.

![Final Score](https://github.com/TusharKesarwani/Front-End-Projects/assets/99584477/5589c824-d6b6-4f56-858f-39347aa84803)

It is very Interesting game .
I have created this request now again because previously I created it before 1st June 
So , please assign it to me under SSOC ' 23 .

**Comment by Divyanshu9822** [comment]
Similar project already exists and also  i've been assigned a issue (#774) from the similar project to solve which has been solved and more issues are there to solve.

**Comment by Gyanthakur** [comment]
@Gaurang1602 please assign this issue me
 I want to contribute on this project ☺️
