### ISSUE TITLE
I want to add hovering effects to the sign-up and sign-in buttons of 3D login page. 

### ISSUE THREAD

**Issue by Mansi8874** [TusharKesarwani/Front-End-Projects#895]
**Is your feature request related to a problem? Please describe.**
So it will look more attractive.

**Describe the solution you'd like**
Add a hovering feature

**Comment by Shraddha16092002** [comment]
I have better ideas to work over this issue. please assign it to me

**Comment by hemraj29** [comment]
Assign this issue to me ,
I have ability to implement this in efficient manner

**Comment by prashant226** [comment]
i want to work on this please assign it to me.

**Comment by TanyaNegi10** [comment]
I want to work on this issue in a better way plss assign it to me.

**Comment by mayurd8862** [comment]
Empower me with the opportunity to take on this project and make a significant impact!
