### ISSUE TITLE
I want to add some cool features and transitions to the buttons of Animated Cards

### ISSUE THREAD

**Issue by Mansi8874** [TusharKesarwani/Front-End-Projects#896]
**Is your feature request related to a problem? Please describe.**
So it look more attractive by adding this features.

**Describe the solution you'd like**
The buttons will have a subtle shadow effect and a smooth transition on hover. The follow button will have a transparent background with a blue border, which changes to a blue background with white text on hover. 

**Additional context**
I want to work on this issue under SSOC. Please assign this issue to me.

**Comment by Shraddha16092002** [comment]
I want to work over this issue. please assign it to me

**Comment by sripesh** [comment]
I will be using React/HTML to make the button and CSS for the shadow effect along with the transition on hover.

I want to work on this issue under SSOC. Please assign this issue to me.

**Comment by Gyanthakur** [comment]
I want to work on this issue. please assign it to me
