### ISSUE TITLE
Adding New Website Elements for Practice.

### ISSUE THREAD

**Issue by ojasaklechayt** [TusharKesarwani/Front-End-Projects#9]
Hello Sir! I have created some cool website elements. Those aren't specifically for this website but they can be added to different websites. So, Can I add them as projects in the projects file? 
I have registered it as a contributor, not an admin.

**Comment by TusharKesarwani** [comment]
Go ahead @ojasaklechayt

**Comment by ojasaklechayt** [comment]
Okay I will create a pull request
