### ISSUE TITLE
Enhancing the website and Removing typos in "Villa Hotel Website"

### ISSUE THREAD

**Issue by KritikaRawat** [TusharKesarwani/Front-End-Projects#902]
**Problem: **
Basically, the content on the About and Blog pages is not arranged visually, and additionally, there are typos on the Blogs page like repeating a name twice, so I will be fixing this as well. Also, no footer is present on these pages so I will also add a footer.

**Describe the solution you'd like**
- Organize the content on the "About" and "Blog" pages.
- Remove Typos and Repetition.
- Add a footer on these both pages.

![WhatsApp Image 2023-06-02 at 23 43 46](https://github.com/TusharKesarwani/Front-End-Projects/assets/107604161/72985bae-c69a-4aea-92b3-6fcb61a0bc7f)

![WhatsApp Image 2023-06-18 at 23 42 18](https://github.com/TusharKesarwani/Front-End-Projects/assets/107604161/909d92ed-1045-4e0e-8cb8-b0c845ef67d1)

**Comment by KritikaRawat** [comment]
I want to be a part of this project. Please assign this to me for SSOC 2.0

**Comment by Shraddha16092002** [comment]
@TusharKesarwani , I want to work over this issue ,please assign it to me
