### ISSUE TITLE
DEV DETECTOR APP :  A Tool to find user's GitHub profile.

### ISSUE THREAD

**Issue by ashutoshgithubs** [TusharKesarwani/Front-End-Projects#903]
## **Describe the project**
The dev detector app I built using HTML5, CSS, and JavaScript with an API serves as a tool to display a user's GitHub profile with additional details such as the number of repositories, followers, and those they follow. This app provides a convenient way for users to gather information about a GitHub user and gain insights into their activity and popularity within the GitHub community.

I have also added the Dark mode feature. Users can easily toggle between dark & light modes.

By leveraging the GitHub API, the app can retrieve the necessary information about a specific user, such as their username, profile picture, bio, and other relevant details like social media links. The only thing you have to do is to enter a valid username.

Overall, the dev detector app simplifies the process of exploring GitHub profiles, providing users with a user-friendly interface to view important statistics and details about GitHub users, and fostering collaboration and information sharing within the developer community.

## Issue Type:
- [ ] New Project

## **Additional context**
https://ashutecher.co/

## **Screenshots**
![Screenshot (267)](https://github.com/TusharKesarwani/Front-End-Projects/assets/97340498/314bbefb-fbd6-4328-aa47-2d9674c03e38)
![Screenshot (268)](https://github.com/TusharKesarwani/Front-End-Projects/assets/97340498/fa8ef662-a3f2-4223-8974-7ba8b4cd6621)

**Comment by ashutoshgithubs** [comment]
@TusharKesarwani Please assign me this task under SSOC 2.0
Thanks

**Comment by Mayuresh-22** [comment]
Great Work 👏
