### ISSUE TITLE
Update the UI of the Villa Hotel website

### ISSUE THREAD

**Issue by JPV2207** [TusharKesarwani/Front-End-Projects#904]
**Is your feature request related to a problem? Please describe.**
The Villa Hotel webiste is static and not looks so tempting and hence I want to improve the UI of the website in order to make it more appealing and sound.

**Describe the solution you'd like**
For improving the UI I want to add a live video on the website home page and along with that I want to add some animation on the website in order to give it a better look.

**Describe alternatives you've considered**
Instead of a having a static website with little or no animation, I want to give it a better look and make it more tempting.

https://github.com/TusharKesarwani/Front-End-Projects/assets/111731727/b6f68d71-476c-4c49-8c62-6dfbb9b4e6cb

**Comment by KritikaRawat** [comment]
@TusharKesarwani  I have already asked this issue to assign to me in the #902 issue under SSOC 2.0.
Thanks

**Comment by Sonikm** [comment]
Please assign this issue to me, I would like to improve the UI of this website.

**Comment by abhyuday1212** [comment]
@TusharKesarwani  assign this issue to me

**Comment by abhyuday1212** [comment]
Please assign this task to me under SSOC'2023 @TusharKesarwani

**Comment by Pradeepyadav210** [comment]
please assign this issue to me, i would like to improve the UI of this website
