### ISSUE TITLE
[Improvement] : Fixing the issue of image not displaying 

### ISSUE THREAD

**Issue by himadribh07** [TusharKesarwani/Front-End-Projects#908]
**BMI Calculator**
Problem:- After entering the weight and height the image is not displaying correctly.

**Expected behavior**
After entering the details image should be displayed, but not displaying. 

**Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/62461681/ea21bb7d-b70d-4ec3-af0e-201a51550b08)

@TusharKesarwani @harshit-paneri could you assign this task to me.

**Comment by Divyanshu9822** [comment]
@TusharKesarwani and @harshit-paneri , this issues is already raised under issue #814. Pls do check and don't assign this issue  as it exists already which is made earlier than this.

**Comment by himadribh07** [comment]
Hi @Arun9739 have made the changes in #1320, Pls review and merge it.

**Comment by Divyanshu9822** [comment]
@Arun9739 @TusharKesarwani  this is already resolved and also pull request is merged. It's duplicate
