### ISSUE TITLE
Update UI of Blog Project Website

### ISSUE THREAD

**Issue by bugzzz4u** [TusharKesarwani/Front-End-Projects#911]
**Is your feature request related to a problem? Please describe.**
The UI of the Blog website looks formal to me. As a user, I would want the look of the website to be more aesthetically pleasing.

**Describe the solution you'd like**
I would change the color theme and change the pictures in order to make it look aesthetic.

**Comment by bugzzz4u** [comment]
@TusharKesarwani and @harshit-paneri please assign me.

**Comment by harshit-paneri** [comment]
> @TusharKesarwani and @harshit-paneri please assign me.

don't tag , mentors can automatically assign after review the issues.

**Comment by harshit-paneri** [comment]
> **Is your feature request related to a problem? Please describe.** The UI of the Blog website looks formal to me. As a user, I would want the look of the website to be more aesthetically pleasing.
> 
> **Describe the solution you'd like** I would change the color theme and change the pictures in order to make it look aesthetic.

mention the project link.

**Comment by bugzzz4u** [comment]
> > **Is your feature request related to a problem? Please describe.** The UI of the Blog website looks formal to me. As a user, I would want the look of the website to be more aesthetically pleasing.
> > **Describe the solution you'd like** I would change the color theme and change the pictures in order to make it look aesthetic.
> 
> mention the project link.
https://github.com/TusharKesarwani/Front-End-Projects/tree/7b056836b7df278170e1d133b4c569beb722b33d/Projects/Blog%20Project%20Website

**Comment by bugzzz4u** [comment]
> > @TusharKesarwani and @harshit-paneri please assign me.
> 
> don't tag , mentors can automatically assign after review the issues.

Okay sir, sorry for the inconvenience

**Comment by Pradeepyadav210** [comment]
please assign me this project
[https://github.com/TusharKesarwani/Front-End-Projects/tree/7b056836b7df278170e1d133b4c569beb722b33d/Projects/Blog%20Project%20Website](url)
