### ISSUE TITLE
Add Digital Clock Project

### ISSUE THREAD

**Issue by Abhay3819** [TusharKesarwani/Front-End-Projects#914]
## **Describe the project**
Hii @TusharKesarwani , I want to add this project so please assign to me.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![git](https://github.com/TusharKesarwani/Front-End-Projects/assets/110670975/20b2607b-8f31-42a3-872f-c3c48781f9fb)

**Comment by Gyanthakur** [comment]
Assign me this issue

**Comment by mayurd8862** [comment]
Assign me this issue...

**Comment by mayurd8862** [comment]
> Assign me this issue...

Even I can provide you better and attractive design of this web-page

**Comment by Gyanthakur** [comment]
fixed this issue #914 fixed

![Uploading Screenshot 2023-06-04 221036.png…]()
