### ISSUE TITLE
drum kit game 

### ISSUE THREAD

**Issue by leesha19** [TusharKesarwani/Front-End-Projects#915]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by priyanshimaheshwari** [comment]
I want to work on this project

**Comment by Harshdev10** [comment]
I want to work on this project.

**Comment by imrish4** [comment]
I want to contribute to this project. Please assign it to me.

**Comment by Arun9739** [comment]
@leesha19 Games are not allowed
