### ISSUE TITLE
Clone of Buy Me a Cofee 

### ISSUE THREAD

**Issue by Shu12388y** [TusharKesarwani/Front-End-Projects#916]
![buy me a coffee](https://github.com/TusharKesarwani/Front-End-Projects/assets/91714143/af4fe8a8-ed08-4096-9eaf-70c5bbabbcdc)
## **Describe the project**
I want to clone a Buy Me a Coffee Website that is missing in your frontend project repo.
We can also add new features to it like nearby creators, creating a Meetup Place, selling creator goodies, etc.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [.] New Project

Can you assign this project to me for SSOC'23  @TusharKesarwani

**Comment by Nancy-30** [comment]
Hello I am Nancy,
Can you assign this project to me for SSOC'23 @TusharKesarwani.
I will use HTML and CSS to clone this website.

**Comment by Samratghosh2004** [comment]
Hi, I am Samrat Ghosh,
Can I be added in this project? I am excited to become a part of it, Thank you.

**Comment by arnab236** [comment]
Hello, I am Arnab Sarkar.
I want to be assigned in this project .Can I get this opportunity to prove my skills?
Thank You.
