### ISSUE TITLE
Soduku game project 

### ISSUE THREAD

**Issue by NaMiKA0305** [TusharKesarwani/Front-End-Projects#917]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [it is an soduku game made with html css and javascript ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Gyanthakur** [comment]
Assign me this issue

**Comment by Arun9739** [comment]
@NaMiKA0305 Games are not allowed
