### ISSUE TITLE
WindBits

### ISSUE THREAD

**Issue by VardaPanchal005** [TusharKesarwani/Front-End-Projects#918]
This webpage's motto is to fetch the the current atmospheric conditions from different cities around the world with the help of Weather API,HTML,CSS and Javascript
![WindBits](https://github.com/TusharKesarwani/Front-End-Projects/assets/114830938/32018ff2-f954-4f55-adfc-4979ca1563f2)
@TusharKesarwani  please assign this issue to me

**Comment by kanishkakataria** [comment]
@TusharKesarwani or @harshit-paneri please assign this issue to me.I will be contributing by styling it a bit more and providing it with pop up messages to tell if travelling should be done,should umbrella be carried,is a hat needed according to the weather forecast in a fancy but elegant way

**Comment by VardaPanchal005** [comment]
> @TusharKesarwani or @harshit-paneri please assign this issue to me.I will be contributing by styling it a bit more and providing it with pop up messages to tell if travelling should be done,should umbrella be carried,is a hat needed according to the weather forecast in a fancy but elegant way
I'm a SSOC contributor too. You can create your own issue

**Comment by kanishkakataria** [comment]
Hey ... i was been told to comment to get an issue assigned .
So i commented ,is there any other process for doing so ?

**Comment by VardaPanchal005** [comment]
You can comment on  Project admin or Mentor's issue . I'm just a contributor. Or  you can create your own issue by going to issues ,click on new issue and write the issue

**Comment by kanishkakataria** [comment]
Thank you so much Varda for your help.

**Comment by VardaPanchal005** [comment]
> Thank you so much Varda for your help.

No problem

**Comment by kanishkakataria** [comment]
@priyanka-6685 its been already issued to me ...I am also a contributor .
Had raised this issue a week ago

**Comment by VardaPanchal005** [comment]
> @priyanka-6685 its been already issued to me ...I am also a contributor . Had raised this issue a week ago

i raised this issue 3 weeks ago but it is still not assigned to me what should i do

**Comment by VardaPanchal005** [comment]
> Hey @VardaPanchal005 , This is very common project and already in the projects, This will count as a duplicate project.
> 
> Try to contribute in previous projects or create a unique project.

But sir  I raised this issue 3 weeks ago where I didn't see this project but it is still not assigned to me and newer projects got assigned...

**Comment by harshit-paneri** [comment]
can you please mention the new project link.

**Comment by VardaPanchal005** [comment]
I’m talking about new issues with this same project

**Comment by harshit-paneri** [comment]
> I’m talking about new issues with this same project

yes, so please mention the issue, so that I can check it.

**Comment by VardaPanchal005** [comment]
#1134 #1063

**Comment by harshit-paneri** [comment]
Okay @VardaPanchal005 now you can start work on it.

**Comment by TusharKesarwani** [comment]
Already present in the repo

**Comment by VardaPanchal005** [comment]
> Already present in the repo

Sir I opened this 3 weeks ago and I was not assigned and 2 same issues were opened similar to me after I opened it
