### ISSUE TITLE
Inconsistencies in Air-Quality Project

### ISSUE THREAD

**Issue by bugzzz4u** [TusharKesarwani/Front-End-Projects#921]
<img width="960" alt="Screenshot 2023-06-03 15 08 33" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/125059410/598adb05-37fe-4157-9fd3-17190649275b">

This color code and theme of this project is not very appealing. The layout of the website could have been arranged in a better way. 
There is a need to change the whole theme of this website and redesigning its layout for better appeal and functioning.

So @TusharKesarwani and @harshit-paneri  ,please assign me this.

**Comment by Divyanshu9822** [comment]
@TusharKesarwani and @harshit-paneri this issue has been  already raised in (#827) which mentions many problem with the solution. It's a existing issue.
