### ISSUE TITLE
Meme Generator Styling

### ISSUE THREAD

**Issue by bugzzz4u** [TusharKesarwani/Front-End-Projects#923]
I want to improve the designing of Meme Generator while keeping the same code. I want to redefine the UI so as to make it more impactive.

**Changes I want to make: **
1. Adding styles like background color.
2. Giving styles to buttons too.

@harshit-paneri  and @TusharKesarwani  ,pls assign me.

**Comment by harshit-paneri** [comment]
Don't tag again and again

**Comment by harshit-paneri** [comment]
mention the project link and what improvement you will do.

**Comment by harshit-paneri** [comment]
Already created
