### ISSUE TITLE
Pomodoro Timer 

### ISSUE THREAD

**Issue by ishaa1304** [TusharKesarwani/Front-End-Projects#925]
Describe the project
Create  a pomodoro timer using HTML,JS,CSS. The Pomodoro Technique is a time management methodIt uses a timer to break work into intervals, traditionally 25 minutes in length, separated by short breaks.

Functionality:
1) Start timer by START
2) Stop timer by STOP
3) Click on CHANGE to change duration
4) Once timer ends, change in color of icon

**Comment by harshit-paneri** [comment]
Hey @ishaa1304 you can start work on this issue.
