### ISSUE TITLE
React eCommerce App

### ISSUE THREAD

**Issue by justAkshitAgrawal** [TusharKesarwani/Front-End-Projects#927]
## **Describe the project**
React Ecommerce: A sleek, secure, and scalable ecommerce app built with React, Tailwind CSS, and Firebase.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by justAkshitAgrawal** [comment]
@TusharKesarwani Please assign this project to me. Thanks!

**Comment by harshit-paneri** [comment]
E com website is already in the projects, It's better you contribute in those and add more feature
