### ISSUE TITLE
Feature Request: Navigation Panel for Question Selection in project "Dynamic Quiz Js"

### ISSUE THREAD

**Issue by Divyanshu9822** [TusharKesarwani/Front-End-Projects#928]
# Description:
I would like to propose the addition of a navigation panel in the Dynamic Quiz Js project, which will allow users to easily navigate between questions. This navigation panel will display the question numbers, and upon clicking on a specific question number, the quiz screen will change to display the corresponding question.

### Details:

- Add a navigation panel to the quiz interface.
- The navigation panel should display the question numbers as clickable options.
- Upon clicking on a question number, the quiz screen should change to display the corresponding question.
- Highlight the current question in the navigation panel to provide visual feedback to the user.
- Ensure that the navigation panel is visible and accessible throughout the quiz.

# Benefits:

- **Improved user experience**: Users can easily navigate between questions without having to scroll or go through each question sequentially.
- **Time-saving**: Users can quickly jump to a specific question they want to answer or review.
- **Enhanced usability**: The navigation panel provides clear visibility of the quiz progress and allows users to track their progress easily.

# Screenshots:

### Current State:

![](https://user-images.githubusercontent.com/90151736/242970326-c80cc82a-d810-4550-99d5-1814cb1786d5.png)

### After adding the feature (Navigation panel):

<img width="1440" alt="image" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/90151736/c29a530d-3786-4f85-b412-1aa9bb23b766">

**Comment by Divyanshu9822** [comment]
Hey @harshit-paneri I've already resolved two issues with this project and i want to add this navigation feature which is shown in issue Description. Pls assign me this so that i can add this cool feature to this project.

**Comment by harshit-paneri** [comment]
> Hey @harshit-paneri I've already resolved two issues with this project and i want to add this navigation feature which is shown in issue Description. Pls assign me this so that i can add this cool feature to this project.

you creating so much issues frequently, It's good if you can create single issue in which you solve all bugs and add more feature.

**Comment by Divyanshu9822** [comment]
Sir but issues were of different types and this was feature request

**Comment by harshit-paneri** [comment]
you are too frequent.
Don't do this for just score.

Create a single issue in which you can mention all new feature and bugs.

**Comment by Divyanshu9822** [comment]
@harshit-paneri sir what should i do for this then. pls assign this as this is the new feature req and i want to add this else give me any solution so that i can add the nav panel and this is the last this which i wanted to do on this project.

**Comment by harshit-paneri** [comment]
Your previous PR is still not merge, you can add this in previous PR.

**Comment by Divyanshu9822** [comment]
Thanks @harshit-paneri  sir I'll commit this in my last PR. But i was following the guidelines which was for each new bug and feature we should raise an issue.

**Comment by harshit-paneri** [comment]
Yes but just not for small small bugs.

You already have code and you just creating issues, that's why I suggested you.

**Comment by harshit-paneri** [comment]
If you have other bugs/ feature in you mind, you can list in this issue, I will reopen it.

**Comment by Divyanshu9822** [comment]
@harshit-paneri Yes sir pls reopen and assign this. I'll do everything in this issue.

**Comment by harshit-paneri** [comment]
> @harshit-paneri Yes sir pls reopen and assign this. I'll do everything in this issue.

If your work is good the score will be also consider in level high.

All the best.

**Comment by Divyanshu9822** [comment]
thankyou sir

**Comment by Divyanshu9822** [comment]
This issue is resolved and additionally updated README. Made a PR request for the same which needs review.
