### ISSUE TITLE
Analog Clock

### ISSUE THREAD

**Issue by SwapnilGanguly** [TusharKesarwani/Front-End-Projects#936]

**Comment by Gyanthakur** [comment]
I want to work on this issue, I'm already created an analog clock in 2022, please assign me this issue

**Comment by arnab236** [comment]
I can make an Analog Clock using HTML,CSS,JS. If I will get the opportunity,I will do my best to make it.Thank you.

**Comment by Samratghosh2004** [comment]
Hey I am Samrat Ghosh, 
Can I be added in this project. I am excited to become a part of it, Thank you.

**Comment by Arun9739** [comment]
@SwapnilGanguly Project already exists
