### ISSUE TITLE
clone of usability hub

### ISSUE THREAD

**Issue by KhushiVaiskyar** [TusharKesarwani/Front-End-Projects#937]
Usability Hub is a remote user research platform that takes the guesswork out of design decisions by 
validating them with real users.I have done this using html and css.

**Comment by harshit-paneri** [comment]
@KhushiVaiskyar Start work on it.

**Comment by Samratghosh2004** [comment]
Can I be added to this project ? I am excited to work on it, Thank you .

**Comment by arnab236** [comment]
UsabilityHub is a core and essential user testing tool in our recommended tech stack. It delivers quick insights and is really easy to use.
Sir,can I join to make the clone of UsabilityHub ?
