### ISSUE TITLE
[SSOC'23] Add Snake Game Frontend Project 

### ISSUE THREAD

**Issue by shubhanshurav** [TusharKesarwani/Front-End-Projects#938]
## **Describe the project you want to add with tech stack**    

- I created this Game using HTML, CSS & JavaScript and also used the DSA concept to create this project.

## Issue Type:

- [ ] Bug Report    
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

**Screenshots (optional)**

-![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/87806305/30463f83-e6b2-41d5-b27a-e340adc8adb9)

- Hey @TusharKesarwani , I want to add Snake Game Project, so please assign this project to me under SSOC'23.

**Comment by harshit-paneri** [comment]
Game is not allow.
