### ISSUE TITLE
Super Burger Landing Page

### ISSUE THREAD

**Issue by Shu12388y** [TusharKesarwani/Front-End-Projects#941]
<h1>Super Burger Landing Page</h1>

![superburger](https://github.com/TusharKesarwani/Front-End-Projects/assets/91714143/850934d4-c761-48c2-b74d-997fd74d07ea)

I want to make a super burger landing page. 
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [.] New Project

can you assign this project to me 
for SSOC'23

**Comment by harshit-paneri** [comment]
make sure it is responsive.

**Comment by Shu12388y** [comment]
@harshit-paneri thank you for assigning this issue
