### ISSUE TITLE
Incorrect Email Validation in SignIn Page Project 

### ISSUE THREAD

**Issue by Mayur-666** [TusharKesarwani/Front-End-Projects#942]
@TusharKesarwani 

In **SignIn Page** project , if we pass  **space in email input** then also the login gets successful . The validator for the email input is not correct . Similar thing happens for its signUp page , the email validation is incorrect  and also allows an blank space response .

The Javascript validation is not complete for this/

**Expected behavior**
It must show error when we pass a space as an input in the email field.

**Screenshots**
### In SignIn Page
![Screenshot (61)](https://github.com/TusharKesarwani/Front-End-Projects/assets/118804110/40eedc92-7434-41cc-8711-76d5411f4686)

### In SignUn Page
![Screenshot (60)](https://github.com/TusharKesarwani/Front-End-Projects/assets/118804110/db0c532c-3c35-4468-b297-6790aa142649)

Kindly assign me this issue so i can correct it.

**Comment by Mayur-666** [comment]
Please assign me this issue @TusharKesarwani

**Comment by Mayur-666** [comment]
Hey @harshit-paneri , I am willing to contribute to this issue please assign it to me .

**Comment by priyanka-6675** [comment]
hello , @TusharKesarwani  , assign this issue to me, i am willing to solve this space input problem . please assign it to me.

**Comment by Mayur-666** [comment]
@TusharKesarwani and @harshit-paneri   please assign it to me , i opened this issue almost 2 weeks ago
