### ISSUE TITLE
Responsiveness for devices

### ISSUE THREAD

**Issue by maitri-vv** [TusharKesarwani/Front-End-Projects#943]
**Describe the bug**
The website doenst view in proper alignment in Mobile view and laptop's with screen size less than standard pixels.

**To Reproduce**
Change the pixel size according to device screen.
**Screenshots**
![WhatsApp Image 2023-06-04 at 11 41 59](https://github.com/TusharKesarwani/Front-End-Projects/assets/87691594/aae64952-b67b-4fa7-acb3-78504dd93c81)
![WhatsApp Image 2023-06-04 at 11 41 59](https://github.com/TusharKesarwani/Front-End-Projects/assets/87691594/71133032-9c62-420f-a998-7b2feea24bb1)

**Expected behavior**
A proper user interface for any screen size. Can be worked with media queries.

**Comment by maitri-vv** [comment]
Kindly check this 
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/87691594/0f7299ae-4bc1-4c47-9d93-4302fba3301f)
PR: #1083

**Comment by TanyaNegi10** [comment]
I would like to work on this too
