### ISSUE TITLE
Graph Visualiser

### ISSUE THREAD

**Issue by dhruvmillu** [TusharKesarwani/Front-End-Projects#944]
## **Describe the project**
Graph Visualiser, visualises graphs. This project will be built in vanilla stack (HTML,CSS and JS)

The project will build Directed/ undirected graphs as specified by the user and apply simple algorithms like Djkstra shortest path and prim's minimum spanning tree.  It will be built using canvas and the nodes will be draggable, with editable labels, and the graph graph edges can be edited using an adjacency matrix

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by dhruvmillu** [comment]
@TusharKesarwani Please assign this to me under SSoC 2.0

**Comment by PiyushBL45t** [comment]
Hey, @TusharKesarwani, I want to work n this issue.
Name: Piyush Bhujbal
GitHub ID: https://www.github.com/PiyushBL45t
Participant Role: Participant at Social Summer of Code 2023.
Approach for this project: 
1. Design the UI and skeletal structure using HTML and CSS and Implement the graph visualizing functionality using JavaScript.
