### ISSUE TITLE
Elixir based Web Application

### ISSUE THREAD

**Issue by shubhisingh184** [TusharKesarwani/Front-End-Projects#948]
## **Describe the project**
An Elixir based web application ( Chat Room)
Tech stack : Elixir and Phoenix liveview and Postgresql database

Elixir is a functional, concurrent, general-purpose programming language that runs on the BEAM virtual machine used to implement the Erlang programming language. Elixir builds on top of Erlang and shares the same abstractions for building distributed, fault-tolerant applications. Elixir also provides productive tooling and an extensible design.
The Chat Room is designated virtual channel where users communicate with each other through the Internet.
I've worked on Elixir and want to add a basic project of on it, as it works with Phoenix Liveview and has high fault tolerance feature, which is well suited for web applications.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

**Comment by harshit-paneri** [comment]
Hey @TusharKesarwani is this tech stack is allow ?

**Comment by TusharKesarwani** [comment]
Only HTML,CSS and JS projects are allowed
