### ISSUE TITLE
Tetris Game using ReactJS

### ISSUE THREAD

**Issue by Mukesh751** [TusharKesarwani/Front-End-Projects#949]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Mukesh751** [comment]
![Screenshot (121)](https://github.com/TusharKesarwani/Front-End-Projects/assets/91366697/8aebda2f-7326-4cf3-8b32-c4024a186cad)

**Comment by harshit-paneri** [comment]
Game is not considering

**Comment by Mukesh751** [comment]
ok Sir
