### ISSUE TITLE
Landing page for a cloud hosting website

### ISSUE THREAD

**Issue by tapan31** [TusharKesarwani/Front-End-Projects#951]
## **Describe the project**
I want to create a landing page for a cloud hosting website like heroku using html, css and javascript.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by harshit-paneri** [comment]
Add Screenshot for better understanding

**Comment by tapan31** [comment]
![image_processing20211004-18932-6sam8s](https://github.com/TusharKesarwani/Front-End-Projects/assets/95282277/cfc98c14-143c-4172-bd88-a5ad855c49a9)
@harshit-paneri 
@TusharKesarwani 
I would like to create a design, similar to this, please assign it to me
