### ISSUE TITLE
Add a new Project on "Logistic Company" Landing page

### ISSUE THREAD

**Issue by rayarka26** [TusharKesarwani/Front-End-Projects#955]
The Page will have the following sections:
About US
Services We Offer
Testimonials
please assign me
Will be only frontend
#ssoc23

**Comment by noobcoder007-exe** [comment]
I am a  contributer......pleaseassign this to me

**Comment by harshit-paneri** [comment]
> I am a contributer under ssoc.... please assign this to me

Hey You can create your own issues
