### ISSUE TITLE
Add New Project ( Simon Game )

### ISSUE THREAD

**Issue by Gaurang1602** [TusharKesarwani/Front-End-Projects#956]
## **Simon Game**
Is a very Interesting Game basically it is a game which increase your memory and also test your memory.
It also increases your memory grasping power.
It is made using HTML , CSS and Javascript.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**

- This is a very interesting game.
- In this game 1 person play at a time.
- In this game firstly the game give you a color which you have to remember and select that color in you chance  and then game again give you a color you have to remember it also and select the first color then second color and so on....

## **Screenshots**

![Simon-game](https://github.com/TusharKesarwani/Front-End-Projects/assets/99584477/cb12dbe2-ec03-4c58-8fb6-5dbf15359a5a)

@TusharKesarwani please assign this issue to me.

**Comment by harshit-paneri** [comment]
Game is not accepted

**Comment by Gaurang1602** [comment]
Sir , can you tell me why this game is not accepted , please .
@harshit-paneri

**Comment by harshit-paneri** [comment]
> Author

not for only this game, all games are not consider.
