### ISSUE TITLE
JavaScript Age Calculator

### ISSUE THREAD

**Issue by ANI2707** [TusharKesarwani/Front-End-Projects#958]
## **Describe the project**
JavaScript Age Calculator calculates the user's age according to the input date provided.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
can you please assign me this project under ssoc'23?
I have provided some SS.

## **Screenshots**

![Screenshot 2023-06-04 193752](https://github.com/TusharKesarwani/Front-End-Projects/assets/108017771/a34e2c3f-4b2c-492d-b17d-b9981e424605)
![Screenshot (224)](https://github.com/TusharKesarwani/Front-End-Projects/assets/108017771/7acd0013-cf4f-44a3-b7bf-7e0609f8ba2b)
![Screenshot 2023-06-04 193921](https://github.com/TusharKesarwani/Front-End-Projects/assets/108017771/c83e6687-c9bd-4cc9-8702-29b9b4a1b45c)

**Comment by ANI2707** [comment]
@TusharKesarwani  Can you please assign me this issue.

**Comment by ANI2707** [comment]
@harshit-paneri  can you please assign me this issue?

**Comment by arnab236** [comment]
Sir,I want to do this project.Will you assign me for this?

**Comment by Samratghosh2004** [comment]
Hi @TusharKesarwani , I am Samrat Ghosh.
Can I get hired as a contributor? I am excited to become a part of it.
