### ISSUE TITLE
Add a new project (BookBuddy)

### ISSUE THREAD

**Issue by krutika-ladani** [TusharKesarwani/Front-End-Projects#960]
## A book-finder website:
This website has an an extensive collection of books and their ratings to cater to a wide range of interests and preferences.
- Built using **HTML, CSS and JavaScript**.
- It is **fully responsive**.
- Using It's **intuitive search** feature, you can easily find books by entering their titles, authors, or genres.
- Each book listing provides **direct links** to the reputable online platform "Open Library" where you can purchase or learn more about them.
- It is integrated with the **OpenLibrary API** to fetch the real time data.
 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## Additional context:
can you please assign me this project under ssoc'23? 

### Laptop screen
![Screenshot (42)](https://github.com/TusharKesarwani/Front-End-Projects/assets/119760273/8dc57855-6786-48aa-b569-df2c3a8ceb11)

### Mobile screen
![Screenshot (43)](https://github.com/TusharKesarwani/Front-End-Projects/assets/119760273/ab83f396-4653-459e-bab8-58d23b45e62a)

**Comment by krutika-ladani** [comment]
@TusharKesarwani @harshit-paneri please assign me this issue under SSOC 2.0.
Thankyou!!

**Comment by arnab236** [comment]
I can do this project and I want to be assigned .So please sir give me an opportunity to do this.
