### ISSUE TITLE
New Project- Landing page for Hospital management system

### ISSUE THREAD

**Issue by Harshawasthi14** [TusharKesarwani/Front-End-Projects#965]
## **Describe the project**
This will be a landing page for the hospital management system.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
This project will be useful for the hospital as well as for the public.
Various details of the hospital will be available to the people.

**Comment by mohitsingh1011** [comment]
@TusharKesarwani assign this to me if not wet assigned under SSoC'23

**Comment by TusharKesarwani** [comment]
Already present in the repo
