### ISSUE TITLE
Contact Page in Front End Projects website

### ISSUE THREAD

**Issue by Chandana-756** [TusharKesarwani/Front-End-Projects#972]
## **Describe the project**
The project is mainly about creating a contact page using HTML, CSS and Javascript but I have created this project with HTML and CSS.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
![Capture](https://github.com/TusharKesarwani/Front-End-Projects/assets/94692989/b39b59c7-e623-4f8e-9de1-1e118a2fff67)

Github repository: https://github.com/Chandana-756/Contact-Page

**Comment by priyanshimaheshwari** [comment]
I would like to work on this

**Comment by Gyanthakur** [comment]
@TusharKesarwani please  assign to me

**Comment by Gyanthakur** [comment]
merge this code 
<img width="943" alt="Screenshot 2023-06-08 113237" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/98226958/01258b74-3a2e-4c28-b307-643e120326bd">

**Comment by TusharKesarwani** [comment]
Not required
