### ISSUE TITLE
Binary - Decimal - Octal - Hexadecimal Converter

### ISSUE THREAD

**Issue by SwapnilGanguly** [TusharKesarwani/Front-End-Projects#973]
## **Describe the project**
A website to convert values among Binary, Decimal, Octal and Hexadecimal number systems. 
Techologies to be used: HTML, CSS, JS

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

I have knowledge in HTML, CSS and JS, and I would also like to use my programming skills to develop a website that would convert values among the 4 different number systems. 

You can check this out: https://swapnilganguly.github.io/NumberSystemConverter-WebDev/

@TusharKesarwani Please assign this issue to me, so that I can start working on this project. Thanks a lot!

**Comment by Pranay38** [comment]
Hey! I want to work on this issue

**Comment by SwapnilGanguly** [comment]
@TusharKesarwani It has been over a week since I had raised this issue. Please assign it to me.

**Comment by aaviiothic** [comment]
please assign me this issue @TusharKesarwani

**Comment by mayurd8862** [comment]
Empower me with the opportunity to take on this project and make a significant impact!

**Comment by SwapnilGanguly** [comment]
@TusharKesarwani It was said that all the issues will be reviewed by 20th June, and today is 21st June. Please look into the matter.

**Comment by TusharKesarwani** [comment]
Already present in the repo
