### ISSUE TITLE
Add 'about us' page and add click action on the contact us button and services 

### ISSUE THREAD

**Issue by Manishkr1007** [TusharKesarwani/Front-End-Projects#974]
A website food delivery and other services.
Techologies to be used: HTML, CSS

Issue Type:
 Bug Report
 Feature Request
 Documentation
 New Project
I have knowledge in HTML, CSS and JS, and I would also like to use my programming skills to develop a website that  show a full frontend design of food delivery and some other services.
@TusharKesarwani Please assign this issue to me, so that I can start working on this project. Thanks a lot!

Issue................
On contact us and services button add link that after clicking on that button our web page scroll down and show contact us or services section as the button is clicked.

**Comment by shiviii43** [comment]
@TusharKesarwani  please assign me this task for SSOC'23

**Comment by priyanshimaheshwari** [comment]
I would like to work on this

**Comment by aaviiothic** [comment]
hey, i want to work on this issue.

**Comment by adi673** [comment]
Heyy, I would like to work on this.

**Comment by Manishkr1007** [comment]
@TusharKesarwani  please assign me in this project

**Comment by Manishkr1007** [comment]
@TusharKesarwani please assign me in this project
