### ISSUE TITLE
Bug in Countify Project

### ISSUE THREAD

**Issue by Rohith1816** [TusharKesarwani/Front-End-Projects#976]
**Describe the bug**
Word Count was wrongly programmed

**To Reproduce**

1. Go to 'Front-End-Projects Repository'
2. Click on 'projects'
3. Scroll down to 'countify' then run it an type words in multiple line without typing spaces at the end
4. See the word count 

**Expected behavior**
The Expected number of words should be 5 but it is showing 3

**Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/111123761/245b249d-960c-48fe-9dc2-baf33cf1cad8)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I have a great knowledge in javascript css and html so please assign this to me i can fix the problem. 
Please assign this to me under #SSOC 2.0

**Comment by Rohith1816** [comment]
@TusharKesarwani Please assign this to me under SSOC 2

**Comment by Pranay38** [comment]
Hey! I would like to work on this issue
