### ISSUE TITLE
food page 

### ISSUE THREAD

**Issue by khushbumaheshwarii** [TusharKesarwani/Front-End-Projects#978]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project
-

## **Additional context**
Add any other context or screenshots about the project here.
assign me this issue under ssoc'23

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by khushbumaheshwarii** [comment]
@TusharKesarwani please assign me

**Comment by Sowmyatiwari** [comment]
I am interested to work on this issue ,please assign me!
