### ISSUE TITLE
Restaurant Menu

### ISSUE THREAD

**Issue by ncharanaraj** [TusharKesarwani/Front-End-Projects#979]
## **Describe the project - Restaurant Menu**
A **restaurant menu** page that filters through the different food menus.

## Issue Type:

- [ ] Feature Request
- [ ] Bug Report
- [ ] Documentation
- [x] New Project

## **Screenshots**
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/43924299/04f136ec-8273-493f-b344-c0934f178616)

**Comment by ncharanaraj** [comment]
Hi, @TusharKesarwani I would like to work on this project. Please, assign it to me.

**Comment by Gyanthakur** [comment]
@TusharKesarwani Please assign me this issue under SSOC '23 ,

**Comment by priyanshimaheshwari** [comment]
I would like to work on this

**Comment by Nirmal369** [comment]
I would also like to work on this under SSOC'23

**Comment by JSWizard1** [comment]
i have a good command on html, CSS, Bootstrap and  JavaScript therefore i will be a right candidate for this work. So pls assign this so that i can start working on this project under SSOC'23. You can check my GitHub account recently I created a project usi9ng Html, CSS and JavaScript.

**Comment by priyanka-6685** [comment]
Sir please assign this issue to me . Yet u have not any issues to me. I want to enhance this page

**Comment by TusharKesarwani** [comment]
Already present in the repo
