### ISSUE TITLE
Security Blog

### ISSUE THREAD

**Issue by vanya31** [TusharKesarwani/Front-End-Projects#98]
I intend to build a Blog website using React, which I'm currently in the process of learning. Also I'm specializing in cyber security, hence the content of the blog will be my research articles written in the process of my preparation for CEH certification.

**Comment by TusharKesarwani** [comment]
> I intend to build a Blog website using React, which I'm currently in the process of learning. Also I'm specializing in cyber security, hence the content of the blog will be my research articles written in the process of my preparation for CEH certification.

Sorry for this but we are not accepting React Projects
