### ISSUE TITLE
To-do List app (only frontend)

### ISSUE THREAD

**Issue by noobcoder007-exe** [TusharKesarwani/Front-End-Projects#980]
It is a very useful app where users can mark their tasks and delete them when they are complete. it can be used to remember tasks  and completing them on time.

**Comment by snehpr966** [comment]
I would like to try

**Comment by Pranay38** [comment]
Hey! I would like to work on this issue .

**Comment by Prasham1710** [comment]
i want to work on this issue

**Comment by AshDDftw** [comment]
i would like to contribute to this issue

**Comment by Gyanthakur** [comment]
please assign me this issue, I want to work on that project.

**Comment by mayank2mahi** [comment]
@TusharKesarwani Please sir assign me this issue. I eagerly want to work on this.

**Comment by Gyanthakur** [comment]
> @TusharKesarwani Please sir assign me this issue. I eagerly want to work on this.

I'm working on this task

**Comment by phoenix1406** [comment]
Sir i can make this entire app  it would be very helpful for me to start my open source journey ,ccoud you please assign me this  project

**Comment by imrish4** [comment]
please assign me this issue, I want to work on that project.

**Comment by TusharKesarwani** [comment]
Already present in the repo
