### ISSUE TITLE
 Contribution Request: Animated Card - Formatting and Centering Issues

### ISSUE THREAD

**Issue by Aqua-beast** [TusharKesarwani/Front-End-Projects#981]
**Describe the bug**
After thorough testing and investigation, I have identified two specific problems related to the card's alignment and the formatting of the text upon clicking.
1. Card Alignment:
When observing the animated card, I noticed that it is not centered as expected. The misalignment affects the overall aesthetics of the project. I believe that proper centering is crucial to maintain a visually pleasing and professional appearance.

2. Text Formatting upon Click:
Upon interacting with the card, I observed some spacing issues in posts, followers, and following text. The text does not appear to be well-formatted, and it lacks the appropriate spacing between words. This makes the content harder to read and diminishes the overall user experience.

**To Reproduce**
1. Go to the 'Front-End-Projects Repository'
2. Click on 'projects'
3. Scroll down to 'Animated '
4. Open the project to see the that the animated card is not centered
5. Hover over the card and notice that the displaced text, lacks some spacing

**Expected behavior**
To summarize, the expected behavior is to have a centered animated card within its container, and when the card hovers, it should display the content with proper formatting and correct spacing between words. These improvements will enhance the overall visual appeal and usability of the animated card component.

**Screenshots**
<img width="1080" alt="Screenshot 2023-06-05 113123" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/85673066/e8ca8497-eb6d-4b9f-af4f-2d867c645f64">
<img width="1080" alt="Screenshot 2023-06-05 115425" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/85673066/a30e8221-8b1a-4b93-9d03-474245db5f47">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I kindly request @TusharKesarwani to assign this issue to me under the #SSOC 2.0 project. By resolving these problems, I aim to enhance the user experience and ensure the animated card aligns with the desired expectations.

**Comment by Aqua-beast** [comment]
I kindly request @TusharKesarwani to assign this issue to me under the #SSOC 2.0 project.

**Comment by Aqua-beast** [comment]
@TusharKesarwani you have added respective labels but also assign this to me.

**Comment by Launchers-1** [comment]
@TusharKesarwani uh, could I get assigned to this issue?

**Comment by sayaditya** [comment]
I would like to do this issue
