### ISSUE TITLE
Landing-Page of Pepsi

### ISSUE THREAD

**Issue by yashpreet2707** [TusharKesarwani/Front-End-Projects#985]
## **Describe the project**
using HTML and CSS made a landing page for Pepsi. It is a very beginner friendly project.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
- Repo link - https://github.com/yashpreet2707/LandingPage-Pepsi
- Deployed Project - https://pepsi-landing-page-yash.netlify.app/

## **Screenshots**

There is a feature of change in size of various elements using hover property.

<img width="1440" alt="Screenshot 2023-06-05 at 3 22 18 PM" src="https://github.com/TusharKesarwani/Front-End-Projects/assets/111020648/97096e28-2be1-446b-9859-4a880ab9a3ce">

**Comment by PriyanshuG24** [comment]
Please assign this project to me as I have the right skill set to handle it effectively and efficiently.

**Comment by PriyanshuG24** [comment]
@yashpreet2707  @TusharKesarwani Can you please assign me this issue under SSOC 2.0 contribution?
Thanks.

**Comment by yashpreet2707** [comment]
Thanks @TusharKesarwani , but you didn't assign me.

**Comment by yashpreet2707** [comment]
I've made the PR @TusharKesarwani 😄

**Comment by yashpreet2707** [comment]
It is completed @TusharKesarwani , please review the PR
