### ISSUE TITLE
A website featuring web 3.

### ISSUE THREAD

**Issue by Pratham-Handa** [TusharKesarwani/Front-End-Projects#986]
## **Describe the project**
I have the idea of creating a fully interactive website which will give knowledge about web 3.0 and its various tech stacks . I will create the frontend using HTML, CSS and JS itself.

** SSOC 2.0 CONTRIBUTER**

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

Hope I will be assigned my issue.

**Comment by TusharKesarwani** [comment]
Create a new issue with proper description
