### ISSUE TITLE
Responsive Design Issue: 'Goto Github Repo' Button Disappears on Shrinking Screen Size

### ISSUE THREAD

**Issue by varundhand** [TusharKesarwani/Front-End-Projects#989]
**Describe the bug**
After thorough testing and investigation, I discovered that the 'Goto Github Repository' kept on disappearing on smaller screen sizes, 

**To Reproduce**
1. Go to the webpage (https://frontendprojects.netlify.app/)
2. Shrink the screen size to a smaller resolution (480 width)
3. Observe that the 'Go to Github repo' button is no longer visible.

**Expected behavior**
The 'Go to Github repo' button should remain visible even when the screen size is reduced

**Screenshots**
Before:

![issue-1 1](https://github.com/TusharKesarwani/Front-End-Projects/assets/110025628/2de0cdee-40da-40f0-b7c8-47ec4283412a)

After:

![issue-1 2](https://github.com/TusharKesarwani/Front-End-Projects/assets/110025628/e975e303-9c71-4430-bee9-e2c6673afbcf)

**Desktop (please complete the following information):**
 -  iOS
 -  chrome
 - Version 22

**Smartphone (please complete the following information):**
 - Device:  iPhone 12
 - OS: [e.g. iOS 16.5

**Additional context**
I kindly request @TusharKesarwani to assign this issue to me under the #SSOC 2.0 project. By resolving these problems, I aim to enhance the user experience and ensure the animated card aligns with the desired expectations.

**Comment by varundhand** [comment]
@TusharKesarwani I'd like to work on it... would you please assign me this

**Comment by liNikham** [comment]
@TusharKesarwani  Hello! I came across the open issue [#989] and I would like to contribute by proposing a solution. May I have permission to work on this issue? I would be glad to collaborate and help resolve it

**Comment by TanyaNegi10** [comment]
I want to contribute on this issue , can u plss assign it to me

**Comment by TusharKesarwani** [comment]
Goto button disappears for making the project responsive
