### ISSUE TITLE
UI of Villa hotel website

### ISSUE THREAD

**Issue by Saurabh8807** [TusharKesarwani/Front-End-Projects#992]
UI of villa Hotel website is simple. It's not attractive.

**Comment by harshit-sharmaaa** [comment]
How did you added this SSOC 2.O label? @Saurabh8807

**Comment by Saurabh8807** [comment]
> How did you added this SSOC 2.O label? @Saurabh8807

While creating an issue by default  ssoc2.0 label is there

**Comment by harshit-sharmaaa** [comment]
ok thankyou

**Comment by priyanshimaheshwari** [comment]
I would like to work on this

**Comment by Saurabh8807** [comment]
thank you sir
