### ISSUE TITLE
Responsive Gaming Website

### ISSUE THREAD

**Issue by vimarsh11** [TusharKesarwani/Front-End-Projects#994]
## **Describe the project**
Our gaming responsive website utilizes HTML, CSS, and JavaScript to deliver a visually stunning and user-friendly interface. With a wide range of games and seamless adaptability to different devices, users can easily navigate, explore genres, and discover new titles. Interactive features enhance the gaming experience, fostering community engagement.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
![Screenshot 2023-06-05 192352](https://github.com/TusharKesarwani/Front-End-Projects/assets/104987339/d8d6129a-cbe1-42d8-bccc-02c430e09699)
![Screenshot 2023-06-05 192317](https://github.com/TusharKesarwani/Front-End-Projects/assets/104987339/f372c698-7958-44c1-9397-795bb485fc3c)

- If applicable, add screenshots to help explain your problem.

**Comment by TusharKesarwani** [comment]
Game projects are not allowed
